### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [OnlyNoobDied/GadgetsMenu#10]
logs
http://pastebin.com/txtj96Qp

timings
https://timings.aikar.co/v2/?id=0993647f88b94a8fb8d712649baad572

config
http://pastebin.com/hsGPWWM4

**Comment by OnlyNoobDied** [comment]
did you install the latest LibsDisguises and ProtocolLib plugin?

**Comment by OnlyNoobDied** [comment]
Fixed, update soon.
