### ISSUE TITLE
Players can give their own box.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#100]
Hello !

For example if you have a mystery box 5 stars : you want to give it to your friend.
You can't with Gadgetsmenu. So could you implement it ?

Thanks !

**Comment by Waffles2112** [comment]
u mean like with the mysterydust? just with mysteryboxes?
& congrats, 100th issue!

**Comment by OnlyNoobDied** [comment]
i will add this feature

**Comment by TheIntelloBox** [comment]
Why closed ?

**Comment by PaulTDD-MC** [comment]
Because @OnlyNoobDied said he will add this feature ;)
