### ISSUE TITLE
BUG with Gadgets and hoppers !

### ISSUE THREAD

**Issue by TimHarrio** [OnlyNoobDied/GadgetsMenu#101]
When I use your plugin on my server, player using this (gadgets or suit) and shot on hopper the item as stocked on hopper and for diamonds fountains it's to OP ! Please correct this and sorry for my bad english.

**Comment by OnlyNoobDied** [comment]
i will fix this bug.

**Comment by murataktasli** [comment]
This bug is still going on. For example when you equip the ninja suit. You can shoot nether stars right into a hopper.

**Comment by OnlyNoobDied** [comment]
i knew it. i will fix this.

**Comment by YellowZaki** [comment]
Bump, it is a very important bug
