### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by OwenEerens** [OnlyNoobDied/GadgetsMenu#102]
I want to know how to add extra pets like a Enderman!

**Comment by OnlyNoobDied** [comment]
you cant

**Comment by OwenEerens** [comment]
But how did Hypixel add pets then? They added a Enderman and MANY more! I would like to see that in this plugin so the players have more choice and fun having pets!

**Comment by OnlyNoobDied** [comment]
Hypixel using their own plugin

**Comment by OwenEerens** [comment]
No they use a modified version of ur plugin! EVERYTHING is the same EXEPT the pets!

**Comment by OnlyNoobDied** [comment]
i am copying hypixel okay :/

**Comment by OwenEerens** [comment]
Well then you did a very good job at it!
