### ISSUE TITLE
No menu?

### ISSUE THREAD

**Issue by pearlthequeen** [OnlyNoobDied/GadgetsMenu#103]
Hi all, I am very new to this site and actually only made it to post this.
I downloaded and installed this plugin, however no one is spawning in with the menu.
In the config it is set that they should, so I don't think thats the problem.
The only time I actually get the menu is when I reload the plugin, and when I try to click a certain setting it doesn't work, It just picks up the block and moves it to my inventory.
Any help would be so very appreciated!

**Comment by PaulTDD-MC** [comment]
Did you click the item in your inventory, or did you try using the command /gmenu main?
If so, does it give you any errors in the console?

**Comment by pearlthequeen** [comment]
I clicked the menu, (nether star) and when it opened with all the options (hat, pet, etc) none of them were able to select. I'm not home right now, but I'll check the console as soon as I get back.

 Message-----

**Comment by PaulTDD-MC** [comment]
what's your  server version?
And do you use bukkit or spigot?

**Comment by OnlyNoobDied** [comment]
Bukkit server are not supported
