### ISSUE TITLE
All pets !

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#104]
Hello ! :D 

Could you add all the pets like the shulker, the llama, the evoker, etc ?
Ps : When is the new update ?

Thanks ! :D

**Comment by OnlyNoobDied** [comment]
no. it is not compatible with 1.8-1.11

**Comment by TheIntelloBox** [comment]
Do a system that the players of 1.8 doesn't have this pet in their GUI and the 1.11 players have it in their GUI.

**Comment by OnlyNoobDied** [comment]
I don't like this. All features in GadgetsMenu are able to use in any
spigot version

**Comment by TheIntelloBox** [comment]
So do a 1.8 version and a 1.11 version ?

**Comment by PaulTDD-MC** [comment]
That whould be a lot of work for maintenaince...
And Spigot doesn't support multiple versions of 1 content version.
