### ISSUE TITLE
Does anyone know the permisions for the mysterybox vault eg. gadgetesmenu.use.mysteryvault some thing like that?

### ISSUE THREAD

**Issue by TheRealTermin** [OnlyNoobDied/GadgetsMenu#106]
Does anyone know the permisions for the mysterybox vault eg. gadgetesmenu.use.mysteryvault some thing like that? Please let me know :)

TheRealTermin

**Comment by PaulTDD-MC** [comment]
It's on the wiki > Permissions.
But here they are:
```
 gadgetsmenu.mysterydust.add
 gadgetsmenu.mysterydust.check
 gadgetsmenu.mysterydust.pay
 gadgetsmenu.mysterydust.remove
 gadgetsmenu.mysterydust.set
 gadgetsmenu.mysterybox.give
 gadgetsmenu.mysterybox.giveall
 gadgetsmenu.mysterybox.mode
```

**Comment by OnlyNoobDied** [comment]
Note: You don't need permission to open Mystery Vault or Mystery Boxes.

If players cannot open Mystery Vault please set your Spawn Protection to '0'.
