### ISSUE TITLE
U_u Features

### ISSUE THREAD

**Issue by CoreMC1** [OnlyNoobDied/GadgetsMenu#11]
Use Google Translate :C

So,

You should added your own money system which ensures that only one player has access to a gadgets, because I use GroupManager (Simple to use)

System example:

Core_:
dracula-gadgets: true
smoke-particle: true

Do not display gadgets not buy.

**Comment by OnlyNoobDied** [comment]
there already have own coin system.Just view it in your config

**Comment by OnlyNoobDied** [comment]
you can customize the amount of credits in each cosmetic configuration.

**Comment by CoreMC1** [comment]
Yes but your plugin it add the permission: /

**Comment by OnlyNoobDied** [comment]
change the command to /manuaddp {PLAYER} {PERMISSION}

**Comment by CoreMC1** [comment]
Oh okay

**Comment by CoreMC1** [comment]
*Testing...*

**Comment by CoreMC1** [comment]
Nope :'(

**Comment by OnlyNoobDied** [comment]
why not?

**Comment by OnlyNoobDied** [comment]
you get errors?

**Comment by CoreMC1** [comment]
My server crash wait ... ;)

**Comment by OnlyNoobDied** [comment]
is it ok?
