### ISSUE TITLE
 Dust buying function and mystery boxes are useless!

### ISSUE THREAD

**Issue by Magino0088** [OnlyNoobDied/GadgetsMenu#110]
Hello,

1) If I create a Mysterybox and boxed all players and they open it even after 100 boxen no success unlocked it is all locked and also no success in sight.
2) If I give a player dust eg. 100 and the buys itself with it, it is the dust deducted but the purchased article does not freigeschalten.

Do I have something to adjust to Permissions or something else.
All additional plugins are Installed and everything runs on Spigot 1.11.2.
Please help!
Thank you!

LG
Magino

**Comment by PaulTDD-MC** [comment]
I'm confused...
What excactly is the problem?

**Comment by OnlyNoobDied** [comment]
what is your permissions plugin

**Comment by OnlyNoobDied** [comment]
[Link](https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-how-can-i-hook-mystery-dust-to-vaultplayerpointsfile-or-mysql-database)
