### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by mpivchev** [OnlyNoobDied/GadgetsMenu#112]
Any idea why this is happening?

`21.04 20:56:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
21.04 20:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811) [custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[custom_server.jar:git-Paper-1037]
21.04 20:56:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:29) ~[?:?]
21.04 20:56:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:68) ~[?:?]
21.04 20:56:39 [Server] INFO java.lang.NullPointerException
21.04 20:56:39 [Server] WARN Task #2480 for GadgetsMenu v3.6.17 generated an exception
21.04 20:05:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
21.04 20:05:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811) [custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[custom_server.jar:git-Paper-1037]
21.04 20:05:10 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:29) ~[?:?]
21.04 20:05:10 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:68) ~[?:?]
21.04 20:05:10 [Server] INFO java.lang.NullPointerException
21.04 20:05:10 [Server] WARN Task #6807 for GadgetsMenu v3.6.17 generated an exception
21.04 19:56:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
21.04 19:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:811) [custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[custom_server.jar:git-Paper-1037]
21.04 19:56:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.run(RewardSystem.java:29) ~[?:?]
21.04 19:56:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.utils.mysterybox.RewardSystem.cancel(RewardSystem.java:68) ~[?:?]
21.04 19:56:39 [Server] INFO java.lang.NullPointerException
21.04 19:56:39 [Server] WARN Task #2480 for GadgetsMenu v3.6.17 generated an exception`

**Comment by OnlyNoobDied** [comment]
i will fix this.

**Comment by mpivchev** [comment]
In the new update? When is it coming? Thanks in advance!

**Comment by OnlyNoobDied** [comment]
this issue will be fixed in the next update.
