### ISSUE TITLE
Give mystery box to all players in X group

### ISSUE THREAD

**Issue by Eufranio** [OnlyNoobDied/GadgetsMenu#114]
I want to give Mystery Boxes for players from the Donor rank, but they aren't always online and I wanted to deliver all boxes in a single command, how could I do that?

**Comment by PaulTDD-MC** [comment]
This plugin doesn't support that (yet). You could use a claim command. And set the claim for a one time use.

**Comment by Eufranio** [comment]
Develop my own plugin with that claim logic or does GadgetsMenu has that?

**Comment by PaulTDD-MC** [comment]
Nope, GadgetsMenu doesn't have such a feature (yet). You could make your own plugin or you could download one. You could use a plugin like [this ](https://www.spigotmc.org/resources/rewards-unlimited-rewards-possibilities.23383/) one.
I hope I helped you along. If not, I'd like to hear from you.
