### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by Someone-NEW** [OnlyNoobDied/GadgetsMenu#117]
i give sometime some spam like this maybe all are not the same:
http://imgur.com/a/QhU5z

**Comment by PaulTDD-MC** [comment]
Can you post your error in a http://hastebin.com/?
And tell us when this erorr occurs?

**Comment by Someone-NEW** [comment]
Its a picture you can see the same. its not just one spam like this i see a many spam like this but not always the same.

**Comment by PaulTDD-MC** [comment]
When does this occur?

**Comment by Someone-NEW** [comment]
https://hastebin.com/aburareyup.vbs
Here i copy all what i have from my log file only from GadgetsMenu is there tnx

**Comment by PaulTDD-MC** [comment]
@OnlyNoobDied take a look at this

**Comment by Someone-NEW** [comment]
? what?

**Comment by OnlyNoobDied** [comment]
i knew that and a new fix version will be release soon

**Comment by Someone-NEW** [comment]
This spam bug are so annoying :(  i hope you know what to do and will be update soon thank you.
