### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#119]
why does it say "Waffles2112 found a crate" to me when i'm Waffles2112
shouldn't it say "you won/found a crate"?
![2017-04-29_20 47 37](https://cloud.githubusercontent.com/assets/24687656/25560573/83d2c2cc-2d1d-11e7-8ec2-c0433a095e3e.png)

**Comment by OnlyNoobDied** [comment]
can you send me the config file

**Comment by Waffles2112** [comment]
[config - Copy.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/966884/config.-.Copy.zip)
sometimes it shows as "Waffles2112 found a crate" and other times it says "You've found a crate"
why does it randomly select between the 2?

**Comment by PaulTDD-MC** [comment]
The Waffles2112 founda crate message is a broadcast message. The other one is a personal message.

**Comment by Waffles2112** [comment]
i know that, but if im Waffles2112, why does it show the broadcast message and not the personal message
in the picture it doesnt show the personal message, it only shows the broadcast message

if im Waffles2112, i shouldnt see the broadcast message, just the personal message

**Comment by Waffles2112** [comment]
it switches between the 2 it shows me randomly and im very confused, like im suppost to always and only see my personal messages
not a broadcast of myself, and not both at the same time

**Comment by OnlyNoobDied** [comment]
i'm not sure what's the problem is. I need to test it.

**Comment by Waffles2112** [comment]
it randomly switches between a broadcast message and a personal message, when it shows that i won a crate
if its me, it should only, show the personal message, not randomly switch between broadcast and personal every time

**Comment by OnlyNoobDied** [comment]
fixed
