### ISSUE TITLE
Right-Click mystery boxes dont work for non-ops

### ISSUE THREAD

**Issue by Cactusje** [OnlyNoobDied/GadgetsMenu#120]
Hey, players with non-op cant right-click my mystery-boxes whats going on?

**Comment by OnlyNoobDied** [comment]
try to set your "spawn-protection" to '0'.

**Comment by Cactusje** [comment]
Nice, its work thanks @OnlyNoobDied

**Comment by dirtysololil** [comment]
Omg, thank dude!! @OnlyNoobDied
