### ISSUE TITLE
Mycel, GrassPath and Grass becoming dirt using CryoTube

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#122]
If you use CryoTube when you are over Mycel/GrassPath/Grass, the block becomes into Dirt and it can't be fixed back.

**Comment by Waffles2112** [comment]
if its dirt, wouldn't the neighboring grass/mycelium grow back over it like its suppost to?
i see the grass path issue though

**Comment by OnlyNoobDied** [comment]
don't worried. I will fix this

**Comment by OnlyNoobDied** [comment]
Resolved
