### ISSUE TITLE
Bugs with suits

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#125]
Bug 1: Mermaid suit can be taken from the GUI and the squid effect doesn't work

Bug 2: Command /gadgetsmenu equip doesn't work with suit items

**Comment by OnlyNoobDied** [comment]
I had written a message in plugin forum. You need to install Lib's Disguise
to use mermaid suit.

**Comment by YellowZaki** [comment]
And what about the command issue?

PD: when will the update be pushed with the recent bugfixes?

**Comment by PaulTDD-MC** [comment]
Soon

**Comment by OnlyNoobDied** [comment]
less than two days
