### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#126]
While having a gadget in slot X, press the number X in any place of your inventory and you'll get gadget copy which can be removed.

**Comment by YellowZaki** [comment]
Another issue about inventory: While plugin is enabled, I cannot move any item using the number keys in the inventory

**Comment by OnlyNoobDied** [comment]
> While having a gadget in slot X, press the number X in any place of your inventory and you'll get gadget copy which can be removed.

You means the gadget can be remove or cannot be remove?

**Comment by YellowZaki** [comment]
Cannot be*

**Comment by OnlyNoobDied** [comment]
1) The first bug only affect when you're in creative mode.

2) I disabled it because some player can use this shortcut key to move item (gadgets, selector) and rename it.

**Comment by OnlyNoobDied** [comment]
i will find a way to fix the second problem.

**Comment by YellowZaki** [comment]
A player in survival mode duped his gadget and I dont know how, he spawned a ocelot using ocelot egg from de Catapult gadget.

**Comment by OnlyNoobDied** [comment]
i found a bug.

**Comment by OnlyNoobDied** [comment]
fixed.

**Comment by YellowZaki** [comment]
You are still able to move gadgets in your inventory throught the number keys.

**Comment by OnlyNoobDied** [comment]
yup, but you cant rename or craft with it.

**Comment by YellowZaki** [comment]
But I have the plugin in a survival server, and players who do that, then they cannot remove it from inventory.

**Comment by YellowZaki** [comment]
Bump @OnlyNoobDied @PaulTDD-MC
