### ISSUE TITLE
Suggestion: Add Affect-Players to CATapult

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#127]
The tittle describes itself

**Comment by OnlyNoobDied** [comment]
CATapult gadget doesn't affect player.

**Comment by YellowZaki** [comment]
Yes, it damages players.

**Comment by OnlyNoobDied** [comment]
are you sure.

**Comment by YellowZaki** [comment]
Yes I am, launch the catapult to a player in survival mode.

**Comment by OnlyNoobDied** [comment]
can you send me your server ip? let me test it.

**Comment by YellowZaki** [comment]
geoblock.es

**Comment by OnlyNoobDied** [comment]
OnlyNoobDied

**Comment by YellowZaki** [comment]
Done. You can find people in /tienda (the shop warp) to test the catapult (try not to kill them :P)

Use /gmenu main

**Comment by OnlyNoobDied** [comment]
i am off. i will test it tomorrow

**Comment by YellowZaki** [comment]
On 1.11, fireworks damage to mobs and players was introduced. Is there a way to stop damage?

**Comment by OnlyNoobDied** [comment]
i will take a look

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
