### ISSUE TITLE
Suggestion - User Data

### ISSUE THREAD

**Issue by Jet315** [OnlyNoobDied/GadgetsMenu#129]
Please add the ability to prevent user data from saving.

**Comment by YellowZaki** [comment]
I want this too. Only for people who have used a comestic item sometime. Because there are a lot of userfiles empty (only vips one are filled)

**Comment by OnlyNoobDied** [comment]
noted

**Comment by OnlyNoobDied** [comment]
Added mystery boxes into user data so every player needed data file.
