### ISSUE TITLE
Gadget file

### ISSUE THREAD

**Issue by Pokekhan** [OnlyNoobDied/GadgetsMenu#131]
Hey there, today I update your plugin and i did what it said by changing the gadget.yml to oldgadget.yml and for some reason it has not work by it has not convert over the prices. from the old gadget file to the new one. 

I get this error: https://hastebin.com/nonozeheta.md

This is the version i am running: http://imgur.com/a/rDzPp

**Comment by TheIntelloBox** [comment]
Give me your file.

**Comment by Pokekhan** [comment]
https://hastebin.com/niwejicinu.bash

**Comment by Pokekhan** [comment]
That the gadget file i called oldgadget.yml

**Comment by TheIntelloBox** [comment]
Give me the file please.

**Comment by Pokekhan** [comment]
which file?

**Comment by Pokekhan** [comment]
https://www.mediafire.com/?01m86xogdj5xct1

**Comment by OnlyNoobDied** [comment]
what do you mean? The gadgets file data doesn't copy to 'oldgadgets.yml' file?

**Comment by Pokekhan** [comment]
I mean the prices that i set in the old version has not moved over to the new version of the config.  Also after doing some a few other tested. I disabled few gadgets in the old config and there have not been moved over to the new gadget config.

**Comment by OnlyNoobDied** [comment]
old data will not copy to new gadgets file. You need to do with yourself
