### ISSUE TITLE
Banner Maker Creator.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#132]
Hello ! :dagger: 

In the menu, in "Banners", I think it would be very nice to add a banner creator, and the players will can save their banners. :)
What do you think ? :)

Thanks ! :D

**Comment by Waffles2112** [comment]
i like the idea, i would also suggest add ability to edit the main menu's display banner

**Comment by OnlyNoobDied** [comment]
Added in the new development version.
