### ISSUE TITLE
Paintball blacklist MOB_SPAWNER not working

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#136]
My players are converting any kind of mobspawners to pig mobspawners by shooting them with the paintball gadget. I set on the blacklist: MOB_SPAWNER but it didn't work.

**Comment by PaulTDD-MC** [comment]
We will test this

**Comment by PaulTDD-MC** [comment]
I have tested it and for me it just works fine. Are you sure you have put the MOB_SPAWNER on a correct way on the blacklist?

**Comment by PaulTDD-MC** [comment]
This is what it should look like:
```  
Paintball Gun:
    BlackList:
    - SAND
    - GRAVEL
    - MOB_SPAWNER
```

**Comment by YellowZaki** [comment]
Yes:

      Paintball Gun:
        Name: Pistola de paintball
        Radius: 3
        BlackList:
        - SAND
        - GRAVEL
        - MOB_SPAWNER
        Cooldown: 3
        Mystery Dust: 10
        Rarity: Common
        Enabled: true
        CanBeFound: true
        Purchasable: true
        Lore:
        - '&7What better way to spruce up'
        - '&7the lobby than with a'
        - '&7little color? Or a lot,'
        - '&7who''''s counting?'

**Comment by YellowZaki** [comment]
With the Paint Trail gadget, players can also become any kind of mobspawner into pig spawner.

**Comment by PaulTDD-MC** [comment]
Hmm... Weird... I tested this on my test server today. I used the latest version of GadgetsMenu and Spigot version 1.11.2. Didn't interact with the mobspawner at all

**Comment by YellowZaki** [comment]
Could you join my server now? I'm online, do "/msg YellowZaki I'm Paul".
I will show you,
IP: geoblock.es

**Comment by PaulTDD-MC** [comment]
yeah

**Comment by PaulTDD-MC** [comment]
can't msg...

**Comment by YellowZaki** [comment]
https://pastebin.com/RETaLcCt

**Comment by YellowZaki** [comment]
06.05 17:59:30 [Server] WARN java.lang.ArithmeticException: / by zero
06.05 17:59:30 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetCategoryManager.inventorySkull(GadgetCategoryManager.java:262)
06.05 17:59:30 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetCategoryManager.openCategoryGadgetsMenu(GadgetCategoryManager.java:81)
06.05 17:59:30 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.selectItem(MainMenuManager.java:259)
06.05 17:59:30 [Server] WARN at com.yapzhenyie.GadgetsMenu.cosmetics.mainmenu.MainMenuManager.onInvClickMainMenu(MainMenuManager.java:195)
06.05 17:59:30 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor736.execute(Unknown Source)
06.05 17:59:30 [Server] WARN at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
06.05 17:59:30 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
06.05 17:59:30 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
06.05 17:59:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
06.05 17:59:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1898)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
06.05 17:59:30 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
06.05 17:59:30 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
06.05 17:59:30 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
06.05 17:59:30 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by OnlyNoobDied** [comment]
Fixed both bugs including paintball gun blacklist doesn't working and "java.lang.ArithmeticException: / by zero" error.
