### ISSUE TITLE
Suggestions & Testing new gadgets for errors (all errors posted)

### ISSUE THREAD

**Issue by KroterPvP** [OnlyNoobDied/GadgetsMenu#137]
**Suggestions:**
> Can you add the "note pling" song to Gadgetsmenu? It should sound when you click items from the gui, select gadgets...

> The crafting Mysteryboxes menu doesn't have an arrow to return to mysterybox main menu.

**Error on startup:**
> https://pastebin.com/Rz2930cH

**Tetherball Gadget error:**
> https://pastebin.com/ESdnkjX1

**Jukebox Gadget error:**
> https://pastebin.com/zifNaMe0

**Original thread posted on Gadgetsmenu discussion:**
> https://www.spigotmc.org/threads/gadgetsmenu-1-8-1-11-2.85227/page-47#post-2399571

**Comment by Waffles2112** [comment]
Personally i have not received any of these errors, except for a different tetherball related error,

and couldn't you just esc or E out of the craft mystery box menu to exit it, then reenter to access the mystery boxes?

i second the first suggestion as well

**Comment by KroterPvP** [comment]
So why I have theese errors?

Yes, esc makes you close the crafting mysteryboxes menu, but an arrow is needed couse it will make it more pretty and usefull.

Thanks :)

**Comment by OnlyNoobDied** [comment]
Sound: BLOCK_NOTE_PLING

**Comment by OnlyNoobDied** [comment]
1.Error on startup is fixed.

Tetherball Gadget error and Jukebox Gadget error is unfixable, so I disable this two gadgets on 1.8 server.
