### ISSUE TITLE
Word of warning when you reload your server

### ISSUE THREAD

**Issue by JulsOSpel** [OnlyNoobDied/GadgetsMenu#14]
When i reload my server with a pet out it duplicates the mob and you can't kill them they will just act like the pets the way to stop this try to kick the player that did this that some times fixs it but if the dos not work then restart the server then you can kill the mobs!

proof: http://www.mediafire.com/view/1fhz3bl4npqi8x2/2016-08-31_19.10.24.png

**Comment by OnlyNoobDied** [comment]
looking for it.

**Comment by OnlyNoobDied** [comment]
did you get any errors from console?

**Comment by OnlyNoobDied** [comment]
New Update: https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-9-1-10.10885/

this bug may be fixed.
