### ISSUE TITLE
Magic 9 Ball Suggestion!

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#141]
you should add "Bob Ross says: There are no mistakes, only happy accidents."
to the Magic 9 Ball Gadget

**Comment by OnlyNoobDied** [comment]
sure. By the way you can add custom messages

**Comment by Waffles2112** [comment]
i know, i just want every one to experience it and not just my server

**Comment by OnlyNoobDied** [comment]
:D
