### ISSUE TITLE
Client crashes in 1.11.2

### ISSUE THREAD

**Issue by TNG-China** [OnlyNoobDied/GadgetsMenu#148]
When I morph to entity then my client will be crashes:
```
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: java.lang.Boolean cannot be cast to di
```
I use latest version 3.7.1.

**Comment by OnlyNoobDied** [comment]
please post the whole error

**Comment by TNG-China** [comment]
@OnlyNoobDied No more, This error from client, That it all.

**Comment by OnlyNoobDied** [comment]
Try to redownload Lib's Disguise and ProtoclLib plugin.

https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs

**Comment by PaulTDD-MC** [comment]
Server version?
Lib's Disguise version?

**Comment by TNG-China** [comment]
@PaulTDD-MC 
Lib's Disguises: v.9.3.0-SNAPSHOT
ProtocolLib: v4.2.1
Server: paperclip-1095
Client: 1.11.2

**Comment by PaulTDD-MC** [comment]
paperclip? Never heard of that 😄

**Comment by TNG-China** [comment]
@OnlyNoobDied It's latest version both.

**Comment by TNG-China** [comment]
@PaulTDD-MC PaperSpigot

**Comment by OnlyNoobDied** [comment]
try to use this version.
https://www.spigotmc.org/resources/libs-disguises.81/download?version=127323

**Comment by TNG-China** [comment]
@OnlyNoobDied I tried, Client still crashes. But I found change this userdata to false, That will be ok. Why?
`Settings:
  Morphs-Self-View: false`

**Comment by OnlyNoobDied** [comment]
i tested latest paperspigot server but i didn't get any error.

**Comment by TNG-China** [comment]
[http://img.hb.aicdn.com/f1020fcb71e1f6abdc1c5b31f5f1061d2940dc6628ac-0j1FPt_fw658](url)
This error from my client, I use vanilla 1.11.2 client, Is not in server.

**Comment by OnlyNoobDied** [comment]
it's not a image.

**Comment by OnlyNoobDied** [comment]
your server version and your client version is same?

**Comment by TNG-China** [comment]
Sure, 1.11.2 both.

**Comment by TNG-China** [comment]
Paperspigot is latest version, Of course support 1.11.2.

**Comment by TNG-China** [comment]
I download paperspigot in this page: [https://ci.destroystokyo.com/job/PaperSpigot/](url)

**Comment by TNG-China** [comment]
Maybe is not your plugin error, I tried /d cow command the client crash too, I'll report to LibsDisguises auther.

**Comment by OnlyNoobDied** [comment]
okay

**Comment by TNG-China** [comment]
@OnlyNoobDied Thanks for your help.

**Comment by OnlyNoobDied** [comment]
did you solve the problem?
