### ISSUE TITLE
[Suggestion] MiniaturePets support

### ISSUE THREAD

**Issue by TNG-China** [OnlyNoobDied/GadgetsMenu#152]
Any chance add support MiniaturePets? This plugin has very interesting pet.
[https://www.spigotmc.org/resources/%E2%8C%BE-miniaturepets-%E2%8C%BE-custom-mobs-great-for-eula.23991/](url)

**Comment by OnlyNoobDied** [comment]
We have our own miniatures so we won't add this feature. If you need to link MiniaturePets, you can use 3rd menu plugin to create your own main menu.
