### ISSUE TITLE
Error in console 1.9+

### ISSUE THREAD

**Issue by Pokekhan** [OnlyNoobDied/GadgetsMenu#153]
Hello I am getting this error every time someone logout of the hub:

https://hastebin.com/awitudovan.bash

This is the version i am running at the moment : 

https://gyazo.com/eead502689b7391c67c640a61c15356e

**Comment by Jet315** [comment]
Same

**Comment by OnlyNoobDied** [comment]
you disable mystery boxes?

**Comment by OnlyNoobDied** [comment]
fixed.
