### ISSUE TITLE
Taking items out of the gui.

### ISSUE THREAD

**Issue by shaun246** [OnlyNoobDied/GadgetsMenu#159]
I've recently found a bug where if you shift click repeatedly on a item in the gui and someone is joining the server while you are doing that it lets you take the item out of the gui and keep it.

**Comment by PaulTDD-MC** [comment]
Even when you relog?

**Comment by OnlyNoobDied** [comment]
what gamemode you're using when you do this action

**Comment by shaun246** [comment]
survival

**Comment by OnlyNoobDied** [comment]
ok. I knew this issue for a long time, but i can't disable players using shift-click to exchange item. If i disable this option, you are not able to use shift-click to change items anymore.
