### ISSUE TITLE
Enderchest stay in the air after server reboot

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#160]
HI I found an issue :(

Sometimes, the enderchest stay in the air:
![image](https://cloud.githubusercontent.com/assets/5159244/26036688/91089630-38b0-11e7-892c-1663adfdf6aa.png)

I need to right-click the ender-chest to remove it from the air BUT this will give it to me, this can be a glitch depends of the players permissons, gamemode, etc :(

This happen when server restart sometimes.

Any way to prevent this?

Thanks you

I have: 
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by Waffles2112** [comment]
how do you have so many bugs, thats what i really want to know

**Comment by maxlehot1234** [comment]
I don't know but I just report them.

**Comment by PaulTDD-MC** [comment]
Just don't reload the server while a mystery chest is being opend...

**Comment by OnlyNoobDied** [comment]
i will fix this. :D
