### ISSUE TITLE
Discoball gadgets with another player near it error.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#161]
When using the discoball gadgets with another player around me, this generate this error in the console:
https://pastebin.com/1xbyAJYa

Thank you

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by OnlyNoobDied** [comment]
you means two players activate two discoball gadgets at the same time?

**Comment by maxlehot1234** [comment]
I mean, if I enable it and another player just came "inside" particles to jump and listen the music, the console generate the error.

I can check later if this was related to .nbs that not been updated or removed when I use it.
Or maybe something to remove this error and replace it by a simple line.

**Comment by maxlehot1234** [comment]
It was related to file edit.

Never happen again. I close this.
