### ISSUE TITLE
broadcaster music gadget and morph error

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#162]
When using broadcaster music gadget, it disappear when I try to choose a morph. BUT if I choose a morph first and then select the broadcast music gadget, I keep the morph. 

Any way to fix this?

Thanks you

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by OnlyNoobDied** [comment]
gadget and morph skill are in the same slot. When you selected gadget then select morph,your gadget will be remove.Otherwise, when you morphed then select a gadget, you can still maintain your morph."morph skill" is not so important, so you can still maintain morph and use gadget.
