### ISSUE TITLE
Starter mystery dust doesn't work.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#163]
The starter mysterydust, doesn't work. I try to reload the plugin and restart the server, not work...

Thank you

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by OnlyNoobDied** [comment]
if your data is saved in database, even you change starter mystery dust in config, it won't change in the database. The only way is to remove data from database.

**Comment by maxlehot1234** [comment]
But this doesn't explain why it doesn't give 50 mystery dust on first player join.

So what is the purpose of this feature if it doesnt work?
