### ISSUE TITLE
2 mystery box open at the same time, double chat message

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#164]
When I try to open 2 mysterybox at a time, the message was disaplyed twice in the chat instead of one...

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by OnlyNoobDied** [comment]
This issue is depends on what block you have set as mystery vault. I can't fix this problems because it cause by minecraft.

**Comment by OnlyNoobDied** [comment]
This issue is depends on what block you have set as mystery vault. I can't fix this problems because it cause by minecraft.

**Comment by maxlehot1234** [comment]
I set it to be on stone...

How this can be a minecraft issue?
