### ISSUE TITLE
Broadcast continue to be disaplyed even if I disable them

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#165]
I remove every broadcast EXCEPT for legendary but other continue to be broadcasted :( Since it spam the chat, I want to broadcast message only when player found a legendary loot.

The config part:
    Found-Loot:
      Enabled: true
      Message:
        Legendary: '&b[Mystery Box] {PLAYER} &bvient de trouver &6Legendaire {ITEM}&b!'
        Common: '&b[Mystery Box] {PLAYER} &bfound a &aCommon {ITEM}&b!'
        Rare: '&b[Mystery Box] {PLAYER} &bfound a &9Rare {ITEM}&b!'
        Epic: '&b[Mystery Box] {PLAYER} &bfound a &5Epic {ITEM}&b!'

I removed Common, Rare and Epic line, since I just want to broadcast when a Legendary item was get, but if I removed those lines and reload the plugin, they are added back....

Any way to prevent this ?

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by PaulTDD-MC** [comment]
How did you remove them?
Just to be sure you did it correct :)

**Comment by maxlehot1234** [comment]
I removed them like this (already explain in the report :) )
I removed Common, Rare and Epic line

So I keep ONLY the legendary line to broadcast legendary only.

**Comment by PaulTDD-MC** [comment]
How did you remove it?
Can you send your configuration section?

**Comment by OnlyNoobDied** [comment]
You can only enable or disable all broadcast. You can't just remove Common, Rare... message, it won't work.
