### ISSUE TITLE
Morph double item glitch?

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#166]
Hi, I just see that when I use morph, players have double item...
![image](https://cloud.githubusercontent.com/assets/5159244/26036856/2b03d1d4-38b4-11e7-915b-e9391d213692.png)

I don't know if its you or lib disguise but thats weird.

Thanks

I have:
- Spigot 1.11.2
- Java 8
- GadgetsMenu version 3.7.2

**Comment by PaulTDD-MC** [comment]
This is a bug to do with Libs disguise..

**Comment by Waffles2112** [comment]
its just client side/happenes to everyone
