### ISSUE TITLE
[Suggestion] Add option to disable few broadcast

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#168]
In this, I HIDE: Opening-Mystery-Box section to make my suggestion more easy to understand.

I just want to know if you can add something to remove some Found-Loot broadcast message.

I just want to display Legendary message broadcasted, but NEVER display Common, Rare and Epic, since they are not so special and unique ;)

Legendary items are "unique" and just these should be displayed on my server.
![image](https://cloud.githubusercontent.com/assets/5159244/26182925/7cbfeaac-3b49-11e7-93d2-8591277ff062.png)

Maybe you can add something to remove broadcasted message when they are set like this: 
![image](https://cloud.githubusercontent.com/assets/5159244/26182938/8b36565c-3b49-11e7-9ade-63e3528fd9d7.png)

Thank you and hope you can add this.

**Comment by PaulTDD-MC** [comment]
#165

**Comment by OnlyNoobDied** [comment]
ok, i will add a option to disable each message

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
