### ISSUE TITLE
Disable skill for morph. Slimeball still be show in the inventory

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#169]
Hi, I disable the ability for ALL morphs, but the slimeball was continue to be disaplayed into the player hotbar.

Is it possible to hide it, since it was not useful if skills are disabled.

I disabled them, because I prefer if you can replace the slimeball by SHIFT or right-click in the air action instead.

Thank you

**Comment by OnlyNoobDied** [comment]
Sure, i am remake whole plugin and i will fix this problem too.
