### ISSUE TITLE
Disabled worlds issue 

### ISSUE THREAD

**Issue by K0alalalala** [OnlyNoobDied/GadgetsMenu#17]
When in a disabled world, if you try to click any item it would say you don't have permission to do that.

Please fix that :D Thanks :) <3

**Comment by OnlyNoobDied** [comment]
when you run a command or selecting cosmetic

**Comment by K0alalalala** [comment]
When you click any item in a disabled world

**Comment by OnlyNoobDied** [comment]
fix it soon
