### ISSUE TITLE
[Bug?] The dust and box amount are not the same in the gui and hotbar item

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#171]
Hi, the dust (Poussières mystères) and mysterybox ( Boîtes à surprises) are not the same in the gadgetmenu GUI and the gadget item in the player hotbar.

![9ypkhd7bdk](https://cloud.githubusercontent.com/assets/5159244/26273641/d4f8a614-3d01-11e7-8637-420f7c8f2e53.gif)

I need to logout and login again to fix this...

Any way to make it the same?

Thank you

**Comment by OnlyNoobDied** [comment]
I need to make it "reset item lore" every times player open the gui?

**Comment by maxlehot1234** [comment]
If you can without lags, it could be great ;)

Thanks again

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
