### ISSUE TITLE
[Suggestion] Make the song replay to fit the duration set in config

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#174]
Any way to make the song restart automatically without delay to fit the duration set in the gadgets.yml?

With this, If I set 60 seconds and song was 30 second, it play again automatically another time.

It can be nice ;)

**Comment by OnlyNoobDied** [comment]
Can't. The Discoball Gadget will automatically deactivate after the duration is ended, because it will repeat the song forever
