### ISSUE TITLE
[Bug] The Bumblebee suit wasn't stop when player stop flying and touch the ground

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#178]
Hi, when players get the Bumblebee suit and fly, song start, fine, but when they touch the ground, the sound continue sometimes..

Any way to stop it when they touch the ground since it was supposed to play when player flying or left click...

Thanks. So sorry for issues by me :(

**Comment by OnlyNoobDied** [comment]
There're two ways to activate bumblebee song.
fly or left-click

if you left-click to activate song, it won't stop when you on the ground
