### ISSUE TITLE
[Suggestion] Add a new placeholder %gadgetsmenu_unlocked_total%

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#179]
Hi, is it possible for you to add a new placeholder like: %gadgetsmenu_unlocked_total%

This will show the total things unlock by the player.

So in fact, it make a total of all percentage to make the big total and allow devs to get this value into their plugins (placeholderapi, leaderheads, etc)

Thank you so much if you can do this ;) It could be really nice

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
