### ISSUE TITLE
Cant use Rainbow Wardrobe

### ISSUE THREAD

**Issue by Ordust** [OnlyNoobDied/GadgetsMenu#18]
Hey, 

everytime i try to use the rainbow wardrobe it only says in chat "reset you rainbow wardrobe" but i cant wear ist.. 

I hope you can help me, i love your plugin ! 

Greetings, 
Ordust

**Comment by OnlyNoobDied** [comment]
can you give me your server ip?

**Comment by Ordust** [comment]
projectcube.eu - but i havent set permissions for normal users.. atm i'm at work, i can give you the permissions at 8:00 p.m (German Time) (in 6 hours), is that ok ?

**Comment by OnlyNoobDied** [comment]
ok

**Comment by Ordust** [comment]
Now you can join on the Server if you want

**Comment by OnlyNoobDied** [comment]
Found the bug.

**Comment by Ordust** [comment]
Can you solve it ?

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/releases/tag/v3.5.8

Fixed

**Comment by OnlyNoobDied** [comment]
fixed?

**Comment by Ordust** [comment]
yeah ! works like a charm ! Thank you very much ♥

**Comment by OnlyNoobDied** [comment]
:D

**Comment by Ordust** [comment]
I saw you was on my server, im atm at work you can rech me on my server at 8 p.m german time (20:00 German Time) -> http://www.worldtimeserver.com/current_time_in_DE.aspx

**Comment by OnlyNoobDied** [comment]
in survivalgame server?

**Comment by Ordust** [comment]
i think in server minigames, thats our prebuild server. You can do a "/friend add Ordust" and then a "/friend jump Ordust" to get teleported to me :)
