### ISSUE TITLE
[Suggestions] Add more mobs

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#180]
Hi, I just want to know if you can add more mobs into pets cosmetics?

http://minecraft.gamepedia.com/Mob

It can be really nice and add more and more things to your amazing plugin.

Thank you so much for reading.

**Comment by OnlyNoobDied** [comment]
If i add new mobs, it does not compatible with 1.8 & 1.9

**Comment by maxlehot1234** [comment]
I know, but you can add them and add a config to enable/disable them like now.

How many people continue to use old version?

**Comment by OnlyNoobDied** [comment]
https://bstats.org/plugin/bukkit/GadgetsMenu#minecraftVersion

100++ servers using 1.8

**Comment by maxlehot1234** [comment]
Ok :( I see some plugin create options that are available only for 1.10 for example, but these things doesn't work before 1.10

I try :(

**Comment by OnlyNoobDied** [comment]
okay, i will add some new mobs in new update
