### ISSUE TITLE
[Suggestion] Add particles categories and add more particles.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#181]
Hi the categories can be:
- spirals
- sphere
- cones
- tornado
- trail
- auras
- etc

Each categorie contain a lot of particles.

So at the end, we can have a big total of more than 200 particles.
Each of tehm can be purchase or get inside loots.

This can be amazing.

I love to make plugins better with my ideas. If I am a dev, plugins will be too big to be uploaded on websites XD

**Comment by OnlyNoobDied** [comment]
These feature will be added in cloaks.

**Comment by maxlehot1234** [comment]
Any news for this? Since it can be nice for particles too ;)

**Comment by OnlyNoobDied** [comment]
It's hard to add these types of particle, because some of the particles doesn't compatible with that type.

**Comment by Matocolotoe** [comment]
Categories are just way to display particles, why would there be compatibility problem ?
