### ISSUE TITLE
Gadgets Menu 1.12.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#182]
Hello ! :D 

All is in the title : could you update Gadgets Menu to 1.12 : Pre-Release 5 and for 1.12 ? :D 

Thanks ! :D 
TheIntelloBox.

**Comment by OnlyNoobDied** [comment]
Actually i silently added 1.12 support on 3.7.4 update.

Notice: MySQL doesn't work on 1.12, i haven't fix that issue yet.
