### ISSUE TITLE
[Suggestion] Add gui to open mysterybox instead of full anim

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#183]
Hi, is it possible for you to create a csgo mysterybox opening or other style?

With this, I can select only 1 block/NPC and multiple players can click on the block/npc to open their mysterybox. This will also reduce few lags and allow multiple players at the same at the same time.

Thats would be better I think for big serers.

Imagine with 500 players that need to open mysterybox :P

**Comment by OnlyNoobDied** [comment]
There's a lot of mystery boxes plugin. You can use it.
