### ISSUE TITLE
[Bug?] Problem with collision

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#184]
Hi, minecraft add collisions few versions ago, so I used this plugin/patch; https://www.spigotmc.org/resources/no-collision-with-patch-only-spigot-1-9-1-11-2.26347/

It works great when I don,t use morphs, pets, etc, but directly when I use a morph, I am push back by another player if I touch him with my body. Smae thing happen if I touch a NPC.

Is it possible to add something inside your plugin for this?

Thank you.

**Comment by OnlyNoobDied** [comment]
I think this will not cause the game balance.
