### ISSUE TITLE
[Suggestion] Disable Bumblebee music when player hold X item

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#186]
Hi, is it possible to disable the Bumblebee music and left click action when the player get X item in hand like:
blacklist:
    - DIAMOND_PICKAXE
    - DIAMOND_SWORD

This can be really useful, since I doesn't use your plugin on a lobby, but on my Prison server. This was an amazing plugin for more than the lobby ;)

Thank you so much.

**Comment by OnlyNoobDied** [comment]
Added an option to turn off bumblebee song by left clicking again with an empty hand
