### ISSUE TITLE
[Suggestion] Paintball Gun Gadget. Add option to choose blocks

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#187]
Hi, is it possible in the new version to choose the block of the gadget, so this will not fuck with custom texturepack and prevent weird things? Since on my server the Stained-Clay (159) are used for luckyblocks.

Maybe something like:
blocks:
    - BEDROCK
    - COAL_BLOCK
    - 18

We can use ID or names of the items, this could be really nice and useful ;)

Thank you so much

**Comment by OnlyNoobDied** [comment]
You can edit blocks that you do not want to replace colour clay in gadgets.yml.

```
Paintball Gun:
        Name: '&aPaintball Gun Gadget'
        Radius: 3
        BlackList:
        - SAND
        - GRAVEL
        - MOB_SPAWNER
```

**Comment by maxlehot1234** [comment]
Any way to add whitelist, since I just want wool to be used... Thank you so much ;)

**Comment by maxlehot1234** [comment]
I try to blacklist all STAINED_CLAY, but doesn,t work.

What I need to do to add :1,:2, :3, :4, etc ?

Thanks

**Comment by OnlyNoobDied** [comment]
The new material format has been added in the new version.
