### ISSUE TITLE
[BIG BUG] Bug with the diamond item shower gadget move on slot 1

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#188]
Hi, when I used this gadget and spam it, it was moved on slot 1.

When I disable the gadget or all cosmetics, this one simply wont remove from the inventory.

I need to ./ci (clear my inventory) to remove it from my inventory.

This is really bad, since ./ci command was deny from my players for security reasons.

Any way to fix this?

Thank you

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
