### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by ItsRevoz** [OnlyNoobDied/GadgetsMenu#19]
i cant find out how i can give my players credits..
can you help me?

**Comment by OnlyNoobDied** [comment]
/menu creditsadd <player> <amount> : Add credits.
/menu creditscheck <player> : Check current credits.
/menu creditspay <player> <amount> : Pay credits to another player.
/menu creditsremove <player> <amount> : Remove credits.
/menu creditsset <player> <amount> : Set credits.
