### ISSUE TITLE
[Console error BUG] Player firstjoin problem+mysterydust issue

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#190]
Hi,

I open a test server and when a player join for the first time, I get this in the console:
https://pastebin.com/40RTu9hE

Is it normal? 

Normally it was supposed to receive 500 Mystery Dust, but he received only 499, why?

Please help me with this as soon as possible,

Maxime.

**Comment by OnlyNoobDied** [comment]
can you send the playerdata file of that player to me?

**Comment by maxlehot1234** [comment]
https://pastebin.com/CS43XGFp

There it is. Happen 1 time only on 10 players. But this will probably happen again in the future.

**Comment by maxlehot1234** [comment]
Another issue with a new player. I don't know why but it seems to be related when they get a mysterybox when they join the server for the first time.

**Comment by maxlehot1234** [comment]
Problem again with a new player when he join for the first time: https://pastebin.com/dEnqn1cK

**Comment by OnlyNoobDied** [comment]
noted. i will check it tomorrow.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Again: https://pastebin.com/1b9s2NQZ

**Comment by OnlyNoobDied** [comment]
I think this is mystery boxes issue, did you edit any of them in the playerdata?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
No I edit nothing in the playerdata. I never edit players datas from plugins, because I know that can create a lot of errors.
Now, when I join: https://pastebin.com/5z3e2DGy
I give mysterybox on players first join. It was related to this for sure, but how I can fix this?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied It happen again. Okay. I stop to comment on this and wait for a permanent fix ;)

Thanks if you can fix this as soon as possible, since it spam the console on each firstjoin

**Comment by OnlyNoobDied** [comment]
try this version
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Contiinue to have the problem on latest gadgetmenu version :(

**Comment by OnlyNoobDied** [comment]
can you send the error messages to me?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
It was on this issue, but there it is: https://pastebin.com/5z3e2DGy

Same error when a new player join the server. It happens 3 times on 4

**Comment by OnlyNoobDied** [comment]
This issue should be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
@maxlehot1234 please inform me if this issue still appearing.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I try but players simply won't receive mysteryboxes :(

I use an external plugin: https://www.spigotmc.org/resources/content-management-interface.3742/
When a firstjoin event was executed, players should receive mysteryboxes, but after 4.0.0 of gadgetmenus, it doesn't work :(

I will check tonight when I back at my home

**Comment by OnlyNoobDied** [comment]
I think you need to modify the command.

**Comment by maxlehot1234** [comment]
Everything was fine now ;)

Thank you
