### ISSUE TITLE
[Suggestion] Add mysterydust and mystery box when players use mysterybox

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#194]
Hi

My players just have a really nice idea for your plugin:

They want something to allow them to get mysterybox (verry low chance) and mystery dust when they open their mysterybox.

I know you give mysterydust when they already have the cosmetics, but get mysterydust and/or mysterybox when they open one, it could be really nice.

Thank you :)

Sorry for my bad english.

**Comment by OnlyNoobDied** [comment]
I think it will make mystery boxes worthless.
