### ISSUE TITLE
Using /hat when wearing a hat

### ISSUE THREAD

**Issue by BiGUNMAN** [OnlyNoobDied/GadgetsMenu#195]
Players can steal the hats by using /hat (essentials) while wearing a hat from the GadgetsMenu hats options. Can you add a "disabled commands" when doing certain actions, such as the following described above.

Worldguard regions in which gadgets are disabled would also be a much appreciated feature.

**Comment by OnlyNoobDied** [comment]
ok

**Comment by BiGUNMAN** [comment]
@OnlyNoobDied Also, would be very useful for banners and suits (any cosmetics where you put things on your head in short).
