### ISSUE TITLE
Playerpoints issue

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#197]
I nocited when i receive playerpoints and i try to open myster vault and try to purchase the chest, it say that i don't have anought money,  it is fixed when i relog, can be fixed?

**Comment by OnlyNoobDied** [comment]
ok, got it.

**Comment by xion87** [comment]
any plain when it will be fixed?, because i am using a automatic playerpoint reward (similiard to carl the creeper of hypixel) and the tokens don't get update, and many user don't know that they need to re-enter in hub for fix it

**Comment by OnlyNoobDied** [comment]
Tonight UTC+8

**Comment by OnlyNoobDied** [comment]
Try this version.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-11-2.10885/

**Comment by xion87** [comment]
Hi i tried the latest version, it completly broke the placeholder support

**Comment by xion87** [comment]
but tokens now work perfect, but i would like that you fix also the {placeholder gadgetsmenu_mystery_dust}

**Comment by OnlyNoobDied** [comment]
how it breaks placeholder?

**Comment by xion87** [comment]
it showing  {placeholder gadgetsmenu_mystery_dust} instead the dust number, was working fine on old update. i am using it on feather board scoreboard.
