### ISSUE TITLE
I found some bugs

### ISSUE THREAD

**Issue by 1434967947** [OnlyNoobDied/GadgetsMenu#199]
frist you can collect items which summoned by Gadgets by hopper
second you can't pvp while using Morphs
third Suits will add player's armour

**Comment by OnlyNoobDied** [comment]
1)Which gadget did you summoned?
2) I'm not suggested you install this plugin on pvp/survival server.
3) suits will definitely increase armor.

**Comment by 1434967947** [comment]
1. Poop Bomb
2. I want to make an server likes blockhunter
3. Bat Launcher sometimes can summon unlimited bat untill the server being stopped(I don't know why this will happen’)

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
