### ISSUE TITLE
Resets config when i do /menu reload

### ISSUE THREAD

**Issue by techano** [OnlyNoobDied/GadgetsMenu#20]
Hello i recently installed this plugins as a part of my creative plot world but when i adjust it to say &8Undead World's gadgets and disable worlds and change the name of the item to the &8undead world's gadgets and it keeps reseting the config for now i am not using this as some players could use this to there advange in skyblock and survival please fix soon!
 
here are the server logs

[latest.txt](https://github.com/OnlyNoobDied/GadgetsMenu/files/460866/latest.txt)

Edit

- Fixed

- You can't use a ' in the prefix

**Comment by OnlyNoobDied** [comment]
so, there's no bug?

**Comment by techano** [comment]
no but i did discover one when in a diasabled world when player try to eat
apples or put on armor it says you dont have permission to use that here
and i have seen a 20% increase in cpu usage

**Comment by OnlyNoobDied** [comment]
ok

**Comment by OnlyNoobDied** [comment]
fix it soon
