### ISSUE TITLE
Is there a website with the same heads as in the plugin?

### ISSUE THREAD

**Issue by Reimzon** [OnlyNoobDied/GadgetsMenu#201]
Hello! Is there a website with the same heads as in the plugin?
P.S: Again wrote the text through a translator. (May be errors)

**Comment by OnlyNoobDied** [comment]
do you means hat texture?

**Comment by k1z1** [comment]
yeah, textures hats, are you have ?

**Comment by OnlyNoobDied** [comment]
i'm using minecraft mojang skin texture.

**Comment by OnlyNoobDied** [comment]
All skin texture will be stored in Mojang's Database.
