### ISSUE TITLE
Menu Item Suggestion

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#204]
please add the config ability to make the join item only appear in certain worlds
like if they switch to a world where its enabled, they'd recieve the item.

**Comment by OnlyNoobDied** [comment]
```
Enabled-Worlds:
- world
```
Already have it in config :/

**Comment by Waffles2112** [comment]
no, thats for all the cosmetics, im talking about just the join item/hotbar item
like enable/disable worlds which you would receive the item, without affecting being able to access the menu and its cosmetics

**Comment by OnlyNoobDied** [comment]
Actually it's same with "enabled-worlds".

You will not be given a menu selector or equip a cosmetic in the world that you didn't set in 'enabled-worlds'.
