### ISSUE TITLE
Placeholder Dust contator broken with recent release

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#205]
Hi in recent release dust ccount is broken, it stoped to work from 3.7.6+ release, i already told that placeholder don't work :(

**Comment by OnlyNoobDied** [comment]
What placeholder you set? it supposed to be %gadgetsmenu_mystery_dust%

**Comment by xion87** [comment]
i am using {placeholderapi_gadgetsmenu_mystery_dust} on featherboard, on 3.7.5 it work fine, instead with 3.7.6 and 3.7.7 it show {placeholderapi_gadgetsmenu_mystery_dust} without loading the placeholder

**Comment by OnlyNoobDied** [comment]
You use it on featherboard plugin?

**Comment by xion87** [comment]
Yeah on featherboard plugin (latest release)

**Comment by OnlyNoobDied** [comment]
Do you enable placeholderAPI in featherboard config?

**Comment by xion87** [comment]
yeah, as i told was working all fine before the gadgetsmenu upgrade, if i return with 3.7.5 it work again

**Comment by OnlyNoobDied** [comment]
em, did you saw a message when GadgetsMenu plugin loaded

> [Placeholder] PlaceholderAPI hooked.

**Comment by xion87** [comment]
[05:00:54] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.7.7
[05:00:54] [Server thread/INFO]: [GadgetsMenu] [Placeholder] PlaceholderAPI hooked.
[05:00:54] [Server thread/INFO]: [GadgetsMenu] [MysteryDust] PlayerPoints hooked.

**Comment by OnlyNoobDied** [comment]
try this command
/papi parse %gadgetsmenu_mystery_dust%
if doesn't work, please tell me

**Comment by xion87** [comment]
was working, the issue was caused by featherboard... i replaced it with another plugin and now is all working great

**Comment by OnlyNoobDied** [comment]
okay
