### ISSUE TITLE
You can purchase non-purchasable suits

### ISSUE THREAD

**Issue by Maxetto** [OnlyNoobDied/GadgetsMenu#207]
Even if you put "Purchasable: false" inside the Suits category, you can buy suit parts despite the "Item Unpurchasable" inside Lore.

I had to put an extremely high Dust value in order to workaround that. (Also, you can't put more than 999999999 as Dust value :P)

**Comment by OnlyNoobDied** [comment]
Fixed. Thank you for reporting this bug.
