### ISSUE TITLE
Cooldown bar bug

### ISSUE THREAD

**Issue by Maxetto** [OnlyNoobDied/GadgetsMenu#208]
When set the length of the bar to less than 100 (50 for me), it will start to work only after the percentage you entered.

Example:
If I set 50 as the bar length and use a Gadget with a cooldown of 10 seconds, the bar will start to change at 5s.

**Comment by OnlyNoobDied** [comment]
Fixed. Due this is not a big issue, i will not post on the forum. Please download it from this link.
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0
