### ISSUE TITLE
InventoryClickEvent Problem

### ISSUE THREAD

**Issue by topthat177** [OnlyNoobDied/GadgetsMenu#209]
Hi, I just installed your plugin and it looks great so a big thumbs up from me, however I cant seem to get it to work. I just purchased the latest version of Lib's proto and disguises and I have the latest version of this plugin running on spigot 1.12. There seems to be some sort of error or exception when the plugin launches and when i open /gmenu main and click on something, nothing opens and i can take the item from the inventory which is strange and it spits an error into the console. Also i dont get the nether star on join and I'm OP.

There is a console Pastebin here: https://pastebin.com/YFBdmW37

I also have chatcontrol installed which is spitting out an error that im not sure about as well which can also be seen at that link if that could be a problem (PacketEvent error or something.)

Any help would be much appreciated as I would really love to use this plugin

**Comment by OnlyNoobDied** [comment]
you're not using spigot. You're currently running craftbukkit server

**Comment by topthat177** [comment]
Only just noticed that, I thought craftbukkit was needed to run spigot. Should I delete this and run spigot then? ie. is that the problem?

**Comment by OnlyNoobDied** [comment]
you need to delete craftbukkit and install spigot

**Comment by topthat177** [comment]
Thankyou so much, this plugin is awesome! Love you work 🗡

**Comment by OnlyNoobDied** [comment]
You're welcome :)
