### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by ChristianPtr** [OnlyNoobDied/GadgetsMenu#21]
Hi!
I am trying to give some gadgets and cosmetics to only for VIPS.
Who could i do that? I try to negete that permissions to the users.
For examaple i want only the Doge hat for the vips. so what i do is.
On the Users group use:
- -gadgetsmenu.hats.doge
And users can still buy it and use it.

**Comment by OnlyNoobDied** [comment]
you cannot just give the hat only for VIP, Any player can buy the hat.

**Comment by ChristianPtr** [comment]
So i can put some gadgets, hats, particles only for VIP?

**Comment by OnlyNoobDied** [comment]
no, all players can purchase items if you enabled it in config.yml

**Comment by ChristianPtr** [comment]
Okey, thanks for your time! It will be a good idea o to add some gadgets for X users :P

**Comment by OnlyNoobDied** [comment]
i will add an option only for VIP.

**Comment by ChristianPtr** [comment]
Okey, thanks for your time!

**Comment by OnlyNoobDied** [comment]
added
