### ISSUE TITLE
Setting a message to '' prints a blank line

### ISSUE THREAD

**Issue by Maxetto** [OnlyNoobDied/GadgetsMenu#210]
Setting a message to '' prints a blank line. How can I put a line to not show at all? (Like Broadcasting Common rewards)

**Comment by OnlyNoobDied** [comment]
which message you do not want to show at all?

**Comment by Maxetto** [comment]
Found-Loot.Message.Common

from the config.yml

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
