### ISSUE TITLE
Disable Fly when using Parachute gadget

### ISSUE THREAD

**Issue by Maxetto** [OnlyNoobDied/GadgetsMenu#211]
If you previously had Fly enabled (or enable it during the Parachute effect) the chickens will stay until you touch ground.

This can bring to unknown and undesiderable effects, like breaking the leads under some blocks, making the chicken free and leaving a lead drop.

**Comment by OnlyNoobDied** [comment]
Ok, i will add this in the next version.

**Comment by xion87** [comment]
+1 for this, i allow my vips to fly around the hub, so it can lead this issue

**Comment by OnlyNoobDied** [comment]
Solved.
