### ISSUE TITLE
Morphs are buggy in 1.8.8

### ISSUE THREAD

**Issue by TheGamingChris** [OnlyNoobDied/GadgetsMenu#212]
If you choose a morph is 1.8.8, the world and all blocks are invisible.

Pictures:

http://www.bilder-upload.eu/show.php?file=0f76de-1497903356.png
http://www.bilder-upload.eu/show.php?file=a6b9d7-1497903411.png
http://www.bilder-upload.eu/show.php?file=6032fe-1497903425.png
http://www.bilder-upload.eu/show.php?file=b2b2ec-1497903436.png

**Comment by TheGamingChris** [comment]
And the consol say: You moved too quickly!

**Comment by Maxetto** [comment]
Use ProtocolLib 3.6.5

It's not an issue of GadgetsMenu.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs
