### ISSUE TITLE
Vault Error

### ISSUE THREAD

**Issue by SkylessCraft** [OnlyNoobDied/GadgetsMenu#216]
Hello there

I have an issue with vault and gadgetmenu.
Once I hook GMenu with vault, GMenu will no longer work and give out this error message:
https://pastebin.com/y4DTQiuM
I am using Spigot 1.10.

Thanks

**Comment by OnlyNoobDied** [comment]
Try this
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by SkylessCraft** [comment]
It is now giving out this error message:
https://pastebin.com/0rXWCYCr

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
