### ISSUE TITLE
Tetherball Bug [Version 3.7.8]

### ISSUE THREAD

**Issue by Dwarvencraft** [OnlyNoobDied/GadgetsMenu#217]
When I spawn in the Tetherball gadget a second pole spawns next to the initial one, and a second, non-leashed chicken spawns, which is killable. 
IMAGE: https://imgur.com/a/lXgoH

Really appreciate it if you could fix this!

-Dwarvencraft Network

**Comment by OnlyNoobDied** [comment]
what is your server version?

**Comment by Dwarvencraft** [comment]
We run Spigot 1.9 but use ViaVersion to support newer client versions.

**Comment by OnlyNoobDied** [comment]
Fixed. Please check new update
