### ISSUE TITLE
GadgetsMenu 3.78 Error flood spam

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#218]
After the gadget on vault foundable i start to having these ocasionally spam
https://pastebin.com/FEMGSJFB

**Comment by OnlyNoobDied** [comment]
I couldn't found any issue from the code. After you can reload/restart the server, you might not get this error again.

**Comment by xion87** [comment]
I keep to receive this error each day, i never have before 3.7.8 (in 3.7.7 i never see this error) update, it pretty spammy and create huge logs (around 100-500mb log)

**Comment by OnlyNoobDied** [comment]
What is your server version? 1.8.8?

**Comment by xion87** [comment]
1.8.8 + viaversion

**Comment by OnlyNoobDied** [comment]
test this.
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by xion87** [comment]
I am using it right now and i get this error first https://pastebin.com/UpLqG8ZZ (not sure if is related) and some minutes later the flood: https://pastebin.com/k03iSHFR

**Comment by OnlyNoobDied** [comment]
i can't found any problems from the code. Are you using latest 1.8.8 spigot?

**Comment by xion87** [comment]
yeah latest 1.8.8 + via version, i am using also titlemanager in same server

**Comment by OnlyNoobDied** [comment]
when this error occur, any message shows you in actionbar?

**Comment by OnlyNoobDied** [comment]
i think i fixed.
test this version.
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by xion87** [comment]
that error disapear, now i got another one: https://hastebin.com/lakugufiga.bash (seem to be related with mobgun)

**Comment by OnlyNoobDied** [comment]
Fixed.
