### ISSUE TITLE
Dublicated Pets :o

### ISSUE THREAD

**Issue by Ordust** [OnlyNoobDied/GadgetsMenu#22]
Hey, 

my pets dublicates themselve, do you know this bug ? 

I dont know if this is an bug of this plugin or Minecraft, if you want to see is i'm atm on my server. 

Greetings !

**Comment by OnlyNoobDied** [comment]
can you give me server ip?

**Comment by Ordust** [comment]
Oh sorry.. sure it's projectcube.eu. We found another bug, sometimes when a player joins the server they got a full inventory of the gadgetselector and they cant remove the other selectors. I have to clear their inventory to fix this. Sorry for reporting this much :c

**Comment by OnlyNoobDied** [comment]
oh.. ok

**Comment by OnlyNoobDied** [comment]
i will fix the bug tomorrow,it's night now

**Comment by Ordust** [comment]
okay, good night :3

**Comment by OnlyNoobDied** [comment]
did you change the selector name before the player logging.

**Comment by Ordust** [comment]
no, i changed nothing on the plugin

**Comment by OnlyNoobDied** [comment]
there's lots bug when server have many players.I didn't test the plugin on large server :(

**Comment by Ordust** [comment]
my server isnt released jet, we have only our builders and admins on the server :) If you want you can test your plugin on our server, i will give you the permissions you need

**Comment by OnlyNoobDied** [comment]
i didn't saw any players on your server 0.0 Everyday 0 player online

**Comment by Ordust** [comment]
We have another time zone than you :D you joined at 4 a.m. German Time zone :D

**Comment by OnlyNoobDied** [comment]
lol

**Comment by OnlyNoobDied** [comment]
i'm now in your server and gotta close xD

**Comment by Ordust** [comment]
This guy on the Server "EL145" had the bug with the full inventory with the selector

**Comment by OnlyNoobDied** [comment]
i can help you the plugin on your server

**Comment by Ordust** [comment]
Nice ! <3 you're the best developer !

**Comment by OnlyNoobDied** [comment]
add me on skype (yapzhenyie)
