### ISSUE TITLE
"You can't use gadgets in this area"

### ISSUE THREAD

**Issue by flipsiide** [OnlyNoobDied/GadgetsMenu#220]
Is it possible to make a region or something so players do not spam the gadgets directly at the spawn point?

**Comment by OnlyNoobDied** [comment]
Yes, i'm trying to make this feature.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next updates.

I will add some custom flags to disable specific cosmetic in the region.
Required WorldGuard 6.2+ plugin.
