### ISSUE TITLE
You can move gadgets on inventory using the number key

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#221]
The title describes itself.

**Comment by OnlyNoobDied** [comment]
i know

**Comment by YellowZaki** [comment]
But there are others plugins that uses item menu which can't be moved from slots in any way. Could you see the code?

**Comment by OnlyNoobDied** [comment]
sure. which plugin?

**Comment by YellowZaki** [comment]
ItemJoin for example.

Here is its src: https://github.com/RockinChaos/ItemJoin

**Comment by YellowZaki** [comment]
I think this is the code:

https://github.com/RockinChaos/ItemJoin/blob/dca027d82037fefa1e4badee826e7082af999192/src/me/RockinChaos/itemjoin/Listeners/InventoryClick.java

**Comment by OnlyNoobDied** [comment]
ok. This bug will be fixed in the next version.

**Comment by YellowZaki** [comment]
Thanks a lot.

**Comment by OnlyNoobDied** [comment]
Don't you mind this bug will be fixed in the next major update which will release on August.

**Comment by YellowZaki** [comment]
August is too late, could you fix it now? (If you haven't time, don't worry)

**Comment by OnlyNoobDied** [comment]
ok, i will update tomorrow

**Comment by OnlyNoobDied** [comment]
Should fixed.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/updates

**Comment by YellowZaki** [comment]
Yes, it works perfect.
Thanks.

**Comment by YellowZaki** [comment]
@OnlyNoobDied I have just updated the plugin to the newest version and this bug have came back :(

**Comment by OnlyNoobDied** [comment]
Did you test it in creative mode?

**Comment by YellowZaki** [comment]
In survival mode with no permissions.

**Comment by OnlyNoobDied** [comment]
Can you describe to me how you move the item with numeric key? Because i tested many times, and i didn't found anything.

**Comment by YellowZaki** [comment]
Imagine you have a gadget on slot 0. Now open your inventory, move your pointer to another slot on inventory and press key 1.

You fixed it, but it is now occuring again. See above.

**Comment by OnlyNoobDied** [comment]
Try the latest version.

**Comment by YellowZaki** [comment]
It works! Thanks.

**Comment by OnlyNoobDied** [comment]
okay. It's a bug.
