### ISSUE TITLE
Any commands with "*" all permissions not working

### ISSUE THREAD

**Issue by CryptoMorin** [OnlyNoobDied/GadgetsMenu#222]
I'm trying to use      - gadgetsmenu.particles.*
using Groupmanager but it only works if you make permission for each particle like - gadgetsmenu.particle
All wont work (None will) with the permission     - gadgetsmenu.particles.*

GroupManager2
GadgetsMenu v3.7.10
Java 8 Build 131
Spigot 1.12

**Comment by OnlyNoobDied** [comment]
I tested on my server. It's worked. I think you may typed the permission wrongly.
