### ISSUE TITLE
Cant give random quality of mystery boxes

### ISSUE THREAD

**Issue by TheGamingChris** [OnlyNoobDied/GadgetsMenu#224]
If you type in "/gmysteryboxes give TheGamingChris 10" it wont work. It shows the help for the command, but normally [quality] means, that the quality is not neccesary.

**Comment by OnlyNoobDied** [comment]
You can't give player random quality mystery boxes

**Comment by TheGamingChris** [comment]
Why is "quality" in this brackets [ ]. This brackts mean that this isn't neccesary. Please edit this to < > in your description and in the plugin-help!

**Comment by OnlyNoobDied** [comment]
okay, i will change that.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
