### ISSUE TITLE
Cooldown disable permission

### ISSUE THREAD

**Issue by GuusKamphuis** [OnlyNoobDied/GadgetsMenu#225]
it would be nice to have a permission to change cooldowns but now every one can change it

example: gadgetsmenu.cooldown.toggle to disable and enable cooldowns

**Comment by OnlyNoobDied** [comment]
You can use this permission 'gadgetsmenu.cooldown.bypass'

**Comment by OnlyNoobDied** [comment]
It can be use when you gave player perm (gadgetsmenu.commands.*)

**Comment by GuusKamphuis** [comment]
ok thx
