### ISSUE TITLE
Bug when disabled cosmetics

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#229]
If, for example the player unlock the parachute gadget and this is the ONLY mouvment gadget he have and I disable it, the player continue to see that he have an available gadget:
![image](https://user-images.githubusercontent.com/5159244/27973140-01084d9a-6327-11e7-9454-5df92df49e8c.png)

But he have nothing since it was disabled in the config:
![image](https://user-images.githubusercontent.com/5159244/27973157-0fcc2428-6327-11e7-935a-4cc3e302bc93.png)

I need to remove the permission to players to fix this issue...
So is it possible to add a check for it to prevent this?

**Comment by OnlyNoobDied** [comment]
i will try my best.

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
