### ISSUE TITLE
USEBUG !!! Items can be drop when using a  gadget on slot XXXX

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#230]
Hi, It is just to told you, that if a player put something on slot 9 and get a gadget, his item simply drop on the ground and other player can take it :(

IS it possible to fix this in the next version?

Thank you so much

**Comment by Waffles2112** [comment]
this is ment to happen..
if a gadget is suppost to go where an item is
the item will drop on the floor
it only makes sense

**Comment by Waffles2112** [comment]
leave the gadget slot to slot 6 as its the least used slot

**Comment by maxlehot1234** [comment]
Good point, BUT, why you don't prevent the gadget to be put into the player inventory if the slot is used?

You can maybe send  a chat message to the player ask him to "free-up" the gadget slot to prevent this?

**Comment by Waffles2112** [comment]
there are reasons the plugin does certain things
perhaps not make gadgets so accessable to worlds that are this big of a problem by removing the players perms to use any gadget in that world?

**Comment by OnlyNoobDied** [comment]
slot 9 is not available. you can only set the value between 0-8
