### ISSUE TITLE
PaperSpigot issue with Broadcast Radio Gadget

### ISSUE THREAD

**Issue by Sam1370** [OnlyNoobDied/GadgetsMenu#231]
Have paperspigot 1.11.2 and latest gadgetsmenu version.
the broadcast radio gadget sometimes makes the server unresponsive

**Comment by Waffles2112** [comment]
the next update should remove the lag
i have the same version of paperspigot 1.11.2, i havent had any problems like that

**Comment by Sam1370** [comment]
Okay, thanks :D

**Comment by OnlyNoobDied** [comment]
I removed this gadget and change it to personal radio gadget.
