### ISSUE TITLE
Problem with pets that are not removed from the server

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#232]
Hi, sometimes, pets are simply stay at a player position and if he teleport to another world /warp or left the server, his pet stay and was not removed...

This is really bad.
![image](https://user-images.githubusercontent.com/5159244/28291915-b55dd148-6b1a-11e7-8e26-61e073189e81.png)

If you can fix this, it could be really nice. Thank you so much.

**Comment by OnlyNoobDied** [comment]
ok

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
