### ISSUE TITLE
You check update on the main thread? Any way to check it async?

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#235]
Hi, I just installed LagMonitor plugin on my server and I have an error.

The dev told me that it comes from Gadgets Menu that run update check on the main thread and that it should be run async.

https://www.spigotmc.org/threads/lagmonitor.137799/page-11#post-2560317

Any way to change this on next update ;) ?

Thank you so much and I really want to see the next MAJOR update

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this bug. I will fix it soon,

**Comment by OnlyNoobDied** [comment]
Should be fixed on the next update.
