### ISSUE TITLE
Permissions to Open Mystery Boxes

### ISSUE THREAD

**Issue by operation283** [OnlyNoobDied/GadgetsMenu#238]
I'm trying to replicate Hypixel's way of opening mystery boxes, where you must have a rank to open a mystery box of a certain level.  I was wondering if you could add permissions for players to open mystery boxes, such as gadgetsmenu.mysterybox.open.1 for opening a 1-star mystery box.  That would be really awesome.

Thanks.

**Comment by OnlyNoobDied** [comment]
ok. I will add some permission for each boxes.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

Example:
```
gadgetsmenu.mysteryboxes.open.1 - Allows player to open 1 star mystery box.
gadgetsmenu.mysteryboxes.open.2 - Allows player to open 2 star mystery box.
gadgetsmenu.mysteryboxes.open.3 - Allows player to open 3 star mystery box.
gadgetsmenu.mysteryboxes.open.4 - Allows player to open 4 star mystery box.
gadgetsmenu.mysteryboxes.open.5 - Allows player to open 5 star mystery box.
```

**Comment by abyashab** [comment]
when i open mystery box its says you dont have permission error ............................ pls solve

**Comment by yapzhenyie** [comment]
> when i open mystery box its says you dont have permission error ............................ pls solve

you need to give yourself the permissions.
`gadgetsmenu.animations.normal`
Check the full permission list here.
<https://github.com/yapzhenyie/GadgetsMenu/wiki/Permissions>
