### ISSUE TITLE
plugins CPU occupancy factor is too high !!!

### ISSUE THREAD

**Issue by MEshitou** [OnlyNoobDied/GadgetsMenu#239]
There is no error in this plugin, but the occupancy rate of CPU is really high.
Through timings, we see the problem caused by PlayerJoinEvent.
Now I'll give my timings link. I hope someone can help me out
https://timings.spigotmc.org/?url=hokubepofo

**Comment by OnlyNoobDied** [comment]
Okay, i will optimize the code on the next update.

**Comment by OnlyNoobDied** [comment]
@
This issue would be fixed in the next update.
