### ISSUE TITLE
The plugin dont run with 1.10

### ISSUE THREAD

**Issue by LecraM2003** [OnlyNoobDied/GadgetsMenu#24]
The plugin dont run with 1.10

**Comment by OnlyNoobDied** [comment]
did you get errors from console?

**Comment by LecraM2003** [comment]
Yes, [17:33:42 ERROR]: Could not load 'plugins/GadgetsMenu.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/OnlyNoobDied/GadgetsMenu/GadgetsMenu : Unsupported major.minor version 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)

**Comment by OnlyNoobDied** [comment]
do you try reload/restart the server?

**Comment by LecraM2003** [comment]
yes two times

**Comment by OnlyNoobDied** [comment]
i will solve the problem tomorrow.

**Comment by OnlyNoobDied** [comment]
you're running java 8?

**Comment by LecraM2003** [comment]
No, java 7.

**Comment by OnlyNoobDied** [comment]
required java 8

**Comment by LecraM2003** [comment]
ok i test with java 8

**Comment by LecraM2003** [comment]
i have test it and it doesnt is working. :(

**Comment by LecraM2003** [comment]
hello?

**Comment by LecraM2003** [comment]
It works now! Thank you!

**Comment by OnlyNoobDied** [comment]
i just woke up lol
