### ISSUE TITLE
Issue on start

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#243]
Line 76: [17:19:21] [Server thread/INFO]: [GadgetsMenu] Loading GadgetsMenu v3.7.10
	Line 76: [17:19:21] [Server thread/INFO]: [GadgetsMenu] Loading GadgetsMenu v3.7.10
	Line 778: [17:19:44] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.7.10
	Line 778: [17:19:44] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v3.7.10
	Line 779: [17:19:44] [Server thread/INFO]: [GadgetsMenu] [Placeholder] PlaceholderAPI hooked.
	Line 780: [17:19:44] [Server thread/INFO]: [GadgetsMenu] [mChecking for updates...[m
	Line 781: [17:19:45] [Server thread/ERROR]: Error occurred while enabling GadgetsMenu v3.7.10 (Is it up to date?)
	Line 783: 	at com.yapzhenyie.GadgetsMenu.updater.UpdaterChecker.<init>(UpdaterChecker.java:34) ~[?:?]
	Line 784: 	at com.yapzhenyie.GadgetsMenu.updater.UpdaterManager.checkUpdate(UpdaterManager.java:36) ~[?:?]
	Line 785: 	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:208) ~[?:?]
	Line 785: 	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:208) ~[?:?]
	Line 785: 	at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:208) ~[?:?]
	Line 797: [17:19:45] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v3.7.10
	Line 797: [17:19:45] [Server thread/INFO]: [GadgetsMenu] Disabling GadgetsMenu v3.7.10

**Comment by OnlyNoobDied** [comment]
there was an issue while using spigot 1.12.1. I will fix it tonight.

**Comment by OnlyNoobDied** [comment]
Please try the new update.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=180714
