### ISSUE TITLE
Particles just on head

### ISSUE THREAD

**Issue by GodOfDeadBush** [OnlyNoobDied/GadgetsMenu#245]
Hi!
When I go on the particle menu and I click on a particle, I haven't the menu to choose the particle on the head, on the, body, random, on leggings...
I just have the particle on my head when I click.

I'm sorry for my english, I'm french.
Good luck and good game for your work,
GodOfDeadBush.

**Comment by OnlyNoobDied** [comment]
This option has been removed.
