### ISSUE TITLE
Players Dont Get gadgets when opened

### ISSUE THREAD

**Issue by tobilub04** [OnlyNoobDied/GadgetsMenu#246]
on my server, players when open their mysteryboxes(given by admin, i dont know how can get them otherwise) they dont get the items inside,

**Comment by OnlyNoobDied** [comment]
You need to setup the permission in config.yml which depends on your permission plugin.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust

**Comment by OnlyNoobDied** [comment]
Close issue due to
