### ISSUE TITLE
[Suggestion] Confirmation before reset cosmetics

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#247]
Is it poSsible to add something that force the player to confirm that want to reset all his cosmetics/gadgets or anything. Maybe by open another guii that was split into TWO (2) color, green= confirm and red=reject, keep gadget/cosmetics

Thank you if you can ;)

**Comment by OnlyNoobDied** [comment]
I think this is useless, what's the function for?

**Comment by TheIntelloBox** [comment]
Yes it's useless. ;)
