### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by VenomPCPL** [OnlyNoobDied/GadgetsMenu#248]
Why the latest version of the plugin does not work with minecraft 1.7.X - 1.8.X (spigot). The server simply does not read the plugin.

**Comment by OnlyNoobDied** [comment]
please send me the errors and the version of your server.

**Comment by VenomPCPL** [comment]
But in the console or the game?

Game version 1.7.X - 1.8.X.

**Comment by OnlyNoobDied** [comment]
in the console.

**Comment by VenomPCPL** [comment]
[14:32:00 INFO]: VenomPCPL issued server command: /gadgetsmenu
[14:32:20 INFO]: VenomPCPL issued server command: /gadgetsmenu about
 There are no errors. This plugin just does not exist.

**Comment by OnlyNoobDied** [comment]
i need the server log when you start the server.

**Comment by VenomPCPL** [comment]
[latest.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/1234990/latest.zip)

**Comment by OnlyNoobDied** [comment]
1) GadgetsMenu plugin only support 1.8-1.12 spigot, 1.7 are not supported.
2) require 1.8 java to run this plugin too.

Seen like  there're lots of plugins doesn't working due to 1.7 java.
