### ISSUE TITLE
[Suggestion] add mysql reconnect

### ISSUE THREAD

**Issue by ansontse09** [OnlyNoobDied/GadgetsMenu#249]
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from 
the server was 84,279,919 milliseconds ago.  The last packet sent successfully to the server was 84,279,919 milliseconds ago.
 is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection 
 validity before use in your application, increasing the server configured values for client timeouts, 
or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

when server startup about one day mysql will timeout lost connect so need to add autoReconnect

**Comment by OnlyNoobDied** [comment]
I already knew this issue. Please wait for the next update.
