### ISSUE TITLE
A question to change the command for open the menù

### ISSUE THREAD

**Issue by Cri16228** [OnlyNoobDied/GadgetsMenu#25]
Hi. I have installed your plugin in my server but I have the same command /menu with another plugin (chestcommand) it's possible to change the command for gadgetsmenu in /gmenu? Or if possible create a version for me.
Thanks

**Comment by OnlyNoobDied** [comment]
you can also use /gmenu or /gadgetsmenu for gadgetsmenu plugin.

**Comment by Cri16228** [comment]
Yes i know but i use itemjoin to set item on login and when i set "command: menu" on compass i see gadgetmenu help and i can't set gadgetsmenu and chestckmmand

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/pkhbfe5xc88axvy/GadgetsMenu.jar?dl=0

**Comment by OnlyNoobDied** [comment]
command: /gadgetsmenu , /gmenu

**Comment by Cri16228** [comment]
A modified version?

**Comment by OnlyNoobDied** [comment]
yup

**Comment by Cri16228** [comment]
Now I can't see gadgets http://imgur.com/a/h9ajL (deleted gadgetsmenu folder in /plugin)

**Comment by OnlyNoobDied** [comment]
wait.

**Comment by OnlyNoobDied** [comment]
fixed.
https://www.dropbox.com/s/pkhbfe5xc88axvy/GadgetsMenu.jar?dl=0

**Comment by Cri16228** [comment]
Now work correctly, thanks :)

**Comment by OnlyNoobDied** [comment]
:)

2016年9月16日 11:20 PM，"Cri16228" <notifications@github.com>写道：
