### ISSUE TITLE
Do not shut down server to update the plugin

### ISSUE THREAD

**Issue by RoboMWM** [OnlyNoobDied/GadgetsMenu#252]
So I know you have some great auto-updater; that's all fine and dandy. But what is _not_ okay is shutting down the server to load in the new, updated plugin! Just wait until the server is shutdown by the owner/a schedule instead, like every other plugin that auto-updates.

Also, your auto-updater doesn't do a great job on Windows, so I'm just stuck with the server constantly being shut down. You should download your file to the `plugins/update` folder, where CraftBukkit will automatically pull in the new, updated jar on the next server boot.

Thanks!

**Comment by Bradisswag** [comment]
Same issue while updating to the latest version.

**Comment by OnlyNoobDied** [comment]
You can turn off this feature.

**Comment by RoboMWM** [comment]
Yes, I'm aware the auto-update feature can be disabled; but I am suggesting a way to improve your auto-updater, which has issues when the plugin's jar file is locked.

**Comment by OnlyNoobDied** [comment]
This issue has been solved. Now it will not restart the server itself.
