### ISSUE TITLE
GadgetsMenu doesn't work?

### ISSUE THREAD

**Issue by oRaid** [OnlyNoobDied/GadgetsMenu#253]
Dear yapzhenyie, GadgetsMenu isn't loading on my server, I updated to the newest version and it isn't loading, Plugman doesn't like it and says it's not a valid plugin. If you could get this fixed ASAP that would be nice!

Thanks,
~oRaid

**Comment by maxlehot1234** [comment]
Everything works for me?

Which server version? Did you removed all files for the plugin like suggested?

**Comment by HellaMixel** [comment]
Make sure you download the latest version of WorldGuard 6.2.1

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.

**Comment by oRaid** [comment]
Thanks!
