### ISSUE TITLE
Jukebox gadgets doesn't work [4.0.0]

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#254]
Hi, the jukebox gadget doesn't work. No sounds work :(

I can get the gadgets use it and click on disk, by I have no sounds :(

Other music gadgets works

Thanks again for the update

**Comment by OnlyNoobDied** [comment]
What's your server version?

**Comment by maxlehot1234** [comment]
1.12.1

**Comment by OnlyNoobDied** [comment]
I tested it, it's working. Did you turn off Jukebox/Note blocks sound in your personal settings?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Personal settings?

**Comment by maxlehot1234** [comment]
FIX, music are disabled from my minecraft. I am so stupid to do reports like this, you can close it.

Sorry for this.
