### ISSUE TITLE
Placeholders for Featherboard don't work

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#255]
I downloaded PlaceHolderAPI and put %gadgetsmenu_mystery_dust% which didn't work 3.7.11 nor 4.0.0
For FeatherBoard I had {placeholderapi_gadgetsmenu_mystery_dust} which worked before the newest update 4.0.0
Not sure what to do.

**Comment by OnlyNoobDied** [comment]
You need to setup the config in your FeatherBoard folder
