### ISSUE TITLE
Plugin disables after restart/reload

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#258]
The plugin will completely unload itself from the plugin list in /pl in-game but the plugin stays in my FTP-Plugins folder. I have to use plugman to load the plugin in after I restart/reload my server

**Comment by maxlehot1234** [comment]
DO NOT RELOAD THE SERVER....

Any server log?
Console error?

We need something to help you

**Comment by OnlyNoobDied** [comment]
I already mention that you need to delete all files before using this version. Otherwise it will disable for the first time due to replacing the data to the new file.

**Comment by HellaMixel** [comment]
I did delete all the files and jar file and put the new jar in

**Comment by OnlyNoobDied** [comment]
Did you get any messages in console that plugin disable itself
