### ISSUE TITLE
Crafting*

### ISSUE THREAD

**Issue by xSoaz** [OnlyNoobDied/GadgetsMenu#259]
Okay so i Connecting the GadgetMenu plugin 
with mySql, + The Mystery Dust.

But there is an issue. when i try to Craft a mystery Box it says that it costs 0 Dust,
i go to the price and says 100 for the Mystery Box #1 
i change it but still is the same.. it says Cost: 0
How to fix this? (Is it beacuse i use Sql?)

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I confirm that I have the same issue...

That's a really big issue and players will abuse it really soon

**Comment by OnlyNoobDied** [comment]
I need messages.yml file.

**Comment by OnlyNoobDied** [comment]
I found the problem. Change the price format without quotation marks
