### ISSUE TITLE
Morph "Abilities" Not Working

### ISSUE THREAD

**Issue by camcielinski** [OnlyNoobDied/GadgetsMenu#26]
Hi,

Today I noticed that the morph abilities that are mentioned in the lore do not work. It says activate the ability by right-clicking the slimeball in your inventory but there is no slimeball. Please help, other than that great plugin! :)

-camcielinski

**Comment by OnlyNoobDied** [comment]
sorry i haven't add pet abilities yet.

**Comment by camcielinski** [comment]
Oh, OK. I was just confused because it is in the morph descriptions. Thanks!

**Comment by OnlyNoobDied** [comment]
i have a lot of features need to add so i think the abilities isn't the most important thing. I will add in next update.
