### ISSUE TITLE
Error when I give mysterydust to another player [4.0.0]

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#260]
Hi, I just try this command:
./mysterydust pay playername100000

And I see this in the caht:
![image](https://user-images.githubusercontent.com/5159244/29848662-3a05cf62-8cf0-11e7-8da2-844c2ca0637e.png)

Problem with the placeholder?

**Comment by OnlyNoobDied** [comment]
Fixed. Please check new update
