### ISSUE TITLE
Error occured when I giveall XX mysteryboxes [4.0.0]

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#262]
Hi, I try to run this command:
/gmysteryboxes giveall 1

And I get this in the chat:
![image](https://user-images.githubusercontent.com/5159244/29849083-8d2ca6aa-8cf2-11e7-9b18-2ca5122244b9.png)

And this in the console:
https://pastebin.com/YLmNgs4T

Thanks and sorry for the spam

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
