### ISSUE TITLE
Internal Error when running /gmenu

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#263]
29.08 19:59:22 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'gmenu' in plugin GadgetsMenu v4.0.0
29.08 19:59:22 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at com.gmail.filoghost.customjoinitems.ItemCommand.execute(ItemCommand.java:124) [CustomJoinItems.jar:?]
29.08 19:59:22 [Server] INFO at com.gmail.filoghost.customjoinitems.JoinItem.executeCommands(JoinItem.java:196) [CustomJoinItems.jar:?]
29.08 19:59:22 [Server] INFO at com.gmail.filoghost.customjoinitems.PlayerListener.onInteract(PlayerListener.java:113) [CustomJoinItems.jar:?]
29.08 19:59:22 [Server] INFO at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
29.08 19:59:22 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
29.08 19:59:22 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
29.08 19:59:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.08 19:59:22 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:git-Spigot-db6de12-18fbb24]
29.08 19:59:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [custom.jar:git-Spigot-db6de12-18fbb24]

Always shows this:

Caused by: java.lang.IllegalAccessError: tried to access method com.yapzhenyie.GadgetsMenu.commands.main.SubCommand.onCommandPlayer(Lorg/bukkit/entity/Player;[Ljava/lang/String;)V from class com.yapzhenyie.GadgetsMenu.commands.main.CommandManager
29.08 20:00:27 [Server] INFO at com.yapzhenyie.GadgetsMenu.commands.main.CommandManager.onCommand(CommandManager.java:172) ~[?:?]
29.08 20:00:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-db6de12-18fbb24]

**Comment by HellaMixel** [comment]
Also if I put just the jar file in I have to /plugman load GadgetsMenu because it doesn't load and I found this error ERROR Error occurred while enabling GadgetsMenu v4.0.0 (Is it up to date?)

**Comment by OnlyNoobDied** [comment]
You should find "customjoinitems" author.

**Comment by OnlyNoobDied** [comment]
This version should work properly.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=185215
