### ISSUE TITLE
Plugin GadgetsMenu v4.0.0 generated an exception while executing task 6017

### ISSUE THREAD

**Issue by Fiks75** [OnlyNoobDied/GadgetsMenu#264]
Spigot 1.12. This error:

30.08 05:30:39 [Server] WARN [GadgetsMenu] Plugin GadgetsMenu v4.0.0 generated an exception while executing task 6017
30.08 05:30:39 [Server] INFO java.lang.IllegalStateException: Asynchronous entity add!
30.08 05:30:39 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1016) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:288) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:327) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.player.PlayerManager.giveMenuSelector(PlayerManager.java:747) ~[?:?]
30.08 05:30:39 [Server] INFO at com.yapzhenyie.GadgetsMenu.listeners.PlayerListener$1.run(PlayerListener.java:70) ~[?:?]
30.08 05:30:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [survival.jar:git-Spigot-596221b-9a1fc1e]
30.08 05:30:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
30.08 05:30:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]

Please fix it.

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.
