### ISSUE TITLE
Found some bugs in version 4.0.0

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#266]
The /gadgetsmenu reload command doesnt work

The black glass panels do not work in the gadgets gategory where you select

My server IP: minecraft.serv.nu

<3

**Comment by xXIOSCARIXx** [comment]
***/gadgetsmenu reload***

oops

**Comment by OnlyNoobDied** [comment]
/gmenu reload command has been removed due to unstable issue.
