### ISSUE TITLE
Paintball gun turns off redstone lamps!

### ISSUE THREAD

**Issue by Nesseley** [OnlyNoobDied/GadgetsMenu#27]
Hey!
I'm using LampControl to turn on redstone lamps without a redstone signal!

When placing blocks with paintballguns, or other gadgets that places blocks, it will turn off when the block is gone.

1. Shoot a redstonelamp that is active without a signal.
2. Wait for the fake block to dissapear.
3. The lamp is now turnd off.

- Nesseley

**Comment by OnlyNoobDied** [comment]
It's important? i think i would not update the plugin right now.I'm developing the next update.

**Comment by Nesseley** [comment]
I will not be able to use this plugin for my server if this is not fixed.. 👎 :(
Players can turn off lamp in my Hub and this will be annoying for my staff to turn back on all the time, and make my server seem bad..

**Comment by OnlyNoobDied** [comment]
alright i will update later.

**Comment by OnlyNoobDied** [comment]
can you screenshot?
