### ISSUE TITLE
Creeper turns invisible when using morph skill

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#270]
Creeper turns invisible when using morph skill

**Comment by OnlyNoobDied** [comment]
what's your server version.

**Comment by xXIOSCARIXx** [comment]
spigot 1.12.1

latest version

**Comment by OnlyNoobDied** [comment]
You installed Lib's Disguise or iDisguise plugin?

**Comment by xXIOSCARIXx** [comment]
Lib's Disguise

latest version of the plugin

**Comment by OnlyNoobDied** [comment]
Please try the new update.

**Comment by OnlyNoobDied** [comment]
Fixed. Thank you for reporting this bug.
