### ISSUE TITLE
Glass panel fill feauture (Bug)

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#275]
Gadgets -> (Fun & Games -> Mobs & NPCs -> Movement -> Musical -> Projectile -> Visual)
Does still not have any glass panels <3

**Comment by OnlyNoobDied** [comment]
This issue would be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0
