### ISSUE TITLE
Pickup items and duplicated playerheads! + rocket launcher bug

### ISSUE THREAD

**Issue by Nesseley** [OnlyNoobDied/GadgetsMenu#28]
- Melon Launcher
We somehow managed to pick up melons from Melon Launcher.
I also used Parachute gadget and it dropped 20 leads.

- Hat
Used a hat, relogged, got the hat in my inventory.

- Rocket launcher
Relog while on it. You will place a quartz block where you land.

Rocket launcher also makes unbreakeable blocks, if you place blocks where the fences where. 
Video of it: https://youtu.be/LEMWv76wQM8 (skip to 2:30)
Server needs to be restarted for the blocks to be removed!

**Comment by OnlyNoobDied** [comment]
noted

**Comment by OnlyNoobDied** [comment]
melon launcher also have bug?

**Comment by Nesseley** [comment]
We managed to pickup the melons (some of them)

**Comment by OnlyNoobDied** [comment]
actually you can pick up the melons

**Comment by Nesseley** [comment]
That sums up the "bug" for melon launcher, I just blocked with worldguard anyway. :P

**Comment by OnlyNoobDied** [comment]
You means you blocked with worldguard but still can pick up the melon?

**Comment by Nesseley** [comment]
No, that not what i mean. Just ignore the melon part of this report! ;)

**Comment by OnlyNoobDied** [comment]
lol

**Comment by OnlyNoobDied** [comment]
Fixed
