### ISSUE TITLE
Possible to run this async please?

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#284]
Hi, I installed the lagmonitor plugin on my server and sometimes, when it detect something wrong about plugins, I know it :P 

I got this error (an information):
https://pastebin.com/ZC9Mb3WP

It could be really nice if you can run this async instead of the main thread ;)

Thank you so much.

**Comment by OnlyNoobDied** [comment]
It should be sync for the first time plugin load.
