### ISSUE TITLE
New config for holograms ? 

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#285]
Hi, I just realize that:
![image](https://user-images.githubusercontent.com/5159244/29897449-ea34576e-8dae-11e7-83d0-c633f683d817.png)

In the new version, I see the same config twice, but with "Line-1" instead of "Line 1"

Error? Bug?

**Comment by OnlyNoobDied** [comment]
replace "Line 1" and "Line 2" to "Line-1", "Line-2".

**Comment by maxlehot1234** [comment]
Already done, but why it was dup^plicated between 4.0.0 and latest version :P That's my point

**Comment by OnlyNoobDied** [comment]
I changed the format.
