### ISSUE TITLE
Auto Download When Disabled

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#287]
why is it when i choose to use a 3.7 version of the plugin and i SPECIFICALY SET AUTO DOWNLOAD TO FALSE
it automaticaly downloads the latest version anyways
EVEN THOUGH I DO NOT WANT IT TO

im pretty sure this is against spigot's terms and rules because its downloading stuff without my consent

**Comment by Waffles2112** [comment]
im getting REALLY PISSED when it keeps auto updating when i SPECIFICALLY TELL IT NOT TO

**Comment by OnlyNoobDied** [comment]
I'm pretty sure if you set it to false it won't update automatically.

```
Auto Update: false
```

**Comment by Waffles2112** [comment]
i did
it didnt fix a damn thing
and keeps redownloading the latest version
and stopping my server

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/42z7piyuxir9oad/GadgetsMenu%20-%203.7.11.jar?dl=0
This is 3.7.11 version without auto update.

**Comment by claer** [comment]
Hello,

I'm also not very happy with the situation. The config file portage did not ended well for us. Would it be possible to release a 3.7.12 version with the autoupdate config option working (I mean being able to disable it)? It would appease angry admins.

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/42z7piyuxir9oad/GadgetsMenu%20-%203.7.11.jar?dl=0
This is 3.7.11 version without auto update

**Comment by claer** [comment]
thank you, I saw it on the previous post. My question was more to release a new 3.x version out of this and not just a quick rebuild. From what I understand, you want to move forward and not maintain the 3.x branch anymore.

Regards.

**Comment by OnlyNoobDied** [comment]
i remade the whole plugin.In 4.0 updates, i want to make it the plugin
performance good.

**Comment by OnlyNoobDied** [comment]
GadgetsMenu plugin is not stable and auto update option will only applied on next server launch.
