### ISSUE TITLE
Depencies for src.

### ISSUE THREAD

**Issue by FyuzYT** [OnlyNoobDied/GadgetsMenu#29]
Hello, plz give depencies for src. I have errors and can not compile project. My IDE - Netbeans 8.1 (Sorry for my english).

**Comment by OnlyNoobDied** [comment]
does not open source yet. Sorry

**Comment by FyuzYT** [comment]
Ok. I can connect your plugin to database IConomy?

**Comment by OnlyNoobDied** [comment]
i will add this features soon.

**Comment by FyuzYT** [comment]
Ohhh... Ok. Close this issue.
