### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#290]
How do i enable the placeholdersAPI in the featherboard config? You closed my issue without solving it :/

**Comment by OnlyNoobDied** [comment]
Can i know what's the placeholder?

**Comment by OnlyNoobDied** [comment]
If you using FeatherBoard, you have different placeholders.

{placeholderapi_*}
(* = placeholder without %%)
ex: {placeholderapi_gadgetsmenu_mystery_dust}

Do you know this?

**Comment by HellaMixel** [comment]
I do know about that. At first I never downloaded PlaceHoldersAPI and I was just using FeatherBoard. I used 
{placeholderapi_gadgetsmenu_mystery_dust}
After the update for 4.0 came put that stopped working on the featherboard. I installed PlaceHolderAPI and used the %% one and that one doesn't work either.

**Comment by HellaMixel** [comment]
Okay {placeholderapi_gadgetsmenu_mystery_dust} works after I updated the 4.0.3. Thank you! ;)

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Resolved I think

**Comment by OnlyNoobDied** [comment]
Okay.
