### ISSUE TITLE
Morph capacity doesn't work

### ISSUE THREAD

**Issue by Cybertheo** [OnlyNoobDied/GadgetsMenu#292]
When i select a morph i not receive the slimeball.

Server Version: Spigot 1.8.8

**Comment by OnlyNoobDied** [comment]
Are you using iDisguise?

**Comment by Cybertheo** [comment]
Yes i using IDisguise

**Comment by OnlyNoobDied** [comment]
iDisguise unable to use morph ability.

**Comment by Cybertheo** [comment]
But Lib Disguises crash on the server

**Comment by OnlyNoobDied** [comment]
You must download the correct version.
ProtocolLib needs too.

**Comment by Cybertheo** [comment]
Yes, i just didn't see your link
