### ISSUE TITLE
Morph error

### ISSUE THREAD

**Issue by Cybertheo** [OnlyNoobDied/GadgetsMenu#296]
I get this error when i try a morph: "java.lang.NullPointerException
> [17:00:20 WARN]: at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.giveSlimeballSilently(MorphManager.java:65)
> [17:00:20 WARN]: at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.giveSlimeball(MorphManager.java:58)
> [17:00:20 WARN]: at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.equipMorph(MorphManager.java:31)
> [17:00:20 WARN]: at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:529)
> [17:00:20 WARN]: at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:235)
> [17:00:20 WARN]: at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
> [17:00:20 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [17:00:20 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [17:00:20 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
> [17:00:20 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [17:00:20 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [17:00:20 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [17:00:20 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [17:00:20 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
> [17:00:20 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
> [17:00:20 WARN]: at java.lang.Thread.run(Thread.java:748)"

I have Libs Disguise and Protocol Lib installed 

Server version : Spigot 1.8.8

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/updates
