### ISSUE TITLE
Morph bugs/suggestions

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#299]
- **Sheep morph**
*spawns another sheep everytime it changes color*
*looks glitchy when walking, should instead change color of the current cheep*
*changes color to quickly*

- **Skeleton morph**
*should be holding a bow*
*since it can shoot arrows*

- **Creeper morph**
*removed nametag after exploding and during explosion*
*this bug only applies to this mob*

- **Snowman morph**
*should place snow where walking*
*for a more realistic snowman*

- **Green slimeball item**
*should be removed*
*due to it being visible in hand, applies to skeleton and zombie*
*should be using the same method as suits when a full suit is equiped for using the active morph skill*

**Comment by OnlyNoobDied** [comment]
>Snowman morph
>should place snow where walking
>for a more realistic snowman

This feature will be added in the next update.

>Sheep morph
>spawns another sheep everytime it changes color
>looks glitchy when walking, should instead change color of the current cheep
>changes color to quickly

>Creeper morph
>removed nametag after exploding and during explosion
>this bug only applies to this mob

This issue will be fixed in the next update.


>Skeleton morph
>should be holding a bow
>since it can shoot arrows
This problem was unable to fix, i tried many times, It doesn't equip a bow.

**Comment by OnlyNoobDied** [comment]
> Skeleton morph
should be holding a bow
since it can shoot arrows
This problem was unable to fix, i tried many times, It doesn't equip a bow.

This feature unable to do it.
