### ISSUE TITLE
Wont remove panes when change world

### ISSUE THREAD

**Issue by johnnymaister123** [OnlyNoobDied/GadgetsMenu#3]
When I go to another world, i've setup perworld inventory and per world plugins, the panes stay in players inventory, i've tried using /ci (clear inventory) and going to gmc and removing panes, but the panes continue to come back please respond soon

**Comment by OnlyNoobDied** [comment]
you need to setup which world you don't want to enable GadgetsMenu cosmetics.

you can setup disabled world in config.yml

**Comment by johnnymaister123** [comment]
I've made it so it disabled a certain world, but when players went to that world the plugin wasnt there but the panes still remained, I suggest you make the panes removable in the config.

**Comment by OnlyNoobDied** [comment]
i will do that.

**Comment by johnnymaister123** [comment]
Have u fixed it?

**Comment by OnlyNoobDied** [comment]
i will fix the bug.
