### ISSUE TITLE
[QUESTION] Multi-servers setup

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#300]
Hi, I just want to know something:

I have multiples servers.
Prison and Skyblock
I want to allow all gadgets on the prison server and store all mysterydust of players into MYSQL.

On the skyblock server, I want to allow players to get few gadgets I enable and allow them to get it by open mysteryboxes.

Both of the servers can use the same MYSQL to "take" the mystery dust of players?

Just to make sure before setup everything :P 

Thank you.

**Comment by OnlyNoobDied** [comment]
Yes, you can do that.
