### ISSUE TITLE
[Feature] Add another thing in the API

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#301]
Hi, are you able to add something, in the MYSQL/datafile that put EVERY mysterybox a players gets?
Not the actual player mysterybox, but the total of all the time ?

Thank you, since it could be really nice for quests plugins

Thanks

**Comment by OnlyNoobDied** [comment]
I think it is useless

**Comment by OnlyNoobDied** [comment]
''/gmysteryboxes check [player]' command will be added in the next update to check player's mystery boxes amount.

**Comment by OnlyNoobDied** [comment]
@maxlehot1234  You can check player's mystery boxes via command now.
