### ISSUE TITLE
Suggestions (Emotes)

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#302]
- **When you click on a emote in the gadgetsmenu it automatically equips the emote**
*instead of getting it in your inventory*

- **Automatically replay the emote animation**
*no need to re-equip the emote after the animation is finished*

- **Should work the same way as hats**
*but is an emote with an animation*

**Comment by OnlyNoobDied** [comment]
This idea will be replaced by Animated Hats.
