### ISSUE TITLE
[ISSUE IMPORTANT] Glitch by pass over the floor 

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#303]
Hi, my players just report a glitch to me: 
https://youtu.be/tVNVnD8m8K0

When the take the guardian morph, leave the server, log back on the server that have gadgets, they "bypass" the floor.
Is it possible for you to make them spawn 1 block up when the login with a morph?

Thank you

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Thi shappen with a lot of morphs :(

Any way to fix this soon? Since this can be use a "floor bypass".


Thank you so much

**Comment by OnlyNoobDied** [comment]
Actually this issue happen with all morphs.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Any fix? Since now players use this to climb walls, reach the top and exit the mines/regions.

They can also be spawn outside each warps cause of pets.

Maybe make players spawn 1 blocks up when they teleport and prevent them to pass trought walls/floor/top, etc.


Thank you

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188340
