### ISSUE TITLE
Gadget item forced upon players when they switch worlds

### ISSUE THREAD

**Issue by CitrusFruit** [OnlyNoobDied/GadgetsMenu#306]
When the gadgets item is disabled, switching to another world then going back to the world you started in forces the item to appear in your inventory... Can't drop it or remove it.

Example: I started in world 1 without the gadgets item, I decided to go to world 2 then back to world 1. I then noticed when I went back to world 1 I had been given the gadgets item for no reason even though it's disabled.

**Comment by OnlyNoobDied** [comment]
What do you mean gadget item? "gadget" or menu selector.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by pavlos235** [comment]
Спасибо
