### ISSUE TITLE
Some more bugs/issues

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#307]
- **Radio gadget**
*plugin creates "BroadcastRadioGadget" folder on first start up, but uses only "RadioGadget" folder*
*i had to rename"BroadcastRadioGadget" to "RadioGadget" and remove "BroadcastRadioGadget" for it to work*

- **Frog suit**
*fall damage should be disabled when using this suit*

- **Kookie fountain gadget**
*Kookie is spelt Cookie*

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

I think "Kookie fountain gadget" doesn't spell wrong because Hypixel has the same name.
