### ISSUE TITLE
Morphs Error

### ISSUE THREAD

**Issue by LoYungSum** [OnlyNoobDied/GadgetsMenu#308]
I am using this plugin for my spigot 1.8.8 server. And using libsdisguises version 8.6.8. When I morph into a mob and move, the console will get spam with "<player's name> moving too quickly".
Or it will tp me back to the void. Why is this happening?

**Comment by LoYungSum** [comment]
Is it the libdisguises or protocolib?

**Comment by OnlyNoobDied** [comment]
Make sure you have both installed correct version.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs
