### ISSUE TITLE
[Question] Update Lib Disguise

### ISSUE THREAD

**Issue by Cybertheo** [OnlyNoobDied/GadgetsMenu#309]
Can I update Lib Disguise to the latest version ?

**Comment by OnlyNoobDied** [comment]
It depends on your server version. If you're using 1.11.2 or higher, you can update Lib's Disguise plugin to the latest version. Otherwise, you must install the version that listed here.

https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs

**Comment by Cybertheo** [comment]
Ok thanks
