### ISSUE TITLE
Paint trail + Paint Gun ruins my Hub. SEVERE

### ISSUE THREAD

**Issue by Nesseley** [OnlyNoobDied/GadgetsMenu#31]
Video for better explaination: https://youtu.be/P78k_pCNUiA

1. walk with paint trail.
2. Use another gadget wich colors the blocks.
3. wait, and the blocks will not go back to what they were.

Also works the other way: https://youtu.be/aymWlWHN84c

**Comment by OnlyNoobDied** [comment]
ok i will fix the bug

**Comment by OnlyNoobDied** [comment]
fixed
