### ISSUE TITLE
lag and leave all players

### ISSUE THREAD

**Issue by MrJellyBeam** [OnlyNoobDied/GadgetsMenu#310]
internal error and players lag & leave of the server. Sorry for my bad english

**Comment by OnlyNoobDied** [comment]
send the error message to me.

**Comment by MrJellyBeam** [comment]
Thanks yout the update fix it :D

**Comment by OnlyNoobDied** [comment]
you didn't post the error how can i fix it. :/

**Comment by MrJellyBeam** [comment]
too many packets :c. or something like that

**Comment by MrJellyBeam** [comment]
Where can I donate?

**Comment by OnlyNoobDied** [comment]
is the bug fixed?

you can donate via Paypal.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki#donate

**Comment by MrJellyBeam** [comment]
yes is the bug fixed.

you can add companions?

**Comment by OnlyNoobDied** [comment]
I will add companions soon.
