### ISSUE TITLE
Is it possible to make players automatically were given a Mystery Box like in version 3.7.11

### ISSUE THREAD

**Issue by pavlos235** [OnlyNoobDied/GadgetsMenu#311]
Is it possible to make players automatically were given a Mystery Box like in version 3.7.11(sorry for bad English)

**Comment by OnlyNoobDied** [comment]
This feature will be added soon.

**Comment by pavlos235** [comment]
Спасибо

**Comment by OnlyNoobDied** [comment]
Please check new update.
