### ISSUE TITLE
Problem fps - mystery vault

### ISSUE THREAD

**Issue by k1z1** [OnlyNoobDied/GadgetsMenu#313]
If you put 5 mystery vault  in a radius of 15 blocks - FPS decreases from 200 to 30
(sorry for my English) =)

**Comment by k1z1** [comment]
and I noticed a strange selection of the text, before this problem was not
https://prnt.sc/gfwvif

**Comment by OnlyNoobDied** [comment]
Did you reload the server instead of restart it?

**Comment by k1z1** [comment]
No, I'm restarting the server .. I think the problem with holograms, but I have a plug-in latest version of the update

**Comment by OnlyNoobDied** [comment]
I found the issue. I updated a testing version to dropbox. I think you installed that testing version.
Please reinstall the plugin
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0
