### ISSUE TITLE
[Feature] Mysteryboxes in GUI instead of vault

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#314]
Hi, It could be really nice to allow us to open Mysterybox inside a GUI instead of a vault.

With this, it prevent too many players to open mysteryboxes at the same place, with particles, sounds, effect, etc, because these type of things could tke a lot of server ressources.

Since you already give "virtual" mysterybox, I think it could be done.
Maybe as an add-on.

I will use this for sure, since I already suggest it, because the actual system was not the best for performances.

Thank you so much and hope we can see this soon ;)

**Comment by OnlyNoobDied** [comment]
This can be done by using "Open Multiple Boxes" button which will be added in 4.1.10 version.
