### ISSUE TITLE
Mysql + spam problems

### ISSUE THREAD

**Issue by ZaferBeyy** [OnlyNoobDied/GadgetsMenu#316]
Hi, I am getting this error when I open Mysql on my Bedwars server ..
--- https://hastebin.com/tajenabofu.md

do I get such an error in my lobby server too?
https://hastebin.com/asexufidid.md

Player-Data:
  Storage: mysql
  MySQL:
    hostname: *******
    username: *********
    database: ******
    port: '3306'
    password: ********
Cosmetic-Item-Purchase:
  #Set to true allows player to purchase cosmetic items.
  Enabled: true
  #315 Set the storage where do you want to save mystery dust.
  #Available storages: 'file', 'mysql', 'coinsapi', 'playerpoints', 'vault'.
  Mystery-Dust-Storage: mysql
  #Set to true will allows player to purchase specified cosmetic.
  Enabled-Cosmetics:
    Hats: true
    Particles: true
    Suits: true
    Gadgets: true
    Pets: true
    Morphs: true
    Banners: true
    Emotes: true
    Cloaks: true

**Comment by ZaferBeyy** [comment]
new problem https://hastebin.com/mamajomasi.md

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
Sorry, i uploaded a testing version.
Please try this updates.
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0
