### ISSUE TITLE
Morphs not Working

### ISSUE THREAD

**Issue by Vennntox** [OnlyNoobDied/GadgetsMenu#317]
21:04:03 org.bukkit.event.EventException
21:04:03 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:03 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
21:04:04 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
21:04:04 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:04 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:04 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:04 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:04 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:04 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
21:04:04 Caused by: java.lang.NoClassDefFoundError: me/libraryaddict/disguise/disguisetypes/FlagWatcher
21:04:04 	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_144]
21:04:04 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_144]
21:04:04 	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_144]
21:04:04 	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:1.8.0_144]
21:04:04 	at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphType.equip(MorphType.java:216) ~[?:?]
21:04:04 	at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.equipMorph(MorphManager.java:32) ~[?:?]
21:04:04 	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:529) ~[?:?]
21:04:04 	at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:235) ~[?:?]
21:04:04 	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source) ~[?:?]
21:04:04 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
21:04:04 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:05 	... 15 more
21:04:05 Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.disguisetypes.FlagWatcher
21:04:05 	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:05 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:05 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_144]
21:04:05 	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:1.8.0_144]
21:04:05 	at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphType.equip(MorphType.java:216) ~[?:?]
21:04:05 	at com.yapzhenyie.GadgetsMenu.cosmetics.morphs.MorphManager.equipMorph(MorphManager.java:32) ~[?:?]
21:04:05 	at com.yapzhenyie.GadgetsMenu.player.PlayerManager.equipMorph(PlayerManager.java:529) ~[?:?]
21:04:05 	at com.yapzhenyie.GadgetsMenu.menu.menus.MorphsMenu.onInvClickMorphs(MorphsMenu.java:235) ~[?:?]
21:04:05 	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source) ~[?:?]
21:04:05 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
21:04:06 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
21:04:06 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-db6de12-18fbb24]
21:04:06 	... 15 more

**Comment by xXIOSCARIXx** [comment]
you need lib's disguises

**Comment by OnlyNoobDied** [comment]
Make sure your Lib's Disguise and ProtocolLib plugin installed the correct version.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs
