### ISSUE TITLE
Translate expires in..........

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#318]
Hi, where I can translate this thing for mysteryboxes:
![image](https://user-images.githubusercontent.com/5159244/29988531-f5f4c2da-8f3b-11e7-88c7-047786b47cf3.png)

I have a french server, so I need to translate it.
I translate days, minutes, seconds, etc, but CAN'T translate expires in:

Thank you so much and thank you so much for all fixs ;)

**Comment by OnlyNoobDied** [comment]
You can modify it in mystery boxes.yml file

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Thank you so much. Yo can close this ;)

Have a nice day/night

**Comment by OnlyNoobDied** [comment]
ok
