### ISSUE TITLE
Issue with enderchest stays in the air

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#319]
HI, I just see that enderchest stay in the air:

![image](https://user-images.githubusercontent.com/5159244/29988816-2f72d186-8f3d-11e7-976c-359e954d6a7c.png)

I already have this issue on older version of the plugin 3.x.x.x

Do you have an idea about this?

Thank you

**Comment by OnlyNoobDied** [comment]
This issue is occurring on older version?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I have that sometimes in the previous version.

I can't do the command each time :P 

Not a big deal, but just a visual "error".

**Comment by OnlyNoobDied** [comment]
If you're 1.12 version, you can use this command

/kill @e[type=Armor_Stand]

**Comment by maxlehot1234** [comment]
I have the error: Player not found when doing this command

**Comment by OnlyNoobDied** [comment]
you must add this "@e"

minecraft:/kill @e[type=Armor_Stand]
