### ISSUE TITLE
Mystery Boxes

### ISSUE THREAD

**Issue by DolphinGamerYT** [OnlyNoobDied/GadgetsMenu#321]
Hi,
I'm trying to put mystery vaults but the hologram spawns all time and makes a lot of lag.

**Comment by OnlyNoobDied** [comment]
Sorry, i uploaded a testing version.

**Comment by OnlyNoobDied** [comment]
Please try this update.
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by DolphinGamerYT** [comment]
The Gift Inventory dosen't work
