### ISSUE TITLE
Delay between opening mystery boxes.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#323]
Hi !

To prevent spam, could you add a delay between opening mystery boxes ?

For example 5 seconds.

**Comment by OnlyNoobDied** [comment]
is it useless?

**Comment by TheIntelloBox** [comment]
Nop.

**Comment by OnlyNoobDied** [comment]
if many players want to open mystery boxes, it will waste lots of times

**Comment by TheIntelloBox** [comment]
My chat is spammed so what can we do ?

**Comment by OnlyNoobDied** [comment]
you can disable broadcast messages in 'mystery boxes'.yml
