### ISSUE TITLE
Gift inventory

### ISSUE THREAD

**Issue by DolphinGamerYT** [OnlyNoobDied/GadgetsMenu#324]
You send a test version but gift inventory dosen't work

**Comment by OnlyNoobDied** [comment]
what do you mean doesn't work? Any error in console?

**Comment by DolphinGamerYT** [comment]
No

**Comment by OnlyNoobDied** [comment]
can't send give to player?

**Comment by OnlyNoobDied** [comment]
can't send gifts to player?  cant open the gui menu?

2017年9月2日 7:41 PM，"Yap Zhen Yie" <yapzhenyie2014@gmail.com>写道：

> can't send give to player?
>
>
>
>

**Comment by OnlyNoobDied** [comment]
can't send gifts to player?  cant open the gui menu?

**Comment by DolphinGamerYT** [comment]
I can open the gui with /gmenu main and in Mystery vault but not gifts, and the chest (Item to open gui) dosen't work.

**Comment by OnlyNoobDied** [comment]
what's your server ip.

**Comment by OnlyNoobDied** [comment]
Is this issue has been fixed?

**Comment by TheIntelloBox** [comment]
It works fine. x)

**Comment by OnlyNoobDied** [comment]
okay.
