### ISSUE TITLE
Ninja suits . Players can't mine/break blocks

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#326]
Hi, when players are equip wqith full ninja suits, they cant break blocks/mine.

I have a prison server and the main goal was to break blocks.

When they left clik, it trowhs a shuriken and rpevent them to mine.

Is it possible to trigger the shuriken on right click instead?

Thank you

**Comment by OnlyNoobDied** [comment]
Added an option to disable suit ability(Ninja,Baker, Plumber, Spooderman) while holding an item on main hand.
