### ISSUE TITLE
JukeBox gadget. Music stop hearing after 60 blocks

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#327]
I just realize that by using jukebox gadget, the sounds stop after 60 blocks up

If I am at y=10 and fly upper than y=70, I stop hearing the music.
2 choices now: Start the music again of go down to continue hearing the music.

**Comment by maxlehot1234** [comment]
Same thing occured in X, Y and Z position.

**Comment by OnlyNoobDied** [comment]
This issue could not be fix.
