### ISSUE TITLE
Performance issues with playerquitevent ?

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#328]
Hi this is what I have now:
![image](https://user-images.githubusercontent.com/5159244/29998231-d448adf0-8ff3-11e7-879c-7db08bd8a24c.png)

And imagine with a lot of more players.

Are you able to make this better?

Thank you so much

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
