### ISSUE TITLE
Players pets not removed from the server when they leave.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#330]
Hi, when players take a pet and leave the server or server restart, these pets ARE NOT removed from the server sometimes and they are not removed if the player login again.
![image](https://user-images.githubusercontent.com/5159244/29999452-f82ff46c-9016-11e7-9de1-1573c0abd90b.png)

This can be used as a glitch to make the server lagging...
Another thing is that players can kill it to get XP....

I already report this for an older version of the plugin. #232 

Any way to fix this fo real?

Thank you

**Comment by OnlyNoobDied** [comment]
hmm, i will add an option to clear all entitys when server restart.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Winner ;)

Thank you, since this is a problem for my players 

They always report thisbug to me and hope it will be fixed soon.


Thank you

**Comment by Cybertheo** [comment]
Just on server restart ? It isn't possible to clear the pet when player disconnect ?

**Comment by Cybertheo** [comment]
Or just add a command to clear pets of players disconnected

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Any ETA for this, this is really, really bad to deal with a lot of pets in the world :P 

Thank you

**Comment by OnlyNoobDied** [comment]
This issue still doesn't fix?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Nope, I continue to have it

**Comment by maxlehot1234** [comment]
This really need to be fixed ASAP. I can't remove all of them each days, that doesn't make sense for me...

I have 20 players that play almost all the day and when they are kicked or when the leyve the server or if the server was restart, their pets stay on the server.

This was count as entity/mobs/monster and with a lot of mobs, the server can start to have TPS drop, performances issues, etc.


If you can fix this in the next update, it could be AMAZING.


Thank you

**Comment by maxlehot1234** [comment]
![image](https://user-images.githubusercontent.com/5159244/30528003-a74f7eb8-9bfc-11e7-9874-8853598b9e0e.png)
This is an example. 4 pets of the same player in the same region, because this player always go here on the server. It was his rank mine.....
This happen to a lot of mines/regions :(

**Comment by OnlyNoobDied** [comment]
i think i forgot to add something to handle player kick event

**Comment by maxlehot1234** [comment]
@OnlyNoobDied That's possible. So a fix will be ready soon ? So cool :)

**Comment by OnlyNoobDied** [comment]
This issue may be fixed in this version.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188340
If this issue still occur, please inform me.
