### ISSUE TITLE
Recent loot

### ISSUE THREAD

**Issue by k1z1** [OnlyNoobDied/GadgetsMenu#331]
i translated all text and see it after the reboot server the text is replaced by "??????" 
https://prnt.sc/ggkdwj

**Comment by k1z1** [comment]
yeah, how i san contact u ?

**Comment by HellaMixel** [comment]
Just go to your FTP file access and select the "GadgetsMenu" folder in the Plugins directory. Then go to dropbox and upload it and paste the download link here.
