### ISSUE TITLE
Previous page.

### ISSUE THREAD

**Issue by BastiaanSahetapy** [OnlyNoobDied/GadgetsMenu#337]
Hey,

I have found a bug in the Gadgets Menu, If you are in a menu, and you go to the next page, the arrow left, changes in previous page, but if you click on it, it sends you to the main menu. Hope this will be fixed soon.

Bug:
https://gyazo.com/0035f5d76520bfdf2834e0e910e34067

**Comment by maxlehot1234** [comment]
Doesn't happen for me

**Comment by BastiaanSahetapy** [comment]
Only at the catagory heads at me, latest version

**Comment by HellaMixel** [comment]
Does that to me

**Comment by OnlyNoobDied** [comment]
Can someone record a video?

**Comment by BastiaanSahetapy** [comment]
https://gyazo.com/0035f5d76520bfdf2834e0e910e34067

Op 4 sep. 2017 23:20 schreef "Yap Zhen Yie" <notifications@github.com>:

Can someone record a video?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OnlyNoobDied/GadgetsMenu/issues/337#issuecomment-327029424>,
or mute the thread

**Comment by HellaMixel** [comment]
Yeah
Video: https://vid.me/FPU2O

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
