### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Cri16228** [OnlyNoobDied/GadgetsMenu#34]
Hi. I have a suggestion for you, add Italian Translation (powerd by me)
if you want I can translate all few string of "Messages.yml"

**Comment by OnlyNoobDied** [comment]
sure. if you translated you can upload it to me. I will add languages support soon

**Comment by Cri16228** [comment]
Yes :) thanks

**Comment by Cri16228** [comment]
I have translated "messages.yml" but there is some text inside all .yml inside "Cosmetics" folder
if I translate them remain in Italian and stop

**Comment by Cri16228** [comment]
Finish. Here [GadgetsMenu](https://www.mediafire.com/?biajpl2tdpeeg29) the translated file, all .yml file like "gadget.yml" or "banner.yml", and Here [Donate](https://paypal.me/cpiva96) my PayPal.Me link to donate me for my work (if you want and if you appreciate my work. FREE OFFERT)

**Comment by MichaelOfficialYT** [comment]
Can anyone help me with italian translation  ?
