### ISSUE TITLE
Mysteryboxes can be made free

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#340]
Is there a setting to change the amount? all them are free

**Comment by OnlyNoobDied** [comment]
you can change the price in messages.yml file. You must make sure thr price
format camt contains a quotation marks.

**Comment by HellaMixel** [comment]
Mystery-Box-Crafting-Menu:
    GUI-Name: Mystery Box Crafting
    Items:
      1-Star:
        Name: '&cMystery Box #1'
        Material: '130:0'
        Price: '100'
        Lore:
        - '&7This Mystery Box contains of'
        - '&7the following:'
        - ''
        - '&aCommon items&7: &c4'
        - '&9Rare items&7: &c1'
        - '&5Epic items&7: &c1'
        - '&6Legendary items&7: &c1'
        - ''
        - '&7Quality: &e✰&7✰✰✰✰'
        - ''
        - '&7Cost: &a{COST} &7Mystery Dust'
        - '&aClick to craft!'

**Comment by HellaMixel** [comment]
It says that but it shows "0" in-game

**Comment by OnlyNoobDied** [comment]
should be like this,
Price: 100

**Comment by HellaMixel** [comment]
Fixed, thank you :), Also do you think you would ever take my suggestion into consideration?

**Comment by OnlyNoobDied** [comment]
You mean "gui shop"? Yes, i have created a GUI-Shop plugin in spigot. What i need to do is add a option to hook Mystery Dust.

**Comment by HellaMixel** [comment]
Sweet! I can't wait for it.

**Comment by OnlyNoobDied** [comment]
This plugin is premium.
https://www.spigotmc.org/resources/tokenshop-1-8-1-11.34455/
I just need to add an option to hook Mystery Dust to that plugin.
