### ISSUE TITLE
Playerdata doesn't delete

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#341]
Whenever I delete the player data when the player joins back he/she still has everything they had before

**Comment by OnlyNoobDied** [comment]
did you restart the server after you delete playerdata.

**Comment by HellaMixel** [comment]
Yes

**Comment by HellaMixel** [comment]
What I am trying to do is remove all the free mysteryboxes players got for free because it was set for free but each time I just delete the file and restart it puts it back but once a player joins the old userdata loads back in and keeps all their mysteryboxes

**Comment by OnlyNoobDied** [comment]
playerdata will sync when they join and leave.If you delete playerdata file
while they still online, it will create a new file when they leave the
server.

**Comment by HellaMixel** [comment]
Okay so what I did was stop my server and deleted the file and it seemed to of worked fine

**Comment by OnlyNoobDied** [comment]
Now, every mystery box has a expiry date. You don't need to remove it
everytime.

**Comment by HellaMixel** [comment]
Well when in my case the mysteryboxes were crafted free so I needed to delete them

**Comment by OnlyNoobDied** [comment]
okay.
