### ISSUE TITLE
GUI issue with display gadgets of players

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#343]
Hi, I just realize that if the player buy a gadget with mystery dust, he see the gadget, but the main category doesn't have the item:
http://i.imgur.com/ul5dvJJ.gifv

Are you able to fix this in the next update?

Thank you

**Comment by OnlyNoobDied** [comment]
Only radio gadget have this issue, because i didn't rename the permission.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
