### ISSUE TITLE
4.0.8

### ISSUE THREAD

**Issue by HellaMixel** [OnlyNoobDied/GadgetsMenu#344]
http://imgur.com/a/GUoOK

Issue: Read bottom of the chat

**Comment by OnlyNoobDied** [comment]
Are you sure you're using the latest plugin?

**Comment by HellaMixel** [comment]
Yeah I am

**Comment by OnlyNoobDied** [comment]
Alright, i will check that.

**Comment by OnlyNoobDied** [comment]
Can you send "/gmenu about" message to me?

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
This issue only occur when player don't have any mystery dust.
