### ISSUE TITLE
can not remove hologram

### ISSUE THREAD

**Issue by komando2000** [OnlyNoobDied/GadgetsMenu#346]
i remove mystery vault by clicking on it then i will try to remove it by command he tell there is no mystery vault created
but hologram still in the world first line (mystery vault) second line (Right click)
if the is any way to remove hologram please tell me i remove plugin and re install it without any effect
please help me as soon as
thanks

**Comment by OnlyNoobDied** [comment]
what do you mean remove mystery vault by clicking on it?

**Comment by komando2000** [comment]
i mean i break it  and when try to remove box (holo text) by command  they tell me there is no mystery vault created but the hologram text sill in world first line (mystery vault) second line (Right click) and can not break block in the old position of the chest
please i need remove the text because i make mystery vault in other place
thanks for help

**Comment by OnlyNoobDied** [comment]
can you send me your 'mystery vaults.yml' file.
And your old mystery vault coordinate

**Comment by komando2000** [comment]
thanks for relpy
this mystery vaults.yml
Mystery-Vaults:
  gift:
    BlockFace: EAST
    Location:
      world: hub
      x: 11.0
      y: 17.0
      z: -31.0
------------------------
the old mystery vault coordinate ( -12 ,16 ,21)
and there not in config file but the hologram still in the world
thank for help

**Comment by OnlyNoobDied** [comment]
Method 1
 Remove gadgetsmenu plugin from the server and run this command.

>  /minecraft:kill @e[type=ArmorStand]

for 1.12

>  /minecraft:kill @e[type=Armor_Stand]

**Comment by OnlyNoobDied** [comment]
any updates on this issue
