### ISSUE TITLE
Players dont get items from the mystery box

### ISSUE THREAD

**Issue by Masonhgg** [OnlyNoobDied/GadgetsMenu#347]
Hey! So I have a problem when they use the mystery box (players) it says in chat for them they get the item so they open up the gui and they go to hats and there hat isnt there. I have read the q and a thing and it was saying change this and that and i did.. 
but i only did the 1st part not the 2nd part. I change it to groupmanager the first part but i did not find the 2nd part in the config file so i think that is what messing it up
Q: What is the problem when player failed to get cosmetics item from opening mystery boxes or purchase it using mystery dust?

You need to change the command that depends on your permissions plugin.

There's two parts of command you need to change.
1) Cosmetic-Item-Purchase:(Can be found in 'config.yml' file)
     # This is the command when player purchase cosmetic items.
     # This command is depends on your permission plugin.
     Execute-Command: pex user {PLAYER} add {PERMISSION}

2) Mystery-Boxes: (Can be found in 'mystery boxes.yml' file)
     Execute-Command: pex user {PLAYER} add {PERMISSION}
For GroupManager plugin.
manuaddp {PLAYER} {PERMISSION}
For PermissionsEx plugin
pex user {PLAYER} add {PERMISSION}
For PowerfulPerms plugin
pp user {PLAYER} add {PERMISSION}

That was what u wrote and I did the 1st thing changed the pex user thing to the group manager but i didnt se the 2nd part in my config file
Plz help me thanks!

**Comment by OnlyNoobDied** [comment]
Did you saw this?
"Can be found in 'mystery boxes.yml' file"

**Comment by Masonhgg** [comment]
I dont have that.... I have mystery vault.yml but it doesnt have that pex thing i need to change

**Comment by Masonhgg** [comment]
Wait i found it! got it to work! ty! <3 #HYPE!

**Comment by OnlyNoobDied** [comment]
:D
