### ISSUE TITLE
Some things from messages.yml  not RELOADED 

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#348]
Hi, I just realize that some lines are not reloaded when I use plugman.

Since you DOESN'T add a reload command inside your plugin, I use plugman and everything was fine except these things:
Received-Mystery-Boxes
Received-MysteryDust

I doesn't test other things.

Are you able to check this on your side?
Anyone else have this issue?

PaperSpigot 1.12.1

Thank you ;)

**Comment by OnlyNoobDied** [comment]
I'm not recommended you use plugman to reload any plugin. Anyway, i will find a way to re-add the reload command.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Can't be close...
How I can translate the text using messages.yml if it won't be change in-game? Even with a server restart?

Any idea about this?

plugman works à 99.9999999% with GadgetsMenus, I use it all the time without any issues, so how it can be an issue ONLY with the messages.yml?

**Comment by OnlyNoobDied** [comment]
Can you send your messages.yml file to me. I think you have set it in wrong format.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied There it is: https://pastebin.com/Zp71v5tA

**Comment by OnlyNoobDied** [comment]
What did you change?

> Received-Mystery-Boxes: '{PREFIX}&eYou''ve received &b{MYSTERY_BOXES} mystery boxes
  &efrom &b{PLAYER}&e.'

> Received-MysteryDust: '{PREFIX}&eYou''ve received &b{MYSTERY_DUST} &emystery dust
  from &b{PLAYER}&e.'

**Comment by maxlehot1234** [comment]
Yes Exactly. I try to change them but can't be translated and go back to default :(

**Comment by OnlyNoobDied** [comment]
what message did you changed? Can you paste it to here.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Close this, it works now. Maybe an update or something occured on my side ;)

And just for you: Everythings works fine with Plugman ;)

**Comment by OnlyNoobDied** [comment]
I'm just not recommended you use plugman.
