### ISSUE TITLE
Does not work 2 line

### ISSUE THREAD

**Issue by pavlos235** [OnlyNoobDied/GadgetsMenu#350]
Does not work 2 line     

    Mystery-Vault:
      Line-1: '&bMystery Vault'
      Line-2: '&e&lRight Click'

**Comment by OnlyNoobDied** [comment]
The holograms doesn't spawn?
What is your server version?

**Comment by pavlos235** [comment]
1.12

**Comment by OnlyNoobDied** [comment]
this issue has been reported and will be resolved in the update.

**Comment by pavlos235** [comment]
Спасибо
