### ISSUE TITLE
BIG ERROR with mysteryboxes disappear

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#352]
Hi, my players get a lot of mysteryboxex for the server opening.

They get their mysterybox, but they DOESN'T have option to switch to the next page...

Anyway to fix this when you can?

Thanks

**Comment by OnlyNoobDied** [comment]
Reopen the vault. It takes times to load all mystery boxes from mysql/file to prevent the lag.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied There it is: https://pastebin.com/Zp71v5tA
