### ISSUE TITLE
[4.0.8] Issues with IDisguise

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#353]
I am using idisguise and 4.0.8 on 1.8.8 server
When i select a morph i will not receive any slimeball on inventory slot

**Comment by xion87** [comment]
Plus i receive this errors https://hastebin.com/irudajatoc.vbs

**Comment by OnlyNoobDied** [comment]
If you using idisguise, you're unable to use morph ability.

**Comment by xion87** [comment]
ty for the info :c
