### ISSUE TITLE
Prevent players to use the gadgets slots

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#354]
Hi, is it possible for you to add something so the players CAN'T use the gadget slots?

It could be really nice and prevent item removed from their inventory?

Ona  prison serer, all slots are used
If their inventory are full and the take a gadgets, they lost their items, because it can be placed on another slot...

Thank you

**Comment by OnlyNoobDied** [comment]
If 'gadget slot' if not emply, it should drop that item on the ground.

**Comment by maxlehot1234** [comment]
Thats bad for me on my server, since on a prison server, players have a lot of time their inventory full for multiple reasons.

If they have a full inventory and take a gadget that drop their best pickaxe, imagine the scenario :O 

Are you able to add a check and send a TITLE/CHAT if the slot was used that told the player to make this slot free to be able to get the gadget?

OR OR OR OR OR
Add something in your code to BLOCK/RESERVED this slot, so players are NOT able to put anything on this slot


Thank you so much ;)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188340
