### ISSUE TITLE
Floating chest sometimes it stay in air

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#355]
I noticed with the new recode, sometimes the small enderchest will not disapear on the vault
![immagine](https://user-images.githubusercontent.com/3611852/30533294-d91fa4de-9c58-11e7-8c11-e4a1ece55fc5.png)

**Comment by maxlehot1234** [comment]
#160 #319 

Already report this :( So it was not just me.

@OnlyNoobDied Please look into this. A command to remove them like: minecraft:/kill @e[type=Armor_Stand]

Doesn't work for me and it was not a solution.

Thank you

**Comment by xion87** [comment]
Well this never happened in 3.x.x version, only in 4.x.x version

**Comment by OnlyNoobDied** [comment]
because he tolds me that happens in the older version of GadgetsMenu.
I already knew this issue would happen in the latest version too. This
issue will be fixed in tge next update.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Ok thank you :)

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188340

**Comment by maxlehot1234** [comment]
@OnlyNoobDied How I can remove enderchest that stay in the air?

**Comment by xion87** [comment]
@maxlehot1234 go close it and use the command kill @e[type=ArmorStand,r=3]

**Comment by maxlehot1234** [comment]
@xion87 Player not found when I execute the command ^^^ :(

**Comment by xion87** [comment]
try with Armor_Stand  (i am using 1.8.8)

**Comment by OnlyNoobDied** [comment]
minecraft:kill @e[type=ArmorStand]

**Comment by maxlehot1234** [comment]
@xion87 @OnlyNoobDied 
Doesn't work. Player not found

**Comment by OnlyNoobDied** [comment]
are you using 1.12?

2017年9月21日 5:17 AM，"maxlehot1234" <notifications@github.com>写道：

**Comment by OnlyNoobDied** [comment]
@maxlehot1234  what is your server ip? Let me help you.

**Comment by xion87** [comment]
if you have essentials use /minecraft:kill @e[type=ArmorStand,r=3]

**Comment by maxlehot1234** [comment]
@xion87 I just find it on the web, but thank you so much ;)
