### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#356]
I just start to use mysql feature but after some while i get this error (7 hours later) and gadgetsmenu disable itself.
Error: https://hastebin.com/zugedihawa.md

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188340
