### ISSUE TITLE
[4.0.10] Player can't see their disguise

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#358]
By using the new release, player stopped to see their disguise enabled and the option toggle view self keep to be disabled, and is impossible to enable it.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Same here #360

**Comment by maxlehot1234** [comment]
@xion87 Look on #360 

You use LibDisguises or I disguise?

**Comment by xion87** [comment]
i use libdisguises

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188464
