### ISSUE TITLE
[QUESTION]  This item(EPIC Banners Wolf) has been disabled, so player won't get the permission.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#359]
Hi what does this message says:
This item(EPIC Banners Wolf) has been disabled, so player won't get the permission.

Player will get something or not?

Thank you

**Comment by OnlyNoobDied** [comment]
This might be an issue.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188464
