### ISSUE TITLE
Bug with pets

### ISSUE THREAD

**Issue by FrozenFever** [OnlyNoobDied/GadgetsMenu#36]
Hello :)

I tried this as a cosmetic perk on my survival server today. So happen I teleported to another player while having my pet cow active. When I did /back and returned, the cow just stopped following me. It was still showing my name but it was completely ignoring me. I could in fact spawn another pet, essentially making it seem like I have 2 pets. If I tp to the nether and back again, I will have 2 pets ignoring me and spawning yet another one will give me seemingly 3. I reloaded, resetted and all but those cows still persist. I had to drop them into the void in the end. Could you possibly help fix this? :)

**Comment by OnlyNoobDied** [comment]
noted.

**Comment by FrozenFever** [comment]
That's really quick response, thumbs up! :)

**Comment by OnlyNoobDied** [comment]
i will fix this bug after my final exam :D

**Comment by OnlyNoobDied** [comment]
Fixed
