### ISSUE TITLE
[BUG 4.0.10] Players can't see their disguise

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#360]
If I choose a disguise, I can't see it.

I try to enable sef view, but change nothing.

Other players see my dsguise, but not me :(

Could you fix this please?

**Comment by OnlyNoobDied** [comment]
Are you using iDisguise plugin?

**Comment by maxlehot1234** [comment]
No Libs'Disquise

**Comment by OnlyNoobDied** [comment]
Oh, set "Enabled-Self-Morph-View" to true in config

**Comment by maxlehot1234** [comment]
I doesn't have this into config.yml.

**Comment by OnlyNoobDied** [comment]
in "settings" section.

**Comment by maxlehot1234** [comment]
NOPE, I have this:
Settings:
  Default-Pet-Name: '&bAnimal de {PLAYER}'
  Starting-Mystery-Dust: 0
  Max-Pet-Name-Characters: 20
  Gadget-Slot: 5

Like you config.yml example on the wiki: https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Config

**Comment by OnlyNoobDied** [comment]
Alright, please give me some time. I will release a fix version when i back
from school. It's now 5:16am

**Comment by maxlehot1234** [comment]
Ohh, it is 17h16 (September 19) here :P

**Comment by xion87** [comment]
yeah is the same issue that i have

**Comment by OnlyNoobDied** [comment]
i knew the problem. If you want a fix it immediately. Try to remove
"Settings" section and reload the plugin.Then, you will see
"Enabled-Self-Morph-View".

**Comment by xion87** [comment]
i will wait the new release don't worry ^^

**Comment by OnlyNoobDied** [comment]
Okay, thanks.

**Comment by OnlyNoobDied** [comment]
Duplicate of #358

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/update?update=188464
