### ISSUE TITLE
Baby pets not working.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#361]
Hi, My players just report that baby pets not working :(

They can choose it but it was ALWAYS an adult one that spawn.

Any way to fix this?

Thank you

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Some players doesn't see them as baby's pets.

I see it as baby, but players see them adult. Any way to fix this?

**Comment by OnlyNoobDied** [comment]
Two player different minecraft version?

**Comment by OnlyNoobDied** [comment]
This plugin is not supported protocol hack
