### ISSUE TITLE
Issue with pets doesn't teleported with the player

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#362]
Hi, my players just found something:

If they use ./warp warpname command, theiur pets doesn't follow them :( 

Not sure if you can add something to fix this?

Thank you

**Comment by xion87** [comment]
i still find abandoned pets over the hub

**Comment by OnlyNoobDied** [comment]
@xion87  Can you give me your server ip.

**Comment by OnlyNoobDied** [comment]
@xion87  @maxlehot1234  Do me a favour please.
Try this version. Because this issue only occur 1.11-1.12, but i test everything on 1.10 spigot.
https://www.dropbox.com/s/vx0xzdc2z5nszxn/GadgetsMenu.jar?dl=0

**Comment by xion87** [comment]
i am using 1.8.9 here but with viaversion

**Comment by OnlyNoobDied** [comment]
Can you try the new version?
https://www.dropbox.com/s/vx0xzdc2z5nszxn/GadgetsMenu.jar?dl=0

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I will test it later today when less players are online and I let you know after few hours/days of testing.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Just to told you that pets are now teleported to the player.

BUT:

If the player was near the discoball gadget with his pet and teleport to another warp for example. The pet was teleported when the discoball gadget STOPPED.


I confirm that EVERYTHING was fixed with this build :)
Thank you, so you can release it to the public if you want I think. Exept if @xion87 have an issue

**Comment by xion87** [comment]
sorry i missed the emails notification, i have tested and seem to work better (no pets found)

**Comment by OnlyNoobDied** [comment]
Ok. seems like the bug has been fixed.

**Comment by xion87** [comment]
Pets still stay at hub ç_ç

**Comment by maxlehot1234** [comment]
@OnlyNoobDied @xion87 I confirm, problem occured again......

Please fix this ;)

Thank you

**Comment by OnlyNoobDied** [comment]
sorry, i will fix this bug after my exam is finished.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Ok ;) Do not forgot it, since it was a big issue ;)

Thank you so much
