### ISSUE TITLE
Permission issue?

### ISSUE THREAD

**Issue by Levi84** [OnlyNoobDied/GadgetsMenu#363]
I tried to do /gadgetsmenu but it said i dont have permission to do "that" in "this" world. i tried /gmysteryboxes, same error. I tried /mysterydust, same error. Anyone know what i'm doing wrong?

**Comment by OnlyNoobDied** [comment]
You need to setup the "enabled-worlds" in config.

```
# List of the worlds where cosmetics are enabled!
Enabled-Worlds:
- world
- world_nether
- world_the_end
```
