### ISSUE TITLE
[ISSUE] Error with radio gadget after plugin reload and cosmetics reset

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#366]
HI, I just try to reload the plugin using: ./gadgetsmenu reload command whyen I I have the radiogadget selected and after that, I try to reset my cosmetics. The sonc continue to be played for 4 seconds approximately.

If for I example, i get the radiogadgets and reset my cosmetics, WITHOUT plugin reload, the song stop after a millisecond approximately.

**Comment by OnlyNoobDied** [comment]
It is because the plugin was loading, and doesn't fully loaded.When plugin is fully loaded, the song will stop   and your gadget will be reset.

**Comment by maxlehot1234** [comment]
Occured only with discoball gadget :P But ok ;)

**Comment by OnlyNoobDied** [comment]
Close this issue due to outdated.
