### ISSUE TITLE
[ISSUE] Discoball gadget stop song fast

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#367]
Hi, the discoball gadget stop playing the musiong really fast I think.
In the middle of the song, stop playing... I set it to be 45 seconds, not 10 seconds :(

Are you able to fix this

Thank you

**Comment by OnlyNoobDied** [comment]
I count the time with my watch and i didn't found any problem. :P

The default value is 60 seconds. You can set the duration time more than 60 seconds.

**Comment by maxlehot1234** [comment]
I set it to 45 seconds and song stop after 15-20 seconds maximum in the middle of the song.

With the radio gadget, everything was fine with the same song...

**Comment by maxlehot1234** [comment]
Fix by put the duration seconds to 80-120 seconds ;) :)
