### ISSUE TITLE
[ISSUE] English name for pets :( :( Really bad for french servers

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#368]
Hi, why are you ONLY accept:
![image](https://user-images.githubusercontent.com/5159244/30786949-982f52aa-a14c-11e7-9c22-29dbb7b72489.png)

My players want to put é,ç,ô, î, etc. I have a french server, so accent are really useful in french.

Are you able to change this?

Thank you so much

**Comment by OnlyNoobDied** [comment]
ok
