### ISSUE TITLE
[FEATURE] Permission that bypass duration for gadgets

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#369]
Hi, is it possible to add a bypass permission that allow the player to listen the song full?

So if I set 60 seconds in the config, but the song last 75 seconds, the player that have the bypass duration permission,c can listen the song at 100%.

It could be nice I think ;)

Thank you

**Comment by OnlyNoobDied** [comment]
Good idea. This option will be added in the next update.

**Comment by OnlyNoobDied** [comment]
Can you help me to name permission :P.

**Comment by maxlehot1234** [comment]
Yes of course @OnlyNoobDied 

EX:
gadgetsmenu.bypasssongs


Also I think that PER song permission, rarity, could be amazing too ;) Like if the song was a gadget ;)

**Comment by OnlyNoobDied** [comment]
any better name?

similar "gadgetsmenu.bypassduration.discoball"

**Comment by maxlehot1234** [comment]
Yes of course ;) It will be USEFUL for biggest donators, staff, owner, events, etc ;)

**Comment by OnlyNoobDied** [comment]
any better name please?

**Comment by maxlehot1234** [comment]
Maybe: gadgetsmenu.bypassduration.music
OR
gadgetsmenu.bypassduration.song


I doesn't have a lot of ideas right now, since it was 3am here :P

**Comment by OnlyNoobDied** [comment]
hmm, okay

**Comment by OnlyNoobDied** [comment]
@maxlehot1234 
Can you help me to check the grammar error.

"You must be stand on higher than two blocks high of solid block!"

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update.
