### ISSUE TITLE
Saddle & Horsearmors

### ISSUE THREAD

**Issue by AccioAce** [OnlyNoobDied/GadgetsMenu#37]
This plugin has a bug so I remove it until is fix.

So bug is when we have this plugin on server you can't add saddles and horse armors to the horses after you claim them with apples

**Comment by OnlyNoobDied** [comment]
i know this bug but i didn't fix it.So i will give you a link to download
latest version.

**Comment by AccioAce** [comment]
ok thanks. when will you be able send me the lastest version? and will the lastest have this bug fix?

**Comment by OnlyNoobDied** [comment]
yes.

**Comment by AccioAce** [comment]
kk. Are you able send me the link through here? or where is the link the the lastest version?

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/430y2io12b9mqd8/GadgetsMenu.jar?dl=0
