### ISSUE TITLE
Does not work on 1.8

### ISSUE THREAD

**Issue by MrKayfer** [OnlyNoobDied/GadgetsMenu#371]
I downloaded this miracle and tried to launch it (on Java8). Gives an error and does not load! Here is the log
[latest.log](https://github.com/OnlyNoobDied/GadgetsMenu/files/1329565/latest.log)

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update. 
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-12.10885/
