### ISSUE TITLE
[Issue] Reloading the plugin in the console BUG

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#372]
Hi, when I reload gadgetsmenu using the console, I get this error:
https://hastebin.com/zepedanaqo.vbs

In-game, it works great and with plugman it works great too in-game/console.

Can you fix this when you can?

Thank you so much.

**Comment by OnlyNoobDied** [comment]
Did you just replace the new plugin to the old plugin

**Comment by maxlehot1234** [comment]
Nope, I simply change something in the configuration file.

I will use the command in-game next time ;)

**Comment by OnlyNoobDied** [comment]
This error will occur when you replace a new plugin
