### ISSUE TITLE
[BIG ISSUE]Gift to a players doesn't work

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#373]
Hi, I try to give a gift to a player, but he doesn't receive the chat message and NEVER received the gift, BUT, he can see that he receive 1 gift...
![image](https://user-images.githubusercontent.com/5159244/30948688-ada23c16-a3df-11e7-9c72-5b5378b43a65.png)

The gift inventory (EMPTY):
![image](https://user-images.githubusercontent.com/5159244/30948699-bceaf686-a3df-11e7-97fb-6b230ddf4ef3.png)

But he should received the pack...

It was not on my gift inventory anymore, since it was supposed to be sent to the other player :(

Please note, that I try to logout and log back on the server and I also try to restart the server

If I use: /gmysteryboxes gift playername 1
It works fine.

If you can fix this or told me how I can fix this, it could be nice.

Hope this issue can be fixed soon :)

Have a nice day/night to you.

PaperSpigot 1.12.2 build #b1216
GadgetsMenus 4.0.13

**Comment by OnlyNoobDied** [comment]
Let me explain to you.

You can give player mystery gifts by using this command. "/gmysteryboxes gift playername 1"
After that, player will receive the mystery gifts in their "Gift Inventory".
Once they send the gift to a player. The player will receive the gifts and can be seen/open in Mystery Vault menu. It's named "Gifted Mystery Box".

**Comment by maxlehot1234** [comment]
I understand, but why I can send a gift to another player and he NEVER received it?



jeudi 28 septembre 2017 04:05 -0400 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
The gift will be add in their "Mystery Vault" inventory.

**Comment by maxlehot1234** [comment]
They are not added into the gift inventory.

That’s weird, but if you told that they are added into the mystery vault, everything was fine 




jeudi 28 septembre 2017 04:11 -0400 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
So, is everything has been fixed?

**Comment by maxlehot1234** [comment]
Yes ;) Thank you
