### ISSUE TITLE
Error when reloading gadgets menus

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#376]
Hi, I just try to use: ./gadgetsmenu reload command and I get this issue in the console:
https://hastebin.com/ohikefepiz.md

So the only fix is to reboot the server :(

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Occured ONLY when I add/remove songs from  songs/DiscoBallGadget folder :(

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update.
