### ISSUE TITLE
Morph selfview

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#378]
When this is enabled you get pushed around constantly lol

* disable push when you have morph selfview enabled

**Comment by OnlyNoobDied** [comment]
This feature is unable to fix.

**Comment by xXIOSCARIXx** [comment]
I disabled push completely with another plugin, so it works fine now xD

**Comment by OnlyNoobDied** [comment]
I knew how to fix that bug, but it's not the best method. It using "/scoreboard teams option collisionRule never"
