### ISSUE TITLE
Server crash and Memory leak BIG time 

### ISSUE THREAD

**Issue by ITzD3stiny** [OnlyNoobDied/GadgetsMenu#379]
hello im using gadgets menu when i got the new update for gadgets when it auto update it self ive been seeing my server crash a lot and i didn't know why i didn't get any errors in the console so i looked at my crashed reports and it was gadgets menu causing the problem so when i deleted the plugin my server stop crashing

and im on spigot 1.8.8

https://pastebin.com/zfZscSGj

please fix this :)

thanks

**Comment by OnlyNoobDied** [comment]
I think there is a problem when update the plugin automatically.

**Comment by ITzD3stiny** [comment]
will this be fixed? @OnlyNoobDied

**Comment by OnlyNoobDied** [comment]
how many rams & plugins do you have in your server

**Comment by ITzD3stiny** [comment]
My server has 8 GB ram plugins 32 I think I left a pastebin link above that shows my server saying not enough memory then it stops so when I check the crash logs clearly showing gadgets menu and MySQL spamming

**Comment by OnlyNoobDied** [comment]
can you test the latest version of GadgetsMenu?
