### ISSUE TITLE
Not issue but got question

### ISSUE THREAD

**Issue by AccioAce** [OnlyNoobDied/GadgetsMenu#38]
Hello 

I also want say thank you for the update. Keep up good work with the plugin! 

I was wondering is there permission for players to reset there gadget. Because my players are having problem by clicking reset button it didn't reset there gadgets.

**Comment by OnlyNoobDied** [comment]
there's no permission for player to reset gadget. If the player cannot reset the gadget, just click another gadget and try to reset again.

**Comment by AccioAce** [comment]
Sorry nvm it work now. 

Thank you so much
