### ISSUE TITLE
Could not pass event InventoryClickEvent to GadgetsMenu v4.0.14

### ISSUE THREAD

**Issue by Fiks75** [OnlyNoobDied/GadgetsMenu#382]
Spigot 1.12. Console error:

04.10 05:15:09 [Server] ERROR Could not pass event InventoryClickEvent to GadgetsMenu v4.0.14
04.10 05:15:09 [Server] INFO org.bukkit.event.EventException: null
04.10 05:15:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
04.10 05:15:09 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
04.10 05:15:09 [Server] INFO Caused by: java.lang.NullPointerException
04.10 05:15:09 [Server] INFO at com.yapzhenyie.GadgetsMenu.listeners.cosmetics.SelectItemListener.onPlayerMoveItem(SelectItemListener.java:81) ~[?:?]
04.10 05:15:09 [Server] INFO at sun.reflect.GeneratedMethodAccessor416.invoke(Unknown Source) ~[?:?]
04.10 05:15:09 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
04.10 05:15:09 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
04.10 05:15:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
04.10 05:15:09 [Server] INFO ... 15 more

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
