### ISSUE TITLE
Add source code to repository

### ISSUE THREAD

**Issue by Phoenix616** [OnlyNoobDied/GadgetsMenu#383]
Currently the git repository does not seem to contain the source code of this plugin. Please add it so that others can modify it and contribute to the development of it.

**Comment by games647** [comment]
@OnlyNoobDied Any news on this or could you add a reason why you don't release the source code. There are people who want to contribute and help for this project.

**Comment by OnlyNoobDied** [comment]
i will post the source code when i get everything done.

**Comment by games647** [comment]
@OnlyNoobDied  So you don't want it to be Open-Source?

**Comment by OnlyNoobDied** [comment]
Sorry, no.
