### ISSUE TITLE
Unknow command when giving permission

### ISSUE THREAD

**Issue by Jacxk** [OnlyNoobDied/GadgetsMenu#385]
When a player opens up a mystery box in the console says unknown command.
I'm using zperms and this is my commmand "zperms player {PLAYER} set {PERMISSION} true"
I have tried with other commands but still does not work.

**Comment by OnlyNoobDied** [comment]
Pleqse check out Q&A page. I'm having exam right now.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust
