### ISSUE TITLE
Disable gadgets/cosmetics on PVP worldguard region

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#386]
Hi, I think it could be nice to add a section to disable gadgets, morph, pets in pvp worldguard region.

Since at the moment, players can morph and the become invincible :(

Thank you so much @OnlyNoobDied

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Any update for this?

**Comment by OnlyNoobDied** [comment]
I will add this feature after my exam is finished.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied AND? Your exams are finish?
