### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#387]
Hello i want to add gadgets to pvp. Can you add an attacker api to gadgets?
For example if I shot batblaster to enemy player on skywars and he fall into void it's doesn't return my nickname.

Damage event doesn't work for it :( Can you create events for gadgets?

It's very important for me. Thanks.

**Comment by OnlyNoobDied** [comment]
I'm not recommended you to put this plugin on your pvp server, because when you run some gadget, player damage will be disabled
