### ISSUE TITLE
GadgetsMenu

### ISSUE THREAD

**Issue by hash1r** [OnlyNoobDied/GadgetsMenu#39]
Hey,
I think your plugin "GadgetsMenu" is great and an essential plugin for a growing server. But I seem to have found a few things while using this plugin. One is after using gadgetsmenu sometimes my players and I end up being unable to teleport or do any tp type commands. As far as I know, the only way to fix is restarting the server, but that isn't very convenient. Second thing is the cowboy gadget. The cowboy gadget has two issues. 1, you can use it to mount NPCs (which I think should be an option) and 2, Once using it, you are stuck with cowboying only one person and when you try going to anyone else, it brings you back to that person. OTherwise this is a great plugin

**Comment by OnlyNoobDied** [comment]
noted

**Comment by OnlyNoobDied** [comment]
Fixed. but haven't test yet.

**Comment by hash1r** [comment]
Alright Cool! Also, the mobs thing don't have the slimeball to do the certain effects

**Comment by OnlyNoobDied** [comment]
actually i haven't add the slimeball morphd skills
