### ISSUE TITLE
MEMORY LEAK PLASE FIX ASAP

### ISSUE THREAD

**Issue by ITzD3stiny** [OnlyNoobDied/GadgetsMenu#390]
okay you told me to update the plugin and i did my server has 8 GB ram now my server is using 7GB ram of usage and when i uninstall gadgetsmenu i only get 500MB-1GB of ram usage please fix this issue

**Comment by maxlehot1234** [comment]
We need a timings, logs, something to help use troublehsoot your problem.

No One except you have an issue. Maybe your host? Another plugin? Your configs?

Show us few things if you need help

**Comment by ITzD3stiny** [comment]
its not my host here are my timings is a memory leak you can't see it dude
https://timings.spigotmc.org/?url=dulusagixo

**Comment by xion87** [comment]
Sample Time: 15s
run this for 10-30 minutes and repaste

**Comment by OnlyNoobDied** [comment]
how many worlds do you have in your server?

**Comment by ITzD3stiny** [comment]
maybe i was wrong sorry last time it did have a memory leak and my server crash but i guess it was fixed in the new update,
something else is causing the problem for the leak

**Comment by OnlyNoobDied** [comment]
okay.
