### ISSUE TITLE
[BIG ISSUE] Players can't rename pets

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#391]
Hi, my players just report something to me...

They can't rename their pets with capitals letters or use colocodes :(

I try to rename my pet and I can't use: test, TEST, &2Test or use é,ç,è,ê,à, etc

Are you able to fix this as soon as you can ?

This is a big issue.

Thank you so much.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
