### ISSUE TITLE
Morph Issue

### ISSUE THREAD

**Issue by Lmmb74** [OnlyNoobDied/GadgetsMenu#396]
Whenever I try to use a morph, I get displayed the following message:
> GadgetsMenu » You must remove your item in slot 5(NETHER_STAR) to equip a morph!

I am using the version 4.0.14 of this plugin, Spigot 1.8.8 and LibsDisguises 8.6.8.

**Comment by OnlyNoobDied** [comment]
it tells you to remove the item in slot 5 before equip morph

**Comment by Lmmb74** [comment]
But that's the item players use to open the GadgetsMenu main menu...

**Comment by OnlyNoobDied** [comment]
You need to change the slot.

```
Settings:
  Gadget-Slot: 5 <-- Change it to 6.
```

**Comment by Lmmb74** [comment]
Sorry, I had not checked that in config 😂. Thanks. Closing.
