### ISSUE TITLE
[Suggestion] Add more line for holograms

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#399]
Hi, could you add support for multiple lines for the vault holograms, so I can set something like this:

![image](https://user-images.githubusercontent.com/5159244/32206777-afd6a5b4-bdcd-11e7-99f0-133ea55c2dbb.png)

Thank you and have a nice day ;)

**Comment by OnlyNoobDied** [comment]
I think 2 + 1(individual) hologram is enough.
