### ISSUE TITLE
Morphs will not work

### ISSUE THREAD

**Issue by johnnymaister123** [OnlyNoobDied/GadgetsMenu#4]
When players click on the morph it just goes into the inventory, and when the press reset morph, it states, you werent morphed

**Comment by OnlyNoobDied** [comment]
can you explain more?

**Comment by johnnymaister123** [comment]
When players click the nether star, and when the press the morphs gui, and try to morph into, lets say a skeleton, all it does is puts the bone in their inventory instead of morphing them

**Comment by OnlyNoobDied** [comment]
can i have your server ip?

**Comment by johnnymaister123** [comment]
I've deleted the plugin do too the panes, even deleting the plugins wouldnt remove the panes so I had to reload the server to its state two days ago, so I'm not going to re install plugin till the panes are fixed

**Comment by Mineleague** [comment]
I have the same issue. Can you please help? IP:play.mineleague.net

**Comment by OnlyNoobDied** [comment]
## 1.10
 - Lib's Disguises: [LINK](https://www.spigotmc.org/resources/libs-disguises.81/download?version=102223)
 - ProtocolLib: [LINK](http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/modules/ProtocolLib/target/ProtocolLib.jar)

Please download this version of plugin.
