### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ZaxiuDev** [OnlyNoobDied/GadgetsMenu#40]
On the gadget with the bow and arrows, when not draw a lot of times we récuèpre arrows if you walk on it.

**Comment by OnlyNoobDied** [comment]
noted

**Comment by RedEyedRocker** [comment]
Add a delay to the bow and negate the delay bypass perms to the opped players.

**Comment by OnlyNoobDied** [comment]
RedEyedRocker, i think i will remove this option.

**Comment by RedEyedRocker** [comment]
No! Please don't do that, that's one of the fun cosmetic. I've even got some ideas with the bow powers like if you shoot the bow then at the spot where the arrow lands, lightning will hit/fire will start with configurable radius/any entities near the configurable radius will freeze for configurable time/the player will teleport.
Please don't remove that bow cosmetic or the option.

**Comment by OnlyNoobDied** [comment]
i means i will remove the admin can bypass the cooldown timer.

**Comment by RedEyedRocker** [comment]
No need to as you can negate the permission node.

**Comment by OnlyNoobDied** [comment]
k
