### ISSUE TITLE
Gadgets lores are not applied when in hand

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#400]
If you set a certain lore for a gadget, when you have it in your hand, the lore is not changed.

**Comment by OnlyNoobDied** [comment]
It should not change for the equipped item.

**Comment by YellowZaki** [comment]
Why? It makes no sense. If I translate a gadget lore, it should be visible everywhere, not only on the select menu.

**Comment by OnlyNoobDied** [comment]
when player equipped a gadget in their inventory, they will just use the
gadget anf will not read the information lore anymore.

**Comment by YellowZaki** [comment]
The gadget is an item, and it has lore.

**Comment by OnlyNoobDied** [comment]
i mean nobody will care about the lore after they select the gadget.

2017年11月9日 10:10 PM，"YellowZaki" <notifications@github.com>写道：

**Comment by YellowZaki** [comment]
I do XD. And my players say: why is the description in another language?

**Comment by OnlyNoobDied** [comment]
Alright, this issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
I thought you want to display lore in the item you selected. I just notice you tell me that the item lore doesn't same as the gui menu shows.
