### ISSUE TITLE
This item(COMMON Pets Cow) has been disabled, so player won't get the permission.

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#401]
Hi, I get this sometimes in the console for no reason. iT OCCURED, WITH ANY "Quality":
This item(COMMON Pets Cow) has been disabled, so player won't get the permission.

And my Players see this in-game
![image](https://user-images.githubusercontent.com/5159244/32593075-7ca00392-c4f4-11e7-838d-d939d8029b83.png)

When the player get the error I have in the console, they see this in the chat:
![image](https://user-images.githubusercontent.com/5159244/32593098-97d2346e-c4f4-11e7-8bdc-2e8c357b70bd.png)

NOTHING more in the console...

If I check the config for the COMMON Pets Cow, it was:
https://hastebin.com/acukojinaw.bash

The mystery box "inventory" was not supposed to update when I reload the plugin to prevent this things to occured?

Thank you so much and how I can fix this?

Also, when you update plugin? You have exams since 1 month ? :P

**Comment by OnlyNoobDied** [comment]
Because of you didn't disable (Common pet cow) before player getting the mystery box so it has a chance that this loot will contains in mystery box.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Any way to remove all my mysterybox ? Maybe inside MYSQL, FILE? etc?

Thank you

**Comment by maxlehot1234** [comment]
I switch into FILE at the moment to remove all my mysterybox...
