### ISSUE TITLE
[SUGGESTION] A remove box command for a player could be nice

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#402]
Hi, I just want to knof if you can add a command like:
/gadgetsmenu reset box <player>

This allow me (server owner) to reset ALL box of a player. For example, if he want to start the server from scratch or if I found him hack the server or if he ask me to remove his box.
It can be useful too if I am do some test and want to reset all my box.

This can also be useful for a problem like this one: #401 (I THINK)

Thank you.

**Comment by OnlyNoobDied** [comment]
#401 issue has been fixed in the new version of GadgetsMenu. In order to ensure that the player's mystery boxes will not be innocent disappeared, this command won't be added.
