### ISSUE TITLE
[Feature] Dev API give player boxes

### ISSUE THREAD

**Issue by AconTM** [OnlyNoobDied/GadgetsMenu#404]
it woud be nice if you can add an API Update to give Players a Box after a Minigame :)

- Acon

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/API#get-players-mystery-boxes

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/API#give-players-mystery-boxes
