### ISSUE TITLE
Can't open Mystery Boxes.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#405]
Hello !

My players have the permissions : 
gadgetsmenu.mysteryboxes
gadgetsmenu.mysteryboxes.open.*
gadgetsmenu.mysteryboxes.open.1
gadgetsmenu.mysteryboxes.open.2
gadgetsmenu.mysteryboxes.open.3
gadgetsmenu.mysteryboxes.open.4
gadgetsmenu.mysteryboxes.open.5

But they can't open the mystery boxes.
What permission is needed ?

**Comment by OnlyNoobDied** [comment]
Can player open mystery vault?

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
