### ISSUE TITLE
Auto-Update causes NoClassDefFoundError

### ISSUE THREAD

**Issue by NLthijs48** [OnlyNoobDied/GadgetsMenu#407]
It looks like the Auto-Update feature immediately replaces the jar file with the new one, causing the plugin to fail with NoClassDefFoundError exceptions until the server is restarted. correct way to update would be placing the .jar file in the `/plugins/update` folder, which will cause it to get copied to the `/plugins` folder at the next restart.

You can see more details in the code of this Bukkit plugin updater: https://github.com/gravitylow/Updater/blob/master/src/main/java/net/gravitydevelopment/updater/Updater.java#L225 (plugin.getServer().getUpdateFolderFile() can be used to get the update folder).

For now I just disabled the auto-update functionality, but considering this is on by default it seems important to me that this issue is looked at.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
