### ISSUE TITLE
[Suggestion] Death effect

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#408]
Hi, are you able to add something that allow the player to choose his death effect?

This will use particles. Players can choose from a pre-create list or he can use a death effect builder. Choose between 2 and 3 particle effects.

I think it could be really nice to have ;)

Thank you so much

**Comment by OnlyNoobDied** [comment]
Seems like this effect only used in mini games.  Not that wonderful if used in lobbies.
