### ISSUE TITLE
[Suggestion] A treasure Chest addon ;)

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#409]
Hi, are you able to add a treasure chest thing?

Of course plugin will offer few animations.
Players can open from 1 to 8 treasure chest base on his permissions.

It could be nice ;)

Thank you

**Comment by OnlyNoobDied** [comment]
What's the different between mystery boxes and treasure chest?

**Comment by maxlehot1234** [comment]
Good question :P Or add ANOTHER way for players to open a mysterybox... Maybe by right-clicking an NPC.

Because having 9999 mystery vault was weird and take a lot of place...

Or allow players to open their mysterybox from anywhere could be much better too ;)

**Comment by OnlyNoobDied** [comment]
oh, i gonna add some new animations. One of the animation is "none".

**Comment by maxlehot1234** [comment]
#336

**Comment by OnlyNoobDied** [comment]
What do you think if i add an option to disable animation for mystery box?

**Comment by maxlehot1234** [comment]
It can be good but the big problem is that I need to create a lot of mystery vaults so each player can open their mysterybox :(

An NPC could be the best thing OR allow players to open thei mysterybox from anywhere.

They can do/box to open the mysterybox inventory and when they click on a box and they confirm that they want to open it, they will see particles, sounds and hologram 2 blocks in front of them that display the cosmetic they won.

It would be amazing if you can and I know you can do this :P

**Comment by TheIntelloBox** [comment]
Could you add it so ? :D

**Comment by OnlyNoobDied** [comment]
Duplicate of #314 
Duplicate of #498
