### ISSUE TITLE
Mob Problems (Endermite one of them)

### ISSUE THREAD

**Issue by AccioAce** [OnlyNoobDied/GadgetsMenu#41]
Hello OnlyNoobDied

I just realize there another bug problem. When I try use egg like endermite and spawn one it doesn't work and it gadgetmenu causing that problem. Wonder if you can get the bugs fix.

Thank You

**Comment by OnlyNoobDied** [comment]
ok

**Comment by AccioAce** [comment]
hopefully is fix soon :)

**Comment by OnlyNoobDied** [comment]
i think it's not a big problem right?

**Comment by AccioAce** [comment]
It is big problem for my server. D: I was wondering if you would fix it?

**Comment by OnlyNoobDied** [comment]
erm, ok

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/ntejgq3vlswp9ld/GadgetsMenu.jar?dl=0
test it

**Comment by AccioAce** [comment]
Hello I tested it. endermite still not spawning with the egg.
