### ISSUE TITLE
/gadgetsmenu purge.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#411]
Hello ! 🗡 

Could you add the /gadgetsmenu purge ? 🗡 

Thanks ! :D

**Comment by OnlyNoobDied** [comment]
purge what?

**Comment by TheIntelloBox** [comment]
Data.

**Comment by OnlyNoobDied** [comment]
What data do you want to delete? Mystery Boxes or Selected cosmetics?

**Comment by TheIntelloBox** [comment]
I want to delete the data of old players who are connected since 6 months for example. :)

**Comment by OnlyNoobDied** [comment]
We does not save "last-join" time in the playerdata, so unable to do it.

**Comment by OnlyNoobDied** [comment]
:D, i found a way to add this command.

**Comment by OnlyNoobDied** [comment]
This command has been added in the latest version.
