### ISSUE TITLE
Lag on quit

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#413]
Hello, 

I have an issue with your plugin. I have a good dedicated server and if i get join bot attack i have a lot of lags causing your plugin

I get lags on:
GadgetsMenu::Event: c.y.G.l.PlayerListener (PlayerQuitEvent)

**Comment by Feerko** [comment]
it was caused by mysql, if i change Storage to file it's works normal.

**Comment by Feerko** [comment]
i tested without your plugin and everything works nice, i get tps drop to only 18. with your plugin my server go down.

it was caused by mysql, if i change Storage to file it's works normal.

**Comment by OnlyNoobDied** [comment]
I found some major issue while using MySQL. I will find out the problem and solve it as quickly as possible.

**Comment by Feerko** [comment]
@OnlyNoobDied can you help me? my server gets big lag.

**Comment by Feerko** [comment]
@OnlyNoobDied it's very important for me, please.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
