### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#420]
Gadgets Menu doesn't restore cosmetics between servers.

**Comment by OnlyNoobDied** [comment]
You use files or mysql storage?

**Comment by Feerko** [comment]
mysql, this exists only with newest version.

**Comment by OnlyNoobDied** [comment]
all cosmetics doesn't sync or just specific cosmetic?

**Comment by Feerko** [comment]
all

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
