### ISSUE TITLE
[SUGGESTION] Holographic Menu

### ISSUE THREAD

**Issue by PetteRed65** [OnlyNoobDied/GadgetsMenu#424]
Why do not you add a "Holographic" menu like the "Prodigy Gadgets" plugin to GadgetsMenu?
And can you add iDisguise to GadgetsMenu instead of Lib's Disguises?

**Comment by OnlyNoobDied** [comment]
There's 134+ hats,113 pets available. Are you sure you want to add 3D menu?

GadgetsMenu also supported for iDisguise but you can't use morph ability.
