### ISSUE TITLE
Quest for Mystery Box.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#426]
Hello,

It would be cool if we can do quests for Mystery Boxes.
For example : Play 4 hours and get 3 Mystery Boxes.

Thanks !

**Comment by OnlyNoobDied** [comment]
This can be done using other plugin.

**Comment by OnlyNoobDied** [comment]
Oops, this feature has been added into the plugin long time ago.
