### ISSUE TITLE
Permissions for mystery boxes doesn't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#427]
Hello,

I have put to a player these permissions : gadgetsmenu.mysteryboxes.open.1, gadgetsmenu.mysteryboxes.open.2, gadgetsmenu.mysteryboxes.open.3, gadgetsmenu.mysteryboxes.open.4, gadgetsmenu.mysteryboxes.open.5 et gadgetsmenu.mysteryboxes.open.*

This doesn't work.
Thanks.

**Comment by OnlyNoobDied** [comment]
player needs one more permission to open the box. I mentioned in the forum.

**Comment by TheIntelloBox** [comment]
Could you give me it please.

**Comment by OnlyNoobDied** [comment]
gadgetsmenu.animations.*
  - gadgetsmenu.animations.none
  - gadgetsmenu.animations.normal
