### ISSUE TITLE
Mob Problems (Endermite one of them) 

### ISSUE THREAD

**Issue by AccioAce** [OnlyNoobDied/GadgetsMenu#43]
Hello OnlyNoobDied

I have tested it but afraid still didn't work

endermite still not spawning if I use the egg to spawn it. I just tested it.

**Comment by AccioAce** [comment]
Sorry nvm it work now. 

Thank you so much

**Comment by OnlyNoobDied** [comment]
lol, i will fix it later

**Comment by OnlyNoobDied** [comment]
so.. is it really fixed?
