### ISSUE TITLE
Cost of item

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#432]
Hello, can you add a placeholder {MYSTERY_DUST} in loot message?
i want to create something like this. If you open an mystery box and it's show message:

[Mystery Box] %player% win a {LOOT} worth {MYSTERY_DUST} mystery dust.

this will add value to the items. Items will become more valuable.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

**Comment by OnlyNoobDied** [comment]
This feature will not mentioned in the updates but you can use it.
