### ISSUE TITLE
Clearing the gadget slot!

### ISSUE THREAD

**Issue by LagBug** [OnlyNoobDied/GadgetsMenu#433]
Instead of having that message: 
![image](https://user-images.githubusercontent.com/25084277/33851515-e06d4a8a-debf-11e7-9ea0-8181b314f659.png)
You could have like an option in config.yml that will clear that slot, so they don't have to throuw the item!

Thanks!

**Comment by OnlyNoobDied** [comment]
If that item is very important for that player, he might be very angry with it.

**Comment by Feerko** [comment]
@OnlyNoobDied you can create few ways in config: clear / drop / nothing. That would be cool.

**Comment by LagBug** [comment]
@OnlyNoobDied That is why I said to add an option to config! The server owner will be able to change like @Feerko said the action! Please add this! It would be very very very useful! :D

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update. Please check the forum
