### ISSUE TITLE
[BUG] Sand castle gadgets won't be place

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#435]
Hi the new sand castle gadgets won't be place. I try to be two block high, buyild a 3 blocks tower and stand on it, same issue :(

Is it normal?

Thank you

**Comment by maxlehot1234** [comment]
Same thing for the pocket beach gadget

**Comment by OnlyNoobDied** [comment]
try stand on the top of 5 x 5 x 2 grass.

**Comment by maxlehot1234** [comment]
It should work on any blocks to be a really nice gadget ;)




mardi 12 décembre 2017 07:08 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Cant, because sand block will fall
