### ISSUE TITLE
[Suggestion] Add more particles shape

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#436]
Hi, I just want to know if you can add a new particleshape options inside the plugin?

When we click on particles inside gadgets main menu, we will see: helix, sphere, halo, spiral, demi spiral, double halo, double helix, etc

You can check here: https://dev.bukkit.org/projects/effectlib

I think it can be nice to have a lot more particles shape ;)

Also, inside custom particles.yml file, you can add:

Shape: Halo

This mean, that it will added into halo sub-menu directly and can be loot/purchase by players :)

Thank you so much

**Comment by TheIntelloBox** [comment]
Good idea.

**Comment by OnlyNoobDied** [comment]
This feature has been replaced with Cloaks
