### ISSUE TITLE
[Bug ?] SWEEP_ATTACK custom particles do nothing

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#437]
Hi, I just try to create a custom particle using SWEEP_ATTACK but it do nothing in-game and no errors. Is it normal?

Thank you so much

**Comment by OnlyNoobDied** [comment]
SWEEP_ATTACK particle is not available.
Here is the particle effects list.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Particle-Effects

**Comment by OnlyNoobDied** [comment]
I will test it in my server.

**Comment by maxlehot1234** [comment]
Yes it was available under 1.9 particle effects at the bottom of the page :(




mardi 12 décembre 2017 07:16 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
yeah, i just noticed that. My bad

**Comment by OnlyNoobDied** [comment]
It works
![2017-12-12_20 32 40](https://user-images.githubusercontent.com/13622737/33884689-a6c03204-df7b-11e7-98ec-1b4e77729581.png)

**Comment by maxlehot1234** [comment]
Not for me under paper spigot 1.12.2





mardi 12 décembre 2017 07:33 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Did you turned off your particles in settings?

**Comment by maxlehot1234** [comment]
No since all other particles works exept this one 




mardi 12 décembre 2017 07:36 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
any typo?

**Comment by maxlehot1234** [comment]
No I copy-paste the effect name 





mardi 12 décembre 2017 08:58 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Send "custom particles.yml" file to me please

**Comment by maxlehot1234** [comment]
@OnlyNoobDied The file was wipe in latest plugin versions :( SO I need to recreate it again :(

I let you know in few hours after my test if I have the same problem.

**Comment by OnlyNoobDied** [comment]
If there is any typo in that file, it will be removed automatically.

**Comment by OnlyNoobDied** [comment]
any updates on this?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I will close it , it work with paperspigot update. Not sure if it was directly link to this or anything else, but it works ;) Thank you for your time
