### ISSUE TITLE
[Bug] Flower giver bug

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#438]
Version 1.8.8:
- for give a flower to a player, the player must click exact on player head or it don't work
- you can offer flower to npc citizens
- the flower will spawn on head flying (not sure if is wanted or not) (see the screenshot)
![immagine](https://user-images.githubusercontent.com/3611852/33883806-90d61848-df3d-11e7-815b-ad89f86b51b4.png)

**Comment by OnlyNoobDied** [comment]
"the flower will spawn on head flying" It's not a bug.

**Comment by xion87** [comment]
it was not supposed to grow on head? xD

**Comment by OnlyNoobDied** [comment]
Yes, it is

**Comment by OnlyNoobDied** [comment]
Flower spawn above the head instead of npc citizens isn't great?

**Comment by OnlyNoobDied** [comment]
The only way to target player is pointing their head.
