### ISSUE TITLE
[HALP] How to add mystery boxes animations?

### ISSUE THREAD

**Issue by ImJustVlad** [OnlyNoobDied/GadgetsMenu#439]
pls add mystery boxes animations psla am desperate

**Comment by OnlyNoobDied** [comment]
More animations will be added soon.

**Comment by ImJustVlad** [comment]
But how can you add by urself?

**Comment by OnlyNoobDied** [comment]
You can't add by urself.

**Comment by OnlyNoobDied** [comment]
More animations will be added in the next update.
