### ISSUE TITLE
Feature : "Customize the messages of the rocket launcher" and the prefix.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#44]
Hello,

The title says all ! :)
I want to customize the messages of the rocket launcher (gadget). :D 
If you want too, I want to customize the prefix. x)

Thanks ! :D

**Comment by OnlyNoobDied** [comment]
ok

**Comment by TheIntelloBox** [comment]
Where can I have this features ? :D

**Comment by OnlyNoobDied** [comment]
wait 3.6.0 update

**Comment by TheIntelloBox** [comment]
Okay. :D
