### ISSUE TITLE
Silkspawners error with latest version of plugin

### ISSUE THREAD

**Issue by xXIOSCARIXx** [OnlyNoobDied/GadgetsMenu#440]
After updating the gadgets menu plugin i get this error in console:

[18:40:27 ERROR]: [SilkSpawners] Failed to dump entity map: entity is null, entityID: 201
[18:40:27 ERROR]: [SilkSpawners] Failed to dump entity map: entity is null, entityID: 201

It occurs only on server start up as i've seen.

**Comment by OnlyNoobDied** [comment]
What's your server version?

**Comment by OnlyNoobDied** [comment]
Did you upgrade GadgetsMenu to the latest version?

**Comment by xXIOSCARIXx** [comment]
Paper spigot 1.12.2 latest

**Comment by xXIOSCARIXx** [comment]
Yes, latest version

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

By the way, do not use 'customarmorstandfollower' spawner.
Disable it in mobs.yml file.

**Comment by xXIOSCARIXx** [comment]
I could not find this, maybe it got removed in a update ;)

2017-12-13 5:13 GMT+01:00 Yap Zhen Yie <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
customarmorstandfollower will be created in mobs.yml in the next update.
