### ISSUE TITLE
How to disable permissions for some?

### ISSUE THREAD

**Issue by Remilin** [OnlyNoobDied/GadgetsMenu#442]
> How to disable permissions for some players to use some gadgets, or pets, or others only if they have a higher rank? Making it like as you hover your mouse over some gadgets, it says that they need to be a donator to use it. 

> And, encountered a 'bug' that a wither skeleton pet can obtain other player's weapon. How to disable this? :I

**Comment by OnlyNoobDied** [comment]
What's your server version and your launcher version?

**Comment by Remilin** [comment]
server version is 1.11

**Comment by OnlyNoobDied** [comment]
minecraft launcher version?

**Comment by OnlyNoobDied** [comment]
By the way, you can only disable player to "Purchasable"and "canBeFound" to avoid that player get that item.
