### ISSUE TITLE
[Suggestion] Prevent to see his particles

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#444]
Hi, I just want to know if you can add something to prevent the player to see his particles?

Like you do for Morph Self view.

Maybe add particles self view settings in the GUI can be nice ;)

Thank you

**Comment by OnlyNoobDied** [comment]
Good idea :D

**Comment by OnlyNoobDied** [comment]
```
  # Set to true will shows particle effect to everyone,
  # otherwise will only show to the player itself.
  Show-Particle-Effect-To-Everyone: true
  # Set to true will shows cloak effect to everyone,
  # otherwise will only show to the player itself.
  Show-Cloak-Effect-To-Everyone: true
```

**Comment by maxlehot1234** [comment]
An any way to prevent myself to see my own particles/cloak?

**Comment by OnlyNoobDied** [comment]
unequip...

**Comment by maxlehot1234** [comment]
I want other players to see my particles but when we mine, or do anything else, I see my own particles. This is my point.

Why not add something to prevent the player to see his own particle?





dimanche 17 décembre 2017 19:53 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
why do people do not want to see himself particle effect?
