### ISSUE TITLE
How to Change Mystery Vault Holo

### ISSUE THREAD

**Issue by blizma** [OnlyNoobDied/GadgetsMenu#445]
I was trying to change the way the Vault looks when you place, it. The dev says to look into the mystery boxes folder, I looked and there nothing in the folder, please help. The people are saying the server is similar to Hypixel

**Comment by OnlyNoobDied** [comment]
You can change the holograms in "mystery boxes.yml" file.

You may find "Holograms" in the file.

**Comment by blizma** [comment]
Thank you

**Comment by blizma** [comment]
But I have not found any files what so ever

**Comment by OnlyNoobDied** [comment]
You can find it in mystery boxes
folder.

**Comment by blizma** [comment]
But the folder is empty upon opening it?

**Comment by blizma** [comment]
And also thank you for dealing with all this nonsense

**Comment by OnlyNoobDied** [comment]
send you send all the files to me?

**Comment by blizma** [comment]
I'm sorry but I'm using a custom hosting program in which I cannot download the files

**Comment by OnlyNoobDied** [comment]
screenshot?

**Comment by blizma** [comment]
![ss1](https://user-images.githubusercontent.com/34592028/34076396-de31d586-e2b3-11e7-8f2e-9b2b0e00e50a.png)

**Comment by OnlyNoobDied** [comment]
GadgetsMenu folder pls.

**Comment by blizma** [comment]
![ss2](https://user-images.githubusercontent.com/34592028/34076621-8e9f290e-e2ba-11e7-9ed7-4fb60c441d28.png)

**Comment by OnlyNoobDied** [comment]
What's your GadgetsMenu version?
Can you give me your server ip? Let me take a look

**Comment by blizma** [comment]
metis.aternos.me, but there is a whitelist

**Comment by OnlyNoobDied** [comment]
My ign is OnlyNoobDied

**Comment by blizma** [comment]
Whitelist is off

**Comment by OnlyNoobDied** [comment]
This issue cause by the free hosting.
