### ISSUE TITLE
[Performance problem] Performance issue with PlayerQuitEvent

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#446]
Hi, I have a performance issue with the plugin:
![image](https://user-images.githubusercontent.com/5159244/34072639-f71c0f7c-e258-11e7-8986-a231685cbe21.png)

Are you able to look into it for me? 

Thank you so much

**Comment by OnlyNoobDied** [comment]
can you give me a full timings report?

**Comment by maxlehot1234** [comment]
Here it is: https://timings.aikar.co/?id=eded1efd12ab4b18b03bd9ddba4773e3

Like you can see, it was not playerquitevent all the time, but check:
![image](https://user-images.githubusercontent.com/5159244/34084002-72f51c58-e347-11e7-9017-82a42a613808.png)


The GadgetsMenu (SELF) take a lot of ressources.

**Comment by OnlyNoobDied** [comment]
This issue should be fixed in version 4.1.18
