### ISSUE TITLE
Characters in config.yml

### ISSUE THREAD

**Issue by GitTobbz** [OnlyNoobDied/GadgetsMenu#447]
Using characters like "Æ", "Ø" or "Å" is not possible in the config file(But it is in messages.yml). Therefore it's not possible to translate the word "pet" to "kjæledyr"(Norwegian). As these letters turn into "??" in the name. The only solution I have found is to change it manually(Re-edit config.yml) every time I start the server or reload the plugin. 

Just changed config.yml:
![p2](https://user-images.githubusercontent.com/22430916/34074774-b2c951a0-e2b6-11e7-9b7a-7e027e09a03e.PNG)

After I reload the plugin with /gmenu reload:
![p1](https://user-images.githubusercontent.com/22430916/34074733-009180ac-e2b6-11e7-90ea-d8e944dc414d.PNG)

**Comment by OnlyNoobDied** [comment]
What's your server version?

**Comment by GitTobbz** [comment]
The server is running Spigot 1.12.2.

**Comment by OnlyNoobDied** [comment]
Use this
```
Default-Pet-Name: "&b{PLAYER}''s kjæledyr"
```
instead of this.
```
Default-Pet-Name: '&b{PLAYER}''s kjæledyr'
```

**Comment by GitTobbz** [comment]
I used 

`Default-Pet-Name: "&b{PLAYER}'s kjæledyr"`

put it does the same thing still.

**Comment by OnlyNoobDied** [comment]
I changed the file format in the next update(4.1.4). Let me know if you can/can't use these characters.

**Comment by GitTobbz** [comment]
Looks like you fixed the problem, thanks.

**Comment by GitTobbz** [comment]
Also, I don't know if i'm the only one with this problem, but the vaults seem to not show up right after I start the server. The vaults are still saved so reloading fixes it.

**Comment by OnlyNoobDied** [comment]
Alright, this should be fixed in the next update.
