### ISSUE TITLE
Monster Morphs/Pets Do Not Spawn In

### ISSUE THREAD

**Issue by xMasterCrafter** [OnlyNoobDied/GadgetsMenu#453]
Running on server version 1.12 
Using disguise plugin LibsDisguise
Monsters do not spawn at all wether mobs are toggled on or off all animals work but monsters do not

**Comment by OnlyNoobDied** [comment]
Did you set the difficulty to peaceful?

**Comment by xMasterCrafter** [comment]
No game difficulty is normal according to the properties file

**Comment by xMasterCrafter** [comment]
one of my admins contacted me they switched the setting on the world via multiverse ill check it out to see if thats the problem

**Comment by xMasterCrafter** [comment]
Problem Solved thank you for your help!

**Comment by OnlyNoobDied** [comment]
So, what's the problem?
