### ISSUE TITLE
Gadgets can be took by players

### ISSUE THREAD

**Issue by EveLynn666** [OnlyNoobDied/GadgetsMenu#456]
Players are able to take the banners if they spam it and they will be able to place it, if they are in creative.

https://imgur.com/a/Dde3D

EDIT: They are able to take any hat they wear, even the hats from suits and they can multiple the emotes..
EDIT 2: They can multiple any item that can be weared, the suits for example, but they can't drop it or put it in a chest.

**Comment by TheIntelloBox** [comment]
Yes I had this bug.

**Comment by EveLynn666** [comment]
i found more on the hats and emotes, seems that this bug works on every hat.

**Comment by TheIntelloBox** [comment]
Yep.

**Comment by OnlyNoobDied** [comment]
I cant do anything if players in Creative mode. I already knew this issue but i cant find any way to fix it.
