### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by johnsoncui02** [OnlyNoobDied/GadgetsMenu#46]
There's a visual bug while using PluginReloader while using the ghost gadget. whereas when i shut down and restarted the server the gadget gets stuck and stops moving and acting like a block. The block cannot be removed no matter what i tried. any solutions to this?

**Comment by OnlyNoobDied** [comment]
noted.

**Comment by OnlyNoobDied** [comment]
to remove those block.
command: /kill @e[type=ArmorStand]

**Comment by OnlyNoobDied** [comment]
do not use pluginreloader to reload plugin
