### ISSUE TITLE
[Suggestion] Option to choose the sound source music

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#460]
Hi, I just want to know if you are able to add sound source.

https://minecraft.gamepedia.com/Commands/playsound

It will be better than the actual master volume.

Maybe allow us to chosse between:
master, music, record, weather, block, hostile, neutral, player, ambient, or voice.

Thank you so much, happy holidays and nice camping

**Comment by OnlyNoobDied** [comment]
I think Note Block Studio doesn't supported for this.

**Comment by OnlyNoobDied** [comment]
As I want to make this plugin compatible with 1.8 ~ 1.12 Spigot server, so this feature can't be add into the plugin.
