### ISSUE TITLE
[Bug] I can't use special character as pet name again...

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#461]
Hi, I know that you are in camping, but I just report it in case I forget this bug :P 

I try to rename my pet with &4 (I try to choose my pet name color) and I can't. I get this message:
![image](https://user-images.githubusercontent.com/5159244/34288862-98ff2eb0-e6bd-11e7-81d7-3ad3166adf15.png)

Is it normal? Since you are supposed to fix it few version ago.

Thank you and welcome back.

**Comment by OnlyNoobDied** [comment]
What character did you use?

**Comment by maxlehot1234** [comment]
I simply to try to add a colour code :(  this one: &



vendredi 22 décembre 2017 04:06 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
It's working in the latest version. I tested

**Comment by OnlyNoobDied** [comment]
By the way, i still haven't go to school camp yet.

**Comment by maxlehot1234** [comment]
Ok I will try tomorrow and let you know :)





vendredi 22 décembre 2017 04:08 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
You cant use these character "$+,:;=?@#|'<>.^*()%!_-".

**Comment by OnlyNoobDied** [comment]
any updates?

**Comment by maxlehot1234** [comment]
@OnlyNoobDied I try to use: & symbol to add a color code and it was not allow :( Why?

**Comment by OnlyNoobDied** [comment]
Are you using the latest version of GadgetsMenu?

**Comment by OnlyNoobDied** [comment]
Any new about this issue?
