### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#462]
Placeholders shows wrong values.
This is a screen of cloaks.

<img width="407" alt="zrzut ekranu 2017-12-24 o 15 05 03" src="https://user-images.githubusercontent.com/16988054/34327085-df9336e6-e8bb-11e7-92ef-dc49245a99b6.png">

<img width="262" alt="zrzut ekranu 2017-12-24 o 15 05 10" src="https://user-images.githubusercontent.com/16988054/34327086-ee206af8-e8bb-11e7-9203-76546b7b534a.png">

**Comment by OnlyNoobDied** [comment]
I think you use the wrong placeholder.
