### ISSUE TITLE
[BUG :(] Pets not removed on player logout :(

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#463]
Hi, Player pets are not removed when the server reboot or player leave under PaperSpigot latest build (#1286) and previous one too :(

Any way to fix this when you can, since pets are not useful if the "owner" of the pet was not online :P 

Thank you so much ;)

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Any news for this issue again?

**Comment by OnlyNoobDied** [comment]
Sorry, i have lots of work need to be done. I will release new update next week.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied And any update on this huge issue? Occured with PaperSpigot OR Spigot...
1.12.2 Both are latest version and same problem occured

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Continue to occured. Please, do something or release the source code to allow devs to work on this or add a dev for 2018 PLEASEEEE

Thanks

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in version 4.1.18
