### ISSUE TITLE
Delete Cosmetics

### ISSUE THREAD

**Issue by timmehz** [OnlyNoobDied/GadgetsMenu#464]
Suggestion: permission and command to delete all cosmetics or certain ones like a command like this /gadgetsmenu del cos <cosmetics name, cosmetics name, etc:all>

**Comment by OnlyNoobDied** [comment]
you can use /gmenu remove

**Comment by timmehz** [comment]
I typed in that command and it printed out the GadgetsMenu help commands.

**Comment by OnlyNoobDied** [comment]
Sorry, the command is /gmenu reset

**Comment by timmehz** [comment]
I have did that command, but it did not reset anything, is there a permission to keep all coses?

**Comment by timmehz** [comment]
I did that and it did not got resetted

**Comment by OnlyNoobDied** [comment]
Did you get any message?

**Comment by timmehz** [comment]
I got the reset message but it did not reset anything

**Comment by OnlyNoobDied** [comment]
Which cosemtic doesn't reset?

**Comment by timmehz** [comment]
all of them

**Comment by OnlyNoobDied** [comment]
What's your server ip?

**Comment by timmehz** [comment]
my server ip is hexturnmc.strangled.net:25565  (I use a sub-domain for safety reasons)

**Comment by timmehz** [comment]
the server well be offline within 38 mins within this message, if you do not come online today then I well message when the server is back up (the server is not a 24/7 server)

**Comment by timmehz** [comment]
ok, the server is up, you can now join.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for new update.
