### ISSUE TITLE
Players can get Crafted MysteryBox in their inventory SOMETIMES

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#467]
HI, I really don't know how players can have the crafted mysterybox in their inventory:
![image](https://user-images.githubusercontent.com/5159244/34457209-ff5fbd8a-ed77-11e7-84cb-34104ff9d48f.png)

Players drop them so I take a screenshot.

Let me know if it was a plugin issue, or internet issue 

Thank you so much ;)

**Comment by OnlyNoobDied** [comment]
This issue might occur if that player is in creative mode. Since i have checked the code.Moreover, internet problem won't occur this problem so this issue caused by some other reasons.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update. If you still have the same problem please inform me.
