### ISSUE TITLE
[Plugin suggestion] Create a new plugin BASE on gadgetsmenus

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#469]
Hi, 

You make a really AMAZING JOB on this plugin.

I just want to know if you can create the same thing, but the server owner can add more things inside mysterybox, items, commands, money, etc.

It can be an addon that was hook inside gadgetsmenus ;)

I am sure this will be the best addition you can do for gasdgetsmenus.

Of course, you can sell the ADDON on spigot for 5-15$USD for sure.
In this addon, we can add something. If it was set to false, we can use only your plugin to add commands, items, money, etc .Cosmetics items will be DISABLED

If we set it to true, cosmetics items will be supported PLUS commands, items, money, etc ;)

Thanks a lot if you can develop this.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/tokenshop-1-8-1-12.34455/

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Not a plugin a like this :P 

I mean a plugin that allow me to add multiple rewards: (tokens, money, gadgets, pets, particles, permission, etc) and players can get them from mysterybox.


Samething like: MYSTERY BOXES by xeRicker from spigot.
You offer a really BETTER configs files ;) so I am sure that you can develop a premium addon maybe?

Thanks again

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
I mean something looks like MYSTERY BOXES  by xeRicker on Spigot.

I am 100% sure that you can add this but as an add-on.

This add-on can become premium on spigot I think.


Thanks a lot and have a nice day

**Comment by OnlyNoobDied** [comment]
This can be done with GadgetsMenu premium version. (Custom loots)
