### ISSUE TITLE
Disguises for 1.8

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#47]
can you add disguise for 1.8.9 servers?  :c

**Comment by OnlyNoobDied** [comment]
let me test lib's Disguises plugin on 1.8 server. i will let you know.

**Comment by OnlyNoobDied** [comment]
can i ask some question, do you test Lib's disguise on 1.8 server?
is it running well or get errors?

**Comment by DebugingLonks** [comment]
Tested this for ya, I get errors, and sometimes it spams me "UNABLE TO RUN COMMAND" (Gadgets spam me that. Well not gadgets, but the plugin msgs me in chat, no gadget problem, just morphs don't work right)

**Comment by OnlyNoobDied** [comment]
i means do not use GadgetsMenu plugin test 1.8 Morphs.
Use LibsDisguises plugin to test it.
/disguise <type>

**Comment by OnlyNoobDied** [comment]
i tested on my server, it keep spam "{Player} move wrongly!"
