### ISSUE TITLE
[Issue?] Mystery Boxes Available hologram

### ISSUE THREAD

**Issue by 7GrandDadMC** [OnlyNoobDied/GadgetsMenu#472]
In original server, when no boxes available, "(Number) Boxes Available" hologram will be hidden but GadgetsMenu's "(Number) Boxes Available" hologram is always visible.

**Comment by OnlyNoobDied** [comment]
i think it's not a big problem.

**Comment by altrisi** [comment]
No, it isn't a a big problem but maybe it would be possible to another string to show if the user don't have any box, so you can write something like "No Boxes Available" or leave it blank.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
