### ISSUE TITLE
Suggestion: Allow cosmetics to only be used if the user have another permission

### ISSUE THREAD

**Issue by altrisi** [OnlyNoobDied/GadgetsMenu#474]
What I mean:
Anyone can find the cosmetics in the Mystery Boxes, but only if the player have some special permission the player can activate/equip/spawn it. This special permission don't need to be mandatory in everything, but it can be configured.
Maybe something like

```
require-extra-permission-to-use: boolean value
extra-permission: 'the.permission.to.use'
```

or just detect if there is something in the extra-permission string (or if it have a different value to 'none').

**Comment by OnlyNoobDied** [comment]
This make the plugin more complicated

**Comment by altrisi** [comment]
Closing as stale
