### ISSUE TITLE
[BUG !!] Animations fro players doesn't work

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#476]
Hi, 

I try to remove the normal permission for players, They can still use it :(

I try to put normal animation to false inside animations.yml and players still use normal animation

I try to remove normal animation from the config and players can still use the normal animation..

HOW I CAN FORCE the NONE animation PLEASE?

Thank you so much

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
