### ISSUE TITLE
[BUG] Bypass doesn't work

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#477]
Hi, I am OP and I can't bypass gadgets cooldown :O 

I try to add myself the permission: gadgetsmenu.cooldown.bypass

Same problem...

Any fix for this please?

**Comment by OnlyNoobDied** [comment]
"gadgetsmenu.cooldown.bypass" permission just allow you to toggle cooldown option. You can enable/disable it in settings menu.

As most of the people hide settings menu, i will add a command to bypass cooldown.

**Comment by OnlyNoobDied** [comment]
"/gmenu settings bypasscooldown <true|false>" command will be added in the next update.
You can modify the settings via command.
