### ISSUE TITLE
Cowboy Gadget Bugs

### ISSUE THREAD

**Issue by hash1r** [OnlyNoobDied/GadgetsMenu#48]
Alright, so there's a few things. Thanks for the continuous support btw.

1) You can stack on NPCs. I've been able to stack on our Delivery Man. We use Citizens

2) After stacking on Delivery man, and 3 other of my friends stacking on each of us, the server crashed. Here's a Pastebin of the error: http://pastebin.com/Cuvyp93q

3) When stacking on someone, there's a 50/50 chance they see you on them. That should be fixed.

4) Sometimes you can't switch from stacking between two different people. Again, it isn't huge but could be resolved.

Cheers mate

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/ajlkghxhaav6qvr/GadgetsMenu.jar?dl=0
test it.

**Comment by OnlyNoobDied** [comment]
did you get any errors?

**Comment by hash1r** [comment]
Sorry for the late reply, I'll test it and let you know.

**Comment by hash1r** [comment]
I've tried with one other person and when I am with an npc and I click on the gadget, it rides successfully but it spams the chat twice saying "There are no players nearby"

**Comment by hash1r** [comment]
Also players still don't see users on them.
