### ISSUE TITLE
Unsupported Version? (1.8.9)

### ISSUE THREAD

**Issue by ImJustVlad** [OnlyNoobDied/GadgetsMenu#486]
I saw that on Spigot it says [1.8-1.12] and i was like "FINALLY! God a supporting cosmetic plugin -.-"
When i downloaded on Aternos It didn't work..
No it's not because of aternos It works on other versions..
**Is it unsupported?**

**Comment by OnlyNoobDied** [comment]
Are you using spigot server?

**Comment by ImJustVlad** [comment]
Yeah

**Comment by OnlyNoobDied** [comment]
Please do not use free server hosting to run this plugin

**Comment by ImJustVlad** [comment]
Sorry.. I will buy mcprohosting soon but on my other server it worked 100% why on 1.8.9 it doesn't work?

**Comment by OnlyNoobDied** [comment]
That "free hosting" server has limited storage for each plugin.

**Comment by ImJustVlad** [comment]
It actually doesn't it has unlimited plugins i have 43 plugins and on the other server i had 110

**Comment by ImJustVlad** [comment]
So i don't think about the storage

**Comment by ImJustVlad** [comment]
Commands do not work

**Comment by OnlyNoobDied** [comment]
I cant do any thing about it.

**Comment by ImJustVlad** [comment]
Ok. I'll try to fix myself
