### ISSUE TITLE
MysteryBox glitch holograms when plugin reload

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#488]
Hi, I get this:

![image](https://user-images.githubusercontent.com/5159244/36065346-8a0bf29a-0e67-11e8-8dab-576227fc54bf.png)

Occured when I reload the plugin, normal?

Thanks

**Comment by OnlyNoobDied** [comment]
Do you modify the plugin version when you reload the plugin?

**Comment by maxlehot1234** [comment]
No :( Simply reload the plugin



lundi 12 février 2018 07:53 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Any error in console? Is these holograms still visible after you restart the server?

**Comment by maxlehot1234** [comment]
After a server restart, everything was fine. It just bad to have to restart it :P and no errors in th console/chat




lundi 12 février 2018 08:01 -0500 de notifications@github.com  <notifications@github.com>:
