### ISSUE TITLE
[Suggestion] Prevent djbooth gadget and discoball at the same time by different players at the same place

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#489]
Hi,

Is it possible to Prevent djbooth gadget and discoball at the same time by different players at the same place?

Thanks

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for new update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in 4.1.17 update.
