### ISSUE TITLE
have a problem Very inconvenient about GUI

### ISSUE THREAD

**Issue by AaronHzy** [OnlyNoobDied/GadgetsMenu#490]
When the player clicks on the purchase will always exit，need to re-open the GUI to continue buying，If buy a lot of things，need to repeat many times

**Comment by OnlyNoobDied** [comment]
This problem will be fixed in the next update.

An option will be added in config.
```
Cosmetic-Item-Purchase:
   Reopen-GUI-Menu-After-Purchase: true
```

**Comment by AaronHzy** [comment]
Great Thank you!
