### ISSUE TITLE
Can't give Mystery Boxes

### ISSUE THREAD

**Issue by SpaicyGaming** [OnlyNoobDied/GadgetsMenu#492]
I can't give Mystery Boxes to players.
I get this error: https://hastebin.com/oqigemavup.md
I'm using the latest plugin version.

**Comment by OnlyNoobDied** [comment]
sorry, can you resend the error.

**Comment by SpaicyGaming** [comment]
Sure: https://pastebin.com/qepBXurn

**Comment by OnlyNoobDied** [comment]
Do you have any item that is RARE?

**Comment by SpaicyGaming** [comment]
My fault. I translated all "Rarity" values from the files in /categories/ in Italian...

I suggest you to make error message the more clear 👍
