### ISSUE TITLE
Cosmetic Item Purchase not appearing in the inventory

### ISSUE THREAD

**Issue by SpaicyGaming** [OnlyNoobDied/GadgetsMenu#493]
When I buy a gadget it doesn't appear in my inventory.
To have the gadget I need to:
1) Open the gui, find the item I've just bought and click on it (After the click it says something like "Gadget disabled")
3) Reopen the gui, find the item I've just bought and click on it

**Comment by OnlyNoobDied** [comment]
Did you disable gadgets in config?

**Comment by SpaicyGaming** [comment]
No I didn't

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update.
