### ISSUE TITLE
Issue with gadgets stay on server after a server restart

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#497]
Hi, my server restart and gadget stay in-game and fuck :(

![image](https://user-images.githubusercontent.com/5159244/36346587-afb0193e-140e-11e8-91d3-5c8d5ad81d6d.png)

Any idea?

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update. Sorry for the inconvenience.
