### ISSUE TITLE
SOURCECODE NEEDED 

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#498]
Hi, I just want to know when you will release the source code so my dev can add more things .

Thanks again ;)

**Comment by OnlyNoobDied** [comment]
What do you want to add in GadgetsMenu?

**Comment by maxlehot1234** [comment]
NPC instead of mystery vault . Already suggest it multiple times ;)

Maybe something to allow multiple players at the same time to open their mysterybox in the same NPC

dimanche 18 février 2018 02:15 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by TheIntelloBox** [comment]
Yeah...

**Comment by OnlyNoobDied** [comment]
Can i add "open multiple boxes" option instead adding NPC feature?

BTW, "Open Multiple Boxes" feature has been added in dev version and will be release very soon.

**Comment by OnlyNoobDied** [comment]
Please check the new update."Open Multiple Boxes" has been added in the latest version.

**Comment by maxlehot1234** [comment]
@OnlyNoobDied 
Nice update BTW ;)

But NPC update could be really nice too so multiple players can righ click on the SAME NPC at the SAME TIME to open their mysterybox.

The NPC can simply trigger the same thing as mysteryvault, but PER PLAYER.

ATM, one player can righ click on mysteryvault at a time which is bad and I need to add 10 mysteryvaults...

With the NPC thing, it would be MUCH better ;) ANyone agree with me?

**Comment by TheIntelloBox** [comment]
Je suis d'accord avec toi. / I agree with you.

**Comment by OnlyNoobDied** [comment]
That idea will change the whole system.  Only GUI menu with random scrolling items animation.

**Comment by maxlehot1234** [comment]
Yes but the npc will add a completly new way to open mysterybox for everyone :)

I am 100% that a lot of people want something like this ;)

Since you doesn't give the sourcecode, my dev won't be able to create it for me :(

**Comment by OnlyNoobDied** [comment]
Sorry, source code won't be release for public.
