### ISSUE TITLE
[Issue with Llama pets] Can't rename them to Lama

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#499]
Hi, all Lama pets are name Llama. I can't change the description, category, pet name, etc, why??

Any idea for this, since it was really weird to have double " Ll"

Thanks again

**Comment by OnlyNoobDied** [comment]
Tell me how you modify the description?
Send me the files. (pets.yml)

**Comment by maxlehot1234** [comment]
@OnlyNoobDied This is the pets.yml file (normal one):
https://pastebin.com/AxzAWArW

And this is the file I want to change with "Llama" replaced by "Lama":
https://pastebin.com/Jbs9g4nf

When I reload the plugin, "Lama" was go back to "Llama" :( Why??
![image](https://user-images.githubusercontent.com/5159244/36638353-dee21d1c-19c0-11e8-80e2-35f64db9ef0b.png)

It looks weird, so if you can check this when you have time, it can be nice

Thanks again and have a nice day/night

**Comment by OnlyNoobDied** [comment]
You are not allowed to edit these things

```
  Lama: <-- You can't modify this.
    Name: '&eLama'
    Enabled: true
    Lore:
    - '&7Click here to see all pets'
    - '&7in the Lama category!'
    Types:
      Brown Lama: <-- You can't modify this.
        Name: '&5Lama: Brown'
        Mystery Dust: 60
        Rarity: Epic
        Enabled: true
        CanBeFound: true
        Purchasable: true
        Move-Speed: 0.6
        Lore:
        - '&7Type: &9Lama: Brown'
        - ''
        - '&7Click to summon this pet.'
```

**Comment by maxlehot1234** [comment]
Fine but why they are named like this "Llama" ??

dimanche 25 février 2018 04:58 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by OnlyNoobDied** [comment]
Mojang named it "Llama", not me.

**Comment by maxlehot1234** [comment]
Weird Idea to name them like this
