### ISSUE TITLE
Gadget Menu

### ISSUE THREAD

**Issue by ZeLFaDore** [OnlyNoobDied/GadgetsMenu#500]
Hi there

1- I noticed that when any player open a mysteryboxes and find any loot ( Common - Rare - Epic - Legendary ) it doesn't open it in the menu selector

2- How to give players random chest in a random time ?

3- Is there is any way to change the sound of opening mysteryboxes ?

4- I made a mysteryboxes new animation for example Test when any player tried to open any box with that animation it said ( You don't have the required permission gadgetsmenu.animations.normal

5- If a player has lag they can add multiple menu selector in their inventory
( https://imgur.com/SWKhXuK )

6- When a player send a gift to any player it shows the massage that they revised the gift but they can't open it

7- I'm trying to translate your plugin from English to my language but I can't translate this I also searched all over the fills and I didn't find it
( https://imgur.com/O2UoQbC )

If there is any way to fix them please reply me in the shortest time
Thanks :)

**Comment by OnlyNoobDied** [comment]
> 1- I noticed that when any player open a mysteryboxes and find any loot ( Common - Rare - Epic - Legendary ) it doesn't open it in the menu selector

Solution: [LINK](https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust)

> 3- Is there is any way to change the sound of opening mysteryboxes ?

You cant modify the sound. 

> 4- I made a mysteryboxes new animation for example Test when any player tried to open any box with that animation it said ( You don't have the required permission gadgetsmenu.animations.normal

How do you create a new animation? Create custom mystery boxes animations are still not allowed.

> 7- I'm trying to translate your plugin from English to my language but I can't translate this I also searched all over the fills and I didn't find it

You can find it in mainmenu.yml file which is in categories folder.

**Comment by OnlyNoobDied** [comment]
> 6- When a player send a gift to any player it shows the massage that they revised the gift but they can't open it

Can you show me in video?

**Comment by OnlyNoobDied** [comment]
These issue has been fixed in the latest update.
