### ISSUE TITLE
[Rename pets issue] When player rename pets, pets name was paste in the chat

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#502]
Hi,

I just want to report this since it was weird :P 
![image](https://user-images.githubusercontent.com/5159244/36638313-be7c8842-19bf-11e8-8f29-e6e313655c2f.png)

When players name/rename their pet, the pet name was paste in the chat too. Any way to change this?

Thanks agagin

**Comment by OnlyNoobDied** [comment]
I will change the format when renaming pet. Maybe.. use Anvil GUI to rename pet.

**Comment by maxlehot1234** [comment]
Nice ;)
dimanche 25 février 2018 06:34 -0500 de notifications@github.com  <notifications@github.com>:

**Comment by Matocolotoe** [comment]
@OnlyNoobDied For the current format you can just cancel the chat event when a player names his pet with EventPriority = HIGHEST ?

**Comment by OnlyNoobDied** [comment]
I use EventPriority.MONITOR :/

**Comment by Matocolotoe** [comment]
Shouldn't it be changeable for this specific event ? You managed to cancel some item pickup events correctly for some gadgets

**Comment by OnlyNoobDied** [comment]
I hope this issue not exist in the latest version. I will close this issue, if you still face this problem you can comment here.
