### ISSUE TITLE
IMPORTANT! Issue with armor stands

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#506]
I have a lot of bugs when player shift + click on head or other item
<img width="612" alt="zrzut ekranu 2018-02-26 o 21 51 51" src="https://user-images.githubusercontent.com/16988054/36694652-5348dc16-1b3f-11e8-8b66-ce92b49bb85a.png">

i get copied item. i can equip armor stand with this item, please fix it quickly

**Comment by OnlyNoobDied** [comment]
Is this issue only exists in Creative Mode?

**Comment by Feerko** [comment]
I'm not sure. I'm trying bug this in sv mode but it doesn't work.

**Comment by OnlyNoobDied** [comment]
This issue only occur when you're in creative mode.
