### ISSUE TITLE
[Feature] Add a way to change GUI items for gadgets, particles, pets, etc

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#507]
Hi, I just want to know if you are able to add something so we can choose the GUI item for everything?

I mean something that allow us to change items for EACH gadgets, pets, particles, cloaks and everything else 

It can be really nice in the next update of a future updates :)

Thanks again

**Comment by maxlehot1234** [comment]
Anything for this?

**Comment by OnlyNoobDied** [comment]
This features will be added in the next few updates
