### ISSUE TITLE
Permission Denied despite having permission node

### ISSUE THREAD

**Issue by Hexical1** [OnlyNoobDied/GadgetsMenu#508]
Hello, I am on MC 1.12.2, with the latest Spigot build. I have used gadgetsmenu before, but after updating it - it seems permissions broke somehow? I get the message "Permission Denied in this world" despite giving the group global permissions, world permissions, and alsu giving my certain user the permissions. I cannot figure out whats going on and I'd like this resolved soon if possible. Thank you!

**Comment by OnlyNoobDied** [comment]
You need to set the "enabled-worlds" in config.yml
