### ISSUE TITLE
Get the richt stuff form the  mysterybox in de memu

### ISSUE THREAD

**Issue by DJLukkie** [OnlyNoobDied/GadgetsMenu#509]
the player finds a Mystery Box and wants to unpack it at box he sees what he gets but this does not appear in the menu as unlocked .. how can you fix this? 
If they have permissions, they can go anywhere. and I do not want that either

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust

**Comment by DJLukkie** [comment]
Nice thas what i was looking for, but when i go to my other lobby (bungee) ist not ther but MySQL is on? how can i fix that?

**Comment by OnlyNoobDied** [comment]
GadgetsMenu doesn't sync the items you had purchased. Your permission
plugin can do it.

**Comment by DJLukkie** [comment]
Nice! thats fix! thank you for helping me out!


I have a small last question. how can I take the effect they have as a pet to another lobby with MYSQL?

**Comment by DJLukkie** [comment]
Nice! thats fix! thank you for helping me out!

I have a small last question. how can I take the effect they have as a pet to another lobby with MYSQL?

(When a player has selected a head and goes to another lobby he could have the same outfit?)

I managed to go to lobby2 from the lobby with clothes, but it does not work the other way around .. I'm stuck

**Comment by OnlyNoobDied** [comment]
you need to enable mysql in both server

**Comment by DJLukkie** [comment]
that is enabeld # This option allows you to set where
# player's data do you want to save.
# 
# Storages: 'file' or 'mysql'.
# 
# If you enable mysql, you need to setup MySQL infos.
Player-Data:
  Storage: mysql
  MySQL:
    hostname: localhost
    username: root
    database: gadgetsmenu
    port: '3306'
    password: 1234
Cosmetic-Item-Purchase:
  # Set to true allows player to purchase cosmetic items.
  Enabled: true
  # Set the storage where do you want to save mystery dust.
  # Available storages: 'file', 'mysql', 'coins-jasperjh', 'coinsapi', 'playerpoints', 'vault'.
  Mystery-Dust-Storage: mysql
  # Set to true will allows player to purchase specified cosmetic.
  Enabled-Cosmetics:
    Hats: true
    Particles: true
    Suits: true
    Gadgets: true
    Pets: true
    Morphs: true
    Banners: true
    Emotes: true
    Cloaks: true
  # This is the player's order to buy cosmetics.
  # This command depends on your permission plugin.
  Execute-Command: pex user {PLAYER} add {PERMISSION}

**Comment by OnlyNoobDied** [comment]
It might be the problem of my plugin. I will check the code.

**Comment by DJLukkie** [comment]
thankyou

**Comment by DJLukkie** [comment]
And finde something?

**Comment by DJLukkie** [comment]
^^ And finde something??

**Comment by OnlyNoobDied** [comment]
I can't find any problem on my side.

**Comment by OnlyNoobDied** [comment]
This problem seem to be fixed in the latest update. If you have a problem, please inform me.
