### ISSUE TITLE
[SOURCE CODE NEEDED] PLEASE

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#511]
Hi, since you will not update the plugin for the next year at least, are youa ble to release the source code, so I can ask my dev to add more things and fix issues I have??

It could be really nice or find someone that can update the plugin during 2018 PLEASE :)

A lot of dev can handle it temporaly, I am 100% sure of it.

With the actual plugin/code, my dev can't do anything since he doesn't have the source code....

Thanks again.

**Comment by RoboMWM** [comment]
And probably fix and improve things like, oh you know, not having to rely on permissions when it has its own data folder anyways...

**Comment by OnlyNoobDied** [comment]
Sorry, source code of GadgetsMenu will not be release.
