### ISSUE TITLE
Bungee/proxy

### ISSUE THREAD

**Issue by orlicmc** [OnlyNoobDied/GadgetsMenu#512]
can you please make a update for bungee so we can use playtime all over the server. i realy would apreachate it.

**Comment by OnlyNoobDied** [comment]
I will link playtime to MySQL, so you just need to enable MySQL. Player's playtime will be saved in MySQL.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

**Comment by OnlyNoobDied** [comment]
This feature has been added in the premium version.
