### ISSUE TITLE
which is the permision to open mysteryboxes with right click

### ISSUE THREAD

**Issue by andygamerr** [OnlyNoobDied/GadgetsMenu#516]
which is the permision to open mysteryboxes with right click

**Comment by OnlyNoobDied** [comment]
[LINK](https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Permissions#mystery-boxes-gadgetsmenumysteryboxesopen-top)

[LINK](https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Permissions#mystery-boxes-gadgetsmenumysteryboxesopen-top)

**Comment by andygamerr** [comment]
??

**Comment by andygamerr** [comment]
I can only open boxes with the left click

**Comment by andygamerr** [comment]
I can only open boxes with the left click

**Comment by OnlyNoobDied** [comment]
Oh, change your "spawn-protection" to '0' in properties file.

**Comment by andygamerr** [comment]
where they find properties file ??

**Comment by andygamerr** [comment]
28/5000
ohh I found, thank you very much
