### ISSUE TITLE
Morphs world change issue

### ISSUE THREAD

**Issue by Feerko** [OnlyNoobDied/GadgetsMenu#519]
Hello, i'm using your API and there is an issue with morphs and world change.

```
on world change:
    if blablabla:
       if {_api}.getSelectedMorph() is set:
           {GadgetsMenuAPI}.getPlayerManager(player).unequipMorph()
```

and this doesn't work, i need to wait ~2 second to work.
for other cosmetics works normally without wait.

**Comment by OnlyNoobDied** [comment]
Sometimes it will delay to execute the command to prevent lag.
