### ISSUE TITLE
Op has all gadgets?

### ISSUE THREAD

**Issue by EyeFone** [OnlyNoobDied/GadgetsMenu#52]
I'm currently an admin on a server using your plugin, but i don't want to have all gadgets
i play like any other user so i want to collect the gadgets by myself, so is there a way to not have everything as an admin/op?

**Comment by PaulTDD-MC** [comment]
give yourself the permission -gadgetsmenu.cosmetics.*

**Comment by EyeFone** [comment]
thank you! :D

**Comment by EyeFone** [comment]
now when i open a mystery box the item appears as not unlocked. :\

**Comment by PaulTDD-MC** [comment]
Did you get the permission?

**Comment by EyeFone** [comment]
yes

**Comment by EyeFone** [comment]
i added - -gadgetsmenu.cosmetics.* to my permissions
but now i dont get the items from the mysteryboxes

**Comment by PaulTDD-MC** [comment]
hmm... It should work. Let me think.

**Comment by EyeFone** [comment]
ok i got it working by editing the permissions file and moving the - -gadgetsmenu.cosmetics.* to the bottom

**Comment by EyeFone** [comment]
Thanks again for the help! :D

**Comment by PaulTDD-MC** [comment]
Good

**Comment by PaulTDD-MC** [comment]
Np
