### ISSUE TITLE
Error with "Execute-Command"

### ISSUE THREAD

**Issue by LoYungSum** [OnlyNoobDied/GadgetsMenu#523]
Here is part of my config: https://hastebin.com/olokupofug.vbs

And here is my list of plugins installed
![image](https://user-images.githubusercontent.com/25066078/38139697-2a1f0e90-3463-11e8-89fe-d120b1eabc56.png)

Although I already have luckperms installed, why when the console type the command and it returns null?

**Comment by OnlyNoobDied** [comment]
When you purchase item occur this problem?

**Comment by LoYungSum** [comment]
Yes

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust

You need to change the commands in configs and "mystery boxes.yml"
