### ISSUE TITLE
LuckPerms

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#525]
Hey,

I have added this in the config to give the permission : lp user {PLAYER} permission set {PERMISSION}

But the plugin says "no permission" when the player open the mysterybox and they don't have the permission to equip what they won : it's locked.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust

You need to change the command in "mystery boxes.yml" file too.

**Comment by OnlyNoobDied** [comment]
Please reply me if this problem has been fixed.

**Comment by TheIntelloBox** [comment]
Fixed. :D

**Comment by OnlyNoobDied** [comment]
such a long day :P
