### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Vennntox** [OnlyNoobDied/GadgetsMenu#526]
Can you pls fix this

00:13:35 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:35 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:35 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:35 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:35 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:35 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
00:13:35 Caused by: java.util.zip.ZipException: error in opening zip file
00:13:35 	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_162]
00:13:35 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_162]
00:13:35 	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_162]
00:13:36 	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_162]
00:13:36 	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_162]
00:13:36 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
00:13:36 	... 5 more

**Comment by OnlyNoobDied** [comment]
Does this error occur after you reinstall GadgetsMenu?

**Comment by Vennntox** [comment]
yes its works thanks after 10 reinstall

2018-04-05 12:58 GMT+02:00 Yap Zhen Yie <notifications@github.com>:
