### ISSUE TITLE
Players can get the head from a suit

### ISSUE THREAD

**Issue by YellowZaki** [OnlyNoobDied/GadgetsMenu#529]
If you click a skull on your inventory and you drag it and drop it on the suit head, the suit head goes to your inventoy.

**Comment by OnlyNoobDied** [comment]
This only happen in Creative mode and i cant do anything with it.

**Comment by OnlyNoobDied** [comment]
However, i added lots of solution to prevent player to use the item for other usage.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
