### ISSUE TITLE
textures.minecraft.net doesn't work

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#533]
Hey ! :D

textures.minecraft.net doesn't work. How could I add my hats ? :D 

Thanks ! :D

**Comment by TheIntelloBox** [comment]
?

**Comment by OnlyNoobDied** [comment]
I already knew this problem and i 

There're lots of methods that you can get player's skin texture but it's a bit complicated.

1. https://api.mojang.com/users/profiles/minecraft/<username>
   Copy "id".
2. https://sessionserver.mojang.com/session/minecraft/profile/<uuid>
   Paste the "id".
3. You will see a long string starts with "value". This is your skin texture.
    Copy that string and paste it in https://www.base64decode.org/
4. Finally you can get your skin url

**Comment by OnlyNoobDied** [comment]
@TheIntelloBox 
Install this app in your computer. You may get the texture using this app.
