### ISSUE TITLE
Mystery Box Animation Permission Bug

### ISSUE THREAD

**Issue by ShawnPR1** [OnlyNoobDied/GadgetsMenu#535]
Hi there.

I don't want new players to be able to use the normal animation, so I didn't give them that permission.
The plugin, however, sets the normal animation as the default animation for opening up mystery boxes. So everytime a new player joins and tries to open a mystery box, they get a message saying they don't have permission (gadgetsmenu.animations.normal).

As I said I don't want new players to be able to use this animation at all, but can't change which one is selected by default. Please add some form of "DefaultAnimation" setting in the config.

This is truly the best cosmetic plugin out there, but for now this bug is quite annoying

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update. New system will choose one of the animation which player has the permission to access.
