### ISSUE TITLE
Parachute doesn't push the player up to the sky

### ISSUE THREAD

**Issue by shoker537** [OnlyNoobDied/GadgetsMenu#537]
When a player (or admin) uses Parachute, it doesn't push the player up to the sky, only less than a simple player jump.
No matter is there a grass or the block is clean.

**Comment by OnlyNoobDied** [comment]
I think this issue caused by 3rd plugin like (AntiAura)

**Comment by OnlyNoobDied** [comment]
Can't be fix.
