### ISSUE TITLE
Impossible to add parameter to mysql url.

### ISSUE THREAD

**Issue by SmilingTrickster** [OnlyNoobDied/GadgetsMenu#538]
In order to use non-ASCII characters (personally Chinese, in this case) with MariaDB (or mysql) database support, a certain parameter is required in the URL when the plugin connects to the mysql database. 
An example would be like: (this is the configuration of PermissionsEx)
`      uri: mysql://127.0.0.1:3306/DATABASE?characterEncoding=utf-8`
However, it doesn't look like GadgetsMenu supports this. I tried to sneak around by adding the parameter after the port like this:

> 
  MySQL:
    hostname: 127.0.0.1
    username: root
    database: DATABASE?characterEncoding=utf-8
    port: '3306'
    password: ******

But 
`java.sql.SQLException: Unsupported character encoding 'utf-8?serverTimezone=EST5EDT'.`
It looks like the code itself adds an extra serverTimezone parameter, so there's no way I can sneak around this.
It would help a lot if this parameter is removed (since I don't see there's any time-related column in the database), or a character encoding option is added.

**Comment by OnlyNoobDied** [comment]
Okay.
