### ISSUE TITLE
Console spam like a debug thing [Need a fix ASAP]

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#541]
Hi I just realized that when players doesn't have enought mystery dust to craft a cosmetics, I get this spam in the console:
![image](https://user-images.githubusercontent.com/5159244/39385085-0efaeb58-4a3d-11e8-8f01-fddcc5ad7848.png)
3 "8" each time a player click on something inside Hats category. It paste "8" even if the price was more than 8 or less than 8.

Any idea for this?

Thanks again if you can realease a quick fix for this

**Comment by OnlyNoobDied** [comment]
https://www.dropbox.com/s/xsiydzxcx6y71nb/GadgetsMenu.jar?dl=0

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Thank you :)
