### ISSUE TITLE
Permission for Superbvote

### ISSUE THREAD

**Issue by SupaMom** [OnlyNoobDied/GadgetsMenu#542]
Since downloading and installing this plugin my players have had so much fun with it, and they love collecting the items, or the dust to eventually craft there own.  But there in lies my question.

I would like to add this feature as a reward inside my Superbvote, so atm they get rewarded (if they choose to vote for my server) IGmoney, but I would love to put the mystery boxes and the dust in as a reward, at the moment I can use the permission IG to give an individual player these items as gifts, but could you tell me (if there is one) the command to run inside my Superbvote config so that a player that votes on a link get's a box/dust. 

Thankyou
SupaMom

**Comment by OnlyNoobDied** [comment]
You may use the in-game commands.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Commands#mystery-boxes-commands
