### ISSUE TITLE
Give mystery box to offline players

### ISSUE THREAD

**Issue by UnioDex** [OnlyNoobDied/GadgetsMenu#546]
I'm using this command: gmysterybox give UnioDex 1 1 ex=false
from console but it says: Player not found.

Can you solve that?

**Comment by OnlyNoobDied** [comment]
If that player had join the server at least one time, you should be able to give mystery box even he's offline.

**Comment by UnioDex** [comment]
Yes, but after restart i can't. I wan't to give mystery boxes also offline players. I give it as a donator reward and players can be in another server.

Actually i solved this problem with API. With GadgetsMenu API you can give items to offline players.

**Comment by OnlyNoobDied** [comment]
use OfflineGadgetMenuPlayer class?

**Comment by UnioDex** [comment]
`MysteryBoxesManager.giveMysteryBoxes(Bukkit.getOfflinePlayer(playerName]), MysteryBoxType.NORMAL_MYSTERY_BOX_5, false, null, null);`

**Comment by OnlyNoobDied** [comment]
acceptable.
