### ISSUE TITLE
JSON Message bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#548]
Hey ! :D 

If I open a box and if I win the RARE Donkey, the message in JSON says "Invalid Item". :D 

Could you fix it ? :D 
Thanks ! :D 
TheIntelloBox. :D

**Comment by OnlyNoobDied** [comment]
what's your server version?

**Comment by OnlyNoobDied** [comment]
Can you screenshot for me.

**Comment by TheIntelloBox** [comment]
Hi again ! :D 

Here is my screenshot: http://www.noelshack.com/2018-24-6-1529168035-json-bug-gadgetsmenu-17-minimum-et-18-super.jpg ! :D 

Thanks ! :D

**Comment by maxlehot1234** [comment]
@OnlyNoobDied Same error for me:

![image](https://user-images.githubusercontent.com/5159244/41504157-da4c3cfa-71b4-11e8-8f88-5ad1c731a5b3.png)
Spigot 1.12.2 #1638 (latest one)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
