### ISSUE TITLE
/mysteryboxes mode remove-vault near {number}

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#55]
Hello !

To remove the mystery boxes we must go in the config.yml or do the command : /mysteryboxes mode remove-vault. But we must stand on the exact position of the hologram.

So could you add /mysteryboxes mode remove-vault near {number}
Number is the number of blocks around you to remove the mystery boxes.

Thanks ! :D

**Comment by OnlyNoobDied** [comment]
you means radius?

**Comment by TheIntelloBox** [comment]
Yeah ! :D

**Comment by OnlyNoobDied** [comment]
added
