### ISSUE TITLE
morph bug

### ISSUE THREAD

**Issue by Yukyxy** [OnlyNoobDied/GadgetsMenu#550]
Hello
When I put a morph, and I press a key to move me the character moves alone even if I do not touch my keyboard.
https://youtu.be/CMdMCaeBxxI

**Comment by OnlyNoobDied** [comment]
What's your server version?

**Comment by Yukyxy** [comment]
1.12.2

**Comment by OnlyNoobDied** [comment]
This might be Lib's Disguise issue. I can't help you with that.
