### ISSUE TITLE
HUGE BUG

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#551]
When i reload the  plugin, plugin crashed and mysterybox stop working.

Latest version reset mysterydust of EVERY PLAYERS. Was supposed to clear mysterybox only...........

What's happen??

**Comment by maxlehot1234** [comment]
Need to stop the server instead of reload the config files to prevent issues...

**Comment by OnlyNoobDied** [comment]
Send the server logs to me please.

**Comment by maxlehot1234** [comment]
I never received any console error.

I have latest version of Spigot 1.12.2 (#1638)

Directly when I do: ./gadgetsmenu reload, mysteryvaults stop working and Gui stop working too

**Comment by OnlyNoobDied** [comment]
I'm not recommended you to use the reload command as it's not stable. I removed this command last time as it's not stable but everyone wanted me to re-add this command even i said the same word. So, i can't do anything with it if you get errors when you use the reload command.

**Comment by OnlyNoobDied** [comment]
Wait, did you reload the plugin when the new version automatically installed?

**Comment by OnlyNoobDied** [comment]
sorry for the inconvenience. As I said the reload command isn't stable, so I can't do anything with it.

**Comment by TheIntelloBox** [comment]
Every plugin has a stable reload command... :D.

**Comment by OnlyNoobDied** [comment]
Every plugin only reload the configurations. GadgetsMenu reload command is "restart the whole plugin"

**Comment by OnlyNoobDied** [comment]
This issue has been fixed in the latest update which release just now. I changed the way of getting player's mystery boxes data.
