### ISSUE TITLE
Huge bug #2 (Can't load mysterybox)

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#552]
I try to give myself mysterybox, but in the gui, he told this:
![image](https://user-images.githubusercontent.com/5159244/41501169-e7faf596-716c-11e8-9c9b-4e3c661ebd1d.png)

Any reason for this? Noone can get mysterybox in latest versio  (4.1.19)

**Comment by OnlyNoobDied** [comment]
Any error in console?

**Comment by maxlehot1234** [comment]
No nothing. Simply take at least 2 minutes to give it to me...

Never have this thing in 4.1.17 and before :(

**Comment by OnlyNoobDied** [comment]
Can you send your mystery boxes data to me.

**Comment by maxlehot1234** [comment]
Yeah I can, but will change nothing I think.

Try to give yourself 200 mysterybox 5 and right click a mysteryvault to see the bug in action ;)

**Comment by OnlyNoobDied** [comment]
I tried to give myself 500 mystery boxes, and nothing happen. :/

**Comment by maxlehot1234** [comment]
It works now. Maybe an issue at this tiem. Sorry for this. I close this

**Comment by OnlyNoobDied** [comment]
okay.
