### ISSUE TITLE
Open Source is needed.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#553]
Hey ! :D 

I know that you don't want to open-source the plugin. :D 
However, if you open source the plugin, there will be more content for all players, so more downloads. :D 
(And maybe more donations ! :D).

Thanks ! :D 
TheIntelloBox. :D

**Comment by OnlyNoobDied** [comment]
Sorry, no.

**Comment by TheIntelloBox** [comment]
Give us just a reason please. :D

**Comment by OnlyNoobDied** [comment]
Sorry, source code won't be available for everyone.
