### ISSUE TITLE
Boots of the suit "Necromancer" can be duplicated.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#555]
Hey ! :D 

My players and I are able to duplicate the Necromancer boots by taking them very fast in the inventory. :D 

Thanks for fixing it ! :D 
TheIntelloBox. :D

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
Actually, every cosmetic items can be duplicated in Creative Mode, not only "Necromancer" suit.

**Comment by TheIntelloBox** [comment]
Hi OnlyNoobDied ! :D Yes you're right ! :D Thanks for fixing it ! :D

**Comment by OnlyNoobDied** [comment]
I knew this bug seens version 3+

**Comment by OnlyNoobDied** [comment]
Sorry, I cant find a way to fix this issue while you're in creative mode.

**Comment by TheIntelloBox** [comment]
Maybe if the player wears an item from CreativeMode, the item disappears ? :D

**Comment by OnlyNoobDied** [comment]
Most of the time, only admin able to to access Creative Mode.

**Comment by TheIntelloBox** [comment]
Nop. False. If a server has a freebuild, everyplayer can have the creative mode. :D

**Comment by OnlyNoobDied** [comment]
Finally found a way to solve this problem. :D

**Comment by TheIntelloBox** [comment]
Fantastic ! :D Thanks a lot ! :D Have a nice morning or a nice day or a nice evening or a nice night OnlyNoobDied ! :D

**Comment by OnlyNoobDied** [comment]
However, there's a small problem. You're unable to move the selector if
"Able-To-Move" enabled in config.

**Comment by OnlyNoobDied** [comment]
can I have your server ip?

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
