### ISSUE TITLE
Big lag issues on quit event

### ISSUE THREAD

**Issue by SaF3rC** [OnlyNoobDied/GadgetsMenu#557]
Hi! My server is having problems with GadgetsMenu. It's producing lag issues on quit event.
Timings: http://prntscr.com/jzuzhh
I'm using PaperSpigot 1.8.8 and MySQL database.

**Comment by OnlyNoobDied** [comment]
Add an option to reduce server lag on quit event in the next update.
Simply disable sync player cosmetics.
```
# Sync player's selected cosmetics when they join the server.
# Set to 'false' to reduce server lag.
Sync-Cosmetics-On-Join: false
```

**Comment by OnlyNoobDied** [comment]
Please check new update.
