### ISSUE TITLE
Morph

### ISSUE THREAD

**Issue by PontusIsBest** [OnlyNoobDied/GadgetsMenu#559]
Hello! When I Morph I'm In The Morph! I Have Photos:

![2018-07-01_12 44 52](https://user-images.githubusercontent.com/40734370/42133614-6e0fe9ae-7d2d-11e8-9d68-24d9806b94a1.png)
![2018-07-01_12 44 47](https://user-images.githubusercontent.com/40734370/42133615-6e288d92-7d2d-11e8-98d7-5bb425862eef.png)

**Comment by OnlyNoobDied** [comment]
I can't do anything with it. Lib's Disguise doesn't provide any API to modify mob location.

**Comment by PontusIsBest** [comment]
Can I Change This? In Like Config.yml?

**Comment by OnlyNoobDied** [comment]
This cannot be modified in config.
