### ISSUE TITLE
Players can open boxes at the same time

### ISSUE THREAD

**Issue by heddib** [OnlyNoobDied/GadgetsMenu#560]
**Description:**
When two or more players have the mystery box confirmation inventory opened at the same time and they press open at the same time, a message in the chat saying that only one box can be opened at the same time appears but both of players get the rewards.

**Steps to reproduce:**
A player open a box while another one is opening a box.

**Server information:**
Server version: Spigot 1.8.8
Plugin version: GadgetsMenu 4.1.21

**Comment by OnlyNoobDied** [comment]
I will check it after my school test.

**Comment by heddib** [comment]
Good luck with your exams and thanks for maintaining the plugin.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by heddib** [comment]
I reopen this issue because it was half-solved, i guess we shouldn't be able to have the confirmation gui opened if a player is already opening a box.
We can't open a box with the confirmation button but it's better to not see the confirmation gui in my opinion.

**Comment by OnlyNoobDied** [comment]
It's a mistake. I will fix this issue in the next update.
