### ISSUE TITLE
Cosmetics reset issue

### ISSUE THREAD

**Issue by heddib** [OnlyNoobDied/GadgetsMenu#565]
**Description:**
When you reset your cosmetics and then you change the world you are / or you disconnect and reconnect, your cosmetics will be enabled.

**Information:**
Server version: Spigot 1.8.8
Plugin version: 4.1.21

**Comment by OnlyNoobDied** [comment]
Can you make a video to reproduce the problems? I cant find any problems in the code.

**Comment by heddib** [comment]
It seems to be fixed with the last update,
