### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by tylerhasman** [OnlyNoobDied/GadgetsMenu#568]
The MySQL code still has memory leaks. Please make sure you are properly closing everything as my server is crashing. I've used profiling software and it is indeed GadgetMenu not closing its MySQL properly.

**Comment by OnlyNoobDied** [comment]
MySQL Memory leaking issue has been fixed in the latest update. Are you using the latest version of GadgetsMenu?

**Comment by tylerhasman** [comment]
Are you talking about 4.1.22?

**Comment by Matocolotoe** [comment]
4.1.22 is the latest version

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
