### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#570]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

**Comment by OnlyNoobDied** [comment]
1.13 is a big update for GadgetsMenu. A lot of things need to modify, so 1.13 support will be delay. I'm sorry.

**Comment by TheIntelloBox** [comment]
You should start working on 1.13 by replacing the old materials by the new.

**Comment by OnlyNoobDied** [comment]
It's a complicated project. After my school assessments I will start develop 1.13 support. Configurations gonna be reset.

**Comment by TheIntelloBox** [comment]
1.13 builds are ready: https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/

**Comment by TheIntelloBox** [comment]
Did you work on it ?

**Comment by Yukyxy** [comment]
please i need the version 1.13
