### ISSUE TITLE
Execute-Command - Does not work on v4.1.22

### ISSUE THREAD

**Issue by iAnimeartz** [OnlyNoobDied/GadgetsMenu#571]
I use Luckperms.
Execute-Command does not work on v4.1.22
Please fix this. (Sorry i'm not good at english)

https://www.photobox.co.uk/my/photo/full?photo_id=500906053462
https://www.photobox.co.uk/my/photo/full?photo_id=500906053137
https://www.photobox.co.uk/my/photo/full?photo_id=500906052768

Server information:
Server version: Spigot 1.8.8
Plugin version: GadgetsMenu v4.1.22

**Comment by OnlyNoobDied** [comment]
The link is not working for me. It's not the direct link.

**Comment by iAnimeartz** [comment]
https://cdn.discordapp.com/attachments/470255122031837184/470255139471622154/614579784249c1e2315a31bf2181ca19b9d17ca76258d74a007a6e3df023be11d706b6d3.png

https://cdn.discordapp.com/attachments/470255122031837184/470255175622328332/80079892b43c9bb6c3f33c26442c39e3654762fd9562959453378e7e02e213ab3c6dc57f.png

https://cdn.discordapp.com/attachments/470255122031837184/470255193301319681/097336474e853abd1295e7150a44bc1a38dd9900d3b97f98854688d81c693156c448ad74.png

**Comment by iAnimeartz** [comment]
Try the link again.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust


You need to change the command in "mystery boxes.yml" too.
