### ISSUE TITLE
Plugin Question

### ISSUE THREAD

**Issue by haer0248** [OnlyNoobDied/GadgetsMenu#574]
When I enable this plugin, console will be show ...
[Server]java.lang.reflect.InvocationTargetException
[Server]at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Server]at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[Server]at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[Server]at java.lang.reflect.Constructor.newInstance(Unknown Source)
[Server]at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetType.equip(GadgetType.java:710)
[Server]at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.GadgetManager.equipGadget(GadgetManager.java:45)
[Server]at com.yapzhenyie.GadgetsMenu.menu.menus.GadgetTypesMenu.onInvClickGadgets(GadgetTypesMenu.java:263)
[Server]at sun.reflect.GeneratedMethodAccessor1201.invoke(Unknown Source)
[Server]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[Server]at java.lang.reflect.Method.invoke(Unknown Source)
[Server]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[Server]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[Server]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[Server]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[Server]at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[Server]at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[Server]at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[Server]at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[Server]at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[Server]at java.util.concurrent.FutureTask.run(Unknown Source)
[Server]at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[Server]at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[Server]at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[Server]at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[Server]at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[Server]at java.lang.Thread.run(Unknown Source)
[Server]Caused by: java.lang.IllegalAccessError: com/yapzhenyie/GadgetsMenu/cosmetics/gadgets/types/Gadget$1
[Server]at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.Gadget.
(Gadget.hava:52)
[Server]at com.yapzhenyie.GadgetsMenu.cosmetics.gadgets.types.GadgetPartyPopper.
(GadgetPartyPopper.java:29)
[Server]... 26 more

It's my server problem or plugin conflict?
Sorry, my English very poor.

**Comment by OnlyNoobDied** [comment]
Please reinstall the plugin. The plugin you installed had broken.
