### ISSUE TITLE
PlayerDeathEvent lag

### ISSUE THREAD

**Issue by SaF3rC** [OnlyNoobDied/GadgetsMenu#575]
Hi!! My server is having lag issues caused probably by the GadgetsMenu's PlayerDeathEvent. How can I fix that??
Timings line: http://prntscr.com/kc2qj4

**Comment by Matocolotoe** [comment]
What's your version of GadgetsMenu ?

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
