### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by jiangdashao** [OnlyNoobDied/GadgetsMenu#576]
When a player joining server,server crashed
![image](https://user-images.githubusercontent.com/21152113/43376580-15441656-93ee-11e8-8c1b-d19b1c9770dc.png)

**Comment by Matocolotoe** [comment]
What's the version of your server and the version of GadgetsMenu you were using when this happened ?

**Comment by OnlyNoobDied** [comment]
All of the MySQL issue should be fixed in the latest update. Please install the latest version. [LINK](https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-13.10885)
