### ISSUE TITLE
BungeeCord Support

### ISSUE THREAD

**Issue by Ganper** [OnlyNoobDied/GadgetsMenu#577]
Hi, does it support your BungeeCord plugin?

Please support Bungee.

**Comment by Feerko** [comment]
Just use mysql.

**Comment by OnlyNoobDied** [comment]
Cosmetics unable to sync between servers using BungeeCord.

**Comment by LuckySe7en03** [comment]
@OnlyNoobDied If I connect the plugins to the same MySQL database, can i connect cosmetics throught my servers? (Sorry for my english)

**Comment by OnlyNoobDied** [comment]
> @OnlyNoobDied If I connect the plugins to the same MySQL database, can i connect cosmetics throught my servers? (Sorry for my english)

Of course you can. Just connect to MySQL database server and all the data will be sync between the servers.
