### ISSUE TITLE
Morphs issue

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#578]
When a player enables a morph and gets kicked, when he reconnects, every action (like right clicking with an item to open a GUI) doesn't work

Minecraft version : 1.8.8
I think this is an issue coming from LibsDisguises but the developer won't accept "issues from an ""outdated version"""

**Comment by OnlyNoobDied** [comment]
Did you downloaded the correct version depends on your server version.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Morphs

**Comment by Matocolotoe** [comment]
Yes, I tested every 1.8 version of LibsDisguises and the one you have uploaded on the GadgetsMenu wiki.
Issue still appears.

**Comment by Matocolotoe** [comment]
Seems to be a LibsDisguises issue because morphs work perfectly in 1.9 and more.

But the author of this plugin won't fix 1.8 issues (even if it's just a small error) because he thinks legacy versions are "outdated" and 1.8 servers are just a "minority" among multiplayer servers nowadays... which is pretty stupid in my mind

**Comment by OnlyNoobDied** [comment]
Sorry, I can't do nothing as LibsDisguises is the only one who can disguise mob and you're able to see your own morph.
