### ISSUE TITLE
Per world messages

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#579]
I suggest you to add a configurable option to define the worlds where the mystery boxes messages are sent.

**Comment by OnlyNoobDied** [comment]
Can you tell me more details.Which messages?

**Comment by Matocolotoe** [comment]
For instance:
- {PLAYER} is opening a Mystery Box !
- {PLAYER} found {LOOT} (Legendary)
- {PLAYER} found a 5-star Mystery Box

**Comment by OnlyNoobDied** [comment]
You wants the message only send to the players who in the same world?

**Comment by Matocolotoe** [comment]
My original suggestion was to send this messages to the players who are in the valid worlds (config.yml, line 89, Enabled-Worlds)

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
