### ISSUE TITLE
Pocket Beach Gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#580]
When activating the pocket beach gadget, you are glitched in the stairs, you don't "ride" them

**Comment by OnlyNoobDied** [comment]
What's your server version?

**Comment by Matocolotoe** [comment]
Spigot 1.8.8

**Comment by OnlyNoobDied** [comment]
Duplicate of #566

**Comment by OnlyNoobDied** [comment]
This issue might caused by 1.8.8 server version. I'm unable to solve this problem.

**Comment by Matocolotoe** [comment]
The gadget worked before :/

**Comment by Matocolotoe** [comment]
See #566
