### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tylerhasman** [OnlyNoobDied/GadgetsMenu#581]
This plugin still has memory leaks. I've decided to remove it from my large network permanently until you properly fix it.

**Comment by Feerko** [comment]
same

**Comment by tylerhasman** [comment]
That setting doesnt exit in the config file

**Comment by Feerko** [comment]
same x2 😂

**Comment by OnlyNoobDied** [comment]
What's your GadgetsMenu version?

**Comment by tylerhasman** [comment]
I updated to the newest, no change

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
