### ISSUE TITLE
A lot of active sheduler

### ISSUE THREAD

**Issue by neanonymousdev** [OnlyNoobDied/GadgetsMenu#582]
VIDEO:
[url](https://github.com/OnlyNoobDied/GadgetsMenu/files/2270061/neanonymous-video-2018-08-08.14-26-16.zip)

pay attention to the number of shedulers (Активные шедулеры)

**Comment by DaNseRYT** [comment]
![image](https://user-images.githubusercontent.com/33249522/43835667-6bce947c-9b1b-11e8-9356-19cb45a52bb7.png)
Perhaps this is worth to do asynchronously?

**Comment by DaNseRYT** [comment]
Fix the shedulers?

**Comment by OnlyNoobDied** [comment]
Code optimized in the latest update(4.4.0). This issue should be fixed in 4.4.0 version.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
