### ISSUE TITLE
Messages no loading

### ISSUE THREAD

**Issue by vinc05** [OnlyNoobDied/GadgetsMenu#583]
> [14:21:19 INFO]: [GadgetsMenu] ------------------------------------------------------
> [14:21:19 INFO]: [GadgetsMenu] GadgetsMenu 4.1.22 is loading... [server: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)]
> [14:21:19 INFO]: [GadgetsMenu] Plugin by Yap Zhen Yie.
> [14:21:19 INFO]: [GadgetsMenu] Date Modified: 9-07-2018
> [14:21:19 INFO]: [GadgetsMenu]
> [14:21:19 INFO]: [GadgetsMenu] Initializing module v1_8_R3
> [14:21:19 INFO]: [GadgetsMenu] ------------------------------------------------------
> [14:21:21 INFO]: [GadgetsMenu] [Placeholder] PlaceholderAPI hooked.

i use 1.8.8 spigot and have set custom messages.yml 
in game no work custom message ?!

https://pastebin.com/GJtycjwZ

i have changed: craft to buy, Mystery dust to token ...

**Comment by OnlyNoobDied** [comment]
Did you restart the server?

**Comment by vinc05** [comment]
Yes

**Comment by vinc05** [comment]
Ok, error was when i replace craft, go conflict with gui string u-u
