### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#589]
The lore of the banners appear in the item in the inventory of the player when enabled
I guess it's a mistake (same thing that for gadgets)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by Matocolotoe** [comment]
@OnlyNoobDied this issue still happens with the custom banners

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
