### ISSUE TITLE
Cosmetics reset issue

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#590]
- If the Sync-Cosmetics-On-Join option is true, resetting cosmetics does not actually reset them when you reconnect or join a valid world
- If it is false, when you join a valid world or reconnect, they are removed

**Comment by OnlyNoobDied** [comment]
When `Sync-Cosmetics-On-Join: true` which means sync player's cosmetics when they reconnect to the server. 
When `Sync-Cosmetics-On-Join: false` which means player's cosmetics will not be sync when they reconnect the server.

**Comment by Matocolotoe** [comment]
Yes but why does resetting them does not work while syncing them ?

**Comment by OnlyNoobDied** [comment]
What do you mean does not work?

**Comment by Matocolotoe** [comment]
After testing many things : when you go in a world where cosmetics are disabled, and then you come back in a world where cosmetics are enabled, they are reset, no matter how the Sync-Cosmetics-On-Join option is set

**Comment by Matocolotoe** [comment]
Seems to be fixed in the newest version
