### ISSUE TITLE
Can't /gmb giveall with chance different crate quality

### ISSUE THREAD

**Issue by Ex-Infinityy** [OnlyNoobDied/GadgetsMenu#596]
why i cant execute giveall command with random chance quality???
everytime i executed the command it only throws error:

23.09 15:24:46 [Server] INFO Echlipse issued server command: /gmb giveall 5 c:(1:40,2:30,3:25,4:15,5:10)
23.09 15:24:46 [Server] ERROR null
23.09 15:24:46 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'gmb' in plugin GadgetsMenu v4.1.22
23.09 15:24:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
23.09 15:24:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
23.09 15:24:46 [Server] INFO Caused by: java.lang.NullPointerException
23.09 15:24:46 [Server] INFO at com.yapzhenyie.GadgetsMenu.commands.mysteryboxes.subcommand.CommandGiveAll.onCommand(CommandGiveAll.java:165) ~[?:?]
23.09 15:24:46 [Server] INFO at com.yapzhenyie.GadgetsMenu.commands.mysteryboxes.subcommand.CommandGiveAll.onCommandPlayer(CommandGiveAll.java:28) ~[?:?]
23.09 15:24:46 [Server] INFO at com.yapzhenyie.GadgetsMenu.commands.mysteryboxes.CommandManager.onCommand(CommandManager.java:152) ~[?:?]
23.09 15:24:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
23.09 15:24:46 [Server] INFO ... 15 more

any suggestion??? or am doing wrong?
sorry for my english

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
