### ISSUE TITLE
Not working  Able-to-move option

### ISSUE THREAD

**Issue by iLefty** [OnlyNoobDied/GadgetsMenu#597]
If I set at config ``Able-To-Move: true``, players still can not move menu selector to another slot.

**Comment by OnlyNoobDied** [comment]
I tested, it works. Can you show me with a video?

**Comment by iLefty** [comment]
https://youtu.be/WQKfxcEm3Hk

**Comment by OnlyNoobDied** [comment]
Do you have any other plugin that lock slot items?

**Comment by iLefty** [comment]
No. I can giv you plugins list.
```
Plugins (40): AAC, AntiAura, BlockVersion, ChatGames, ChestCommands, Citizens, ClearLag, Coins, CombatTagPlus, CoreProtect, DeluxeMenus, Essentials, EssentialsChat, EssentialsSpawn, GadgetsMenu, GameModeHop, GeneralLib, HolographicDisplays, Kingdoms, KoTH, LuckPerms, mcMMO, MobHunting, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolSupport, RandomTP, Scavenger, Sentinel, SkinsRestorer, TitleAPI, TitleManager, TradeMe, TrueCommand, Vault, WGExtender, WorldBorder, WorldEdit, WorldGuard
```

**Comment by OnlyNoobDied** [comment]
Is there any other plugin give player item on join?

**Comment by iLefty** [comment]
Only essentials, which give items on first join.

**Comment by OnlyNoobDied** [comment]
can I have your config.yml

**Comment by OnlyNoobDied** [comment]
I found the problem. version 1.12 or higher are not able to move the item.

**Comment by OnlyNoobDied** [comment]
New update will be release after my exam over.

**Comment by iLefty** [comment]
When it will be?

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
