### ISSUE TITLE
DJ Gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#599]
The DJ Booth Gadget tells you to be on the ground even if you are on the ground

**Comment by OnlyNoobDied** [comment]
You mean this message "You must be on the flat ground to use this!"?

**Comment by Matocolotoe** [comment]
Exactly

**Comment by OnlyNoobDied** [comment]
Actually, this message inform you need to have some space around the player. You need to make sure that your surrounding do not have any grass/flowers and need to be flat. 

If there's any misunderstanding by the message, please correct me.

**Comment by Matocolotoe** [comment]
Thanks for responding, I understand now !
