### ISSUE TITLE
Morphs issue

### ISSUE THREAD

**Issue by Mineleague** [OnlyNoobDied/GadgetsMenu#6]
Hi there OnlyNoobDied,
Sorry to bother you, but I am having an issue with the morphing part of the plugin. I had to remove it from my GUI because it would not work. The problem is that when I try to click on a morph in the GUI, it gives me the item, E.g. a bone for skeleton morph, and I can stick it in my inventory. I don't even have a morph, because upon clicking the remove morphs block, it says that I don't currently have a morph. This is becoming a big issue as my players really want morphs. I would greatly appreciate a quick response. IP is play.mineleague.net. By the way I love your plugin and it is a great addition to my hub.

Thanks, Mineleague.

UPDATE:
2 more bugs so sorry. I found a bug with the TNT fountain, as the TNT does not fountain and it causes damage. Also pets don't despawn on leave so my hub has tons of useless pets that show when owner joins but don't follow. Thanks for reading!

**Comment by Mineleague** [comment]
2 more bugs so sorry. I found a bug with the TNT fountain, as the TNT does not fountain and it causes damage. Also pets don't despawn on leave so my hub has tons of useless pets. Thanks for reading!

**Comment by OnlyNoobDied** [comment]
I think you downloaded the wrong version of Lib's Disguises.
Can you tell me your server version?

**Comment by Mineleague** [comment]
1.10.2

**Comment by OnlyNoobDied** [comment]
## 1.10
 - Lib's Disguises: [LINK](https://www.spigotmc.org/resources/libs-disguises.81/download?version=102223)
 - ProtocolLib: [LINK](http://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/modules/ProtocolLib/target/ProtocolLib.jar)

Please download this version of plugin.

**Comment by OnlyNoobDied** [comment]
do you have the same issue?

**Comment by Mineleague** [comment]
Yes I still have the issue

**Comment by Mineleague** [comment]
Fixed but no hotbar slimeball. Using version 9.0.7 of libs disuises

**Comment by Mineleague** [comment]
sorry

**Comment by Mineleague** [comment]
I can't use the special mob powers as I am not given a slimeball when I click the mob.

**Comment by OnlyNoobDied** [comment]
i haven't add this option :P

**Comment by Mineleague** [comment]
Do you have any idea when this update is coming out? Best plugin ever very excited for update :)
