### ISSUE TITLE
Make cosmetics disabled on world change

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#60]
You should add a feature where all cosmetics are disabled upon a world switch so that when players switch worlds, they don't glitch their cosmetics like gadgets into worlds they're not allowed to have them. you should make this togglable in the config.yml

You should also add a permission add command sections to each cosmetic's yml file so that depending on what cosmetic they win in a mystery crate, a different command is executed to, for example add a gadget permission to a certain world whilst the other cosmetics would be added to all worlds.

**Comment by OnlyNoobDied** [comment]
```
Enabled Worlds:
- world
- world_nether
- world_the_end
```

**Comment by OnlyNoobDied** [comment]
i cant add the permission features with specified cosmetic

**Comment by Waffles2112** [comment]
oh
But i mean like i have gadgets enabled via permission in just a few worlds and i was saying like disable the cosmetics upon a world change so they wouldnt obtain those cosmetics in a world where those specific types arnt allowed

**Comment by OnlyNoobDied** [comment]
sorry, no.
