### ISSUE TITLE
Command to give player the gadgets selector

### ISSUE THREAD

**Issue by GuerreroCraft61** [OnlyNoobDied/GadgetsMenu#600]
Can you add command o give a player gadgets selector?
I use SkyWars X and it remove the selector after I join

**Comment by Matocolotoe** [comment]
If you mean a command to force the plugin to give the gadget to the player if his inventory was cleared, it's a good idea !

**Comment by FireFingertips** [comment]
> If you mean a command to force the plugin to give the gadget to the player if his inventory was cleared, it's a good idea !

Yeah, it would be awesome because I don't seem to get gadget when I join after reloading the plugin and anyone new doesn't seem to get it even though I have the give-item-on-join thing to true

**Comment by OnlyNoobDied** [comment]
@FireFingertips This is because you didn't have "gadgetsmenu.menuselector" permission.

**Comment by FireFingertips** [comment]
I figured out the issue, it is nothing to do with the permission as I am the owner and have all the permissions, it seemed like when it updated, it created a second file, and basically they were both clashing over each other, I deleted the old one and it worked perfectly! 😃

**Comment by OnlyNoobDied** [comment]
A `menuitem` command has been added in the new update. (Premium) It will also be added in the next update of free version.
