### ISSUE TITLE
fix gadgets list

### ISSUE THREAD

**Issue by Shuheidev** [OnlyNoobDied/GadgetsMenu#602]
when u found some gadgets, u can find this situation. 

Group of gadgets have item of locked gadget, but in this group u can see opened one

![image](https://user-images.githubusercontent.com/15435167/47007984-0e22ab80-d142-11e8-9cb0-227c41b4dcc4.png)

![image](https://user-images.githubusercontent.com/15435167/47007964-0531da00-d142-11e8-99f5-362f778bd183.png)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
