### ISSUE TITLE
Command Blocks

### ISSUE THREAD

**Issue by Blu3FireEdeN** [OnlyNoobDied/GadgetsMenu#608]
Use command blocks with Gadgets Menu

Thanks !

**Comment by Matocolotoe** [comment]
What are you actually suggesting ? ._.

**Comment by Blu3FireEdeN** [comment]
When I try to execute this command in a command block : 

"gmenu reset all @p",
the command block output is "[01:53:56] GadgetsMenu » This feature will be added soon."

It's not an issue, just a suggestion (i don't know where i could suggest this)
Thanks

**Comment by Matocolotoe** [comment]
Actually when any other command sender than a player tries to execute a GadgetsMenu command this message appears, and if you want to suggest anything, just create an issue ;)
