### ISSUE TITLE
console commands error

### ISSUE THREAD

**Issue by zenandreas** [OnlyNoobDied/GadgetsMenu#609]
Hello,

Apparently its not compatible with the UltraPermission plugin. I've modified the permission command in config and it returns console error of uknown command.

The Uperms plugin command is: /upc addPlayerPermission <Player> <Permission> (Options)

so i've added in the config:

  Execute-Command: upc addPlayerPermission {PLAYER} {PERMISSION}

-----------------------------------------------------

After this, i've tried adding a random console command "say test" and still doesnt work. Not sure what commands throws in the console but nothing works

**Comment by OnlyNoobDied** [comment]
There are two commands you needed to change. Did you done both?

https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust

**Comment by zenandreas** [comment]
Yeah, didn't know about that one xD  Sorry
