### ISSUE TITLE
Cowboy gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#614]
When a player becomes invisible (with a /vanish for example), and if another player is riding him with the Cowboy gadget, he doesn't ride him anymore and strangely teleports to him every 0.5 second

**Comment by OnlyNoobDied** [comment]
Cowboy gadget will not able to ride vanished player in the next update.

**Comment by OnlyNoobDied** [comment]
[GadgetsMenu.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/2584261/GadgetsMenu.zip)
You may test the cowboy gadget too.

**Comment by Matocolotoe** [comment]
@OnlyNoobDied Could you please add something to make player unride his target if it becomes invisible to him ?

**Comment by OnlyNoobDied** [comment]
You mean while the player riding him, he become invisible?
