### ISSUE TITLE
Items found recently

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#615]
In the mystery box, when a player hasn't found 5 items (or more) in total, it appears like that in `Mystery-`Box-Information message :

Items found recently :
`1.`

If the {RECENT_LOOT_1} returns nothing maybe you could set this like :

`1. None`

Based on the `None-Cosmetic-Has-Been-Selected` message ?

**Comment by OnlyNoobDied** [comment]
`No-Recent-Loot-Found` message will be added in the next update.

**Comment by Matocolotoe** [comment]
Thanks ! :D
