### ISSUE TITLE
Give mystery dust and mystery boxes to an offline player

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#618]
Currently you cannot give mystery boxes or mystery dust to an offline players with commands, but it can be done with the API. Could you please add the possibility of giving them to offline players ?

**Comment by OnlyNoobDied** [comment]
You're able to give an offline player mystery boxes.

**Comment by Matocolotoe** [comment]
It says the player couldn't be found

**Comment by Aurelien30000** [comment]
I confirm this issue with the use of your API.

**Comment by OnlyNoobDied** [comment]
Can anyone show me how you make it work?

**Comment by Aurelien30000** [comment]
For my part, I would like to give mystery boxes during an action on a website (vote, purchase...) and if the player who made this action isn't connected on the MineCraft server, I can't give it directly. I save it in a variable and I only give it to its connection.

I propose you to change the currenly API to OfflinePlayer : 

PlayerManager com.yapzhenyie.GadgetsMenu.api.GadgetsMenuAPI.getPlayerManager(Player player)

This shouldn't cause any concern on your side as a player is also considered an offlineplayer but not the other way around.

**Comment by OnlyNoobDied** [comment]
I need to recode MySQL, please give me some time.

**Comment by OnlyNoobDied** [comment]
Actually, you're able to give offline player mystery boxes by command.

**Comment by OnlyNoobDied** [comment]
@Matocolotoe @Aurelien30000  Are you sure you can't give a offline player mystery box?

**Comment by OnlyNoobDied** [comment]
Do you disable the "worlds" saving the playerdata?

**Comment by Matocolotoe** [comment]
Nah, my main lobby (`Hub` world) has the complete playerdata folder

**Comment by OnlyNoobDied** [comment]
This feature haven't added in the latest update. It will be implemented in the next few updates.

**Comment by OnlyNoobDied** [comment]
The reason that I didn't add (give offline player mystery dust) is some of the economy plugin does not support offline player.

**Comment by Matocolotoe** [comment]
You could just add a message to inform that offline player mode isn't supported for the hooked plugins.

**Comment by Matocolotoe** [comment]
any news on this @OnlyNoobDied ?

**Comment by OnlyNoobDied** [comment]
Due do 3rd economy plugin doesn't supported for offline player, I am unable to add this feature.

**Comment by OnlyNoobDied** [comment]
By the way, what mystery dust storage are you using?

**Comment by Matocolotoe** [comment]
i'm using yaml files

**Comment by Matocolotoe** [comment]
or you could just specify that it doesn't work for economy plugins that don't support offline players

**Comment by OnlyNoobDied** [comment]
This feature has been added in the new version.

**Comment by Aurelien30000** [comment]
Thanks <3
