### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by download042** [OnlyNoobDied/GadgetsMenu#619]
Hi!

I receive this error in my console, every 2 minutes:
https://pastebin.com/gTcf2WEa

Actually i haven't detected a real problem, or bug. Only this error, in my console, which is very confusing.

I tried the plugin on different server versions, different GadgetsMenu versions, and i got the same error.
Tried on Spigot 1.11.2 and 1.12.2;
Tried with GadgetsMenu: 4.1.16 and 4.2.2

Thank you in advance for your answer!

**Comment by OnlyNoobDied** [comment]
I know what's the problem. I will this problem in the next update.

**Comment by download042** [comment]
Thank you!😃

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
