### ISSUE TITLE
Small request about particles and cloaks

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#620]
Is it possible to detect if a player can (or not) see another player with ProtocolLib ?
If it is possible could you please only show particles and cloaks to players that see the player with the cloak or the particle ?

(If you are doing a loop for players to see particules you can use `canSee` effect with Bukkit I think)

**Comment by OnlyNoobDied** [comment]
`Hide-Particle-Effect-For-Vanish-Player: true`
`Hide-Cloak-Effect-For-Vanish-Player: true`
What do you think about this syntax?

**Comment by Matocolotoe** [comment]
Yeah, that would be super nice !
Just a missing "ed" at "Vanish"
