### ISSUE TITLE
Errors related to pets

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#621]
When I :
- spawn a pet
- disconnect
- reconnect in a world where cosmetics are not enabled (as op, but I think it does the same as not op)

The `No-Permission` message appears and "(prefix) Player not found !" appears in console
The pet also despawns when I get back into a valid world but he is still enabled when I go in the menu

But if I reload the plugin, my pet reappears if I'm in a valid world

**Comment by OnlyNoobDied** [comment]
I can't find any problems. Can you give me more details? (console messages, video)

**Comment by OnlyNoobDied** [comment]
I can't find any problems. Can you give me more details? (console messages, video)

**Comment by Matocolotoe** [comment]
I'll try to explain this as clearly as possible

First, I enable a pet in a world where cosmetics are enabled, let's say my lobby.
I change world and cosmetics are disabled in that world.

Then, I disconnect and I reconnect. Before getting teleported to the lobby, I get the `No-Permission` message and in console, the `Player-Not-Found` message is printed.
Once I am in the lobby, my pet despawned but is still selected. If I reload the plugin with /gmenu reload, it reappears (I enabled `Sync-Cosmetics-On-Join`, shouldn't I ? xd)

**Comment by OnlyNoobDied** [comment]
do you use any PerWorldPermission plugin or something related to it?

**Comment by Matocolotoe** [comment]
No, I use PermissionsEx but the only per world permissions I set up is for worldedit for builders

**Comment by OnlyNoobDied** [comment]
I can't reproduce the issue in my server. :(

**Comment by Matocolotoe** [comment]
I'll try to do it on a test server in 1.8.8 and tell you what happened

**Comment by Matocolotoe** [comment]
Actually I just have to reconnect for this to happen

**Comment by Matocolotoe** [comment]
I'll check everything that I did regarding permissions because I can't reproduce it on a 1.8.8 server

**Comment by Matocolotoe** [comment]
After investigating it came from permissions, I have to manually assign the `*` permission to myself
