### ISSUE TITLE
Small request about halloween animation

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#624]
Would be nice if the rotation of the mini block depended on the mystery vault's rotation if it's a chest or an ender chest

For example if it's a chest and it is facing the north, the mini block will be facing the north

**Comment by OnlyNoobDied** [comment]
The facing depend on when you adding a mystery vault.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue seem only happen in 1.13 server. weird :/

**Comment by OnlyNoobDied** [comment]
nvm, this issue will be fixed in the next update.

**Comment by Matocolotoe** [comment]
the mythic quest for 1.8 and 1.13 compatibility xd
anyways, thanks for responding c;

**Comment by Matocolotoe** [comment]
also @OnlyNoobDied the sound of the Crafting sound seems weird

**Comment by OnlyNoobDied** [comment]
> also @OnlyNoobDied the sound of the Crafting sound seems weird

This problem will be fixed in the next update.

**Comment by Matocolotoe** [comment]
Double thanks xd
