### ISSUE TITLE
TicTacToe Gadget

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#626]
Hello, I'd like to report a bug of I meet with this Gadget. It seems that it's impossible to launch several games at the same time. Let me explain, 2 groups of 2 players invite each other, a first group accepts, the game starts without trouble. But, when the second also runs the game, that of the first group will cut and the names of the players will be "corrupt / mixed / incorrect". I hope I made myself understood, don't hesitate to ask me more details ^^.

**Comment by Matocolotoe** [comment]
Also, when two games start at the same time, one of them just ends weirdly

**Comment by OnlyNoobDied** [comment]
any news?

**Comment by OnlyNoobDied** [comment]
Sorry for the inconvenience that I can't test the bug myself. Please inform me if you tested. @Matocolotoe , @Aurelien30000

**Comment by Matocolotoe** [comment]
Everything works fine 👍
