### ISSUE TITLE
Problem with the pages system

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#627]
When you click on the button to go to the previous page, it makes you go back to the main menu

**Comment by OnlyNoobDied** [comment]
I think you click twice the button

**Comment by Matocolotoe** [comment]
It comes from a conflict between different buttons that have the same item type
You should check the name of the item according to the messages.yml file

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This problem only happened in 1.8 server.
