### ISSUE TITLE
/gmenu main doesn't works

### ISSUE THREAD

**Issue by Yukyxy** [OnlyNoobDied/GadgetsMenu#628]
Hello the menu main doesn't work in the last version
https://pastebin.com/XL75AdnD
server spigot 1.13.2
version plugin 4.2.3

**Comment by OnlyNoobDied** [comment]
Restart the server and tell me the result later.

**Comment by Yukyxy** [comment]
https://pastebin.com/yQ7u3sWw

**Comment by Yukyxy** [comment]
sorry it was the message file that my staff translated

**Comment by OnlyNoobDied** [comment]
I'm sorry to tell you that something went wrong.

You may try these method to solve this problem.
First, change the "Config-Version" to 1.0.7 and restart the server.

If the problem still exist, you need to delete some files(mainmenu.yml, gadgets.yml, custom particles.yml, animations.yml, mysteryboxes.yml, config.yml, messages.yml).

**Comment by OnlyNoobDied** [comment]
Okay, seem to be fixed now?
