### ISSUE TITLE
Players able to pass through the worldborder with TP Stick Gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#629]
Just wondering if it's technically fixable 🤔

**Comment by OnlyNoobDied** [comment]
Do you have a server? Can you give me the ip?

**Comment by OnlyNoobDied** [comment]
I am wonder how can you find so much problems..

**Comment by Matocolotoe** [comment]
Yes I have a server. I'm sorry, everything is in French
And idk how I found so many issues either on servers like Hypixel or some plugins, I'm sorry if I am clumsy
