### ISSUE TITLE
MysteryBox hologram multiplying everytime a player joins

### ISSUE THREAD

**Issue by Estok** [OnlyNoobDied/GadgetsMenu#63]
https://cloud.githubusercontent.com/assets/20013341/21414800/a9be7fcc-c7e1-11e6-9508-6d1b171c1df8.png

You can see it in the image.

**Comment by OnlyNoobDied** [comment]
you means holograms will create when a player join the server?

**Comment by OnlyNoobDied** [comment]
Did you get error from console?
