### ISSUE TITLE
MysteryBox -> Recent loot bug

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#630]
**Describe the bug**
As a new player, when you open the mysterybox menu and you see the item "Mystery Box Information", the line 1 of "recent items" doesn't show the "none" lore.

**To Reproduce**
See above, it's simple to reproduce.

**Expected behavior**
The line 1 of the Mystery Box Information must show "none" at right :

```
Your five most recent items found are:
1. none
```

Instead of:

```
Your five most recent items found are:
1.
```

**Further Information (please complete the following information):**
 - Server Version: [Paper 1.12.2 Build #1589]
 - GadgetsMenu Version: [GadgetsMenu 4.2.3]
 - Console stack trace if have: [No error]

**Screenshots**
http://image.noelshack.com/fichiers/2018/47/5/1542990624-2018-11-23-16-39-05.png

**Additional Information**
Nothing

**Comment by OnlyNoobDied** [comment]
I already knew that bug and will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This problem only occur when you use MySQL to save data.
