### ISSUE TITLE
Players sometimes they are able to get the enderchest from the crate craft menu

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#634]
**Describe the bug**
Players sometimes they are able to get the enderchest from the crate craft menu

**To Reproduce**
1. Go to 'craft chest menu'
2. Purchase a chest
3. Money will not go down and you have the chest on inventory

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: Paper 1.12.2
 - GadgetsMenu Version: 4.3.0
 - Console stack trace if have. https://gist.github.com/xion87/28f1d3cd95066dbd97111a8b2edfd229

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by OnlyNoobDied** [comment]
Oops, all of the purchase system broken.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
