### ISSUE TITLE
3 feature requests

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#638]
Would be nice if we could customise :
- [x] Name of the exploding sheep
- [x] GUI name of gadgets' categories (`Fun & Games` for example)
- [x] Slots of the categories' icons (`mainmenu.yml`)

**Comment by OnlyNoobDied** [comment]
`GUI name of gadgets' categories (Fun & Games for example)`
Actually, you can modify the GUI name. The GUI name same as the item name.
```
Gadgets:
  Fun And Games:
    Name: '&eFun & Games'
```

**Comment by Matocolotoe** [comment]
Yeah I know but it would be nice if the two things were seperated
