### ISSUE TITLE
Enabled Worlds feature improvement [Suggestion]

### ISSUE THREAD

**Issue by Estok** [OnlyNoobDied/GadgetsMenu#64]
I suggest the plugin should save the player's active cosmetics and active them every time the player joins the server or enters the enabled world. There should also be an option to auto-spawn your pet every time the player joins the server.

**Comment by OnlyNoobDied** [comment]
there is already have this feature.

**Comment by OnlyNoobDied** [comment]
if you don't reply, i will keep this as resolved.
