### ISSUE TITLE
All of my hats/emojis are appearing as Steve Heads

### ISSUE THREAD

**Issue by TMD15** [OnlyNoobDied/GadgetsMenu#642]
For some reason all the hats for the plugin at least for me appear as Steve heads. I have no idea why they just do. As for my friends who join my server all the hats work for them and they appear as normal. Do you know of any way I can fix this issue? It's giving me OCD, thanks.
![2018-12-15_19 21 23](https://user-images.githubusercontent.com/45928307/50064659-65fc8380-0180-11e9-9ae1-436233f91312.png)

**Comment by TMD15** [comment]
>           It might be your internet problem.

its not, I know because my brother also plays on my server and he uses the same wifi as me but he can see all the hats

**Comment by OnlyNoobDied** [comment]
I'm not sure what's the problem. It might be your texture pack, settings or any other problem on your side.
