### ISSUE TITLE
Website Crates with Players and buying issue

### ISSUE THREAD

**Issue by plasmapug0019** [OnlyNoobDied/GadgetsMenu#643]
Ok.... I am starting a server and I have a website up. Tebex (aka buycraft) to be accurate. and I want it to let players buy crates from there. however nothing really works. what command do I use in that case? the plugin makes the website unable to use the command because the plugin requires a players name and I cant put the @ thing that targets the executing entity. THE OTHER THING: De-op players can't buy cosmetics. I checked the perms and the config. nothing. Help?

**Comment by OnlyNoobDied** [comment]
You may use these commands to add it into Tebex.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Commands#mystery-dust-commands
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Commands#mystery-boxes-commands

"De-op players can't buy cosmetics"
Player need to earn Mystery Dust to unlock cosmetic items.
