### ISSUE TITLE
Confirm Open lag issue

### ISSUE THREAD

**Issue by Duartteno** [OnlyNoobDied/GadgetsMenu#645]
**Further Information (please complete the following information):**
 - Server Version: 1.12.2
 - GadgetsMenu Version: 4.3.1

**Screenshots**
<img width="1409" alt="gadgetsmenu" src="https://user-images.githubusercontent.com/44345095/50349807-4af19100-053d-11e9-8086-988cff9fcc35.png">

**Comment by OnlyNoobDied** [comment]
Some of the latency issues will be fixed in the next update.

**Comment by StayMM** [comment]
@OnlyNoobDied i can confirm this issue.
<img width="1385" alt="lag" src="https://user-images.githubusercontent.com/46968611/52522328-233cc080-2c84-11e9-99e7-78e8c0ed9d0a.png">

**Comment by Matocolotoe** [comment]
Should be fixed as the plugin owner said, any news on this @Duartteno @StayMM ?

**Comment by Matocolotoe** [comment]
@OnlyNoobDied Some things still takes a lot of performance
![image](https://user-images.githubusercontent.com/42092549/61556574-6a648400-aa62-11e9-9525-7a96f43c6439.png)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
