### ISSUE TITLE
No clickable items in the GUI

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#646]
Hi,

Is it normal that on 1.13.2 I am not able to click on any gadgets, cosmetics, etc?

They have no effects like if the click was not recorded...

I try a right or a left click on differents cosmetics and still get the same problem, it simply doesn't work :(

Do you have an idea for this?

Please not that I use the latest premium version of GadgetsMenu

**Comment by OnlyNoobDied** [comment]
Can I have your server ip? Let me take a look.

**Comment by OnlyNoobDied** [comment]
By the way, any errors from the console?

**Comment by maxlehot1234** [comment]
No nothing and it was  alocalhost server :(

I remove gadgetsmenu folder to letthe plugin generate a new one and still get the issue.

All files and folders are generate, but nothing was clickable :(

**Comment by OnlyNoobDied** [comment]
The main menu item not working only or all the menus not working?

**Comment by maxlehot1234** [comment]
I can click items in the main menu, but if I try to click on a particle for example, It doesn't apply.

Here is a video about this: https://www.youtube.com/watch?v=xUEkWq_cTO0&feature=youtu.be

Also check the hat, it doesn't work as expected

**Comment by OnlyNoobDied** [comment]
Try this. https://www.dropbox.com/s/k0wbyhn8b2b9fp7/GadgetsMenu.jar?dl=0

**Comment by OnlyNoobDied** [comment]
Let me know if you installed the version I gave you.

**Comment by maxlehot1234** [comment]
Nope same problem

**Comment by maxlehot1234** [comment]
Anyway I go sleeping, since it was 3:37 am here.

I will answer you later today ;)

Thanks for your time and continue your nice job.

Happy new year 2019 too btw ;)

**Comment by OnlyNoobDied** [comment]
I tested with the latest build of 1.13.2 spigot and it works great. In this case, if you can't select any item in any cosmetic gui menu, it will occur errors in console. If there's no errors in console, it might be a plugin conflict.

**Comment by OnlyNoobDied** [comment]
Any news about the issue? Is it fixed?

**Comment by maxlehot1234** [comment]
No same problem. I realize that WGorldGuard and WorldEdit simply doesn't work and simply doesn't create any folder or files on my server.

Need to check this too.


But for the GadgetsMenu issue, it was not fixed. I'm at job right now, but I create a local server on my computer that was accessible anywhere in the world. So I can give you the IP later tonight, so you can check the issue I have.
Of course, I will not put the IP here for security reason so how I can give the IP to you only? Do you have a discord?

Thanks again @OnlyNoobDied

**Comment by OnlyNoobDied** [comment]
Can you find my discord via the plugin discord? You can find GadgetsMenu
discord at the plugin forum.

**Comment by OnlyNoobDied** [comment]
My discord :Yap Zhen Yie#0090

**Comment by ItsSniper** [comment]
I am experiencing this same issue. Any info on if it'll be fixed soon?

**Comment by OnlyNoobDied** [comment]
@maxlehot1234 @ItsSniper Found the problem. This issue is affected by WorldGuard plugin. I will fix this issue as quick as possible.

**Comment by OnlyNoobDied** [comment]
I used 10+ tabs to find solution :/
