### ISSUE TITLE
Spooderman Suit's ability

### ISSUE THREAD

**Issue by glowgrew** [OnlyNoobDied/GadgetsMenu#649]
**Describe the bug**
Spooderman Suit's ability is throw web. If the web being throwed into the void there's will be an infinite cooldown of an ability

**Further Information (please complete the following information):**
 - Server Version: 1.13.2
 - GadgetsMenu Version: 4.3.2

**Screenshots**
https://gph.is/2VI8H4b

**Comment by OnlyNoobDied** [comment]
Can you try again after 8 seconds when you throws the web into the void.

**Comment by glowgrew** [comment]
Nothing changed :/

**Comment by OnlyNoobDied** [comment]
It might deactivate the gadget after 8 seconds.

**Comment by glowgrew** [comment]
> It might deactivate the gadget after 8 seconds.
https://gph.is/2VK5FMN

**Comment by OnlyNoobDied** [comment]
I mean you can throws web again after 8 seconds.

**Comment by glowgrew** [comment]
I understand. But I still can't

**Comment by OnlyNoobDied** [comment]
Hmm, this issue will be fixed in the next update.
