### ISSUE TITLE
Purchase items

### ISSUE THREAD

**Issue by ZoSwe** [OnlyNoobDied/GadgetsMenu#65]
Does GroupManager work for the purchase feature, because when I put in the command in config it won't work, it'll not give them the permission.

**Comment by PaulTDD-MC** [comment]
You would have to change this:

```
  Run-Command: pex user {PLAYER} add {PERMISSION}
```
to:

```
  Run-Command: manuaddp {PLAYER} {PERMISSION}
```

**Comment by ZoSwe** [comment]
I've but it wont go through in to users.yml. It says in the console that it adds to the player but it aint showing up there :/

**Comment by OnlyNoobDied** [comment]
i think will sync data every 10 minutes.
```
settings:
   data:
    save:
      minutes: 10
```
in GroupManager config.yml
