### ISSUE TITLE
[Question] Disable Mystery Box after time

### ISSUE THREAD

**Issue by arkobat** [OnlyNoobDied/GadgetsMenu#651]
Hello.
I'm trying to disable the mystery box players receive after some online time.
However, I can't seem to find a setting for this. I've checked both the config.yml, and the permissions, but nothing has caught my attention.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-why-player-get-mystery-box-randomly
