### ISSUE TITLE
Animated hats problem (config).

### ISSUE THREAD

**Issue by andrei923** [OnlyNoobDied/GadgetsMenu#652]
when I set **Purchasable: false** for any hat from the config it automatically sets to true.

 - Server Version: 1.8.8
 - GadgetsMenu Version:4.3.3
 - Console stack trace if have.

**Comment by OnlyNoobDied** [comment]
Do you mean animated hats file or custom animated hats file? Anyway to reproduce the problem?

**Comment by andrei923** [comment]
\GadgetsMenu\categories - animated hats.yml

**Comment by andrei923** [comment]
set Purchasable: false than reload the plugin(also tried to turn off edit & start server).

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
