### ISSUE TITLE
Connection handler

### ISSUE THREAD

**Issue by StayMM** [OnlyNoobDied/GadgetsMenu#654]
**Describe the bug**
PlayerQuitEvent creates huge lag

**Further Information (please complete the following information):**
 - Server Version: 1.12.2
 - GadgetsMenu Version: Newest

**Comment by OnlyNoobDied** [comment]
What storage are you using? File or MySQL

**Comment by StayMM** [comment]
mysql

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.
