### ISSUE TITLE
Suggestion about the API

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#657]
I was wondering if it would be possible to extend the GadgetsMenu API for future releases.
For example, you could add an event that fires when a player gains, looses... mystery dust

**Comment by OnlyNoobDied** [comment]
Any other events you wanted to suggest?

**Comment by Matocolotoe** [comment]
that's all for me, it would already be nice if these 2 were added :p

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

**Comment by OnlyNoobDied** [comment]
AssignMysteryDustEvent - Called when set mystery dust for a player.
GainMysteryDustEvent - Called when player gain mystery dust.
RemoveMysteryDustEvent - Called when remove mystery dust from a player.
