### ISSUE TITLE
Weird thing about opening of multiple boxes

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#658]
**Describe the bug**
idk if it's a bug or a weird thing that I configurated wrongly (because with the default config this didn't happen) but when any player opens up to 250 boxes at a time, the `Unknown-Error` message appear

**Further Information**
 - Tested for server versions : 1.8.8, 1.12.2
 - GadgetsMenu Version: 4.3.6
 - No console stacktrace

**Comment by OnlyNoobDied** [comment]
What error message?

**Comment by Matocolotoe** [comment]
"An unknown error occured"

**Comment by OnlyNoobDied** [comment]
The error occur when player click "Confirm Open Multiple Boxes" menu?

**Comment by OnlyNoobDied** [comment]
I can't find the problem if there's no error in console :/

**Comment by Matocolotoe** [comment]
Got the message key : `Failed-To-Purchase`

**Comment by OnlyNoobDied** [comment]
Did "Confirm Open Multiple Boxes" menu name same as "Confirm Purchase" menu name?

**Comment by Matocolotoe** [comment]
Yes, is that why ?

**Comment by OnlyNoobDied** [comment]
Yup.

>

**Comment by Matocolotoe** [comment]
works now 👍
please put a tree morph so i can disguise into a tree when me be dumb XD
