### ISSUE TITLE
Mystery boxes animations

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#659]
**Describe the bug**
When a player opens a mystery box and the animation contains items that rotate around the block, sometimes, only 2 items appear instead of more.

**Expected behavior**
About 5 items should rotate around the box.

**Further Information**
 - Server Version : 1.8.8
 - GadgetsMenu Version : 4.3.7
 - No error in console

**Comment by OnlyNoobDied** [comment]
Depends on what type of box you are opening. If you are opening 1 star box,
only one block will appear.

**Comment by Matocolotoe** [comment]
Didn't know that, thanks for the answer c;
