### ISSUE TITLE
Morphed players will get invulnerable

### ISSUE THREAD

**Issue by thomas-worm** [OnlyNoobDied/GadgetsMenu#660]
**Describe the bug**
Players who use the morphs get invulnerable. They don't get damage by monsters, fire, water (missing air), ... any more.

**To Reproduce**
1. Go to your gadgets menu.
2. Click on the morph
3. Try to get damage from mobs.

**Expected behavior**
We expect the players to interact as normal players (= get damage), if they are morphed.

**Further Information (please complete the following information):**
 - Server Version: 1.13.2
 - GadgetsMenu Version: 4.3.7

**Comment by OnlyNoobDied** [comment]
From the beginning we add morph, we decided to disable damage while they morphed.

**Comment by OnlyNoobDied** [comment]
However, we planning to add an option to toggle mob disguise damage in free version.

**Comment by OnlyNoobDied** [comment]
Please check for new update.
