### ISSUE TITLE
Add option to disable Full Suit Abilities

### ISSUE THREAD

**Issue by Segysmundo** [OnlyNoobDied/GadgetsMenu#666]
If it's not too much work I'd love to know if you could add an option that would allow us to enable/disable the suit's full set abilities.

Some people like to spam or abuse some suit abilities and it's somewhat annoying, by disabling their abilities people would still be able to wear the suits but not abuse their effects.

The only option right now is to completely disable that suit :(

Thnx.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
