### ISSUE TITLE
no perms = no unlocks

### ISSUE THREAD

**Issue by AcaiiTV** [OnlyNoobDied/GadgetsMenu#667]
Players have:
gadgetsmenu.animations.*
gadgetsmenu.mysteryboxes.open.*
gadgetsmenu.autoequip.foundloot
gadgetsmenu.autoequip.purchase
gadgetsmenu.commands.namepet
gadgetsmenu.mysteryboxes.gift
gadgetsmenu.menuselector

Everything in the menu shows 0 unlocked even after they've opened a mysterybox.

Players with permissions such as gadgetsmenu.cloaks.* can use cosmetics but it unlocks everything.

**Comment by OnlyNoobDied** [comment]
You need to change `Execute-Command` base on your permission plugin.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-what-is-the-problem-when-player-failed-to-get-cosmetics-item-from-opening-mystery-boxes-or-purchase-it-using-mystery-dust
