### ISSUE TITLE
mySQL not transferring items between servers

### ISSUE THREAD

**Issue by FireAlert** [OnlyNoobDied/GadgetsMenu#668]
hi i am running a bungee-cord spigot minecraft server and using this plugin. i have two lobby's (both on separate servers connected by MySQL). if somebody buys something on one lobby 1 and then goes to lobby 2 they do not keep the things they bought in the menu but if the item was in use it will keep it on them. it will also transfer the mystery dust and mystery boxes. hope you can tell me how to fix this!

**Comment by OnlyNoobDied** [comment]
It doesn't save unlocked cosmetic items in the free version. It only available in the premium version.
