### ISSUE TITLE
Few Gadgets Broken

### ISSUE THREAD

**Issue by cdmvirt** [OnlyNoobDied/GadgetsMenu#669]
**Describe the bug**
Tether-ball places poll and chicken but they are not attached, Miniatures take away nav items if equiped (Clicking on miniature while holding item)

**Further Information (please complete the following information):**
 - Spigot 1.13.2
 - GadgetsMenu Version: 4.4.6

**Comment by OnlyNoobDied** [comment]
Seems like minecraft "design" that the leash did not attach on the chicken.
