### ISSUE TITLE
Paintballs and Mysterys

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#67]
1. When a player such as myself shoots a paintball from the paintball gadget, it does not effect all the blocks it lands on/hits, and at times, it doesn't effect them at all
![2016-12-23_01 56 07](https://cloud.githubusercontent.com/assets/24687656/21449505/75f384f8-c8b3-11e6-8814-dcb57be2fc06.png)
(Only one paintball was fired from the paintball gun in this figure)

2. What is up with this blank row at the bottom of mystery boxes, it seems pretty pointless and takes up a lot of space when a player has like 100 or something mysteryboxes
![2016-12-23_01 57 05](https://cloud.githubusercontent.com/assets/24687656/21449526/afe340c2-c8b3-11e6-950a-624373b0b9b4.png)

**Comment by OnlyNoobDied** [comment]
1) Paintball Gun Gadget will only fill 10% of the radius, it's not a bug.

2) I will put some item in the empty slot, like Gift, Mystery Box information in future.
