### ISSUE TITLE
Tic Tac Toe Issue

### ISSUE THREAD

**Issue by topthat177** [OnlyNoobDied/GadgetsMenu#670]
**Describe the bug**
When the player initiates with another player, they can accept or decline etc. If they accept/decline while they have an active cosmetic on or in their hand (this case the tic tac toe game as well)... 

Says "Cannot use that command while cosmetics are enabled."
Also says "You don't have a pending challenge from that player."
Initiating Player cannot re-send game invite because "You've already sent a challenge request to [Player]" - Have to leave server or go to a world where gadgets are disabled to resend.

If player receiving request have nothing enabled and they accept - It works... but the accepting player has the server issue them an "Unknown Command" message.

Also get unknown command message if the decline but initiator is told that they declined the request.

If the accepting player has a hat or possibly another cosmetic on and they accept. It works unlike if they have the gadget on. But they still get the Unknown Command and "Cant use that command while you have a cosmetic enabled".

There are a lot of combinations with a lot of different errors here. I tried to outline them all but there are probably more. Hope this makes sense.  

**To Reproduce**

Just try doing what I've described above.

**Expected behavior**

Also described above.

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.12.2/g
 - GadgetsMenu Version: 4.3.9
 - Console stack trace if have: N/A

**Screenshots**

-- https://imgur.com/a/55GxeYt

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by topthat177** [comment]
Flower Giver and any other gadgets that require acceptance/rejection from another player have similar issues.

**Comment by OnlyNoobDied** [comment]
Can I have your config.yml file please.

**Comment by topthat177** [comment]
https://pastebin.com/BvK7dEsJ

**Comment by topthat177** [comment]
Sorry for slow reply.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
