### ISSUE TITLE
Still issues with world changing

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#674]
**Describe the bug**
There are still issues with world changing.

**To Reproduce**
1. Set `Sync-Cosmetics-On-Join` to true in the config
2. Activate some cosmetics
3. Go in an unvalid world
4. Return in a valid world

**Expected behavior**
Cosmetics shouldn't reset while changing worlds like this.

**Further Information (please complete the following information):**
 - Server Version : 1.8.8
 - GadgetsMenu Version : 4.3.10
 - No stacktrace in console

**Comment by OnlyNoobDied** [comment]
Need to change the way of sync cosmetics.

**Comment by Matocolotoe** [comment]
Yeah and I don't know if it's related but the server has a 1 second lag when an op opens the main menu

**Comment by OnlyNoobDied** [comment]
Is this only happened on the first join?

**Comment by OnlyNoobDied** [comment]
Let us discuss about this issue. This issue will be fixed in the next update.

However, equipped cosmetics won't be sync if the player leave the server in an invalid world. Is there any problem?

**Comment by Matocolotoe** [comment]
This might cause problems if the player joins and is teleported to a valid world after joining

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check the new update.
