### ISSUE TITLE
Disconnection in an invalid world thing

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#676]
In response to the issue #674 it would be nice if disconnecting in an invalid world would not result in a cosmetics total reset.

**Comment by OnlyNoobDied** [comment]
>Let us discuss about this issue. This issue will be fixed in the next update.
>
>However, equipped cosmetics won't be sync if the player leave the server in an invalid world. Is there any problem?

Confirmed that this issue still exist after the new update. I have to change some code to make it works.

**Comment by Matocolotoe** [comment]
How does the current system for cosmetics syncing work ?

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
