### ISSUE TITLE
GadgetMenu Bug

### ISSUE THREAD

**Issue by AccioAce** [OnlyNoobDied/GadgetsMenu#677]
Hello, 
It seems like GadgetMenu permissions aren't working for the players.

**Comment by OnlyNoobDied** [comment]
First, do you have a permissions plugin? You need one to make them work.

**Comment by AccioAce** [comment]
Yes, I do, it use to work fine until the recent update.

**Comment by OnlyNoobDied** [comment]
Which part of the permissions doesn't work?

**Comment by AccioAce** [comment]
> Which part of the permissions doesn't work?

/gmenu main - But I'm not sure about other permission. But it seems like players can't open it.

**Comment by OnlyNoobDied** [comment]
Is the user in an valid world which has been set in `Enabled-Worlds` while execute the command?

**Comment by AccioAce** [comment]
Nope, they just don't have the permission. I'm not sure If chatcontrol can be blocking it or not. Or it could be the plugin buggy. I'll need to check it on the new version without chatcontrol.

**Comment by OnlyNoobDied** [comment]
`/gmenu main` doesn't required any permission. Player do not need a permission to do so.

**Comment by OnlyNoobDied** [comment]
Is the problem still exist or it cause by 3rd plugin?

**Comment by AccioAce** [comment]
It works now, I see now it was caused by the 3rd plugin. Gmenu Maine is all
good

- thanks

**Comment by OnlyNoobDied** [comment]
Great. :D
