### ISSUE TITLE
Custom Head as Material for crafted chest

### ISSUE THREAD

**Issue by Endothelium** [OnlyNoobDied/GadgetsMenu#678]
Hello, it would be nice if we could change the default ender chest in the craft menu and for the animation.

See this config, the material texture doesnt work.

![image](https://user-images.githubusercontent.com/11161697/57039138-1ebcee00-6c5c-11e9-80cd-fac82d7110b6.png)

![image](https://user-images.githubusercontent.com/11161697/57039208-5166e680-6c5c-11e9-8694-078351687d70.png)

It would be nice if we could change this texture, there are a lot of nice chest in head database.

And another that would be really nice, would be if that texture set previously could be display in the chest animation.

Thanks

**Comment by OnlyNoobDied** [comment]
Fully head texture material support will be added in the next update which will be released on premium version first. Free version will follow up after 2-3 days.

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
