### ISSUE TITLE
Cloaks

### ISSUE THREAD

**Issue by Waffles2112** [OnlyNoobDied/GadgetsMenu#68]
When a player has a cloak enabled when they leave, when they rejoin the cloak doesn't auto enable like pets, and particles do, but upon a plugin reload, the cloak then enables

**Comment by OnlyNoobDied** [comment]
can you tell me your server ip? seen like you found many bugs XD

**Comment by Waffles2112** [comment]
Lovecraft.ro.Lt
.3.

**Comment by Waffles2112** [comment]
srry for the long time inbetween replies
i has other stuff i am doin atm

**Comment by OnlyNoobDied** [comment]
nvm

**Comment by Waffles2112** [comment]
kk
