### ISSUE TITLE
Recent Loot suggestion

### ISSUE THREAD

**Issue by Saphirrcr** [OnlyNoobDied/GadgetsMenu#680]
In the mystery vaults, the item "Mystery-Box-Information" list the recent loots dropped ({RECENT_LOOT_5})

But it also indicates the rarity of the item, which is not hideable.

The prefix is annoying, translated in french (in my opinion)
It would be nice if we could choose or not to have it

![m](https://user-images.githubusercontent.com/29708237/57402651-0c046500-71d8-11e9-981e-0442b13681f9.PNG)

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update.
