### ISSUE TITLE
Send Message (already had loot) issue

### ISSUE THREAD

**Issue by Saphirrcr** [OnlyNoobDied/GadgetsMenu#681]
**Describe the bug**

**To Reproduce**
In mystery boxes.yml config file :
##
Already-Had-Loot:
    Common:
      Give-Mystery-Dust:
        Enabled: false
        Min: 1
        Max: 3
      Send-Message:
        **Enabled: true**
        Message:
        - '&7Pas de chance ! Vous possédiez déjà ce cosmétique.'
      Execute-Command:
        Enabled: false
        Command:
        - eco give {PLAYER} 2
##

Yet, opening a mystery box only display the message set up in Found-loot :

##
Found-Loot:
    Common:
      Play-Sound:
        Enabled: true
        Sound: ENTITY_CHICKEN_EGG
      Send-Message:
        Enabled: true
        Message:
        - ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
        - '             &b&lCoffre aux trésors'
        - ''
        - '  &7La pêche a été bonne !'
        - '  &71x &a&l{LOOT}'
        - ''
        - ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄`
##

 - Server Version: paperclip-624 (MC1.13.2)
 - GadgetsMenu Version: 4.3.11

![Message](https://user-images.githubusercontent.com/29708237/57403617-6272a300-71da-11e9-9c57-8a6a3018476a.PNG)

**Comment by OnlyNoobDied** [comment]
So, what problem do you have?

**Comment by OnlyNoobDied** [comment]
The `Already Had Loots message only display once you already get that loot or you have the permission to access that loot.

**Comment by Saphirrcr** [comment]
I already had the gadgets from the mystery box, yet I did not receive the message

**Comment by OnlyNoobDied** [comment]
You already have that before you open the mystery box?

**Comment by Saphirrcr** [comment]
The legendary Item yes

**Comment by OnlyNoobDied** [comment]
@Saphirrcr Are you using LuckPerms plugin?

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.
