### ISSUE TITLE
Items can be removed from the pets menu

### ISSUE THREAD

**Issue by GingeyBook** [OnlyNoobDied/GadgetsMenu#683]
**Describe the bug**
When selecting any item in the pet menu, the item gets picked up and can be moved around by the player.

**To Reproduce**

1. Go to 'pet menu
2. Click on any item
3. The item can be removed

**Expected behavior**
When an item is clicked it should spawn the pet

**Further Information (please complete the following information):**
 - Server Version: 1.13.2
 - GadgetsMenu Version: 4.3.15

**Screenshots**
![image](https://user-images.githubusercontent.com/16448464/57641437-01085680-7583-11e9-9f90-478deea87702.png)

**Additional Information**
This happens for all players. Doesn't matter the permission level

**Comment by OnlyNoobDied** [comment]
I will check it after school.

**Comment by OnlyNoobDied** [comment]
@GingeyBook Did you saw any errors in console?

**Comment by GingeyBook** [comment]
Nothing.

**Comment by OnlyNoobDied** [comment]
What is your server ip? Can I test it in your server?

**Comment by Dvellan** [comment]
Hello, i've got the exact same problem.

**Comment by OnlyNoobDied** [comment]
@Dvellan What is the version of your server?

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.

**Comment by Dvellan** [comment]
i'm on 1.13.2 version
i downloaded gadgetsmenu yesterday

**Comment by Dvellan** [comment]
ok i saw you just posted a new version. im gonna check if it is fixed. Thank you for your time :)

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue.

**Comment by OnlyNoobDied** [comment]
@Dvellan Hopefully it's working perfectly.
