### ISSUE TITLE
Error with adding new lines

### ISSUE THREAD

**Issue by MysticalPower** [OnlyNoobDied/GadgetsMenu#69]
Could you tell me how to add lines to the description in the cosmetics file
![default](https://cloud.githubusercontent.com/assets/20573498/21472762/30e7db3a-caf1-11e6-9696-0a2d03872b4c.png)
? Error

**Comment by MysticalPower** [comment]
Sorry for my English, I am from Russia :)

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Config#how-to-use-cosmetics-yml-files-cosmetics-folder

**Comment by OnlyNoobDied** [comment]
remove line 12, and rewrite again
