### ISSUE TITLE
Could not pass event InventoryClickEvent to GadgetsMenu

### ISSUE THREAD

**Issue by TakoidGit** [OnlyNoobDied/GadgetsMenu#690]
**Describe the bug**
When using the GadgetsMenu GUI on Spigot, errors are thrown sporadically. 

**To Reproduce**
1. Use the GUI on latest Spigot build of 1.14.2.

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.14.2
 - GadgetsMenu Version: v4.4.16
 - Console stack trace if have: https://pastebin.com/fPJBDAg0

**Comment by OnlyNoobDied** [comment]
Is there anyways that you can reproduce this issue?
