### ISSUE TITLE
"Invalid item" on JSON messages

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#691]
Found this while hovering on the mystery box message in 1.12.2

![2019-06-08_14 30 39](https://user-images.githubusercontent.com/42092549/59147356-9409a480-89fa-11e9-941a-ba90ac76ef29.png)

When I use JSON messages with Skript it works fine tho

Spigot : 1.8.8
GadgetsMenu : 4.3.19 (guess it happens too with 4.3.20)

**Comment by OnlyNoobDied** [comment]
Investigate that this issue happened when you use different version between server and launcher.

**Comment by Matocolotoe** [comment]
Yes, happens will all JSON messages and may be related to ViaVersion
(see this : https://github.com/ViaVersion/ViaVersion/issues/799)

**Comment by OnlyNoobDied** [comment]
This issue should be fixed if you change this option in viaversion config.yml
```
# Should we fix nbt for 1.12 and above clients in chat messages (causes invalid item)
chat-nbt-fix: true
```

**Comment by Matocolotoe** [comment]
Already enabled

**Comment by Matocolotoe** [comment]
This issue comes from ViaVersion when you are on 1.12 on a 1.8 server
