### ISSUE TITLE
EntityPotionEffectEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by TakoidGit** [OnlyNoobDied/GadgetsMenu#692]
**Describe the bug**
Gadgets which use potion effects seem to spam an error in console. This happened when I was not online so I was unable to try to figure out which gadget was the cause.

**To Reproduce**
Unknown.

**Further Information (please complete the following information):**
 - Server Version: Paper-70 1.14.2
 - GadgetsMenu Version: 4.4.16
 - https://pastebin.com/wAtqpuBK

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
@TakoidGit By the way, your server TPS is lower than 17.

**Comment by TakoidGit** [comment]
I know. That log is from before the incremental chunk saving update to Paper yesterday so performance was quite terrible. It's much much better now. :)

Thanks for the fix! Sorry for lack of context in these reports as well. It's really difficult trying to identify which gadget is throwing errors when multiple players on the server are all using them in different situations.

**Comment by OnlyNoobDied** [comment]
I haven't release new updates, I will do it when I'm free. Sorry for the
inconveniences.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
