### ISSUE TITLE
[Error] When crafting Mystery Box

### ISSUE THREAD

**Issue by StrupeServer** [OnlyNoobDied/GadgetsMenu#694]
Hey. I gave myself some Mystery Dust to test out the crafting feature.

![image](https://user-images.githubusercontent.com/51787924/59432632-1376e980-8de8-11e9-9fe1-8c855984a1a7.png)
I gave myself 2500 dust and crafted the most expensive box. It tells me the action was successful.

![image](https://user-images.githubusercontent.com/51787924/59432665-2be70400-8de8-11e9-9145-090273622b11.png)
This error pops up in my console.

![image](https://user-images.githubusercontent.com/51787924/59432678-36a19900-8de8-11e9-8b16-f767b27b8b61.png)
And it tells me I got no box in the Inventory. Weird?

I don't know if it's just my server or not but definately worth mentioning. Thanks! Great plugin otherwise!

**Comment by OnlyNoobDied** [comment]
What did you modify in `mystery boxes.yml`? There's no loots been added in mystery boxes system.

**Comment by StrupeServer** [comment]
> What did you modify in mystery boxes.yml? There's no loots been added in mystery boxes system.

I've not touched that config file. Only the config.yml and messages.yml

**Comment by OnlyNoobDied** [comment]
Can I have your `config.yml` and `mystery boxes.yml`?

**Comment by StrupeServer** [comment]
https://pastebin.com/2SxsGzHb
^ config.yml

https://pastebin.com/u25KEsxM
^ mystery boxes.yml

Most of my changes are language changes to fit my server which is Norwegian. I don't know what I triggered. Thank you so much for your effort to help me though, rare to see that from developers nowadays! :D

**Comment by OnlyNoobDied** [comment]
Did you make any changes in cosmetics folder like changing the Rarity of an item?

**Comment by StrupeServer** [comment]
> Did you make any changes in cosmetics folder like changing the Rarity of an item?

I did do some changes to the rarities, yes.

Common > Vanlig
Rare > Sjelden
Epic > Episk
Legendary > Legende

Those changes were made in config.yml and mystery boxes.yml
Do I need to change those somewhere else as well? I thought it would just be visual if it were in the configuration.

**Comment by OnlyNoobDied** [comment]
From the errors I found that you changed the Rarity of the items which located in cosmetics folder such as `Hats.yml` and `Gadgets.yml`. If you changed the rarity in those items, you need to change it back otherwise it won't work.

Here is an example.
```
Hamburger:
  Name: '&aHamburger Hat'
  Mystery Dust: 12
  # Rarity: Common, Rare, Epic, Legendary (This is the rarity list that you only can put)
  Rarity: Common 
```

**Comment by StrupeServer** [comment]
![image](https://user-images.githubusercontent.com/51787924/59434777-7f5b5100-8dec-11e9-987e-9cbf689f9d9f.png)
That's weird because I've not changed them? I checked every single cosmetic .yml file

**Comment by OnlyNoobDied** [comment]
You just give me GadgetsMenu folder.😂

**Comment by StrupeServer** [comment]
[GadgetsMenu.zip](https://github.com/OnlyNoobDied/GadgetsMenu/files/3286267/GadgetsMenu.zip)

Hahah no worries.

**Comment by OnlyNoobDied** [comment]
Hmm, seems like it works perfectly. Did you try to restart the server and test again?

**Comment by StrupeServer** [comment]
That suddenly worked! I did restart it twice before posting about this bug so it's still circulating around in the system, it's just unclear what triggers it and how. But great! It's working now :D

**Comment by OnlyNoobDied** [comment]
Maybe you changed something and make it works.

**Comment by StrupeServer** [comment]
I found the reason. When placing down a mystery vault, and reloading the plugin using /gadgetsmenu reload will break the vault-chest. When re-placing the vault-chest you won't be able to open mystery boxes. Hope this explaination can help you :)

**Comment by StrupeServer** [comment]
Yes, I don't think this is the same error as before.

![image](https://user-images.githubusercontent.com/51787924/59441087-4de88280-8df8-11e9-9cb8-e64ef2c35136.png)

**Comment by OnlyNoobDied** [comment]
Sorry for the late reply, ProtocolLib still not supported for the latest 1.14.2 version. You need to wait for it.
