### ISSUE TITLE
Config option to toggle 'Zero-Mystery-Box-Available' hologram

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#695]
**Is your feature request related to a problem? Please describe.**
Not really, but it's more like an enhancement regarding the holograms above the mystery vaults.

**Describe the solution you'd like**
Would be nice if there was an option to toggle the `Zero-Mystery-Box-Available` hologram, so that if a player has no mystery boxes, no hologram is shown (or his customName is hidden).

**Describe alternatives you've considered**
Setting its name to '' but it's weird since the armor stand is still there

**Additional context**
N/A

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
