### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by WatiBlaZeR** [OnlyNoobDied/GadgetsMenu#697]
Hello,
I would like to use placeholderAPI in order to recover the player's dust number but with the DeluxMenu and ItemJoin plugin it does not work. In addition I do not find the ecloud to make the command / papi ecloud downlad gadgetsmenu

Sorry if my English is not good I'm french..

Cordially
WatiBlaZeR

**Comment by OnlyNoobDied** [comment]
You do not need to download any expansions to use GadgetsMenu placeholders.
You can just use the placeholders directly.

>

**Comment by WatiBlaZeR** [comment]
I try whith {MYSTERY_DUST} but not working

**Comment by OnlyNoobDied** [comment]
It should be %gadgetsmenu_mystery_dust%.

This is the list of GadgetsMenu placeholders.
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Placeholders
