### ISSUE TITLE
Paintball gadget

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#698]
Crops do not restore when paintball clay blocks disappear, and flowers drop out of the flower pots once the clay blocks are placed.
Same thing for trapdoors (hope you use async block placement xD)

Spigot 1.8.8
GadgetsMenu version : latest 4.3.22

**Comment by OnlyNoobDied** [comment]
What's wrong with the trapdoors?

**Comment by Matocolotoe** [comment]
If they are placed with async ways and aren't stuck to a block they get destroyed

**Comment by OnlyNoobDied** [comment]
It can't be placed in async way. I fixed crops & flower pots issue. The only problem left is trapdoors, I do not sure what's the problem with trapdoors.

**Comment by Matocolotoe** [comment]
For example with FAWE you can put trapdoors not attached to blocks in 1.8

**Comment by OnlyNoobDied** [comment]
Oh, you can place any blocks beside the clay block
