### ISSUE TITLE
Not really and issue more of an question

### ISSUE THREAD

**Issue by johnnymaister123** [OnlyNoobDied/GadgetsMenu#7]
Have you updated the fix for the panes for the plugin?

**Comment by OnlyNoobDied** [comment]
I cannot update the plugin right now. I'm testing new features.

**Comment by johnnymaister123** [comment]
can you email me at johnnymaister@gmail.com when it has been updated, im looking foward to it :D

**Comment by OnlyNoobDied** [comment]
i will inform you here when new version release.

**Comment by OnlyNoobDied** [comment]
https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-9-1-10.10885/

new version released.
