### ISSUE TITLE
Shield / Firework creator.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#70]
Hello !

Could you add a menu with many pre-custom Shields ? :D (like the plugin CustomShields)
And could you add too a firework creator for the Vip ?

Thanks !

**Comment by OnlyNoobDied** [comment]
sorry i cannot add custom shields because it is not compatible with 1.8~1.11 spigot

**Comment by TheIntelloBox** [comment]
Oh. :(

**Comment by OnlyNoobDied** [comment]
sorry. Can you show me the firework creator? maybe i can add that.

**Comment by TheIntelloBox** [comment]
I don't want to copy that but you can see this video : https://www.youtube.com/watch?v=Psj8QKN7LkU

**Comment by OnlyNoobDied** [comment]
sorry, if you have more ideas that is useful please inform me
