### ISSUE TITLE
Playtime : blacklisted worlds

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#701]
**Is your feature request related to a problem? Please describe.**
People can AFK in a certain world like a lobby to earn mystery boxes, without even playing on the server

**Describe the solution you'd like**
Add a blacklisted world list in the config where playtime regarding mystery boxes wouldn't count there

**Describe alternatives you've considered**
An "anti-AFK" but maybe not in a lobby...

**Comment by OnlyNoobDied** [comment]
What if blacklisted worlds are `enabled-worlds` instead of adding one more
option.

**Comment by Matocolotoe** [comment]
Oh yeah, great idea !

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update.
