### ISSUE TITLE
Additions to developer API

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#702]
Would be nice if the developer API had the following things :
- set a player's pet name
- get the total amount of gift packs received by a player
- get the total amount of gifts packs sent by a player
- event when a player opens a mystery box
- event when a player sends/receives a gift pack

**Comment by OnlyNoobDied** [comment]
- set a player's pet name
- get the total amount of gift packs received by a player
- get the total amount of gifts packs sent by a player
These method already available in PlayerManager. I will describe the method when I'm free.

**Comment by OnlyNoobDied** [comment]
@Matocolotoe Send Gift Event is enough as it contains sender and receiver.

**Comment by Matocolotoe** [comment]
oh yeah okay

**Comment by OnlyNoobDied** [comment]
@Matocolotoe What is your GadgetsMenu version?

**Comment by Matocolotoe** [comment]
It's the latest version

**Comment by OnlyNoobDied** [comment]
premium or free version?

**Comment by Matocolotoe** [comment]
free

**Comment by OnlyNoobDied** [comment]
New events have been added in the latest update.

You can check the API here.
https://github.com/OnlyNoobDied/GadgetsMenu/tree/master/com/yapzhenyie/GadgetsMenu/api

**Comment by OnlyNoobDied** [comment]
PlayerManager methods
`playerManager.setPetName(String name);
playerManager.getGiftSent();
playerManager.getGiftReceived();`

**Comment by Matocolotoe** [comment]
Awesome ! Thank you ! :D

**Comment by OnlyNoobDied** [comment]
Close this issue.
