### ISSUE TITLE
reqperm=false not working in some cases

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#705]
Probably found one : when the player has the permission to open X stars mystery boxes and he receives mystery boxes of X + 1 stars with `reqperm=false` in the command, it doesn't work.

**Comment by OnlyNoobDied** [comment]
Both are not connected :/
Anyway to reproduce this issue?

**Comment by Matocolotoe** [comment]
Give a player the permission to open 4 stars boxes
Then /gmb give <player> 1 5 reqperm=false

**Comment by OnlyNoobDied** [comment]
I tested in my server and it's fine. I think your command syntax wrong.

**Comment by Matocolotoe** [comment]
GitHub just removed the player thing, now it is correct but it's still weird that the `reqperm=false` really doesn't work sometimes...

**Comment by OnlyNoobDied** [comment]
It should work fine every time, `reqperm=false` is saved independently with the mystery box data.
