### ISSUE TITLE
expiration timeout for items

### ISSUE THREAD

**Issue by crystalwizard** [OnlyNoobDied/GadgetsMenu#710]
I'd like a way to set an expiration timer on items/particles/morphs and so on. 

The timer would be set on the individual item once it is collected from a mystery box and when the timer counts down to zero, the object would be removed from the player.

Timers should also be able to be set on purchased items and the cost of the item reduced because the item is temporary, not permanent

**Comment by OnlyNoobDied** [comment]
Quite hard to implement it as GadgetsMenu contains 500+ items. Adding this feature will double the complexity of the files

**Comment by crystalwizard** [comment]
not so - add one field to items:  ItemExpired
Add one small fuction -> If (expires ==0;) return else if (expires == ItemExpired && ItemExpired != 0;) <remove from player> return;
Then spend a few minutes adding the ItemExpired field to each item, setting it to 0 by default.

**Comment by OnlyNoobDied** [comment]
This feature was unable to implement as GadgetsMenu [Free] doesn't save unlocked cosmetic items in its database.
