### ISSUE TITLE
Question before buying premium

### ISSUE THREAD

**Issue by DJJasper12** [OnlyNoobDied/GadgetsMenu#712]
Hi,
I am interested in buying the Premium version and supporting the plugin, but had one question before I'll buy it.

I have a minigame server setup with different lobbies for each game and every map in a single server.

Is it possible to:
Install GadgetsMenu Premium in all the lobbies and sync the collectibles using the MySQL database?

Thanks for making this awesome plugin!

Kind regards,
DJJasper12

**Comment by OnlyNoobDied** [comment]
Of course, you can sync cosmetics in all lobbies using MySQL.

**Comment by DJJasper12** [comment]
Ah great!
I even like the plugin more now!

**Comment by OnlyNoobDied** [comment]
Thank you😄
