### ISSUE TITLE
How to get mystery dust

### ISSUE THREAD

**Issue by wolgix** [OnlyNoobDied/GadgetsMenu#713]
How can players get mystery dust?
Any way to earn it free?

**Comment by OnlyNoobDied** [comment]
Only gain Mystery Dust by command or get it from Mystery Boxes.
Mystery Dust can be hook into other economy plugin such as Vault, PlayerPoints.

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Commands
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-how-can-i-change-the-mystery-dust-storage

**Comment by wolgix** [comment]
Should be good you are gaining mystery dust by playtime, or you can find some crates with mystery dust :)
But thanks

**Comment by OnlyNoobDied** [comment]
Player can craft Mystery Boxes using Mystery Dust.
You can use other plugin such as (Time is Money) to gain Mystery Dust as it can hook into any other economy plugin.
