### ISSUE TITLE
Morph Self View Error

### ISSUE THREAD

**Issue by topthat177** [OnlyNoobDied/GadgetsMenu#714]
When selecting a morph with self view enabled the following NPE appears in console. You also only see your player with self view enabled instead of the morph and after a while of moving around you go invisible. The error also prints when you reset the reset cosmetics.

**To Reproduce**
1. Turn on Self View
2. Select any morph
3. See Error in console and that it doesnt display the morph to the player
4. Move around for a bit and notice you become invisible.

**Further Information (please complete the following information):**
 - Server Version: Paper 1.14.4
 - GadgetsMenu Version: 4.3.24
 - Console: https://pastebin.com/uL8FVK4Q

**Comment by OnlyNoobDied** [comment]
Have you follow the guide?
https://www.spigotmc.org/resources/libs-disguises.32453/

**Comment by topthat177** [comment]
Yes I followed that, the morphs work and other players can see you as a particular mob, however, you cannot see yourself as the mob when Self-View is enabled and it prints the error in console.

**Comment by OnlyNoobDied** [comment]
I will look for it.

**Comment by OnlyNoobDied** [comment]
Not sure why this issue comes out. The stack trace shows that player unequip morph.

**Comment by topthat177** [comment]
![2019-10-01_15 46 52](https://user-images.githubusercontent.com/29544476/65937360-021f1f00-e463-11e9-87bb-77cafbc6fcad.png)
![2019-10-01_15 48 24](https://user-images.githubusercontent.com/29544476/65937369-08150000-e463-11e9-8f75-de5399e54e7f.png)
![2019-10-01_15 48 41](https://user-images.githubusercontent.com/29544476/65937374-09dec380-e463-11e9-81ef-0044fdc73d3f.png)

**Comment by topthat177** [comment]
And like I said previously, when self view is enabled and you move, you go invisible. Note there are no active effects so I'm not vanished or invisible.

![2019-10-01_15 55 11](https://user-images.githubusercontent.com/29544476/65937767-37783c80-e464-11e9-869f-5c8a52cfaf6a.png)

**Comment by OnlyNoobDied** [comment]
I can't fix this bug on my side. Possibly causes by ProtocolLib as 1.14.4 still in dev mode.

**Comment by topthat177** [comment]
Ok I'll report it to them, unlikely to get fixed :(

Thanks anyway.
