### ISSUE TITLE
[Suggestions]  Custom Miniatures

### ISSUE THREAD

**Issue by ahah789456** [OnlyNoobDied/GadgetsMenu#717]
I would like to be able to customize even miniatures like pets and particles.

**Comment by OnlyNoobDied** [comment]
May I have the buyer details?

**Comment by ahah789456** [comment]
ahah789456@naver.com

**Comment by OnlyNoobDied** [comment]
Due to the way I code, unable to add custom miniatures feature.

**Comment by Matocolotoe** [comment]
excuse me wtf

**Comment by OnlyNoobDied** [comment]
> excuse me wtf

what :/
