### ISSUE TITLE
Spooderman suit

### ISSUE THREAD

**Issue by IIuoneR** [OnlyNoobDied/GadgetsMenu#718]
When using the spooderman ability, a web is thrown. When landing a web - crash in the console

Need smooth teleportation to where the item fell

**Further Information (please complete the following information):**
 - Server Version: [spigot paper 1.14.4]
 - GadgetsMenu Version: [e.g. 4.3.25]
 - Console stack trace if have: https://pastebin.com/W2kQLSph

**Comment by OnlyNoobDied** [comment]
It will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
