### ISSUE TITLE
Big error

### ISSUE THREAD

**Issue by kkachniarz220** [OnlyNoobDied/GadgetsMenu#719]
https://pastebin.com/ejJedLv8

**Comment by OnlyNoobDied** [comment]
Update ProtocolLib plugin.
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by kkachniarz220** [comment]
Again the same error update update

**Comment by kkachniarz220** [comment]
So can you help me?

**Comment by OnlyNoobDied** [comment]
Please give me some time, I will look for it.

**Comment by kkachniarz220** [comment]
Okay, im waiting for next update :)

**Comment by OnlyNoobDied** [comment]
There're some issue between GadgetsMenu and Citizens plugin, I need some time to find a solution.

**Comment by kkachniarz220** [comment]
Still waiting

**Comment by OnlyNoobDied** [comment]
To temporary fix the issue, please do some changes in `mystery boxes.yml` file

```
Individual-Holograms:
      Enabled: true <-- set to false
```

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
