### ISSUE TITLE
Morphs

### ISSUE THREAD

**Issue by DebugingLonks** [OnlyNoobDied/GadgetsMenu#72]
Ay do morph abilities exist yet? Ya said in 3.6 ;3

**Comment by DebugingLonks** [comment]
Oh actualy they do work. Just guardian is broken

**Comment by OnlyNoobDied** [comment]
yes.Morph abilities is already exist.

**Comment by DebugingLonks** [comment]
Ye, Guardian morph ability isnt working tho. Thata what i meant

**Comment by DebugingLonks** [comment]
And yes ik they exist good job on them too

**Comment by OnlyNoobDied** [comment]
oh . i am working on it.
