### ISSUE TITLE
Explosive Bow

### ISSUE THREAD

**Issue by Sulort** [OnlyNoobDied/GadgetsMenu#722]
When you are using the gadget "explosive bow" you can destroy with the tnt-block itemframes and the items in the frames. they are all dropping to the ground. 
could you pls fix it. thanks.

**Further Information (please complete the following information):**
 - Server Version: paper 1.14.4
 - GadgetsMenu Version: 4.5.4

**Comment by OnlyNoobDied** [comment]
Can you reproduce the problem with a video? I can't reproduce the same problem in your server.

**Comment by Sulort** [comment]
ok, i will see

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
