### ISSUE TITLE
Morph Creeper

### ISSUE THREAD

**Issue by Sulort** [OnlyNoobDied/GadgetsMenu#723]
Is it possible to implement for the morph "creeper" the option (Affect-Players), like in the gadget "Bat Launcher". 
It would be necessary if you dont want to push a player with the creeper-explosion but still have the functionality to explode.

**Comment by OnlyNoobDied** [comment]
Currently I am busy with my studies. I will plan to add this feature as soon as possible.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.
This feature will be added in the next update.

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update.
