### ISSUE TITLE
I don't have permission to /gadgetsmenu equip etc. 

### ISSUE THREAD

**Issue by Equity7** [OnlyNoobDied/GadgetsMenu#727]
**Describe the bug**
I don't have permission to /gadgetsmenu equip etc. I have all commands as owner. I saw that 2 years ago, someone had the same issue and you said you need to have permission to gadgetsmenu.menuselector.* which I made sure I gave myself. I also reinstalled the plugin. Can you tell me how this was resolved?

**To Reproduce**
3. See error

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: [e.g. 1.13.2]
 - GadgetsMenu Version: [e.g. 4.4.0]
 - Console stack trace if have.

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by OnlyNoobDied** [comment]
Did you get any message when you access the command?
Moreover, describe your issue clearly and provide the information that is required. Not just type all things in the title.

**Comment by Equity7** [comment]
So sorry this is my first time posting anything and it seems to have gone in the title and cut off! My mistake!

 1. I go to my server and type /gmenu equip pet(or any other gadget) [name of gadget] [name of player] and I get an error message "you don't have the required permission gadgetsmenu.commands.equip." For example, /gmenu equip Baby_Cow Joe123.
 2. I am op and have Luckperms and I double checked that I have gadgetsmenu.* permission and I especially added both gadgetsmenu.commands.equip and gadgetsmenu.menuselector.* perms.
3. I saw someone else had this issue exactly in 2017 and your response was to add gadgetsmenu.menuselector.* perms. 


I expected the command to work and not get the error.


Server version 1.14.4
Gmenu version 4.3.26
I have no errors in the console except the no permissions error

**Comment by OnlyNoobDied** [comment]
Can you equip gadget using the menu?

**Comment by Equity7** [comment]
Yes everything else works perfectly! A couple gadgets won't equip but there are so many, it doesn't matter to me. It is a wonderful plugin but I do want to be able to give players some gadgets as perks.

**Comment by Equity7** [comment]
And when I type /gmenu permissions, every permission is yellow except gadgetsmenu.commands.equip which is red.

**Comment by OnlyNoobDied** [comment]
Did you add `-gadgetsmenu.command.equip` in the permissions file?

**Comment by Equity7** [comment]
I am op and have Luckperms and I double checked that I have gadgetsmenu.* permission and I especially added both gadgetsmenu.commands.equip and gadgetsmenu.menuselector.* perms

**Comment by OnlyNoobDied** [comment]
Try remove `-gadgetsmenu.command.equip` permission

**Comment by Equity7** [comment]
Ok I removed it from myself  and the owner group and the reply was that I do not have permission. I don't know if you meant to put an s at the end of command because without the s the perms plugin doesn't recognize it.

So then the perms for both owner and specifically for me:
both have gadgetsmenu.*
both have gadgetsmenu.commands.equip.* specifically as false

Before that I had same as above but with gadgetsmenu.commands.equip.* specifically as true for both the owner group and me at a user level.

No permission either way. And I did try both without an s on the end but of "command" but luckperms ignored it because it isn't an existing permission. When I type /gmenu permissions, it has an s on the end of "command".

**Comment by OnlyNoobDied** [comment]
Would you mind give me your permission file?

**Comment by Equity7** [comment]
Certainly will! I appreciate your helping me!
Luckperms is all in-game there is an in-game editor and no file in the ftp but I took screenshots. This is a test server so there is no one but me and no admins.

Is our conversation posted on the web?

**Comment by OnlyNoobDied** [comment]
Erm yes, everyone can see this conversation. You can pm me on spigot if you want to say something secretly :P

**Comment by Equity7** [comment]
Well you want me to post my permissions file here?

**Comment by OnlyNoobDied** [comment]
Up to you. You can pm me if you want.

**Comment by Equity7** [comment]
how do I pm you

**Comment by iFamm** [comment]
how do you add the commands in aternos

**Comment by yapzhenyie** [comment]
> how do you add the commands in aternos

You should not use GadgetsMenu in aternos free server as the plugin will not work properly.
