### ISSUE TITLE
Permissos

### ISSUE THREAD

**Issue by CubeMain** [OnlyNoobDied/GadgetsMenu#728]
tengo un Problema Uso de complento de Permisos el Luckperms pero al cambiar en el apartado de GadgetsMenu/config.yml la opcion de  *Execute-Command:* cambie a lp user {PLAYER} permission set {PERMISSION} pero no lee el comando y en consola sale Error comando no encontrado Que estoy haciendo mal

**Comment by OnlyNoobDied** [comment]
Can you explain your issue in English? Moreover, when you have the issue? Open Mystery Boxes or purchase cosmetic item?

**Comment by CubeMain** [comment]
I have a Problem Using Full Permissions on Luck but when changing in the GadgetsMenu / config.yml section the Run-Command option: change a user lp {PLAYER} set of controls {PERMIT} but do not read the command and console sale Error command not found What am I doing wrong

**Comment by CubeMain** [comment]
that happens in the mystery box

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item

**Comment by OnlyNoobDied** [comment]
Is your problem solved?
