### ISSUE TITLE
Permission error with crates.

### ISSUE THREAD

**Issue by Blocksnmore** [OnlyNoobDied/GadgetsMenu#729]
When a user opens a mystery box they get an error message along the lines "You do not have the permission **gadgetsmenu.pets.sheep**" when it was supposed to give the cosmetic

**Comment by CubeMain** [comment]
eso igual me pasa a mi

**Comment by Blocksnmore** [comment]
Please speak english, kthxbye

**Comment by OnlyNoobDied** [comment]
https://github.com/OnlyNoobDied/GadgetsMenu/wiki/Frequently-Asked-Questions#q-player-had-purchased-a-cosmetic-item-or-gain-from-mystery-boxes-but-they-still-cant-use-that-item
