### ISSUE TITLE
TPS Dips to 15-16

### ISSUE THREAD

**Issue by VanillaChan6571** [OnlyNoobDied/GadgetsMenu#730]
**Describe the bug**
TPS drops to 15-16 causing lag through the entire network.

**To Reproduce**
1. Go to the server.
2. Click on a mysterybox.
3. See the lag of tps and does not recover in fact it starts lagging before anyone gets online.

**Expected behavior**
No lag, no issues. (clearly a issue is here)

**Further Information (please complete the following information):**
 - Server Version: 1.12.2 Paper
 - GadgetsMenu Version: 4.5.5
 - No errors.

**Screenshots**
https://i.imgur.com/BYRoGnc.png

**Additional Information**
Before updating 4.5.5+ [4.4.21] had no issue with TPS.

**Comment by OnlyNoobDied** [comment]
What data storage are you using? MySQL of File?

**Comment by OnlyNoobDied** [comment]
Please reply the message otherwise I will close this issue.

**Comment by Aurelien30000** [comment]
Can confirm this issue but with PlayerQuitEvent
GadgetsMenu linked to MySQL (MariaDB) on a local machine

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
