### ISSUE TITLE
Mysterious boxes do not work permits He

### ISSUE THREAD

**Issue by CubeMain** [OnlyNoobDied/GadgetsMenu#732]
I have a Problem Using Full Permissions on Luck but when changing in the GadgetsMenu / config.yml section the Run-Command option: change a user lp {PLAYER} set of controls {PERMIT} but do not read the command and console sale Error command not found What am I doing wrong

In THE MYSTY BOZ

**Comment by OnlyNoobDied** [comment]
Duplicate of #728
