### ISSUE TITLE
Pets or Miniatures are sometimes not teleported to owner.

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#733]
**Describe the bug**
Sometimes, when you move far away with elytra or fly and get back to the floor, your pet or miniature is not teleported to you and is stucked somewhere (I think that this bug can cause trouble with entities like that).

Thanks in advance ;)

**To Reproduce**
1. Equip a Pet or a Miniature
2. Use a commande to be teleported far away (500 blocs is enough for example)
3. Sometimes, your pet isn't teleported to you and when you go back to your previous location, he is not where he should be :c Your cosmetic "disappeared".

**Expected behavior**
Miniature or Pet should be teleported to owner.

**Further Information (please complete the following information):**
- [13:04:57 INFO]: [GadgetsMenu] GadgetsMenu [Premium] 4.5.6 is loading...
- [13:04:57 INFO]: [GadgetsMenu] [server: git-Paper-650 (MC: 1.13.2)]

**Screenshots**
None

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?
None

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
