### ISSUE TITLE
Starting-Mystery-Dust option doesn't work

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#734]
**Describe the bug**
On the first join, I should receive 50 mystery dust, but my account has still 0.

**To Reproduce**
1. Setup MYSQL storage
2. Delete all data about your player on GadgetsMenu
3. Join the server
4. You didn't receive the starting mystery dust amount

**Expected behavior**
I should receive the starting mystery dust amount set in the config

**Further Information (please complete the following information):**
- [13:04:57 INFO]: [GadgetsMenu] GadgetsMenu [Premium] 4.5.6 is loading...
- [13:04:57 INFO]: [GadgetsMenu] [server: git-Paper-650 (MC: 1.13.2)]

**Screenshots**
None

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?
None

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
