### ISSUE TITLE
Clients on 1.8.x cannot join 1.14.4 server using ViaVersion.

### ISSUE THREAD

**Issue by VanillaChan6571** [OnlyNoobDied/GadgetsMenu#736]
**Describe the bug**
Using ViaVersion to connect to a 1.14.4 server from 1.8.x client just disconnects player.

**To Reproduce**
1. Join Server 1.14.4 Server with 1.8.x client
2. Join it
3. Disconnect Message appears.

**Expected behavior**
Just to join the actual server.

**Further Information (please complete the following information):**
 - Server Version: 1.14.4 Paper
 - GadgetsMenu Version: 4.5.6
Error from console: https://hastebin.com/abaceqimig.pl

**Additional Information**
Using ViaVersion 
Protocol Support doesn't kick you but spams console.

**Comment by OnlyNoobDied** [comment]
Please resent the error message.

**Comment by VanillaChan6571** [comment]
https://pastebin.com/DfhTZGcv

**Comment by Matocolotoe** [comment]
I don't think this is something actually fixable in GadgetsMenu itself since it just uses 1.11+ methods for 1.8 clients, who are not supposed to be able to join 1.14 servers (except with ViaBackwards or stuff like that), hence perfect compatibility is not guaranteed...

**Comment by OnlyNoobDied** [comment]
Are you sure you're using the latest version of GadgetsMenu and the ProtocolLib plugin is supported 1.14.4 version?
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by OnlyNoobDied** [comment]
This issue can be fixed by update ProtocolLib plugin.
