### ISSUE TITLE
Add new option to config.yml urgent

### ISSUE THREAD

**Issue by Serial1990** [OnlyNoobDied/GadgetsMenu#737]
Could u pls insert a option to enable the falling damage for the suite gadgets like u have done it for the disguise.

** 
  # Do you want to enable mob disguise damage?
  # Set to false will disable damage if disguised.
  Enabled-Mob-Disguise-Damage: true
**

**Comment by OnlyNoobDied** [comment]
Some suits disable fall damage because of the ability issue. For example, Frog suit have Jump ability which need to disable fall damage.

**Comment by OnlyNoobDied** [comment]
It shouldn't have an option to disable/enable it in config.

**Comment by Serial1990** [comment]
Could u pls insert another option to choose the value of the Speed (Flash Suite) and Jump (Frog Suite) as an alternative?
