### ISSUE TITLE
Mysql synchronization is not working

### ISSUE THREAD

**Issue by kkachniarz220** [OnlyNoobDied/GadgetsMenu#738]
Player in database have unlocked cosmetic items but in game does not have.
In config im using mysql storage and on enabling plugin im getting info about successfully connection to mysql.
Sync-Cosmetics-On-Join flag is set to true

**Comment by kkachniarz220** [comment]
![err](https://user-images.githubusercontent.com/50884231/69835149-0a6bbe80-1248-11ea-90ed-6c7d2aa62898.PNG)


on reload:
![err1](https://user-images.githubusercontent.com/50884231/69835150-0a6bbe80-1248-11ea-96e8-72279413af96.PNG)

**Comment by OnlyNoobDied** [comment]
Is this issue happen in bungeecord server?

**Comment by kkachniarz220** [comment]
Yes, but before update everything was ok

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
