### ISSUE TITLE
Duplicate menu netherstars

### ISSUE THREAD

**Issue by Mictali** [OnlyNoobDied/GadgetsMenu#74]
In the configurations, under the "Menu Item" section, if I set "Able to Move" to true, then move the nether star off my action bar into my inventory, next time I log in a new nether star is placed back into the default slot 4 so now I have multiple menu objects.  Seems to give a new star if there isn't one in the bar every time you log in.  I've turned off giving the item for now and just use the slash command.

**Comment by OnlyNoobDied** [comment]
hmm noted.

**Comment by OnlyNoobDied** [comment]
fixed.
