### ISSUE TITLE
Gadget Paintball Gun 

### ISSUE THREAD

**Issue by Sulort** [OnlyNoobDied/GadgetsMenu#740]
Hi, 
when you are using the paintball gun gadget, you can destroy grown farmland, e.g. potatoes or carrots etc. even if you put the block farmland, dirt and potatoes on the blacklist.

 - Server Version: [1.14.4]
 - GadgetsMenu Version: [e.g. 4.5.5]

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
