### ISSUE TITLE
PlaceholderAPI Values are bugged

### ISSUE THREAD

**Issue by Free-Lunch-1** [OnlyNoobDied/GadgetsMenu#741]
![image](https://user-images.githubusercontent.com/58997510/71318784-92608380-24e9-11ea-97f5-806ed4a6bfc8.png)

Whenever using the required placeholder (In fact, I tried around 20 different values to try to get this to work), the values get set to MYSTERY_BOXES.

Using the latest version

**Comment by OnlyNoobDied** [comment]
What placeholder you put and the version of GadgetsMenu?

**Comment by Free-Lunch-1** [comment]
Free Version.
I have left the default there **{MYSTERY_BOXES}**
Ive tested:
%gadgetmenus_mystery_boxes%
%mystery_boxes%
{%gadgetmenus_mystery_boxes%}
{gadgetmenus_mystery_boxes
{%mystery_boxes%}
etc

**Comment by OnlyNoobDied** [comment]
Where do you get this message? By gadgetsmenu command?

**Comment by Free-Lunch-1** [comment]
That was in the GUI but it is fixed (somehow?). The hologram above the Mystery Vault shows this:
![image](https://user-images.githubusercontent.com/58997510/71319081-46afd900-24ed-11ea-9430-a9c513d210a1.png)
`      Available-Mystery-Boxes:
      - '&c{MYSTERY_BOXES} Available'
      - '&f{MYSTERY_BOXES} Available'`

**Comment by OnlyNoobDied** [comment]
What is the version of your server?
If is 1.14.4, please download the latest version of ProtocolLib.
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by Free-Lunch-1** [comment]
Yes and done

**Comment by Free-Lunch-1** [comment]
Doesnt work

**Comment by OnlyNoobDied** [comment]
Make sure you have test it before reply this message.

**Comment by Free-Lunch-1** [comment]
I've had the latest version since I started developing this server a month ago

**Comment by OnlyNoobDied** [comment]
The version that you download on spigot doesn't support 1.14 minecraft.

**Comment by OnlyNoobDied** [comment]
Download it from the link that I gave you.

**Comment by Free-Lunch-1** [comment]
I dont download it from spigot

**Comment by OnlyNoobDied** [comment]
Do you get any errors in the console?

**Comment by Free-Lunch-1** [comment]
Let me see logs

**Comment by Free-Lunch-1** [comment]
> [19:08:23] [Server thread/INFO]: [GadgetsMenu] Enabling GadgetsMenu v4.3.27
> [19:08:23] [Server thread/INFO]: [GadgetsMenu] ------------------------------------------------------
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]            GadgetsMenu 4.3.27 is loading...
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]          [server: git-Paper-236 (MC: 1.14.4)]
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]                Plugin by Yap Zhen Yie.
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]            Date Modified: 10 November 2019
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]                            
> [19:08:23] [Server thread/INFO]: [GadgetsMenu]              Initializing module v1_14_R1
> [19:08:23] [Server thread/INFO]: [GadgetsMenu] ------------------------------------------------------
> [19:08:23] [Server thread/INFO]: [GadgetsMenu] Enabled Mystery Vault individual hologram.
> [19:08:23] [Server thread/INFO]: [GadgetsMenu] [Placeholder] PlaceholderAPI hooked.

**Comment by Free-Lunch-1** [comment]
No errors from ProtocolLib or PlaceholderAPI either

**Comment by OnlyNoobDied** [comment]
Normally the issue is ProtocolLib, are you sure you're using the latest version of ProtocolLib :o

**Comment by Free-Lunch-1** [comment]
I reinstalled it and restarted my server and it is still there

**Comment by Free-Lunch-1** [comment]
Fixed it by going onto a completely different version of ProtocolLib

**Comment by OnlyNoobDied** [comment]
-_-

**Comment by Romuux** [comment]
> Fixed it by going onto a completely different version of ProtocolLib
> 
> > -_-
> > I already told you from the beginning
> 
> The ProtocolLib link that you sent above didnt work, neither did the latest version. You never told me anything lol

Hi, Can you tell me wich exact version of ProtocolLib did you used for fix the problem ?
We have exact same problem, and like you the last jenkins release do no fix the problem...
Thanks

**Comment by OnlyNoobDied** [comment]
You can download the version from spigot. Protocollib has release
new version on spigot.
