### ISSUE TITLE
Item to select all pieces of a suit

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#743]
**Is your feature request related to a problem? Please describe.**
To select all pieces of a suit, we have to click on the 4 items.

**Describe the solution you'd like**
An item to select all pieces instantaneously that would appear in every suit GUI.

**Comment by OnlyNoobDied** [comment]
This feature will be added in the next update.

**Comment by OnlyNoobDied** [comment]
This feature has been added in the latest update.
