### ISSUE TITLE
Using 'Vault' as the filetype for storing Mystery Dust along with EssentialsEconomy means that buying cosmetics deducts about only half the price it is marked up as.

### ISSUE THREAD

**Issue by B-Knight49** [OnlyNoobDied/GadgetsMenu#745]
**EDIT: This has suddenly just fixed itself and I can no longer reproduce it. I'm leaving it open though because there most definitely was a problem.** 

**Describe the bug**
File type is set to 'vault' and we're using $ from Essentials as our primary currency. It's not a discount either, they're disabled. Best way to explain this bug is with an example:

I literally just bought something from GM that is priced as $11,500. I set my balance to $251,500. After I bought it, my balance went to $244,600 - so it only took $6,900. I did the same thing with a balance of $250,500 and it, once again, only took $6,900 this time leaving me with $243,600. 

This time I set my balance to $60,000 and bought something marked as $45,200. I was left with $32,880 - it took $27,120.

**To Reproduce**
1. Go to config.yml, set storage type for Mystery-Dust as 'vault'
2. Price something up in the $1000+ range
3. Purchase it
4. Currency reduced by smaller amount than intended

**Expected behavior**
No discountarino.

**Further Information (please complete the following information):**
 - Server Version: Paper #103 - Minecraft 1.15.2
 - GadgetsMenu Version: 4.5.7

**Screenshots**
Not necessary I don't think. See example.

**Additional Information**
N/A. Lemme know what else you might need.

**Comment by OnlyNoobDied** [comment]
Can I have your server ip so I can test it myself?

**Comment by OnlyNoobDied** [comment]
I found the bug and it only happen when you're as op join the server and deop yourself then buy a item.
This issue will be fixed in the next coming update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.

**Comment by B-Knight49** [comment]
> I found the bug and it only happen when you're as op join the server and deop yourself then buy a item.

That makes sense. We were testing earlier prior to realising the bug and we did exactly that, cheers.
