### ISSUE TITLE
Teleport Stick

### ISSUE THREAD

**Issue by Jakaboii** [OnlyNoobDied/GadgetsMenu#746]
**Is your feature request related to a problem? Please describe.**
You're able to glitch through blocks using the teleport stick

**Describe the solution you'd like**
It'd be nice if the plugin could check if people are trying to glitch through blocks (So if someone tries to teleport somewhere where it's a block and then air)

**Describe alternatives you've considered**
The plugin could teleport people behind the "glitched" block instead of them going through or in front of it

**Additional context**

**Comment by OnlyNoobDied** [comment]
what is your GadgetsMenu version?

**Comment by Jakaboii** [comment]
I just updated to the newest one, but I haven't tested on it

I used 4.3.29 when testing

**Comment by OnlyNoobDied** [comment]
It is hard to avoid this issue. If you doesn't want that, you can disable that gadget.

**Comment by Jakaboii** [comment]
Alright, thanks!
