### ISSUE TITLE
Plugin disabled caused of MYSQL table does not exist...

### ISSUE THREAD

**Issue by maxlehot1234** [OnlyNoobDied/GadgetsMenu#749]
Hi,

I just update my server to Java 11 with my server hosting and realize that your plugin disabled itself cause of this:
https://gist.github.com/maxlehot1234/ee351ae1da103a373bdb69a0598a4d87

Just wondering if you can fix this in the next update, since it prevent the plugin to load.

Of course all other plugins connected to the same MYSQL server loads great without any error.

Thanks again

**Further Information (please complete the following information):**
 - Server Version: [PaperMC 1.15.2 build 161]
 - GadgetsMenu Version: [e.g. 4.5.11]

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
