### ISSUE TITLE
Death Effects and Arrow Trails

### ISSUE THREAD

**Issue by tomkeuper** [OnlyNoobDied/GadgetsMenu#751]
I want to use this plugin on like game servers aswell, but i dont want mobs etc on those server but arrow trails and such could be a very cool idea. If you want i can provide a lot of examples

**Comment by OnlyNoobDied** [comment]
You can provide me the examples as much as possible, and I will consider adding these features

**Comment by OnlyNoobDied** [comment]
@tomkeuper Any updates?

**Comment by tomkeuper** [comment]
> @tomkeuper Any updates?
Sorry i didnt see your post as i use gitlab all the time, I will provide them the coming days

**Comment by tomkeuper** [comment]
Here are some arrow trails I had using a different plugin, the gifs provided are just for inspiration there are a ton more that could be added, I know hypixel has a cosmetics tab where you can enable things like this, I have yet to find a good plugin that also allows stuff like this. I dont know if this is a thing you would want to add to the main plugin or make a seperate plugin for game server stuff, like a bedwars server. Hypixel has like a seperate menu for bedwars with wood colors and death cries and also arrow trails. Maybe this is easier to implement?

Bloody https://gyazo.com/9c55531f1a9bbd402d6557f31f935503
Candy Cane https://gyazo.com/3e0d3f59a1465c410c1b61da682b20c5
Confetti https://gyazo.com/b955a9c2074c24687fa55a976ef786f6
Enchanted https://gyazo.com/278e969e6cf03bef8aa1708123947e65
Flame https://gyazo.com/ffbe0ddae3d42a918ab5dc951d4e00c6
Frost Lord https://gyazo.com/e8a52ed4146eb4f0e36477dd8ce128c9
Green https://gyazo.com/b3a07b8e60f24782ec501b886722a7ed
Lava https://gyazo.com/a747fabe100243d08d38fed78e38e553
Love https://gyazo.com/78031dbfd56fbbf19c3223bed8ae89e7
Magical https://gyazo.com/e444e13ba7cd7668653cee8dca33fdd2
Music https://gyazo.com/a6112eb52ace4fe2b70f8760ec73058a (This one is kinda bugged in the gif, it should just follow the arrow)
Rain https://gyazo.com/9564f7dde2ad82a9b7331324cea31bff
Shadow https://gyazo.com/07816539908eb0dfc2a2cb5a1582c4c5
Sparkly https://gyazo.com/dd3851e6bf274f34822683dc1c06c72e
