### ISSUE TITLE
/gmenu reload doesn't enable the plugin back

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#754]
**Describe the bug**
The `/gmenu reload` command disables the plugin, but doesn't load it back.

**To Reproduce**
Execute the command.

**Expected behavior**
The plugin should load.

**Further Information (please complete the following information):**
 - Server Version: 1.8.8
 - GadgetsMenu Version: Premium 4.5.16
 - Console stack trace :
![image](https://user-images.githubusercontent.com/42092549/79443608-55f5ed80-7fda-11ea-8d9a-097a5472175d.png)

**Comment by OnlyNoobDied** [comment]
What name did you put for the GadgetsMenu jar file?

**Comment by Matocolotoe** [comment]
`GadgetsMenu [Premium] v4.5.16`
Does it really cause the issue ?

**Comment by OnlyNoobDied** [comment]
Naming the plugin as `GadgetsMenu` will works fine.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update. You may put any kind of name as you like. :P

**Comment by Matocolotoe** [comment]
Thanks ! :D
