### ISSUE TITLE
Notifications of Mystery Boxes finds while in vanish through Premium Vanish

### ISSUE THREAD

**Issue by ChitterChatter** [OnlyNoobDied/GadgetsMenu#755]
**Is your feature request related to a problem? Please describe.**
Hi there, I am not sure if this is a bug or feature request? or even something I have missed in the config?  When my staff is in vanish through premium vanish, it still shows a notification to all when they have randomly found a mystery box

**Describe the solution you'd like**
when using vanish from premium vanish, and even in game vanish through cmi or essentials, notifications or finding mystery boxes is silenced?

**Describe alternatives you've considered**
haven't considered any.

**Additional context**
I don't have any further information or anything.

**Comment by OnlyNoobDied** [comment]
So you want to hide the broadcast message if the player is vanished?

**Comment by Matocolotoe** [comment]
That would be great indeed.

**Comment by OnlyNoobDied** [comment]
This problem will be fixed in the next update. You may try it after I released new update and tell me the result.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
