### ISSUE TITLE
Mystery Boxes MySQL Storage

### ISSUE THREAD

**Issue by RyderForReal** [OnlyNoobDied/GadgetsMenu#757]
**Is your feature request related to a problem? Please describe.**
No, it isn't.

**Describe the solution you'd like**
A MySQL storage option for mystery boxes.

**Describe alternatives you've considered**
none

**Additional context**
Currently, almost everything but mystery boxes can be stored in a MySQL database. It would be a nice feature to have it for mystery boxes, too.

**Comment by OnlyNoobDied** [comment]
Can you explain your suggestion more specifically? Mystery Boxes can be stored in MySQL.

**Comment by RyderForReal** [comment]
Wait what? I selected MySQL for player storage & default (MySQL) for Mystery Dust but mystery boxes weren't synced between servers

**Comment by OnlyNoobDied** [comment]
Are you sure your Mystery Boxes doesn't sync between server? I takes time to load if you have a thousand of Mystery Boxes.

**Comment by RyderForReal** [comment]
There's only 12 mystery boxes on the server right now as it is in development. And yea.

**Comment by OnlyNoobDied** [comment]
Can you give me your server ip so I can test that in your server.

**Comment by RyderForReal** [comment]
mc.RyderG.net. Whitelisted tho. whats your ign?

**Comment by OnlyNoobDied** [comment]
I will join your server on tomorrow. My ign is OnlyNoobDied

**Comment by RyderForReal** [comment]
whitelisted and opped. Servers affected are hub and opsb (op skyblock)

**Comment by RyderForReal** [comment]
*update: just gave you all gadgetsmenu perms instead of op

**Comment by OnlyNoobDied** [comment]
@RyderForReal I'm not whitelisted in OP Skyblock server.

**Comment by RyderForReal** [comment]
strange.. can you retry?

**Comment by RyderForReal** [comment]
is there a problem with something bc you're leaving so often?

**Comment by OnlyNoobDied** [comment]
> is there a problem with something bc you're leaving so often?

My own internet issue. I got very high ping, around 3000ms+

**Comment by RyderForReal** [comment]
no, i whitelisted you on both. thats the strange thing

**Comment by RyderForReal** [comment]
i'll just give you op on the proxy, maybe thats the thing blocking you

**Comment by OnlyNoobDied** [comment]
Can we chat on discord instead of github?

**Comment by RyderForReal** [comment]
of course. RyderForReal#2177

**Comment by OnlyNoobDied** [comment]
![ping](https://user-images.githubusercontent.com/13622737/79739676-1825fb80-8331-11ea-90ec-8052b89f6102.png)
Can you imagine it?

**Comment by RyderForReal** [comment]
no xD. whats your discord?

**Comment by OnlyNoobDied** [comment]
Yap Zhen Yie#0090

**Comment by RyderForReal** [comment]
sent the request. brb

**Comment by OnlyNoobDied** [comment]
This issue has been solved by enabling `bungee-mode` in spigot.yml file
