### ISSUE TITLE
Error in console with SQL

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#758]
**Describe the bug**
The following error often appears when teleporting to a world where cosmetics are enabled.

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.8.8
 - GadgetsMenu Version: Premium 4.5.18
 - Console stack trace: see screenshow below

**Screenshots**
![image](https://user-images.githubusercontent.com/42092549/79688157-a96f7200-824c-11ea-9521-bda2c47deeb0.png)

**Additional Information**
The error is not consistent, it appears quite randomly.

**Comment by OnlyNoobDied** [comment]
Gotcha! A SQLite has been found. This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
