### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by CoSiski** [OnlyNoobDied/GadgetsMenu#76]
When i'll open the Gadget menu and click on a Hats or anything else it wont open. What happends is that ill just get the Item in my inventory 

**I appreciate some help!**

- CoSiski

**Comment by OnlyNoobDied** [comment]
what version of your server? you're using spigot server or bukkit server?

**Comment by CoSiski** [comment]
I'm using Spigot 1.8.3

**Comment by CoSiski** [comment]
I tried it on a test server and the plugin did work on there but doesn't on my head server

**Comment by OnlyNoobDied** [comment]
did you get any error from console?

**Comment by CoSiski** [comment]
No it didnt show any errors

**Comment by OnlyNoobDied** [comment]
i think other plugin that installed on your server blocked.

**Comment by CoSiski** [comment]
I tried to turn off all the plugins and let GadgetsMenu on but it still wouldnt open any choise like Hats or Particles

**Comment by OnlyNoobDied** [comment]
can you give me your server ip so that i can join your server.

**Comment by CoSiski** [comment]
85.114.135.204:26850

**Comment by OnlyNoobDied** [comment]
fixed.
