### ISSUE TITLE
JSON messages

### ISSUE THREAD

**Issue by zuhir** [OnlyNoobDied/GadgetsMenu#760]
I have error with JSON messages (Invalid item!) and i searched for info here, i found [this](https://github.com/OnlyNoobDied/GadgetsMenu/issues/691) but isn't a solution so, my suggestion is add an option to disable JSON messages.
My spigot server is 1.8.8 and i have ViaVersion 2.2.3, and my MC is 1.12.2 (tested too with 1.15.2)

**Describe the solution you'd like**
A config option to disable all JSON message in the plugin

**Describe alternatives you've considered**
I don't have any other solution for this problem, because is a ViaVersion problem i think.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
