### ISSUE TITLE
Horse pet bug

### ISSUE THREAD

**Issue by zuhir** [OnlyNoobDied/GadgetsMenu#761]
**Describe the bug**
Sometimes, if you spawn "Horse: Creamy" pet can spawn a mule.
And "Mule" spawn a horse, every time (Dark brown horse exactly)
Spigot version: 1.8.8
GadgetsMenu version: 4.3.36

**Additional info**
Spigot server is 1.8.8 but i have ViaVersion installed and i'm playing in 1.12.2

**Comment by OnlyNoobDied** [comment]
This issue can't be fixed in GadgetsMenu. Minecraft made a big changes in 1.11 version which include redesign entity horse. This changes make a differences between old version and newer version. I can't do anything on it. The only way to solve this issue is to update your server to 1.12 version.
