### ISSUE TITLE
Ice walker suit bug

### ISSUE THREAD

**Issue by zuhir** [OnlyNoobDied/GadgetsMenu#762]
Ice walker suit generate snow on torchs, levers, slabs and stairs.
Gadgetsmenu version: 4.3.37
Spigot version: 1.8.8
![Sin título](https://user-images.githubusercontent.com/17429859/80218369-7ac01580-8617-11ea-8353-cfd99441fc97.png)

**Comment by OnlyNoobDied** [comment]
A small bug, it will not affect the game experience.

**Comment by zuhir** [comment]
> A small bug, it will not affect the game experience.

In 1.15.2 servers can kick you for that, is like you are flying, on 1.12.2 no problem, you can walk on snow pad

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
