### ISSUE TITLE
Players are also able to fly with rocket gadget

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#763]
**Describe the bug**
You recently fixed an issue that allowed players to fly with parachute. This issue also concers rocket :/

**To Reproduce**
1) Disable fly
2) Run rocket gadget
3) You can fly...

**Expected behavior**
Players shouldn't be able to fly.

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu Version: Premium 4.5.20

Thanks in advance, this issue is really annoying :)

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by Matocolotoe** [comment]
Can confirm, please fix ASAP :(

**Comment by DukeOfDerp77** [comment]
> This issue will be fixed in the next update.

@Matocolotoe

**Comment by Matocolotoe** [comment]
> > This issue will be fixed in the next update.
> 
> @Matocolotoe

I'm not blind, the issue is just very detrimental to servers which disallow flying

**Comment by DukeOfDerp77** [comment]
@Matocolotoe 
I was just saying. I know its important but I am just letting you know it'll be fixed when it can.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
