### ISSUE TITLE
DATABASE ERROR - java.sql.SQLException: Field 'Pet_Name' doesn't have a default value

### ISSUE THREAD

**Issue by alexeses** [OnlyNoobDied/GadgetsMenu#764]
Hello! 

A pleasure, apparently I'm using GadgetsMenu Premium through MySQL and it's giving problems, we're talking that if you skip the error I'll mention below, the mode goes crazy in terms of CPU consumption. 

This happens when a player entered the mode as you can see in the following picture: https://prnt.sc/s65i15

I expect a solution from the author, at first if I put the Gadgets Menu (gratia) it doesn't give any problem. He used the last version of the plugin itself.

My configuration: https://paste.ubuntu.com/p/q4fhqSSNnj/

Greetings, if you need more information, please do not hesitate to ask me.

**Comment by OnlyNoobDied** [comment]
Can you double check all of your server is using GadgetsMenu Premium version instead of Free version.

**Comment by alexeses** [comment]
Hello!

Apparently, I have some servers that have the Gasgets Menu for free. I'll take care of changing it on all my servers. 

Thank you for your help.

Greetings.
