### ISSUE TITLE
MYSQL CONNECTION TIME - PREMIUM VS FREE

### ISSUE THREAD

**Issue by alexeses** [OnlyNoobDied/GadgetsMenu#765]
Hello!

A pleasure, I'm changing all the plugins of Gadgets Menu to the PREMIUM version, however, I've noticed that the free version is faster when connecting to the database. That is, it takes 2s, you practically don't notice it, however, the premium version takes between 30s-60s. Times when more/less. 

GMenu Free: https://prnt.sc/s6mwk1
GMenu Premium: https://prnt.sc/s6mxru

May I ask why? Is there a way for them to optimize that connection?

A greeting,
Alex.

**Comment by OnlyNoobDied** [comment]
Are you the first time updating the plugin to premium version? If yes, there's some changes in mysql setup which converting the old data and create new tables and etc. The time consume to connect MySQL database would be less than previous. In the other hand, the time consume also depends on your internet connection. There isn't any different in MySQL database coding between free and premium.

**Comment by alexeses** [comment]
Hello!

Yes, I have mostly the GMenu Premium and mostly the GMenu Free, I'm trying to move it as soon as possible. 

That is, you say that if I move everything to the GadgetsMenu premium and wait for those times to be converted, the load radius will be much faster?

Greetings,
Alex.

**Comment by OnlyNoobDied** [comment]
Usually, you must only use either one Free or Premium but not both together
with MySQL database. If you use both version, you might get mysql error too.

**Comment by alexeses** [comment]
Hello! 

Thank you very much for your comments. I hope you have a good day.

A salute,
Alex.
