### ISSUE TITLE
Particles appearing in other worlds

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#766]
**Describe the bug**
When a player has a particle enabled in a world, the particle appears at the same exact position in all the other worlds of the server.

**To Reproduce**
See above.

**Expected behavior**
The particle should be shown to players in the same world.

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.8.8
 - GadgetsMenu Version: 4.5.20
 - No error

**Comment by OnlyNoobDied** [comment]
This is very weird. Any video can provide to prove that?

**Comment by Matocolotoe** [comment]
https://www.youtube.com/watch?v=1af6ZV8ct6A

**Comment by Aurelien30000** [comment]
I can confirm the issue on Paper 1.15.2 with Gmenu 4.5.22, please check and fix it if possible :/

**Comment by OnlyNoobDied** [comment]
Just spend some time to review code and I found out a small issue which sending the particle to every player which in different world.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.

**Comment by Aurelien30000** [comment]
Thanks!
