### ISSUE TITLE
Setting "Execute command" to true doesn't execute it

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#767]
**Describe the bug**
In the main config file, the `Execute-Command.Enabled` setting is ignored. The plugin always uses built-in storage.

**To Reproduce**
1. Set `Execute-Command.Enabled` to true
2. Run `/pex user <player>`
3. No permission is added

**Expected behavior**
The command should be ran.

**Further Information (please complete the following information):**
 - Server Version: Spigot 1.8.8
 - GadgetsMenu Version: 4.3.21
 - No console stack trace, but we can see in the console that the command is not ran

**Comment by DukeOfDerp77** [comment]
@Matocolotoe 
Not sure if you did it in mystery boxes.yml, but its also in there. You gotta change it there too.

**Comment by Matocolotoe** [comment]
Thanks ! I'm more than stupid...

**Comment by DukeOfDerp77** [comment]
@Matocolotoe 
Haha no problem!
