### ISSUE TITLE
Infinite cooldown on Spooderman Suit

### ISSUE THREAD

**Issue by Matocolotoe** [OnlyNoobDied/GadgetsMenu#769]
**Describe the bug**
When throwing cobwebs into the void with the Spooderman Suit, the suit ability's cooldown is not reset.

**To Reproduce**
See above.

**Expected behavior**
The cooldown should reset.
If it comes from the items, they should be removed.

**Further Information**
 - Server Version: Spigot 1.8.8
 - GadgetsMenu Version: 4.5.21
 - No stack trace

**Additional Information**
Re-equiping the suit fixes the problem.

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
