### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Jibba** [OnlyNoobDied/GadgetsMenu#77]
Installed plugin on my server. Can set everything up fine but am unable to click items to open menus. E.g opening a mystery vault shows boxes available that I have given myself to test, but clicking them does nothing. 

TL:DR
Clicking items in menus wont work for me

**Comment by OnlyNoobDied** [comment]
give me your server ip.

**Comment by Jibba** [comment]
131.153.27.18:25581
Its a test server for our main network.
Can you let me know when you will be on so that I can give you necessary permissions.

**Comment by OnlyNoobDied** [comment]
when i am free, i will join your server.

**Comment by Jibba** [comment]
What time will that be. Its a test server but you will still need permissions correct?

**Comment by OnlyNoobDied** [comment]
ok. CraftBukkit server is not supported. you can only use spigot server to run this plugin
