### ISSUE TITLE
Baby Skeleton Horse pet summons an adult

### ISSUE THREAD

**Issue by topthat177** [OnlyNoobDied/GadgetsMenu#771]
When you summon the baby or regular skeleton horse it spawns an adult. Baby zombie horses work as expected.

 - Server Version: Paper 1.15.2
 - GadgetsMenu Version: 4.3.38

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by topthat177** [comment]
Cheers

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
