### ISSUE TITLE
Swimming pool gadget turns concrete powder to concrete

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#773]
**Describe the bug**
Swimming pool gadget makes concrete powder bellow to turn concrete.

**To Reproduce**
Use the swimming pool gadget(or whatever it's called) where there is concrete powder bellow the water on the floor and the water turns the concrete powder to solid concrete as soon as it touches it.

**Expected behavior**
Concrete powder would stay as powder.

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu Version: 4.5.21

**Suggested fix:**
Add config option to disable `MoistureChangeEvent`

**Comment by OnlyNoobDied** [comment]
When the concrete powder touch water, it turns to concrete. This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
