### ISSUE TITLE
Gadgets changing block types cause flowers on top of the block to break

### ISSUE THREAD

**Issue by FaberoM** [OnlyNoobDied/GadgetsMenu#774]
**Describe the bug**
Using a gadget like a paintball gun to a grass block which has flowers on it causes the flowers to break due to flowers being only able to place to the grass/dirt. So when the gadget replaces the grass block with something else, the flower breaks.
**To Reproduce**
Use block changing gadget to a grass block with flower on top and vola.

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu Version: 4.5.21

**Suggested fix:**
Add config option to disable `BlockPhysicsEvent`

**Comment by OnlyNoobDied** [comment]
Can you specify which flower is affected?

**Comment by FaberoM** [comment]
This includes grass, tallgrass, flowers and everything that needs to be on top of a grass_block. When a grass block changes, a BlockPhysicsEvent is called for the plant above and since it's not a grass_block anymore the plant pops out

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
