### ISSUE TITLE
Gadget Lores [Free Version]

### ISSUE THREAD

**Issue by baailey** [OnlyNoobDied/GadgetsMenu#775]
**Is your feature request related to a problem? Please describe.**
Players are able to list the gadgets on auction houses, in trade menus etc. which causes said gadgets to glitch out in the inventory of any players who purchase the listed item. The only way to remove the gadget from their inventory is by clearing it completely.

**Describe the solution you'd like**
I suggest introducing a lore to the gadgets, maybe something as simple as 'Right click to use!'. These lores make it easier to block the items via the config of other plugins.

**Describe alternatives you've considered**
Blocking the actual Minecraft item, however that is rather counterproductive.

**Additional context**
N/A

**Comment by OnlyNoobDied** [comment]
Anyway to use NBT tag determining gadgets? Every GadgetsMenu item has NBT tag including hats, gadget, emotes and suits.

**Comment by baailey** [comment]
Unfortunately not, the trading and auction house plugin I use only offers a way to block said item(s) through the lore.
