### ISSUE TITLE
Issues with PlotSquared v5 and the pet system

### ISSUE THREAD

**Issue by ofunny** [OnlyNoobDied/GadgetsMenu#777]
**Describe the bug**
While players are riding pets, they can not use any plot command on a PlotSquared plot. Especially critical when players can access plots (where the got denied/banned) while they are riding a GM pet. Also players can not get kicked out of a plot while the ride a pet.
According to the PlotSquared team, this has to be a bug in GadgetsMenu and the way it handles the pet riding. Other plugins with cosmetic pets to not face this issue. It looks like PlotSquared is not able to find a player while it rides a pet. Maybe GadgetsMenu is obscuring the player position somehow.

**To Reproduce**
1. Install https://www.spigotmc.org/resources/plotsquared-v5.77506/ and setup a basic plot world.
(https://wiki.intellectualsites.com/plotsquared/installation/installation-instructions)

2. Give yourself all basic perm packs so you can test all plot comments
https://wiki.intellectualsites.com/plotsquared/commands-and-permissions/permission-packs

3. Create a plot with /p auto or /p claim

4. enter the plot while you ride a GadgetsMenu pet and try to use any "/p ..." command like /p clear, /p kick playername etc. – it won't work.

5. Remove your pet, let somebody else enter your plot while riding a  GadgetsMenu pet. Try to kick him "/p kick otherplayername" – won't work, or deny him "/p deny otherplayername" and look if he can enter the plot, while riding a pet, he can, even if he should not be able to.

6. repeat step 4 and 5 without pets and you see it works normally

**Expected behavior**
It should not make any difference if you ride a GM pet or not while using plot commands – it should work like with other pet plugins.

**Further Information (please complete the following information):**
 - Server Version: PaperMC, Build 307, also tested on 300 and 304, MC 1.15.2
 - GadgetsMenu Version: newest version
 - PlotSquared Version: newest version

**Additional Information**
The problem has also been reported to the PlotSquared dev team, you can see their answers here https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/119#issuecomment-631984988 and also talk with them on Discord https://discord.com/invite/KxkjDVg

Since I will run a citybuild server network, this feature is critical for me and for any other PlotSquared user. PlotSquared is actually the biggest and best plot plugin on the marked.

Thank you

**Comment by ofunny** [comment]
Actually I found other plugins also what have a problems to detect a player while riding a pet. For example the plugin advanced portals will not initialise a warp as long as a player rides a pet in the portal. As soon as he gets of, it works. On the other side I can interact with NPCs or chests. use doors and buttons on a pet without problems. So it I guess is only a problem to get player position based/tracked events while on a pet.

**Comment by OnlyNoobDied** [comment]
I need to test it in my server. This issue would not be fixed very soon as I need to do some testing.

**Comment by ofunny** [comment]
Thanks, is not totally urgent. Most of the time is not a problem that people have to get of a pet. It is really just stupid if they can bybass bans or kicks on some areas like plots. Anyways, thank you for working on it.

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
@ofunny This issue has been fixed in the latest update. Player who riding pets will get kicked/removed from a owner's plot when 
the owner use `/plot deny` or `/plot kick` command.
