### ISSUE TITLE
GadgetsMenu pets should not get removed when you use PlotSquared "remove road mobs" option!

### ISSUE THREAD

**Issue by ofunny** [OnlyNoobDied/GadgetsMenu#778]
**Is your feature request related to a problem? Please describe.**
The plugin PlotSquared delivers an option to remove mobs on roads (what are not on plots), this feature is important for the server performance. Unfortunately it will remove all mobs, also cosmetic mobs like GadgetsMenu pets. The developers of PlotSquared would like to implement a option to ignore cosmetic mobs by tag or however you track your pets (mobs) in GadgetsMenu. To do so, they would need your answere how you track them and if this mobs got tagged or anything else.

**Describe the solution you'd like**
Please read point 4. of the following ticket and also the answers of the dev team
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/119#issuecomment-631984988
May you can provide more information and help the PlotSquared team.
Also on Discord https://discord.com/invite/KxkjDVg

**Describe alternatives you've considered**
Actually there is no alternative, without this feature roads can get full of mobs what suck up resources.

**Comment by DukeOfDerp77** [comment]
PlotSquared is just not compatible with some features of gadgets menu.

**Comment by ofunny** [comment]
Yes, it is not compatible at the moment, but as far as I understood they may implement a tagging system for NPC to avoid this issue and give cosmetic plugins like GM the possibility to work with it.

**Comment by DukeOfDerp77** [comment]
So if they are fixing this, the bug is for?

**Comment by ofunny** [comment]
Is not a bug, is a Suggestion, actually to provide at least some information about the tagging mehtod.

**Comment by DukeOfDerp77** [comment]
alright.

**Comment by ofunny** [comment]
Actually, I'm totally sorry about that report, I really don't know how but GadgetMenu pets do not get removed by PlotSquared kill road mobs feature – I do not know how you fixed that. Normal mobs get removed. Since the PS team told me it is a very destructive feature and will destroy all mobs, I did not test again with the newest version. So only the other ticket is relevant, can we remove this one?

**Comment by OnlyNoobDied** [comment]
Duplicate of #777

**Comment by OnlyNoobDied** [comment]
GadgetsMenu is unable to get removed from any other plugin due to custom mob.
