### ISSUE TITLE
Not Storing data

### ISSUE THREAD

**Issue by Jibba** [OnlyNoobDied/GadgetsMenu#78]
Hi there,

Everything is working fine except for when a player gets a cosmetic. When they get it from either purchase or mystery box, it doesnt save. So all players have nothing regardless of purchase. Im thinking its due to either my sql base or something with placeholders as there is no clear definition of what needs to be done with these.

**Comment by hazycraft** [comment]
That's because you need to edit the config.yml on line 42 there is 
Run-Command: pex user {PLAYER} add {PERMISSION}
You must not be using PermissionsEX so change pex to whatever permissions plugin you use...
I.E. I use PowerfulPerms so on my server I would have line 42 set as
Run-Command: pp user {PLAYER} add {PERMISSION}

**Comment by OnlyNoobDied** [comment]
it depends on your permission plugin. If you use GadgetsMenu on many server, you need to enable permission plugin MySQL too

**Comment by Jibba** [comment]
I use GroupManager, thanks for your help on the issue.
Another issue is that every player appears to have permission to use every
gadget? I've added these as follows to only the highest ranks permissions
yet every player has perms. Is there something in the config to disable
access to all players?
gadgetsmenu.hats.*

 gadgetsmenu.particles.*
 gadgetsmenu.suits.*
 gadgetsmenu.gadgets.*
 gadgetsmenu.pets.*
 gadgetsmenu.morphs.*
 gadgetsmenu.banners.*
 gadgetsmenu.emotes.*
 gadgetsmenu.cloaks.*

**Comment by OnlyNoobDied** [comment]
" gadgetsmenu.gadgets.*" this permission means player can access all gadgets

**Comment by Jibba** [comment]
This permission is for the highest rank. None of my other ranks have it yet
they can all access it?

**Comment by OnlyNoobDied** [comment]
if you give that player this permission, he can access all gadgets, otherwise he cannot use any gadget

**Comment by Jibba** [comment]
Hi there,

Actually all of my non donation ranks currently have access to gadgets etc
even though they have no perms whatsoever with regards your plugin.

**Comment by OnlyNoobDied** [comment]
i think you have setup something in your permission plugin that allows
highest rank able to use normal player rank permissions.
