### ISSUE TITLE
People who ride a pet do not take damage in PVP

### ISSUE THREAD

**Issue by Scratch1337** [OnlyNoobDied/GadgetsMenu#781]
Sorry for my bad English. Your plugin is installed on my survival server. People who use Pets in PVP do not take damage. What can I do about it?

**Comment by OnlyNoobDied** [comment]
I will do a testing in my server and if the issue is exist, I will try to fix it as soon as possible. Currently you can disable pet riding functions in your survival by adding a worldguard region in `Blacklisted-Regions` which can be found in config.yml

**Comment by OnlyNoobDied** [comment]
Unable to reproduce the same issue while riding pets. Could you reproduce the same problem and record it in video?
