### ISSUE TITLE
banners and others can be took by players

### ISSUE THREAD

**Issue by Yukylyu** [OnlyNoobDied/GadgetsMenu#785]
Hello
**Describe the bug**
Players are able to take the banners **(survival mode)**.

**same issues #456 but mode survival too...
https://github.com/OnlyNoobDied/GadgetsMenu/issues/456**

https://zupimages.net/up/20/23/na7e.png

This bugs work with:
- banners
- head animated
- heads
- emotes

**To Reproduce**
1. Use banner cosmetics
2. Take the banner on the head

**Further Information (please complete the following information):**
 - Server Version: 1.15.2
 - GadgetsMenu v4.3.34

**Comment by Aurelien30000** [comment]
Try with the latest version : 4.3.39 (free) and 4.5.22 (premium)

**Comment by OnlyNoobDied** [comment]
This issue usually occur because of plugin conflict.

**Comment by OnlyNoobDied** [comment]
@Yukyxy Try version 4.3.41, I change the event priority to prevent plugin conflict.

**Comment by Yukyxy** [comment]
@OnlyNoobDied no it's same i can take banner/heads

**Comment by OnlyNoobDied** [comment]
@Yukyxy Do you have CMI plugin in your server?

**Comment by Yukyxy** [comment]
yes

**Comment by OnlyNoobDied** [comment]
Can you reproduce the issue with the latest GadgetsMenu update & latest CMI build?

**Comment by Yukyxy** [comment]
yes and i use GadgetsMenu v4.3.43 / CMI v8.7.0.5

**Comment by Xwdit** [comment]
> Can you reproduce the issue with the latest GadgetsMenu update & latest CMI build?

I have this problem too, please fix this bug as soon as possible...
@OnlyNoobDied 

Players can take things out of helmet slot ,and if they put them in inventory they will be not cleanable and movable

**Comment by OnlyNoobDied** [comment]
> > Can you reproduce the issue with the latest GadgetsMenu update & latest CMI build?
> 
> I have this problem too, please fix this bug as soon as possible...
> @OnlyNoobDied
> 
> Players can take things out of helmet slot ,and if they put them in inventory they will be not cleanable and movable

According to other player, CMI released a new build that have solve this issue. You may try with the latest CMI build.

**Comment by Xwdit** [comment]
> > > Can you reproduce the issue with the latest GadgetsMenu update & latest CMI build?
> > 
> > 
> > I have this problem too, please fix this bug as soon as possible...
> > @OnlyNoobDied
> > Players can take things out of helmet slot ,and if they put them in inventory they will be not cleanable and movable
> 
> According to other player, CMI released a new build that have solve this issue. You may try with the latest CMI build.
> I will also release a patch update which fixes this issue soon.

ok thanks

**Comment by Yukyxy** [comment]
the bug is still there in the latest versions cmi & gadgetsmenu, it is not resolved

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
