### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by RayNot** [OnlyNoobDied/GadgetsMenu#787]
mystery boxes -> mystery boxes

What do I need to add so that when you open the box in the chat, the nickname with the prefix is displayed, and not just the nickname

Sorry for my English :(

**Comment by OnlyNoobDied** [comment]
Most of the messages about mystery boxes can be changed in `messages.yml` & `mystery boxes.yml` files.

**Comment by RayNot** [comment]
No, I don't need it
When I write %vault_prefix%{PLAYER} the prefix is not displayed

**Comment by OnlyNoobDied** [comment]
Oh, GadgetsMenu doesn't support placeholders yet.

**Comment by RayNot** [comment]
Oh, thank You for your response
