### ISSUE TITLE
Updater issue JDK 11

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#788]
**Describe the bug**
Using jdk 11, updater fails to check.
```[GadgetsMenu] Failed to check for an update on spigot.```

**To Reproduce**
- Use jdk 11, starts the server.

**Expected behavior**
Updater should work.

**Further Information (please complete the following information):**
 - Server Version: Any
 - GadgetsMenu Version: 4.5.22

**Comment by OnlyNoobDied** [comment]
I tested with Java 11.0.7 and I found out that no issue occur. Are you still facing "Fail to check update" issue?

**Comment by Aurelien30000** [comment]
Yes, issue persists on 11.0.6, I'll try on 11.0.7 and let you know about the result.
If needed, you could consider a "debug" version to find out the exact problem :p

**Comment by Aurelien30000** [comment]
Hum, I don't know why, but it works now 🤔

**Comment by OnlyNoobDied** [comment]
It might be connection issue which it failed to get data from spigotmc.

**Comment by Aurelien30000** [comment]
However, a small visual bug is present.
![image](https://user-images.githubusercontent.com/43724816/85377700-c0c32800-b539-11ea-8127-0207f09ca9ba.png)

4523 is shown instead of 4.5.23

**Comment by Aurelien30000** [comment]
Actually, this message only appears if ne new update is available ^^

**Comment by OnlyNoobDied** [comment]
Can you test with the latest update?

**Comment by Aurelien30000** [comment]
Seems fixed :D Thanks, I'll let you know for a future update, just in case !
