### ISSUE TITLE
Visible particles in /v

### ISSUE THREAD

**Issue by therealatsuga** [OnlyNoobDied/GadgetsMenu#789]
Hi. I want to apologize for my poor English, it's not my first language. We have found that you can see the particle effects when you are in /v. Is there any way to fix it? We're using CMI

**To Reproduce**
1. Activate some particle effects
2. go to /v
3. Teleport to a player 

**Expected behavior**
Well....

**Further Information (please complete the following information):**
 - Server Version: [e.g. 1.15.2]
 - GadgetsMenu Version: v4.5.22
 - Console stack trace if have. -> none

**Screenshots**

**Additional Information**
We're using CMI, not essentials

**Comment by OnlyNoobDied** [comment]
This issue will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
