### ISSUE TITLE
Disable GUI

### ISSUE THREAD

**Issue by morjanmihail** [OnlyNoobDied/GadgetsMenu#790]
Hello guys,

   First of all, I love your plugin. <3 Got one question, do you know if it's possible to disable the GUI from permissions? I disabled all of them and seems that I can still access the main menu. Would love a feature like this if it's not possible already.

Kind regards,
Mihai

**Comment by OnlyNoobDied** [comment]
If you want to disable player access the menu via `/gmenu main` or `/gmenu menu` command, you might have to use plugin that blocks player using certain command. These two commands are not require any permission to access to.

**Comment by morjanmihail** [comment]
Thank you very much!
