### ISSUE TITLE
GM makes player right click when opening a menu of a gadget category.

### ISSUE THREAD

**Issue by itaquito** [OnlyNoobDied/GadgetsMenu#792]
**Describe the bug**
Hello!
When you open one of the gadgets categories (or the back item) that appear on the main gadgets menu (`/gadgetsmenu menu gadgets`), it will make the player right-click or punch, you can see this by the animation the player does when you try to open a menu of a gadget.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30180886/87059890-77c4d200-c1cf-11ea-830f-51002ac7d673.gif)

This becomes a problem when you have a custom menu on an item that opens it. When the player punches it will trigger the item, making the menu open.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30180886/87060233-e6099480-c1cf-11ea-950c-cbdc220be0e8.gif)

**To Reproduce**
1. Make an item that opens a menu.
2. Leave your hotbar selector above that item.
3. Open the gadget menu.
4. Click a gadget category (or the back item).
5. See how the menu of the item opens.

**Expected behavior**
The player shouldn't do these actions, I believe this wasn't an error on previous versions of the plugin.

**Further Information (please complete the following information):**
 - Server Version: `This server is running Paper version git-Paper-375 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
 - GadgetsMenu Version: `Plugin Version: 4.3.43 (Up to date)`
 - Console stack trace if have.

**Screenshots**
Player making the punch animation when a menu of a gadget opens.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30180886/87059890-77c4d200-c1cf-11ea-830f-51002ac7d673.gif)

This punch action makes the item trigger the menu. (Actual problem)

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30180886/87060233-e6099480-c1cf-11ea-950c-cbdc220be0e8.gif)

**Additional Information**
Thank you very much.

**Comment by OnlyNoobDied** [comment]
I was unable to reproduce this issue with the same server build (paper-375) and with GadgetsMenu version 4.3.33
Are you still facing the same problem? If yes, what minecraft launcher version you're using?

**Comment by Aurelien30000** [comment]
That's because he plays in 1.16.x and the server is one version below ^^
