### ISSUE TITLE
Plugin should have a feature in the config, to disable the star item....

### ISSUE THREAD

**Issue by graffixserver** [OnlyNoobDied/GadgetsMenu#793]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OnlyNoobDied** [comment]
You should check `config.yml` file before create this issue.

```
Menu-Item:
  # Should give player menu selector when they join the server.
  Give-On-Join: true
```
