### ISSUE TITLE
disable Mystery Boxes when in vanish or hook with premium vanish?

### ISSUE THREAD

**Issue by ChitterChatter** [OnlyNoobDied/GadgetsMenu#795]
Maybe this is already included and I am just not seeing it in the config/options? 
Hopefully if that is the issue, someone could perhaps help direct me on how I can fix this?

**Is your feature request related to a problem? Please describe.**
It is frustrating when you are in vanish and you don't want the players/staff to see you and you win a mystery box and it announces it. 

**Describe the solution you'd like**
We use CMI and staff go in vanish with that. Our admins use premium vanish. When staff is in vanish they sometimes randomly win a mystery box. We still want to keep the Mystery boxes announcing for players, but is there a way to turn off the announcements when someone is in vanish?

I don't really have anything else to say about it all, maybe this already is a feature and I am just blind. lol. 

Thank for your time and all you do :)

**Comment by OnlyNoobDied** [comment]
@ChitterChatter May I know which broadcast message? When player get mystery box reward, it should not announce when they player is vanished.

**Comment by baailey** [comment]
The message that displays is the default message saying 'x found a Mystery Box'.

 I've also just experienced this issue and I'm running GadgetsMenu Premium 4.5.29 along with PremiumVanish 2.5.15

**Comment by OnlyNoobDied** [comment]
Working on this issue.

**Comment by OnlyNoobDied** [comment]
These messages will no longer send to other players when the target player is vanished.
- Player found mystery box message
- Player opening mystery box message
- Player found loot message

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
