### ISSUE TITLE
Disable regions start spamming messages

### ISSUE THREAD

**Issue by ArefyNetwork** [OnlyNoobDied/GadgetsMenu#797]
**Describe the bug**
I have a PVP region in my lobby with morphs disabled on config.yml, but when a player enters the region, it starts spamming the "Not-Allow-Morph-In-Region" message to the player, can you add an option to stop sending in mass these messages, please?

Thanks!

**Screenshots**

Config.yml: https://i.gyazo.com/b516f3328c20b5a4b32c53506b79c586.png

Message spamming all the time when a player enters the region without any morph selected: https://cdn.discordapp.com/attachments/660285160725676052/744690371413409832/unknown.png

Messages.yml: https://i.gyazo.com/dd30e5383c02bedabf272f399074dcb4.png

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
