### ISSUE TITLE
cant spawn pets in mainworld

### ISSUE THREAD

**Issue by CloudeLecaw** [OnlyNoobDied/GadgetsMenu#799]
Whem i tried to spawn a pet in the mainworld world it allways tells me
`[GadgetsMenu] Couldn't spawn pet!`
in all other worlds in the whitelist it works normal.
i cant find the reason for this
i also tested it with a new world and also
with just PEX + SPIGOT 1.16..2 + GadgetsMenu [1.8 - 1.16.2] [Premium] 4.5.29
to see that its no plugin that is interacting here

maybe something went wrong with the plugin and the worldwhitelisting of world?

**Comment by OnlyNoobDied** [comment]
I found that when the world is upgrade from 1.16.1, the pet unable to spawn. I will find a way to fix it.

**Comment by CloudeLecaw** [comment]
i tried to generate a new 1.16.2 world. but this give the same result...

**Comment by OnlyNoobDied** [comment]
Can you try again in another world with other name except `world`?

**Comment by CloudeLecaw** [comment]
i did
in all other worlds it works normal
first i thought i has to do with permissions so i removed whole pex file
and created a new profile wit just an owner andthe '*' permsssion

but same result
in world - world they can spawn
in all others they spawn when they are on the enabled list

i also testest just + Paper 1.16.1 + GadjetsMenü + Pex + Regenerated new world/world_the_end world_nether
Also checked that mobs and monster can spawn in world - they spawn normal just the pets doesnt and the console gives me this output

**Comment by OnlyNoobDied** [comment]
Yeah, mojang did some changes to the world chunk.  I'm still figuring what is the problem and try to fix it when I'm free to.

**Comment by CloudeLecaw** [comment]
i may can tell you something helpful
The problem is just effected by some changed in the file: level.dat
i need to do more tests to see what value in theire is causing this problem

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by CloudeLecaw** [comment]
It fixed in the last version =)

Could you tell us what was the reason exactly? <3
