### ISSUE TITLE
GUI not Working

### ISSUE THREAD

**Issue by SkylessCraft** [OnlyNoobDied/GadgetsMenu#80]
Hello there

When I'm using any GUI from the Cosmetic Menu, I can take the Items out the menu.
That means I am not able to use the GUI.

Thank you.

**Comment by PaulTDD-MC** [comment]
Does an error pop in the in console?

**Comment by SkylessCraft** [comment]
Yes:
![grafik](https://cloud.githubusercontent.com/assets/18294402/21921870/71065326-d96b-11e6-9373-06ae7ff737bb.png)

**Comment by OnlyNoobDied** [comment]
i'm now in school, i will check it later.

**Comment by OnlyNoobDied** [comment]
hmm, you must use spigot.

**Comment by SkylessCraft** [comment]
Yes I am using Spigot 1.10

**Comment by OnlyNoobDied** [comment]
you're using Bukkit server when you send the error
