### ISSUE TITLE
Make it possible for pets to teleport with you?

### ISSUE THREAD

**Issue by CloudeLecaw** [OnlyNoobDied/GadgetsMenu#801]
when you called your pet and use a command like /spawn or /home u get teleported (or its something equal)
at the new point your pet seems to be gone.
(mabe when noone was there before) and the pet is gone then.

You can relog or recall the pet.
But would be nicer if the pets teleport with yu in these cases

**Comment by OnlyNoobDied** [comment]
May I know which GadgetsMenu version you're using?

**Comment by CloudeLecaw** [comment]
The Premium 4.5.30 together with Paper 1.16.2 Build 185

**Comment by OnlyNoobDied** [comment]
Is this problem solved in the latest build?

**Comment by CloudeLecaw** [comment]
well we have not noticed it. the issue seem to become very very rarly, i would not say solved, i would say it just happens very rarly since last update (i dont know if there where changes in it for that)
