### ISSUE TITLE
Pet Trading System

### ISSUE THREAD

**Issue by doitliketyler** [OnlyNoobDied/GadgetsMenu#805]
**Is your feature request related to a problem? Please describe.**
Players keep asking me if they can trade their unwanted pets.

**Describe the solution you'd like**
Pet trading system.

**Describe alternatives you've considered**
Would be cool if it worked with TradeMe by Zrips

**Additional context**
Thats all I got.

Thoughts?

**Comment by OnlyNoobDied** [comment]
GadgetsMenu is a cosmetics plugin and won't provide such function.

**Comment by doitliketyler** [comment]
Adding a pet trading system wouldn't make it "not" a cosmetics plugin so I don't understand what point you are trying to make.

**Comment by OnlyNoobDied** [comment]
GadgetsMenu use the combinations of database & permissions to handle cosmetic items which makes it is not easy to add this function. If I add this function, it might creates a lot of issues on removing the permission from the owner and adding the permission to the trader. Therefore, I consider not adding this function.
