### ISSUE TITLE
Events additions

### ISSUE THREAD

**Issue by mikroskeem** [OnlyNoobDied/GadgetsMenu#809]
**Is your feature request related to a problem? Please describe.**
As my lobby has a little minigame in it which involves picking up items etc. then in ideal I'd make slots with server selector/menus in them unmovable, and unpopulated slots reserved (by using placeholder items for example).

**Describe the solution you'd like**
As GadgetsMenu does not populate cosmetic slot by default, and current options when adding the item to said slot aren't sufficient (WARN, DROP), then adding an event which will be fired before applying and after removing cosmetics would help me a lot.

Using the event I could remove the placeholder item shortly before cosmetic slot would be populated & set it back after when cosmetic was removed.

Besides that, if event could be cancellable, then I'd also have more control of cosmetics whether they can be applied or not under certain conditions.

**Describe alternatives you've considered**
Make equipping cosmetics drop existing slot contents & removing the drop when placeholder item is being dropped. That didn't work.

**Additional context**
None.

**Comment by OnlyNoobDied** [comment]
```
# Do action when player equip cosmetic.
  # Replace: Replace the old item with equipped cosmetic.
  # Warn: Send a warning message to the player and reject to equip cosmetic.
  # Drop: Drop the old item on the ground and equip cosmetic.
  Equip-Cosmetic-Item-To-Slot: WARN
```
Just change it to `REPLACE`

**Comment by mikroskeem** [comment]
This won't do - I'd still like to have events to extend the plugin in ways I need (note the additional use case(s) I described - more control & setting placeholder item back).
