### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ohadguetta** [OnlyNoobDied/GadgetsMenu#81]
i opened the menu and i tried to click all of the buttons and it didnt work!
this is the problem:
https://youtu.be/oPywt5tj7tU
thats all my plugins:
legendery trolls,world edit,pex,fastcraft+,biteskywars,multiverse core,world guard,citizens,old pvp,placeholder api, essentials,essentialschat,holographic displays,vault,cratesplus,gadgets menu

**Comment by OnlyNoobDied** [comment]
require spigot server.
