### ISSUE TITLE
Traduzione

### ISSUE THREAD

**Issue by TecnoFra** [OnlyNoobDied/GadgetsMenu#811]
Salve, 
Il mio problema consiste nel tradurre il plugin, appena finisco di tradurlo avvio il server, aggiorno le cartelle e me ne crea un altra perché quella tradotta da errore, non ho sbagliato niente nella traduzione in quanto è la 10 volta che controllo.
Mi faccia sapere
Arrivederci

**Comment by OnlyNoobDied** [comment]
Use this (http://www.yamllint.com/) to check which part is wrong.
