### ISSUE TITLE
leaving morph deletes/hides items

### ISSUE THREAD

**Issue by icubruh** [OnlyNoobDied/GadgetsMenu#812]
**Describe the bug**
ok, so im a moderator on a mc server, basically a few of our players are having issues with coming out of the morph feature and seeming to lose armour. unconfirmed yet but it may be that it is only  visual glitch as one player said they were able to click the empty slot and the armour reappeared.

**To Reproduce**
its a feature weve only just implimented on the  server, however 3 players have already come forward, mentioning the issue. on e of our developers has tested it and found that this is the case (though not checked to see if able to retrieve item by clicking the empty box, i shll report back  straightaway, if i find that it is so)

**Expected behavior**
on exiting morph mode, that the player has theyre full inventory intact

**Further Information (please complete the following information):**
 - Server Version: 1.16.3
 - GadgetsMenu Version: newest
 - Console stack trace if have.

**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by OnlyNoobDied** [comment]
This issue only happened when the player is in creative mode. This problem is not handle by GadgetsMenu, instead it's Lib's Disguise.

Lib's Disguise stated that in its config.yml file:
```
# For self disguises, they need to have the armor and the held item removed
# Else they see floating armor, floating held items.
# This turns the items invisible in the disguised players inventory. It does not actually remove them!
# Be warned that in creative this can actually delete the item from the inventory due to a weird bug
RemoveArmor: true
```
