### ISSUE TITLE
It might you have forgotten to remove some debugs (1.16.2+ only)

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#814]
**Describe the bug**
Console is spammed by "DI 1" or "DI 2" while a rabbit pet is alive.

**To Reproduce**
Select a rabbit pet, move away and check your logs.

**Expected behavior**
No debug messages.

Thanks! ;)

**Further Information:**
 - Server Version: 1.16.3 Tuinity
 - GadgetsMenu Version: 4.6.1 Premuium
 - Console stack trace if have.

**Screenshots**
I even found the issue 😅 
![image](https://user-images.githubusercontent.com/43724816/98026736-e0356000-1e0b-11eb-9e04-4bc6a4ae0b49.png)

**Comment by OnlyNoobDied** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by OnlyNoobDied** [comment]
This issue has been fixed. Please check for the new update.
