### ISSUE TITLE
Fungun.

### ISSUE THREAD

**Issue by TheIntelloBox** [OnlyNoobDied/GadgetsMenu#82]
Hello !

Could you add a FUNGUN like HiveMc or many plugins, in GadgetsMenu ?
This could be nice.

Thanks ! :D

**Comment by OnlyNoobDied** [comment]
can you show me

**Comment by TheIntelloBox** [comment]
https://www.spigotmc.org/resources/fungun.4304/

**Comment by Waffles2112** [comment]
i second this suggestion
but i believe that it should be optional to give on join, and that a new section/menu would be added that supported multiple fungun types

**Comment by OnlyNoobDied** [comment]
i think i will only add this into new gadget

**Comment by OnlyNoobDied** [comment]
this feature will be add in next version.
