### ISSUE TITLE
no me abre los menus 

### ISSUE THREAD

**Issue by xXMasterCrackXx** [OnlyNoobDied/GadgetsMenu#86]
no me abre los menus tengo la ultima version el jugador no puede ver los gadgets al intentarlo aparece un mensaje que es igual a error que puedo hacer ya trate con todo solo puede abrir los menus si tiene gadgetsmenu.cosmetics.*

**Comment by OnlyNoobDied** [comment]
english?

**Comment by Waffles2112** [comment]
ill translate it for you
im in a spanish class

hablo espanol

**Comment by Waffles2112** [comment]
'Does not open the menus I have the latest version the player can not see the gadgets when you try it appears a message that is equal to error that I can do and try with everything you can only open the menus if you have gadgetsmenu.cosmetics.*' 
(this is a rough translation, im sorry if i missed anything)

i think this issue message is ment to go along with issue #87
i think he means that on his server, players can only open the menu with the permission node 'gadgetsmenu.cosmetics.*'

**Comment by Waffles2112** [comment]
based on issue #87

**Comment by OnlyNoobDied** [comment]
#87
