### ISSUE TITLE
Add iDisguise compatibility instead libdisguises

### ISSUE THREAD

**Issue by xion87** [OnlyNoobDied/GadgetsMenu#88]
I would like this plugin use idisugise, since latest protocollib and libidisguise work work bad on viaversion server (1.8-1.11) i can donate if you want ^^

**Comment by UHCChampions** [comment]
I dont think so LibsDisguises adds great mob viewing from itsself

**Comment by xion87** [comment]
yeah but libdisguise dont support old version... i am using libdisguise and it trow errors with viaversion and cause server crash with 1.8.8

**Comment by Waffles2112** [comment]
u should upgrade ur server so its more up-to-date with the later versions of libsdisguise

**Comment by OnlyNoobDied** [comment]
Lib's Disguise is better than iDisguise for disguise mobs, butLibsDisguise is not compatible. I will contact iDisguise plugin author to add some feature before i planning to change disguise plugin

**Comment by xion87** [comment]
Yeah is a nice idea, idisguise is 1.8/1.11.2 compatible like the gadget plugin, so i think is better in terms of perfomance and safety instead libdisguise

**Comment by OnlyNoobDied** [comment]
i wouldn't use iDisguise for Morph because iDisguise cant see self disguise. You cannot see your own disguise.

**Comment by xion87** [comment]
Yeah is not necessary, i noticed libdisguise work with recent gadgetmenu :)
