### ISSUE TITLE
Suggestion for something :D

### ISSUE THREAD

**Issue by UHCChampions** [OnlyNoobDied/GadgetsMenu#89]
**_I think it would be a good suggestion adding companions like Hypixel's ones Id love them 💃 thanks!_**

**Comment by OnlyNoobDied** [comment]
soon

**Comment by EazyFTW** [comment]
<3

**Comment by UHCChampions** [comment]
im about to faint 😨 😨 😨 😨 😨 😨 😨 😨 😨 😨 😨 😨 😨
