### ISSUE TITLE
Every rank has perms to every gadget?

### ISSUE THREAD

**Issue by Nickfish011** [OnlyNoobDied/GadgetsMenu#90]
Hello, I was wondering if there was a way I could make certain ranks not have permission to certain menus for the gadgets. Like even if I don't put the permissions under the rank, the rank still has access to it for some reason, even though it shouldn't.

**Comment by OnlyNoobDied** [comment]
i think you have setup wrong your ranks.
Can you send me the ranks?

**Comment by Nickfish011** [comment]
Yeah I'm not sure.. All the essentials that I have added to the ranks work just fine. The thing is about the gadgetsmenu essentials/perms is I didn't even add them to the ranks, and yet they have still have perms to all the options in the gadget menu. Do you know what file I need to look for to find the ranks? Sorry I'm clueless lol.

**Comment by Waffles2112** [comment]
what permissions plugin are you using?

**Comment by Nickfish011** [comment]
Groupmanager

**Comment by PaulTDD-MC** [comment]
You should be able to add the permissions for the cosmetics to the group by using the command:
/mangaddp <group> <permission>

**Comment by Nickfish011** [comment]
Yeah
