### ISSUE TITLE
Setting up certain gadgets for certain ranks

### ISSUE THREAD

**Issue by turtle2funky** [OnlyNoobDied/GadgetsMenu#91]
So i have gone through all different files in gadgets and i can't find out how to give certain ranks certain gadgets. For example, say the ranks are 1, 2, 3 and i want rank 1 to have say hats and particles. Then rank 2 to have hats, particles, gadgets, and suits. And finally, rank 3 could have all groups of different gadgets. Again i have searched through the files and i am trying to find out how to give the ranks we have on our server limited access to certain gadgets. Thanks

**Comment by Waffles2112** [comment]
thats called using the Permission Nodes -.-
i didnt know someone could be so oblivious and ignorant

**Comment by Waffles2112** [comment]
u use the permission nodes this plugin has, in your permissions file which would contain all the ranks, you would give/set nodes under those ranks so they have those things
not to be completly mean but im just curious as to how u didnt know that
like what do u think the "permissions" section is for?

**Comment by OnlyNoobDied** [comment]
please check your permissions plugin wiki.
