### ISSUE TITLE
every time i change text in the suits its not changing

### ISSUE THREAD

**Issue by ohadguetta** [OnlyNoobDied/GadgetsMenu#92]
http://pastebin.com/Ctn3Y00B

**Comment by OnlyNoobDied** [comment]
please send the text via http://pastebin.com

**Comment by ohadguetta** [comment]
i sended

**Comment by OnlyNoobDied** [comment]
don't give me this okay. I need original format

**Comment by ohadguetta** [comment]
http://pastebin.com/a2N9Tc0J

**Comment by ohadguetta** [comment]
here

**Comment by OnlyNoobDied** [comment]
tq

**Comment by OnlyNoobDied** [comment]
you said you have change the language into "hebrew". Where is it?

**Comment by ohadguetta** [comment]
http://pastebin.com/Ctn3Y00B

**Comment by ohadguetta** [comment]
Maybe its bexause of the ' in the ninja suit
I dont know

**Comment by OnlyNoobDied** [comment]
all wrong. Please do not change the format(like delete ' ' empty space)

**Comment by PaulTDD-MC** [comment]
you could replace all ' on the outside out the text to "
That should work too
