### ISSUE TITLE
Plugin not showing

### ISSUE THREAD

**Issue by ICraftMyBomb** [OnlyNoobDied/GadgetsMenu#93]
Hi! I'm using Spigot 1.11.2 and the Plugin is not in my Plugins list! I've installed it in /minecraftbukkit/plugins/GadgetsMenu.jar and I cannot use the command. List of installed Plugins:

- ShopGUIPlus
- AdvancedBan
- AntiCheatReloaded
- BalloonFiesta
- ChestCommands
- ChestRegen
- CmdSigns
- ColoredSigns
- ColorTab
- CopsAndRobbersPlus
- CoreProtect
- CrackShot
- CraftBook
- CrazyEnchantments
_ CS-CoreLib
- csgo
- CustomEnchantments
- EasyWarp
- Elevators
- EssentialsPro
- EssentialsX
- ExoticGarden
- FunMessages
- GadgetsMenu
- HolographicDisplays
- iControlU
- iDisguise
and ~40 more

**Comment by OnlyNoobDied** [comment]
how many rams in your server.

**Comment by ICraftMyBomb** [comment]
2GB

**Comment by ICraftMyBomb** [comment]
It's not even laggy, ping is good.

**Comment by OnlyNoobDied** [comment]
GadgetsMenu require high ram usage while loading.

**Comment by ICraftMyBomb** [comment]
It's not even showing up with /pl, neither is it creating a Folder!

**Comment by OnlyNoobDied** [comment]
try remove all plugins except GadgetsMenu.

**Comment by ICraftMyBomb** [comment]
Okay, will try... I'll backup it tho.

**Comment by ICraftMyBomb** [comment]
Still doesnt work.

**Comment by ICraftMyBomb** [comment]
Please help me!

**Comment by ICraftMyBomb** [comment]
@OnlyNoobDied

**Comment by PaulTDD-MC** [comment]
Any errors in console?

**Comment by ICraftMyBomb** [comment]
Nope.

**Comment by PaulTDD-MC** [comment]
Hmm, so if your plugins folder is empty except for GadgetsMenu, then restart the server. The plugin is still not working?

**Comment by ICraftMyBomb** [comment]
Yes :(

**Comment by OnlyNoobDied** [comment]
reinstall GadgetsMenu

**Comment by PaulTDD-MC** [comment]
Has the reinstall worked?
