### ISSUE TITLE
Paintball Gun Gadget Creating Floating Torches

### ISSUE THREAD

**Issue by sxjx** [OnlyNoobDied/GadgetsMenu#948]
**Describe the bug**
Placing torches around all sides of a block, then using the paintball gadget on the torches, allows the block the torches are placed on to be removed while the torches are temporarily terracotta, resulting in floating torches.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place a 1 block thick pillar of blocks, only a few high
2. Place torches on each side of the top block, so there are 4 torches in total
3. Use the paintball gadget on the torches, so they all change to terracotta
4. Whilst the torches are terracotta, break the pillar
5. Floating torches should remain

**Expected behaviour**
Paintball gun gadget should not work on torches like it does not work on blocks like plants or signs.

**Further Information (please complete the following information):**
 - Server Version: git-Paper-386 (MC: 1.19.3)
 - GadgetsMenu Version: 5.3.1
 - Console stack trace if have. N/A

**Screenshots**
https://imgur.com/5kxr3F3 Torches being changed by the gadget

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment]
You can just add torch into blacklist.

**Comment by sxjx** [comment]
We added it to the Blacklist. It didn't solve the issue

**Comment by yapzhenyie** [comment]
Have you put these two materials in the blacklist?
```
- WALL_TORCH
- TORCH
```

**Comment by sxjx** [comment]
Hi, yes both were added. Torches are still replaced regardless.

**Comment by yapzhenyie** [comment]
ok, I will check on this issue.

**Comment by yapzhenyie** [comment]
> Hi, yes both were added. Torches are still replaced regardless.

This issue will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
