### ISSUE TITLE
Suggestion 👍

### ISSUE THREAD

**Issue by mart074a** [OnlyNoobDied/GadgetsMenu#95]
Like the Mysterydust that can be stored in mysql.
Is it possbile to do the same with mysteryboxes ? :)

And another suggestion is to able to give Dust and Boxes to offline players ;)

**Comment by Waffles2112** [comment]
you can already give dust to offline players (in latest versions)
and to store the mysteryboxes in mysql is a great idea, considering the length of text is required for each individual box

**Comment by OnlyNoobDied** [comment]
i am working on it.
