### ISSUE TITLE
New Pet Bee are looking for the wrong permission

### ISSUE THREAD

**Issue by CloudeLecaw** [OnlyNoobDied/GadgetsMenu#951]
gave our VIPs the new permission gadgetsmenu.pets.bee.* and the setting for the bees is 
```
        Enabled: true
        CanBeFound: false
        Purchasable: false
```

 but even with the permission for it they can summon it. instead of that the menue tells them they cant be bought 
The menue of the bees shows like they unlocked no bees and the summenü too and if i click it i get the massage i cant buy it

![Snag_c6cbda7](https://user-images.githubusercontent.com/12080017/229381904-c4f32f4f-744e-42f7-a688-7967212b6ab5.png)

![Snag_c6ce8fd](https://user-images.githubusercontent.com/12080017/229381913-a6d710e7-5045-4ce9-8e0d-989d4a89267e.png)

![Snag_c6cf9c5](https://user-images.githubusercontent.com/12080017/229381915-6627ce04-7f6f-4825-8cd8-636abdee7964.png)

our Owner this does not happen he has all bees shown and useable correct
So it might be gadgetsmenu.pets.bee.* is not the right permission?

![Snag_c6de157](https://user-images.githubusercontent.com/12080017/229381966-fd1de0ba-070d-4893-959b-124db2d4e5df.png)

**Comment by yapzhenyie** [comment]
The permission is `gadgetsmenu.pets.bee.*`, please confirmed that you have this permission in your permission list.

**Comment by CloudeLecaw** [comment]
![Uploading Screenshot_2023-04-03-14-49-44-394_com.rhmsoft.edit.pro-edit.jpg…]()

**Comment by CloudeLecaw** [comment]
![Uploading Screenshot_2023-04-03-14-49-44-394_com.rhmsoft.edit.pro-edit.jpg…]()

**Comment by CloudeLecaw** [comment]
![Screenshot_2023-04-03-14-49-44-394_com rhmsoft edit pro-edit](https://user-images.githubusercontent.com/12080017/229526241-bcbb6637-02b1-4ace-83da-8329deff0ba1.jpg)

**Comment by CloudeLecaw** [comment]
now after a restart its working fine =)
maybe it was because of the update was loaded with plugman?
Well im happy that it works now.

Thank you so much for the great support <3

**Comment by yapzhenyie** [comment]
> now after a restart its working fine =) maybe it was because of the update was loaded with plugman? Well im happy that it works now.
> 
> Thank you so much for the great support <3

Oh great. Good to know your issue is solved.
