### ISSUE TITLE
Wrong bat behavior when mounting

### ISSUE THREAD

**Issue by Aurelien30000** [OnlyNoobDied/GadgetsMenu#952]
**Describe the bug**
When the bat pet is stuck, i.e. cannot reach you due to a block/wall and does not teleport, mouting it will sometimes lead to an unexpected flying behavior always in the same direction with a rather huge speed.

**To Reproduce**
1. Enable the bat pet.
2. Block it behind a block.
3. Mount it carefully.
4. Try to move and see the arbitrary direction and abnormal speed.

**Expected behavior**
A normal flying behavior.

**Further Information (please complete the following information):**
 - Server Version: ``Paper version git-Paper-494 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9b77660)``
 - GadgetsMenu Version: ``5.7.0``

**Screenshots**
https://user-images.githubusercontent.com/43724816/231449144-d22b1660-98e4-4fd5-9872-4fc8905b38cb.mp4

**Additional Information**
Thanks :)

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, I will test it in my server and fix this issue if it's confirmed.

**Comment by yapzhenyie** [comment]
This issue will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
