### ISSUE TITLE
Incompatibil with PowerRanks

### ISSUE THREAD

**Issue by Vennntox** [OnlyNoobDied/GadgetsMenu#956]
**Describe the bug**
Incompatibility with PowerRanks

**To Reproduce**
1. I reload your Plugin with PlugmanX

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: 1.8.8
 - GadgetsMenu Version: 4.8.1

**Screenshots**
![Unbenannt321](https://github.com/yapzhenyie/GadgetsMenu/assets/31446572/7205a855-0d51-485d-8ec6-2007f7bc0f87)

**Additional Information**

And that doesn't work with PowerRanks

  -This command will be executed when player purchase a cosmetic item.
  -You need to change this command according to your permission plugin.
  Execute-Command: pr addplayerperm {PLAYER} {PERMISSION}

**Comment by yapzhenyie** [comment]
You shouldn't reload the plugin via Plugman. Restart server is the only and most appropriate method to reload the plugin.

**Comment by Vennntox** [comment]
I know, but adding permissions still doesn't work with Power Ranks.

![2023-05-31_16 28 34](https://github.com/yapzhenyie/GadgetsMenu/assets/31446572/7a461db2-9433-4936-8d11-6d721cd6a372)
![2023-05-31_16 28 26](https://github.com/yapzhenyie/GadgetsMenu/assets/31446572/ca8fd7d9-b312-481f-a308-abac22372d4b)

**Comment by yapzhenyie** [comment]
> I know, but adding permissions still doesn't work with Power Ranks.
> 
> ![2023-05-31_16 28 34](https://user-images.githubusercontent.com/31446572/242309124-7a461db2-9433-4936-8d11-6d721cd6a372.png) ![2023-05-31_16 28 26](https://user-images.githubusercontent.com/31446572/242309180-ca8fd7d9-b312-481f-a308-abac22372d4b.png)

can you share me your `mystery boxes.yml` file?

**Comment by Vennntox** [comment]
Oh, I see, I have to change it there too, not just in the config. Sry

**Comment by yapzhenyie** [comment]
> Oh, I see, I have to change it there too, not just in the config. Sry

Great!
