### ISSUE TITLE
Animated Hats making helmets disappear

### ISSUE THREAD

**Issue by baailey** [OnlyNoobDied/GadgetsMenu#958]
**Describe the bug**
If you have an Animated Hat enabled, your helmet will disappear if you're holding it and you right-click.

**To Reproduce**
1. Equip an Animated Hat
2. Hold a helmet and right-click

**Expected behavior**
For the Helmet to remain in your inventory, or for the Animated Hat to auto-disable

**Further Information (please complete the following information):**
 - Server Version: git-Paper-80 (MC: 1.20.1)
 - GadgetsMenu Version: 5.8.4

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
