### ISSUE TITLE
Horse Pets not having Coats that match their names

### ISSUE THREAD

**Issue by baailey** [OnlyNoobDied/GadgetsMenu#960]
**Describe the bug**
The Horse Coats do not match their Pet name

**To Reproduce**
1. Spawn a Black Horse, Gray Horse or the Dark Brown Horse
2. See the Horse Coat does not match the name

**Expected behavior**
For the Coat to match the name of the Horse. Much like how the Cat name matches their fur, or the Sheep name matches the wool

**Further Information (please complete the following information):**
 - Server Version: git-Paper-80 (MC: 1.20.1)
 - GadgetsMenu Version: 5.8.4

**Screenshots**
![image](https://github.com/yapzhenyie/GadgetsMenu/assets/62433969/c91de548-7030-4087-a5bc-d87b453650b1)

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
