### ISSUE TITLE
help urgenttt!!!

### ISSUE THREAD

**Issue by PROPRATIK01** [OnlyNoobDied/GadgetsMenu#964]
![2023-11-20_22 30 11](https://github.com/yapzhenyie/GadgetsMenu/assets/130739651/8873e72e-1324-4aa6-81ba-dd2004c2df8d)
![2023-11-20_22 48 59](https://github.com/yapzhenyie/GadgetsMenu/assets/130739651/b7c85afe-5011-410a-a0ea-d1235c2dbb1e)
how can i update this text 
reply fastttt

**Comment by yapzhenyie** [comment]
You can change these messages in `messages.yml` & `mystery boxes.yml` file.
