### ISSUE TITLE
I NEED HELP

### ISSUE THREAD

**Issue by PROPRATIK01** [OnlyNoobDied/GadgetsMenu#965]
HOW TO RESET ALL PLAYERS DATA AND DELETE ALL COSMETICS HE HAVE

**Comment by iiAhmedYT** [comment]
TALK IN CAPS MORE SO WE CAN HEAR YOU BETTER!!! I CAN'T HEAR YOU!!!!

**Comment by actuallySoheil** [comment]
why opening a issue when you can just use their discord support.

**Comment by yapzhenyie** [comment]
To answer your question, you just need to delete the database file in
GadgetsMenu folder if you're using SQLite. For MySQL, just drop all
GadgetsMenu's related tables.

**Comment by yapzhenyie** [comment]
By default, player does not has access to any cosmetic items, unless you
grant them the relevant permissions.
