### ISSUE TITLE
A way to change / disable the Name Your Pet button in GUI

### ISSUE THREAD

**Issue by PrinceBunBun981** [OnlyNoobDied/GadgetsMenu#966]
**Is your feature request related to a problem? Please describe.**
When GadgetsMenu is on a server where a proxy takes over chat, typing the name for the pet in chat is ignored and not sent to the plugin when using the GUI.

**Describe the solution you'd like**
We currently have **/pet name** as an alternative to rename your pets, but no way to let players know to use the command since the GUI version that listens to chat input doesn't work. So simply being able to either (a) remove the item altogether, or (b) change the lore of the item to show **/pet name <name>** would be nice, or even suggesting the command in chat when clicking the button.

**Describe alternatives you've considered**
An alternative to this could be what was mentioned in https://github.com/yapzhenyie/GadgetsMenu/issues/502, an Anvil GUI that allows players to rename their pets.

If this exists already, my apologies, I have tried looking through the configs and wiki for an option but haven't seen anything.

**Comment by yapzhenyie** [comment]
Simple, you can disable this item in `messages.yml` file.

```
  Rename-Pet:
    Name: '&eName Your Pet'
    Material: NAME_TAG
    Show: true <-- change to false
```

**Comment by PrinceBunBun981** [comment]
Completely missed that in `messages.yml`. Thanks!
