### ISSUE TITLE
update to 1.20.3 and 1.20.4!

### ISSUE THREAD

**Issue by games4681** [OnlyNoobDied/GadgetsMenu#967]
you update the free version of gadgets menu to 1.20.3 and 1.20.4 and forget to update the premium version (who paid for) to 1.20.3 and 1.20.4
can you update this version too?

**Comment by yapzhenyie** [comment]
I'm still looking for the solution for some issues in the premium version. New update will be released asap once the issues are resolved.

**Comment by games4681** [comment]
thank you!
i closed as completed
