### ISSUE TITLE
Unable to equip things, and boots color error

### ISSUE THREAD

**Issue by Vennntox** [OnlyNoobDied/GadgetsMenu#968]
**Describe the bug**
I can't give things to the minature, and the shoes aren't the color they're supposed to be.

**To Reproduce**
3. See error

**Expected behavior**

**Further Information (please complete the following information):**
 - Server Version: Paper 1.8.8
 - GadgetsMenu Version: [Premium] 5.15.0
 - Console stack trace if have.

**Screenshots**

![Screenshot 2023-12-30 091349](https://github.com/yapzhenyie/GadgetsMenu/assets/31446572/94ab568a-9849-498b-ae82-6dc105f586d8)
![2023-12-30_09 03 10](https://github.com/yapzhenyie/GadgetsMenu/assets/31446572/82294101-1e63-4220-8a19-cb6f5f6903d6)

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?

**Comment by yapzhenyie** [comment]
You are not allowed to change the default miniature styling. What you can do is disable the default Doge Miniature and create a new custom miniature in `custom-miniatures.yml` file.

**Comment by Vennntox** [comment]
This is the custom-miniatures.yml

**Comment by Vennntox** [comment]
[custom-miniatures.zip](https://github.com/yapzhenyie/GadgetsMenu/files/13797579/custom-miniatures.zip)

**Comment by Vennntox** [comment]
Oh, two Doge miniatures, I didn't notice. One question is it possible to give equipment a specific name? for CIT support
