### ISSUE TITLE
Custom GUI Names for Cosmetics, not inheriting the displayname.

### ISSUE THREAD

**Issue by MartinAVP** [OnlyNoobDied/GadgetsMenu#969]
**Is your feature request related to a problem? Please describe.**
Currently the GUI for cosmetics (like choosing which part of the suit you want) inherits the name from the displayname of the suit. 

**Describe the solution you'd like**
Have a section in the config of each suit that would be GUI-Name: which would allow to set up a custom 

**Describe alternatives you've considered**
Changing the name of the cosmetic worked, but it couldn't get the result I wanted.
![Screenshot 2024-01-14 092143](https://github.com/yapzhenyie/GadgetsMenu/assets/129893589/5fe39b69-2394-468f-9460-b04c1935ffeb)

**Comment by yapzhenyie** [comment]
Thank you for raising this suggestion. This feature is now available in the latest free version.
