### ISSUE TITLE
Error GadgetsMenu for Scoreboard

### ISSUE THREAD

**Issue by mosscraft** [OnlyNoobDied/GadgetsMenu#97]
Hey,
I have an error on scoreboard its not show me.
i add this: %gadgetsmenu_mystery_dust%
i want to add Mystery Dust amount for player.
my plugin used: InfoboardReborn
I hope, you can to help me.
Good Day!
mosscraft

**Comment by OnlyNoobDied** [comment]
InfoboardReborn plugin is not support PlaceHolderAPI plugin for placeholders.

**Comment by mosscraft** [comment]
Which Plugin support PlaceHolderAPI?
