### ISSUE TITLE
Explosive bow arrow

### ISSUE THREAD

**Issue by Link0Darck** [OnlyNoobDied/GadgetsMenu#970]
**Describe the bug**
We get the arrow back when we shouldn't

**To Reproduce**
right click on the ground with the explosive arc in the gadget category

**Expected behavior**
What I want is for him not to recover the arrow because we are in a hub so no items on the ground

**Further Information (please complete the following information):**
 - Server Version: This server is running CraftBukkit version 3950-Spigot-2888990-d485cde (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)
 - GadgetsMenu Version: 5.16.2

**Screenshots**

**Comment by Link0Darck** [comment]
https://github.com/yapzhenyie/GadgetsMenu/assets/28543376/9bee81ea-e7c8-4016-9a10-3d29b29713ab

**Comment by yapzhenyie** [comment]
Let me check on it.

**Comment by dandanjieshuoMC** [comment]
作者，你的付费版趣味道具我可以宣传一下吗？

**Comment by yapzhenyie** [comment]
> Minecraft.1.20.2.-.Multijoueur.serveur.tiers.2024-03-08.20-36-02.mp4

This issue has been fixed. Please check for the new update.

**Comment by yapzhenyie** [comment]
> 作者，你的付费版趣味道具我可以宣传一下吗？

Hi there, this is not a proper channel to discuss about this. Can you please join our Discord server, we can further discuss your topic there. 
https://discord.gg/sF6zxp6

**Comment by dandanjieshuoMC** [comment]
> > 作者，你的付费版趣味道具我可以宣传一下吗？
> 
> 嗨，这不是讨论这个问题的适当渠道。您能否加入我们的 Discord 服务器，我们可以在那里进一步讨论您的话题。 https://discord.gg/sF6

我这里网络不咋行，我在中国，国外的部分网站我访问不了，你这个链接也是一样，唯独嫩访问的就是GitHub了。
