### ISSUE TITLE
Spawning a Llama kicks you and others from the server

### ISSUE THREAD

**Issue by baailey** [OnlyNoobDied/GadgetsMenu#974]
**Describe the bug**
When a Llama pet is spawned, it will kicked you or others in the vicinity around you from the server consistently

**To Reproduce**
1. Spawn a Brown Llama by yourself or with others
2. Get kicked for Network Protocol Error

**Expected behavior**
For no one to be kicked

**Further Information (please complete the following information):**
 - Server Version: Paper version 1.21-124-master
 - GadgetsMenu Version: e.g. 5.18.5
 
**Screenshots**

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?
This doesn't occur with the Creamy Llamas, but with every other variant. Could not recreate this issue with other pets either.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.
