### ISSUE TITLE
Playful Panda (baby) has a broken name

### ISSUE THREAD

**Issue by baailey** [OnlyNoobDied/GadgetsMenu#975]
**Describe the bug**
The baby playful panda's name has the &k effect, even though it is not in any of the files.

**To Reproduce**
1. Hover your cursor over Playful Panda (baby)

**Expected behavior**
For the name to show as `&6Panda: Playful (Baby)`

**Further Information (please complete the following information):**
 - Server Version: Paper version 1.21-124-master
 - GadgetsMenu Version: 5.18.5

**Screenshots**
![image](https://github.com/user-attachments/assets/3c6789ee-8c9e-4f89-918f-f1a69d80fd51)

**Additional Information**
Any other information that you would like to provide that may be relevant to the issue?
How the panda is entered in the pets.yml: 
![image](https://github.com/user-attachments/assets/0df4457c-7ae7-4509-b8c6-c857b0a3bc5a)

**Comment by yapzhenyie** [comment]
GadgetsMenu provides an option to rename the pet. Therefore, the Playful panda pet's name is set by you, it is not an issue nor name is broken.

**Comment by baailey** [comment]
ah, thanks. user-error
