### ISSUE TITLE
Lag in mysql mode

### ISSUE THREAD

**Issue by NivixX** [OnlyNoobDied/GadgetsMenu#98]
The playerJoin event cause lag when the plugin is on mysql mode --> http://prntscr.com/e4xsa0
( up to 45% TPS DROP on my timings )

If I use the file mode , I didn't get any lags.

- Paper Spigot 1.8.8
- Last version of Gadget menu.

Thx !

**Comment by Waffles2112** [comment]
the plugin is 1.8.8 compatable, but it is primarly maintained and intended for 1.9 - 1.11
so perhaps try to update your paper spigot

**Comment by OnlyNoobDied** [comment]
i will fix this issue

**Comment by OnlyNoobDied** [comment]
this issue will be fixed in the next update.
